### ISSUE TITLE
Kodi crashes approx. 1 minute after opening

### ISSUE THREAD

**Issue by BoozasMrs** [jurialmunkey/skin.arctic.fuse#1003]
### Skin section

Other

### Current Behavior

Open's fine, looks great, asks to set up lists as it's not ben done before, allows me to select maybe 3 options and then it crashes. 

### Expected Behavior

Are there any additional set up requirements to stop this?

### Steps To Reproduce

Installed Artic Skin as fresh build
Waited for the install to finish and reboot
Restarted Kodi
wait for Menu to ask if you want to pick the addons/lists
the list to pick from displays
Have time to select 2-3 addon's
Kodi Crashes

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
I don't know what "Asks to setup lists" means. That doesn't sound part of this skin.
