### ISSUE TITLE
Video player OSD - Access to chapter thumbnails

### ISSUE THREAD

**Issue by Bindou01** [jurialmunkey/skin.arctic.fuse#1005]
### Skin section

Video OSD

### Current Behavior

To access the thumbnails, currently it is necessary to press once to display the OSD, then go down once, then go up again.  Indeed, when you press the down arrow once to display the thumbnails, the cursor arrives directly on the "add bookmark" button, rather than on the top line of the thumbnails.

### Expected Behavior

The down arrow should position the cursor directly over the thumbnails.

### Steps To Reproduce

...

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
This is not a bug. The default control in the bookmarks/chapters window must be a button in case there are no bookmarks otherwise you are stuck on nothing and cannot get back to the control.

**Comment by Bindou01** [comment]
> This is not a bug. The default control in the bookmarks/chapters window must be a button in case there are no bookmarks otherwise you are stuck on nothing and cannot get back to the control.

Ha ok, too bad!  And there is no way to establish a line of code that allows you to put the cursor on the first line in both cases?
