### ISSUE TITLE
Player Video OSD - Chapter name missing

### ISSUE THREAD

**Issue by Bindou01** [jurialmunkey/skin.arctic.fuse#1007]
### Skin section

Video OSD

### Current Behavior

When moving forward a chapter, the OSD displays the number of minutes advanced, but not the number of the chapter we are in.

### Expected Behavior

I find that it would be very relevant to display the chapter thumbnails with their names each time we progress from one chapter to another, a bit like a breadcrumb trail.  The one before, the current one, and the one after that.  Something like that.  That would be brilliant.

### Steps To Reproduce

.

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
Works fine for me.

![screenshot00613](https://github.com/user-attachments/assets/c69814e6-65ec-430e-826b-5bbc1b28921a)

**Comment by Bindou01** [comment]
Hi Jurial,
In order to get around the problem of the shadow zone which prevents us from clearly seeing the scenes that we may be looking for, we have set the automatic closing of the OSD after 4s, but, during this timing, do not  only the time information appears, "+11:30" for example.  Is it possible to adjust the chapter name in a "statistical" way and display this time information on the right?

**Comment by Bindou01** [comment]
Should I make a video to illustrate the problem?
