### ISSUE TITLE
:bug: Skipping 2 widgets if no entry on stacked TV genre

### ISSUE THREAD

**Issue by diddy81** [jurialmunkey/skin.arctic.fuse#1012]
### Skin section

Widgets

### Current Behavior

if there is no entry on the stacked tv show genre widget then when clicking down to go passed it skips the stacked widget and the next widget

### Expected Behavior

pushing down should only skip passed the stacked  tv show widget

### Steps To Reproduce

1. Have "the mandalorian" appear in a widget with the "stacked tv show genre" widget underneath it and 2 other normal widgets underneath that
2. navigate down and it will skip passed the genre widget and also he next widget

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
I can't control this behaviour. Which widget next gains focus is managed by kodi and is one of the reasons why stacked widgets are labelled experimental.
