### ISSUE TITLE
Skin settings, details, status bug (movies) 

### ISSUE THREAD

**Issue by JFG1000** [jurialmunkey/skin.arctic.fuse#1018]
### Skin section

Other

### Current Behavior

Hey jurial on the latest update we cannot enable/disable status under movie ratings, tv shows is fine but movies isn't, please could this be fixed, many thanks 

### Expected Behavior

Can usually enable/disable to either have mode ratings appear or not. 

### Steps To Reproduce

Skin settings, details 

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by xyzfre** [comment]
I don't think it's a bug, now the date for Movies is in the info line and give us more space for ratings.

**Comment by JFG1000** [comment]
> I don't think it's a bug, now the date for Movies is in the info line and give us more space for ratings.

Not on about the date, I'm on about it displaying "airing, in production etc" and i think it is a bug or the option to enable/disable surely wouldn't be there, you can enable/disable for shows just movies and they serve exactly the same purpose

**Comment by JFG1000** [comment]
@xyzfre my apologies I've realised this now.

**Comment by OfficerKD637** [comment]
I believe it's a bug and I have mentioned it as a comment here https://github.com/jurialmunkey/skin.arctic.fuse/commit/ed1dcc79703194f0a04543c9c9ac73e64b2cef0a#r144629083

Enabling status should display 4 ratings and leaving it disabled should give you 6

**Comment by xyzfre** [comment]
I love how he did this with the movies ,now we get a full date in the info line instead of the year and more candy, more ratings for movies which is perfect.
