### ISSUE TITLE
:bug: Incorrect Premiere date shown in movie information screen

### ISSUE THREAD

**Issue by FrostByteLXV** [jurialmunkey/skin.arctic.fuse#1024]
### Skin section

Video Info Dialog

### Current Behavior

The movie information shows a day of "-d" for the Premiere date all movies.  Checked Estuary skin and Premiere date is correct.

### Expected Behavior

The information screen shows a number for the day in the Premiere date.

### Steps To Reproduce

1. Open information screen for any movie.
2. Premiere date is displayed incorrectly.

### Screenshots and Additional Info

Arctic Fuse
![Kodi_20240727_082100](https://github.com/user-attachments/assets/021778aa-03d9-4248-932c-072207fd0c3d)

Estuary

![Kodi_20240727_082253](https://github.com/user-attachments/assets/31cc6d53-967e-42bf-9192-a21e26172bfc)

Kodi 22 latest nightly
Arctic Fuse 0.7.32.  I noticed this with the previous versions, and it may have been happening for a while now, so not sure when it really started or if it's always been that way.

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by adamosborne83** [comment]
Hi,

https://github.com/jurialmunkey/skin.arctic.fuse/issues/1019

This is the last closed issue, as I raised this earlier.

**Comment by FrostByteLXV** [comment]
Thanks, I only checked the open items.  I'll try to close
