### ISSUE TITLE
:bug: Edit visibility condition of "Label_ListItem_StatusDate" so that it only applies to TV Shows/Seasons/Episodes

### ISSUE THREAD

**Issue by OfficerKD637** [jurialmunkey/skin.arctic.fuse#1027]
### Skin section

Widgets

### Current Behavior

Hi J!

The new update is phenomenal! I love it and it solves everything that was mentioned in that thread (all while still keeping the skin so visually pleasing and consistent!)

I noticed that enabling the 'Detailed' status in TV Shows also leads to the status of Movies having an 'Unknown' (1449) suffix. I [assume](https://github.com/jurialmunkey/skin.arctic.fuse/commit/4270dd13fbf764ed4427c7c5b41bf866890c9413#commitcomment-144728867) you'd need to edit the visibility condition of the "Label_ListItem_StatusDate" variable so as to not affect movies. 

You're the code boss so you know best haha.

Here's an example:
![image](https://github.com/user-attachments/assets/b4ac62c1-c3d6-4610-8676-c8153ba09255)

### Expected Behavior

Detailed status only affect TV Shows and not movies

### Steps To Reproduce

Enable 'Detailed' status under TV Shows 

All movie items have their status label + 'Unknown' 

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
Yeah I realised after I tested on my TV that I forgot to consider what happens when status is enabled for Movies too.

Fixed here: https://github.com/jurialmunkey/skin.arctic.fuse/commit/42278826326d3ec55166da653e00c8378ad83b01

**Comment by OfficerKD637** [comment]
Oh man I'm speechless haha. I'm probably going to sound like a crazy Jurial fanboy but it's so difficult not to!

Apart from you being a genius (duh), the way you've fostered this amazing community by patiently listening to all of our demands (no matter how silly they are) is so wholesome and one of a kind. 

You don't have to yet you still take the time for curious fellas like me to explain how the code works and I can't be grateful enough for that. 
And the way you name your commits is so helpful when trying to learn what each line of code does in the skin (and your general naming schema is super organized!)

Your attention to detail is on another level! Quick example: I observed that Returning shows had the date and day/month but no year. I thought hmmm that's a weird oversight. Like the skin says Severance is supposed to return on 16 Jan... Is that next year? Or 2026? Before I could jump the gun and post a bug report, I observed some items with the new 'TBC' label and decided to read more about the commit on GitHub. 
And man oh man... I discovered how the Airing + Day (Today, Tomorrow, etc.) is implemented, and only shows that are supposed to return within a year have the date + Month, the rest are TBC. Learning how the code logic works blew my mind!

Sorry to keep rambling but I wanted to express my sincere gratitude for your immense generosity! (welp that's about all the big positive words I know!)

**Comment by jurialmunkey** [comment]
> Like the skin says Severance is supposed to return on 16 Jan... Is that next year? 

Yeah I was a little on the fence about this one. I didn't want it to only show a date for items *this* year because once you get to December it'd be annoying to see "Returning 2025" but it'd actually be in starting in a couple of weeks. 

I went with if it's in the next 11 months then it shows the date, otherwise it shows the year because that date is probably more speculative then anyway.

I'll try it out for a while and then refine more once I get a better sense of it in action. 

>  I discovered how the Airing + Day (Today, Tomorrow, etc.) is implemented, and only shows that are supposed to return within a year have the date + Month,

Yeah I wanted to have something a bit more warm/descriptive rather than cold/technical, so I thought this was a good way to handle it

e.g. Airing Monday feels way more friendly than Next 29/07/2024

Also the text gives an extra clue as to whether it is a new season (Returning), in the middle of a season (Airing), or an entirely new show (Premiering), which I thought was a nice touch.

**Comment by OfficerKD637** [comment]
You're the greatest! Thank you so much!

I don't mean to be nitpicky but I noticed a very very tiny visual bug (and the only reason is because my eyes were a few inches from my laptop screen. It's pretty impossible to spot this on a TV while watching from several feet away).

When you have the side menu set to minimized 'always' and you switch between the side menu icons and the home widgets/spotlight, you can see that the calendar icon wobbles/wiggles a bit. It's extremely subtle and quite hard to notice.

I have no idea why this is happening but once I resized all the icons to a 1:1 ratio (like 32x32) it resolved the issue. 
I noticed the other film rating icons (except the IMDb) also follow the 1:1 ratio and they are unaffected by this visual bug as well.

Let me know if you can recreate it on your end or I could provide a screen recording too.

**Comment by OfficerKD637** [comment]
@jurialmunkey I know it’s always good practice to keep bug reports separate for different issues, but I wasn’t sure if this tiny one needed it.

Let me know and I’ll create a new one if it’s easier to track that way.
