### ISSUE TITLE
[BUG] Allow selecting wall items is not working after latest update

### ISSUE THREAD

**Issue by AakashC2020** [jurialmunkey/skin.arctic.fuse#103]
### Skin section

Home Widgets

### Current Behavior

Hi @jurialmunkey,

In your last update you added the awesome feature to Allow selecting items on the wall. However, after the latest update it's not working anymore. I'm not sure whether this was intentional but it was really a very useful feature. Could you please add it back? 🙏

### Expected Behavior

Items on the wall should be selectable like it was in the previous update.

### Steps To Reproduce

Go to any wall view, poster or landscape. Items are not selectable any more. 🙁

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
The behaviour is inverted because I found it confusing the other way.

Press UP from scrollbar to return to the row. 
Click on the scrollbar instead to focus the wall.

**Comment by AakashC2020** [comment]
> The behaviour is inverted because I found it confusing the other way.
> 
> Press UP from scrollbar to return to the row. Click on the scrollbar instead to focus the wall.

Yes, it worked. Thank you so much for the quick reply and explanation! The new wall view is awesome! 🙂❤️
