### ISSUE TITLE
:bug: Calendar icon wiggles/wobbles when navigating the skin (very tiny visual bug)

### ISSUE THREAD

**Issue by OfficerKD637** [jurialmunkey/skin.arctic.fuse#1033]
### Skin section

Widgets

### Current Behavior

Hey J!

Hope you're doing well!

I don't mean to be nitpicky but I noticed a very very tiny visual bug (and the only reason is because my eyes were a few inches from my laptop screen. It's pretty impossible to spot this on a TV while watching from several feet away).

When you have the side menu set to minimized 'always' and you move between the side menu icons and the home widgets/spotlight, you can see that the calendar icon wobbles/wiggles a bit. It's extremely subtle and quite hard to notice.

I have no idea why this is happening but once I resized all the calendar icons to a 1:1 ratio (like 32x32) it resolved the issue.
I noticed the other film rating icons (except the IMDb) also follow the 1:1 ratio and they are unaffected by this visual bug as well.

Let me know if you can recreate it on your end.

Here's a clip at 50% speed. You can notice the calendar icon wobbling when I switch back and forth between the side menu icons and the spotlight buttons

https://github.com/user-attachments/assets/0841f4cf-7c70-4e26-9f4a-50621abfb9c3

### Expected Behavior

Calendar icon to stop wiggling (or keep it if you like the cute little dance)

### Steps To Reproduce

1. Enable 'Status' in Movies and TV Shows
2. Have side menu set to minimized always
3. Move between the side menu icons and the spotlight buttons or widgets in your home screen

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
What screen resolution? 

Sounds like a Kodi rounding error/issue due to an imperfect screen ratio which doesn't match with one of resolutions. If its a rendering issue it should be fixed in Kodi not workedaround in the skin.

**Comment by OfficerKD637** [comment]
I am running my Windows laptop at 1920x1080 but I also noticed this on my TV (webOS) which is 3840x2160
I think these are the standard FHD and 4K resolutions? 

On closer inspection, the wiggle is more like a horizontal bounce animation. As if the icon (which is not exactly a 1:1 square - rather a slight 1:1.12 vertical rectangle) wobbles/bounces side to side inside a square container (approx. 2-3 times) before settling in.
