### ISSUE TITLE
:bug: Global Spotlight stopped displaying randomised trakt ‘your lists’

### ISSUE THREAD

**Issue by Qirat77** [jurialmunkey/skin.arctic.fuse#1034]
### Skin section

Widgets

### Current Behavior

I previously had global spotlight set to display random trakt ‘your lists’ via tmdbhelper’s randomised function. Worked fine until lately. Now spotlight shows the fallback artwork.

### Expected Behavior

Global Spotlight should show randomised trakt ‘your lists’. 

### Steps To Reproduce

In customise widgets…Spotlight>Global Spotlight>add-ons>video add-ons>tmdbhelper >randomised >random your list…doesn’t show my lists.

These lists do still appear in tmdbhelper > trakt> your lists, however. 

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
Are you sure it works in TMDbHelper? (i.e. not as a widget?)

Pretty sure this is a TMDbHelper bug. Please report there.
