### ISSUE TITLE
:bug: Randomising Widgets Issue

### ISSUE THREAD

**Issue by karlosmexicanos** [jurialmunkey/skin.arctic.fuse#1038]
### Skin section

Widgets

### Current Behavior

The randomizing feature for widgets is fantastic, but there's one minor issue: it also randomizes the position of the expand button, which might result in it being missing or appearing in the middle of the cards. I really appreciate the effort you've put into this—thanks for your hard work!

### Expected Behavior

When selecting the randomize option, I expected the expand button to remain at the end of my shows or movies and not be moved around.

### Steps To Reproduce

I did this in the customise widget options 

### Screenshots and Additional Info

![17227330429996968843217179287735](https://github.com/user-attachments/assets/a06c5420-ba6b-4f9d-bb9a-53025ffcc4fa)

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
I don't know what "expand" is. If this is a next page type of item from a plugin then that's an issue with that plugin not correctly setting the "specialsort" property to "bottom" for that next page item. You will need to ask the author of the plugin to fix it.

This property is documented in the listitem api docs
https://alwinesch.github.io/group__python__xbmcgui__listitem.html#ga96f1976952584c91e6d59c310ce86a25
