### ISSUE TITLE
:bug: Ratings selections not saving when reopening Kodi

### ISSUE THREAD

**Issue by achnisch** [jurialmunkey/skin.arctic.fuse#1039]
### Skin section

Other

### Current Behavior

I am currently trying to have 2 ratings only for both movies and shows (IMDB and Awards). Default appears to be 4 ratings for each so I go to the third/fourth ratings and select clear and then OK. The ratings selection is saved for the current session but when exiting the app and opening again these settings are no longer saved and revert back to having third/fourth ratings enabled.

### Expected Behavior

Ratings settings to be saved after exiting/opening Kodi

### Steps To Reproduce

1. Go to Settings > Skin Settings > Details
2. Under Movies/TV shows ratings section, select third/fourth ratings
4. Select clear and then OK for each rating
5. Close out of skin settings
6. Exit Kodi
7. Open Kodi

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
Should be fixed now. You'll need to re-clear them again after the update so that they get the "None" value set, but then after that it should stick (on startup it checks if the value is empty and if it is sets it to the default, so now that it has a value "None" instead it should stay disabled).

**Comment by achnisch** [comment]
Perfect, thanks for the fix and for all your awesome work!
