### ISSUE TITLE
[Feature] Add Clearlogos for Movie and TV Show landscape widgets which don't have landscape images

### ISSUE THREAD

**Issue by AakashC2020** [jurialmunkey/skin.arctic.fuse#104]
### Skin section

Home Widgets

### Feature description

Hi @jurialmunkey,

Some new Movies and TV Shows don't have landscape images, so the fan art is used in the landscape style for their widgets. However, these fan arts when used as landscapes in the widgets don't have clearlogos or names and they appear very empty. Is it possible to add clearlogos to those fan arts in the widgets like you've currently set for the fan arts in the card style widgets? If this is possible then please add the Clearlogos only for Movies and TV Shows, and not for TV Episode thumbs in landscape style widgets. TV Episode thumbs in landscape style are fine as they are at present

### Why is this feature needed? Please justify and explain.

It'll make the Movie and TV Show landscape style widgets look even better.

### Screenshots and Additional Info

Currently landscape style widgets which don't have landscape images and are therefore using fan arts without Clearlogos:

![IMG20230816234628](https://github.com/jurialmunkey/skin.arctic.fuse/assets/65297828/ec7ef90f-77bf-44ac-9eaf-58a16856103b)

Card Style widgets for which Clearlogos are getting added automatically on the fan arts:

![IMG20230816235018](https://github.com/jurialmunkey/skin.arctic.fuse/assets/65297828/239a0e74-04b1-40f8-b013-8c7f8216a292)

Please don't include Clearlogos in TV Episode thumb images in landscape widgets as they look fine currently and should be without Clearlogos like they are at present:

![IMG20230816234725](https://github.com/jurialmunkey/skin.arctic.fuse/assets/65297828/5b260886-c706-4dd6-a37d-cda0478defc6)

### Checklist

- [X] I have made a separate issue for each feature I am requesting.
- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by ambulancePilot** [comment]
This would be great if possible!

**Comment by AakashC2020** [comment]
Thank you @jurialmunkey !
