### ISSUE TITLE
:bug: Make the arctic mirage compatible with arctic fuse on a clean install

### ISSUE THREAD

**Issue by diddy81** [jurialmunkey/skin.arctic.fuse#1041]
### Skin section

Other

### Current Behavior

you dont have issue's turned on for screensaver.arctic.mirage so adding this here
arctic mirage requires script.skinshortcuts to choose a widget for the screensaver but it is not set in the addon.xml
since arctic fuse does not need skinshortcuts this screensaver installs fine but can no longer choose a widget to display if using this skin

### Expected Behavior

Should get a dialog to select a widget in screensaver.arctic.mirage when clicking on "widget path" in the screensaver settings

### Steps To Reproduce

1 make a clean kodi install 
2 install arctic fuse
3 install arctic mirage
4 try to set a widget path in the screensaver settings

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
Can't you just install skin shortcuts?
