### ISSUE TITLE
:bug: No details for Music Videos

### ISSUE THREAD

**Issue by rahaaatul** [jurialmunkey/skin.arctic.fuse#1051]
### Skin section

Video Info Dialog

### Current Behavior

There's no artist or actor info in details.

![Screenshot (91)](https://github.com/user-attachments/assets/84e4d483-6d15-4a59-9c78-122bfc31f841)

### Expected Behavior

Should display artist/actor. Here's an estuary example for the same video:

![image](https://github.com/user-attachments/assets/73e8747b-4964-4e83-99c8-81b518bf8521)

### Steps To Reproduce

1. Open information page of a music video.
2. Go to details tab.
3. See it's empty.

### Screenshots and Additional Info

I'd also like to ask for more focus on better music video theming. I feel like it's being neglected.

Also, any idea why actors are appearing as artists in `music videos` > `artist` tab?

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
> I'd also like to ask for more focus on better music video theming. I feel like it's being neglected.

Yes it has been neglected because I don't use musicvideos in Kodi. Also previously they used to go through the music library / info and so worked basically the same as music but now that seems to have changed and they only use video library (technically correct I guess but much more work to support)
