### ISSUE TITLE
:bug: Kodi broken.

### ISSUE THREAD

**Issue by KaaaooS** [jurialmunkey/skin.arctic.fuse#1053]
### Skin section

Other

### Current Behavior

I slide and not open option menu.

![Screenshot_2024-08-21-01-11-41-459_org xbmc kodi](https://github.com/user-attachments/assets/6b6e47ad-7c34-4893-b142-7f528c04dc12)

### Expected Behavior

.

### Steps To Reproduce

Delete all shortcuts and now not access to settings.

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
Not sure what you expected to happen after deleting everything... Lol

Press s on keyboard will open options or sometimes long press back works for some systems
