### ISSUE TITLE
horizontal info buttons topbar Flash

### ISSUE THREAD

**Issue by adamosborne83** [jurialmunkey/skin.arctic.fuse#1055]
### Skin section

Widgets

### Current Behavior

Hey J, 
Hope you're well. Long time no bug report.

See video, but when I go into info on a movie from a widget, you'll see a flash of text at the top.

### Expected Behavior

Not to flash

### Steps To Reproduce

Go into a movie info.

### Screenshots and Additional Info

https://imgur.com/a/SlBLfGs

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
Oops. I only tested from library, not home/hubs. Forgot to add the condition there! This should fix it.

**Comment by adamosborne83** [comment]
Thank You.
