### ISSUE TITLE
:bug: Clearlogo as SVG is not transparent

### ISSUE THREAD

**Issue by ThisIsCyreX** [jurialmunkey/skin.arctic.fuse#1057]
### Skin section

Widgets

### Current Behavior

The clearlogo will have a black background if that logo-file is a SVG-file.
![image](https://github.com/user-attachments/assets/0ff50b59-0bc4-42ac-a958-d9b4fefc77b7)

### Expected Behavior

Have SVG like PNG be transparent.
![image](https://github.com/user-attachments/assets/eb502f5c-f236-4880-8960-123314a1e263)

### Steps To Reproduce

1. Use a SVG file as clearlogo (for example [this from tmdb.org](https://image.tmdb.org/t/p/original/1sbAPe5cFhayW0NHTqPe3eGc0an.svg))
2. Update it for the media you're testing
3. View the results in Kodi

### Screenshots and Additional Info

I use Kodi with Jellyfin (and Addon Jellyfin for Kodi).

*I wasn't able to check if the same happens in Estuary. I don't think the default-skin has a view with clear-logos.
Instead I used the [Estuary Mod](https://github.com/b-jesch/skin.estuary.modv2/tree/Omega) to check.
![image](https://github.com/user-attachments/assets/c07df25f-3cd2-4d25-95eb-a7f1b2d00566)
So it does happen there too. If it is a Kodi problem, just close the issue :)

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
Not a skin issue. Kodi does not support svg images - I'm actually surprised they display at all.
