### ISSUE TITLE
:bug: Skin Reboot

### ISSUE THREAD

**Issue by mawrick26** [jurialmunkey/skin.arctic.fuse#1065]
### Skin section

Fonts and Languages

### Current Behavior

The skin load and after time kodi reboot. I think it's when tthe title of a movie or tv show contains accentuated character.

### Expected Behavior

Skin don't reboot.

### Steps To Reproduce

Load skin with accentuated character.

### Screenshots and Additional Info

[01_KODI_CRASH.log](https://github.com/user-attachments/files/16823831/01_KODI_CRASH.log)

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
Not a skin issue. CoreELEC issue from what I can tell. The skin isn't in charge of executing code for decoding unicode characters.

**Comment by mawrick26** [comment]
Thanks you very much for reply. 
I will see with the coreELEC dev so.
