### ISSUE TITLE
TheMovieDb error

### ISSUE THREAD

**Issue by Blurayx** [jurialmunkey/skin.arctic.fuse#1066]
[kodi.log](https://github.com/user-attachments/files/16829785/kodi.log)

[kodi.old.log](https://github.com/user-attachments/files/16829786/kodi.old.log)

### Skin section

Library

### Current Behavior

TheMovieDb error: macOS, Dune HD Homatics 4k,Nvidia Shield. Linux OS.
I have been getting this error for about 5 months. Currently, using skin.arctic.fuse-0.7.29. Getting the same issue with 0.7.38.

### Expected Behavior

TheMovieDb error

### Steps To Reproduce

It can happen anytime.

### Screenshots and Additional Info

<img width="883" alt="1" src="https://github.com/user-attachments/assets/23ea5bcd-0165-4988-9781-312d963ff209">

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [ ] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
You've got a corrupted database.
> CACHE: _database ERROR! -- database disk image is malformed
> database_v6_ItemBuilder.db_simplecache

Close Kodi and delete the cache file:
`kodi/userdata/addon_data/plugin.video.themoviedb.helper/database_v6/ItemBuilder.db`

Then restart Kodi.

Nothing to do with the skin.

**Comment by Blurayx** [comment]
Thank you 😀

**Comment by jurialmunkey** [comment]
> Thank you 😀

Let me know if you continue to have the error, but I think simply deleting the file and allowing the database to be rebuilt new will be enough (possibly might get an error on first startup afterwards complaining that the database doesn't exist, but should be fine from then on after it creates a new one).

**Comment by Blurayx** [comment]
I'll keep up up dated. 
On a different matter. I'm not sure if you've seen my last comment Episode info #984

Thanks

**Comment by jurialmunkey** [comment]
> I'll keep up up dated. On a different matter. I'm not sure if you've seen my last comment Episode info #984

Yep, I'm not getting into the status discussion again. Way too many opinions. You can read all about it here:
https://github.com/jurialmunkey/skin.arctic.fuse/discussions/1009

**Comment by Blurayx** [comment]
No worries, I'll stick to 0.7.29 until it stops working. Then go back to AH2
Thanks.

**Comment by jurialmunkey** [comment]
> I needed the last TV shows airing dates.

You can see this in the info dialog.

**Comment by Blurayx** [comment]
With 0.7.29 & AH2 I can compare the release date to calendar date, then instantly know without searching the web e.g. IMDB.
No worries, I'll stick to my original plan 0.7.29 with working so far without issues 🙂

<img width="580" alt="Screenshot 2024-09-03 at 8 01 01 AM" src="https://github.com/user-attachments/assets/15243289-6cd6-4481-a052-33baf17218dd">
