### ISSUE TITLE
Home Icon not central when only one category is created.

### ISSUE THREAD

**Issue by DROIDshield** [jurialmunkey/skin.arctic.fuse#109]
### Skin section

Home Widgets

### Current Behavior

Been changing my setup slightly to only have one set of categories under home so all of my widgetsare listed below. 

Once all other categories are disabled or deleted to only leave the main one, it jumps to the left of its general home position.

I have found that if I create a blank name category it then pulls the original Home icon back into place.

Think this might be a bug?

### Expected Behavior

The home category should stay in position even after being the only category enabled. 

See the before and after pics showing the blank cat is created and home is pulled back into position. 
![20230823_140904](https://github.com/jurialmunkey/skin.arctic.fuse/assets/97023369/02141379-6802-4607-96ea-d3ca7ba4140d)
![20230823_141843](https://github.com/jurialmunkey/skin.arctic.fuse/assets/97023369/9de2b639-d31d-4964-b28a-6a2055c6afe6)

### Steps To Reproduce

Settings
Customise Home
Categories 
Create only one category and test. 

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
Definitely a bug so I'll see if I can fix it -- *but* if you're only using one category you may as well turn off the categories altogether by changing the home screen style to "Basic".

**Comment by DROIDshield** [comment]
Funny you should say use basic... I would but I prefer the look of the classic as it shows the spotlight information and the first like line of widgets scrolling... looks much more comprehensive... I often live these scrolling together and spot something worth dipping into ☺
