### ISSUE TITLE
Fully customizable hubs

### ISSUE THREAD

**Issue by patkino** [jurialmunkey/skin.arctic.fuse#11]
### Skin section

Home Widgets

### Feature description

Option to add custom hubs with full functionality just as default ones

### Why is this feature needed? Please justify and explain.

Since i need YouTube hub - I made it out if "Live TV" default hub, cause in "Custom" hub iption its impossible to make "submenu lists"

### Checklist

- [X] I have made a separate issue for each feature I am requesting.
- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by jurialmunkey** [comment]
Boring technical reasons for why there can't be separate custom hubs. 

However, you can achieve the same thing by reusing a hub like you're doing now and then changing the side menu item to a custom item using a custom action to open that hub:

The hub actions are
`ActivateWindow(1101)`  -- Movies
`ActivateWindow(1102)`  -- TV Shows
`ActivateWindow(1103)`  -- Music
`ActivateWindow(1104)`  -- Live TV / PVR

I can add these to the default items.

**Comment by patkino** [comment]
Well it didn't help me. 
Can you just add a possibility to have multiple standard hubs (e.g. 2 movie hubs) and an option to change the title.
For now if I use Custom hub and make it "ActivateWindow(1101) it just puts a shortcut to Movie Hub

**Comment by jurialmunkey** [comment]
You need to set the item to be the hub you need (e.g. Movies). Then setup the hub how you like. Then change the side menu item to "Custom" and set the custom action. You can get up to 4 hubs this way.

Currently it is too difficult to have extra custom hubs with the way they work and the options available in skinshortcuts.

**Comment by patkino** [comment]
As far as I get it only movies and tvshows have the option of submenulist widgets.
So if I want to set up a YouTube hub - I have to choose one of those.
But it seems like the skin doesn't allow to have two different movie hubs, because when I set a custom hub to 1101 layout - it works just as a shortcut to Movie item (doesn't open in side menu, jumps to Movies)

**Comment by patkino** [comment]
So I've managed to make YouTube hub out of the livetv layout, renamed it at changed the icon.
The only thing left - id "recently played" tv widget and "tv groups". Can't remove them
