### ISSUE TITLE
[BUG] PVR progress indicators

### ISSUE THREAD

**Issue by r95sguy** [jurialmunkey/skin.arctic.fuse#111]
### Skin section

PVR and Live TV

### Current Behavior

Progress indicators for PVR widgets doesn't show current progress, not sure since which update it has started.

### Expected Behavior

Indicators under PVR to show progress

### Steps To Reproduce

PVR widgets

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
Yeah the method being used was really inefficient (basically checks each value starting from 1 to 100 and then sets the image for that percentage - so potentially 100 checks per item). 

Kodi doesn't really have a good way like it does with resume percentage to get the progress value directly for live tv (it has to be converted using a variable like I was doing before), so I've reverted to using a bar for live tv progress.
