### ISSUE TITLE
[BUG] Trakt Comments focus issue under video info dialog

### ISSUE THREAD

**Issue by AakashC2020** [jurialmunkey/skin.arctic.fuse#114]
### Skin section

Video Info Dialog

### Current Behavior

Hi @jurialmunkey,

Greetings! I've noticed that when we go to the video info dialog for any Movie or TV Show and then go to the Trakt button on the side menu, then the focus is always set on the second comment instead of the first one. If you then press left then the focus shifts to the first comment  This is not a big issue but looks a bit distracting.

### Expected Behavior

The focus should be on the first comment instead of the second one when we go to the Trakt button on the side menu in the video info dialog of any Movie or TV Show.

### Steps To Reproduce

Go to the video info dialog of any Movie or TV Show. Then go to the Trakt button on the side menu. The focus will be on the second comment always.

### Screenshots and Additional Info

![IMG20230826232032](https://github.com/jurialmunkey/skin.arctic.fuse/assets/65297828/2a4cfefc-456b-48de-a90d-153dca6427e0)

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
Kodi "bug". Nothing I can do about it really.

When a list reloads, Kodi will try to refocus the same item in the list. It bases this off the item's path. 

Problem is that reviews don't have a path because they're not playable and they're not a folder, so they all have the same "path" and Kodi gets confused thinking they're all the same item -- and when they're all the same, for some reason it decides to focus the second item in the list.

I might be able to trick it in TMDbHelper by adding some details to the item path but nothing can be done from the skin side.

**Comment by jurialmunkey** [comment]
^^^ That change in TMDbHelper should "fix" it by adding the comment_id to the path of each review -- which should make each one unique and trick Kodi into treating them as different items.

**Comment by AakashC2020** [comment]
> ^^^ That change in TMDbHelper should "fix" it by adding the comment_id to the path of each review -- which should make each one unique and trick Kodi into treating them as different items.

Hi @jurialmunkey,

I don't think this TMDbHelper add-on version with the change has been updated to the Repo. Please correct me if I'm wrong. Thank you!

**Comment by AakashC2020** [comment]
> ^^^ That change in TMDbHelper should "fix" it by adding the comment_id to the path of each review -- which should make each one unique and trick Kodi into treating them as different items.

Thank you so much @jurialmunkey ! The latest version of TMDbHelper add-on has resolved this issue.
