### ISSUE TITLE
[BUG] Widget Contents Repeated when using "Wrap"

### ISSUE THREAD

**Issue by berkhornet** [jurialmunkey/skin.arctic.fuse#115]
### Skin section

Home Widgets

### Current Behavior

When setting the "Content Row Navigation Style" to "wrap", if the number if items returned by the widget occupy less than the available space, the contents are repeated. In the attached examples the widget contained 5 and 1 items respectively.

### Expected Behavior

Only display each item once in this case.

### Steps To Reproduce

Set up widget that will display a limited number of items.

### Screenshots and Additional Info

![screenshot00001](https://github.com/jurialmunkey/skin.arctic.fuse/assets/67786207/efeadefc-2a03-435c-8d70-77061e2d5983)
![screenshot00002](https://github.com/jurialmunkey/skin.arctic.fuse/assets/67786207/cc452889-97a2-446e-bc0b-434c22893feb)

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
That's how I *want* it to behave (wrap without duplication) but Kodi doesn't have a way to do it natively, and so far haven't figured out any tricks to fake it.

The trick I use for the categories/submenu buttons to wrap without duplication only works when there's a static ID, so it won't work for widgets.

**Comment by berkhornet** [comment]
@jurialmunkey -  many thanks for your reply. It's not a major issue, but good luck in finding a solution.

**Comment by jurialmunkey** [comment]
Superseded by changes in next version which remove support for wraplists entirely.

I think the main reasons wraplist was wanted initially were:

1. Navigation - wrap from ends without travelling over side menu
2. Visibility - see more of widget content at list end
3. Cosmetic - avoid overlapping at screen edges 

Both navigation and visibility issues have already been addressed by other settings for fixedlists. So I can't see much point in keeping the option considering it has a lot of other issues and overcomplicates the code.

And if there's a string demand for it, I can address the cosmetic point by adding an option to push the x position offset for the the fixedlists so they don't have the left side overlap/peek.

**Comment by berkhornet** [comment]
Many thanks for the explanation. All sounds good to me.
________________________________

**Comment by berkhornet** [comment]
I pressed send to early.

The main  reason I experimented with wrap list was that left side overlap, so if you could add the suggested option in the future that would be great

Many thanks for all your efforts.
________________________________
