### ISSUE TITLE
[BUG] Episode Air Date

### ISSUE THREAD

**Issue by Jcloak** [jurialmunkey/skin.arctic.fuse#118]
### Skin section

Home Widgets

### Current Behavior

Great work so far!

When viewing a list of episodes, it always displays the next air date (if continuing) or last air date (if show is finished) instead of the actual air date of the individual episode.

### Expected Behavior

The actual air date of the episode should appear

### Steps To Reproduce

1) Select a show
2) Select a season
3) Show air date is displayed instead of episode air date

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
It also displays the premiered date...

![screenshot00133](https://github.com/jurialmunkey/skin.arctic.fuse/assets/4618719/545dace9-5a65-4a57-ab40-ac158dde1f3e)

**Comment by Jcloak** [comment]
I see. I misunderstood what the infoline setting referred to when it said "Genre / Premiered" I have it configured for "Ends at time" I assumed "Premiered" just meant when the movie or show first came out. I guess in the context of an episode it makes sense though.

It would be nice to have "Ends at time" with "Premiered" as well if possible. For individual episodes, Genre seems like the least useful item out of the three.

Thanks again.

**Comment by jurialmunkey** [comment]
> Genre seems like the least useful item out of the three.

Genre is not shown for individual episodes (as you can see in my screenshot).
Genre is shown for Movies/TV; Premiered is shown for Episodes/Videos

> It would be nice to have "Ends at time" with "Premiered" as well if possible

Then something else needs to make way. The only option would be MPAA rating.

**Comment by Jcloak** [comment]
Sounds good. Thanks for the update!
