### ISSUE TITLE
[Feature] Browse for subtitle" from the Subtitles settings list in Video OSD

### ISSUE THREAD

**Issue by 666jones** [jurialmunkey/skin.arctic.fuse#119]
### Skin section

Home Widgets

### Feature description

Would it be possible to have a option to disable Browse for subtitle..." from the Subtitles settings list in Video OSD.

I just download my subtitles and every time I accidentally click on browser subtitles it causes Kodi to freeze for around 1/2 minutes 

### Why is this feature needed? Please justify and explain.

Just to have a smoother experience 

### Checklist

- [X] I have made a separate issue for each feature I am requesting.
- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by jurialmunkey** [comment]
That's a standard Kodi dialog. The skin can't control what options are shown there.
