### ISSUE TITLE
Live Tv Widget

### ISSUE THREAD

**Issue by patkino** [jurialmunkey/skin.arctic.fuse#12]
### Skin section

Home Widgets

### Feature description

As it appears, there's a possibility to make tvchannels list as a usable widget on the homepage

### Why is this feature needed? Please justify and explain.

I don't use Live TV hub, since I don't need any pvr options, except just watching channels. For now I have "TV channels" button on homepage, which makes tvchannels list float out.
If it's possible- I would ask to make this list a separate widget to place on the homepage.

### Checklist

- [X] I have made a separate issue for each feature I am requesting.
- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by jurialmunkey** [comment]
Sorry I'm not sure if I quite understand.

There's already an option for a tv channels widget:
`Default Widgets > Live TV > All channels`

**Comment by patkino** [comment]
![IMG-20230723-WA0000](https://github.com/jurialmunkey/skin.arctic.fuse/assets/85682547/d4c94c74-1675-4ca2-83d2-d277c38ca1dd)
This one.
Is it possible to make it a "widget"?

**Comment by jurialmunkey** [comment]
Sorry, that's not possible. Only possible to have that view inside MyPVRChannels window.

**Comment by patkino** [comment]
Ok

**Comment by DROIDshield** [comment]
What PVR is being used here as I use live tv and would love to implement it into the skin if possible.

**Comment by patkino** [comment]
I use "IPTV simple" pvr

**Comment by DROIDshield** [comment]
Will give it a try and see how it looks.
