### ISSUE TITLE
[BUG] Full sized keyboard layout option issue

### ISSUE THREAD

**Issue by 666jones** [jurialmunkey/skin.arctic.fuse#121]
### Skin section

Home Widgets

### Current Behavior

Hello,

I have selected full size keyboard layout option however it won't display full screen only displaying on the side screen.

I have restarted Kodi and tried selecting this option and unselecting it however side keyboard remains.

Kind regards
SJ

### Expected Behavior

Full sized keyboard 

### Steps To Reproduce

1. Enable full size keyboard layout
2. Go to the search widget keyboard is still displaying as side layout

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
That option only changes the real keyboard when you click a text entry field. The search dialog will still be on the side.

**Comment by 666jones** [comment]
Ahh that's makes sense. Thanks for the explanation :)
