### ISSUE TITLE
[BUG] moviedb Helper error

### ISSUE THREAD

**Issue by dawuman** [jurialmunkey/skin.arctic.fuse#124]
### Skin section

Home Widgets

### Current Behavior

Every time I open KODI, the database will be refreshed and an error such as "Suppressing retries for 30 seconds" will pop up, which is encountered in skins such as arc. zephyr/horizon. 2/arc. fuse. I checked the log and found that plugin. video. themoviedb. helper reported an error

### Expected Behavior

1. As a Chinese user, sometimes I may encounter issues with accessing api.tmdb.org, so I would like to choose to disable plugin Video The moviedb Helper, to avoid access errors, many Chinese users will encounter this issue. Please consider it.

2.As shown in the log below, sometimes the inability to access api.tmdb.org is not due to network reasons. I suspect it is because the default API key exceeds the number of calls. Therefore, can users set their own API key for TMDB?

### Steps To Reproduce

1. open kodi
2. waitting 10s
then show "Suppressing retries for 30 seconds "

### Screenshots and Additional Info

![微信图片_20230910232324](https://github.com/jurialmunkey/skin.arctic.fuse/assets/5250711/8e19e14d-9ef3-4bb2-8235-22f50d00788e)

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
TMDbHelper is an essential part of the skin so it cannot be disabled.
