### ISSUE TITLE
any way to add more menu items?

### ISSUE THREAD

**Issue by daveftw84** [jurialmunkey/skin.arctic.fuse#130]
### Skin section

Other

### Feature description

there is only option to use 4, i know that i can change the four to what ever four i want but i kinda need a few more

### Why is this feature needed? Please justify and explain.

movies, tv shows, live tv, video games, music, addons

### Checklist

- [X] I have made a separate issue for each feature I am requesting.
- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by daveftw84** [comment]
i guess i can get rid of addons, use the shorctus under home, movies or tv shows and not use music

**Comment by jurialmunkey** [comment]
This is addressed in v0.4 which will be released in next couple of days. The side menu now has unlimited items.

You can get a preview of 0.4 from the Omega testing branch:
https://github.com/jurialmunkey/skin.arctic.fuse/archive/refs/heads/omega_testing.zip
 
Note that v0.4 no longer uses the SkinShortcuts addon and the new script is not backwards compatible with Skinshortcuts config files, which means it will not inherit your old setup.

I'm working on an import addon to assist in the migration, so once that's ready I'll be pushing it to my Kodi repo.

**Comment by jurialmunkey** [comment]
v0.4 now in main repo.
