### ISSUE TITLE
Authorize Trakt to tmdb helper and trakt addon in one go, straight from skin

### ISSUE THREAD

**Issue by daveftw84** [jurialmunkey/skin.arctic.fuse#131]
### Skin section

Other

### Feature description

This skin is awesome out the door but i feel like its desperatly missing something to let users know about how much they can benfit with this skin using a trakt account. Kinda feels like you forgot or you dont recommend using trakt. alot of the local library features can easily be replaced with a trakt account and the trakt tmdb helper menus on skin ....  this all can easily work out the gate if you wanted. a button next to settings or a pop up menu to authorize trakt would be great.. 

i also think there should be access to tmdbhelper settings from the skin, since this skin relies on it soooo much.

### Why is this feature needed? Please justify and explain.

this skin can easily replace local library with tmdb helper

### Checklist

- [X] I have made a separate issue for each feature I am requesting.
- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by jurialmunkey** [comment]
Tmdbhelper settings you should be able to access via dependencies section in skin settings.

I'll have a think about a Trakt auth button.

**Comment by daveftw84** [comment]
would be easier just to hit context over addon then that. 
the addon is obviouly the motor of the skin.

**Comment by daveftw84** [comment]
Like "set default movie/tv player" buttons in the movie section or tv
section.
Or a tab inside kodis settings to adjust most of the skins settings. .. the
addon settings are kind of more important than anything inside the kodi
settings.
Or maybe some maintenance comnands, like clear cache in that menu
(powermenu) where quit is.
Just my ideas, That I always do first with your skins.

Maybe even preset library folders, so the add to collection works out the
gate too?
I use your add on and skins to make menus out of my emby library since
Eminence 1 days, to create a set-top box experience for me and
family/friends.
I'm pretty stupid compared to you but i'm A lot smarter than most users. I
can see ninety percent of users not even know these features exist

**Comment by jurialmunkey** [comment]
Next version will add a button to the options/power side menu to configure TMDbHelper. 

As part of that change, the side buttons can now be configured in the options menu. (Defaults are Configure TMDbH, Reload Skin, and Quit).
