### ISSUE TITLE
[BUG] Clearlogo sometimes not showing up.

### ISSUE THREAD

**Issue by woodside007** [jurialmunkey/skin.arctic.fuse#133]
### Skin section

Home Widgets

### Current Behavior

Sometimes on random TV shows the clearlogo won't show even though there is one. It shows the text label. If I go into info and select artwork it shows that a clearlogo is already there. If I don't pick anything and just back out it will then show the clearlogo. See attached screenshots.

![Screenshot 2023-09-18 053404](https://github.com/jurialmunkey/skin.arctic.fuse/assets/8515006/5ba636ed-b774-4f27-9ec1-3e5220ee8f14)
![Screenshot 2023-09-18 053436](https://github.com/jurialmunkey/skin.arctic.fuse/assets/8515006/9b0ccb41-3e18-446a-828d-0059f4cfe8aa)
![Screenshot 2023-09-18 053455](https://github.com/jurialmunkey/skin.arctic.fuse/assets/8515006/e8b18c42-a19f-4798-bd95-9b73f8bb5060)

### Expected Behavior

Clearlogo to show instead of text label if there's a clearlogo set.

### Steps To Reproduce

Scroll widgets until you come across one that shows a text label that you think should have a clearlogo. Click on info. Scroll down to select artwork. Click on choose artwork and see there is already clearlogo artwork. Don't choose anything and then back out. Clearlogo shows.

It seems randomly clearlogo isn't being set like it should. If I switch skins to Arctic Horizon 2 clearlogo shows on all shows that have one like it's supposed to.

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by woodside007** [comment]
Here is a video that may also help to explain what's happening.

https://youtu.be/JJlITBi-SJc

**Comment by RentreX** [comment]
@woodside007 this should now be fixed with TMDBHelper v5.1.42

**Comment by jurialmunkey** [comment]
Let me know if this is still happening with v5.1.42 - I think it's likely same cause as #154 based on the screenshot (looks like a single channel logo here, so will be hitting the L to RGBa conversion issue in pillow).
