### ISSUE TITLE
Disable caching on most of skin's menus

### ISSUE THREAD

**Issue by daveftw84** [jurialmunkey/skin.arctic.fuse#137]
### Skin section

Home Widgets

### Feature description

when clicking on a menu like video addons and opening up an addon. if you go back to the home and then try to open video addons again, it will open the last addon you opened. 

### Why is this feature needed? Please justify and explain.

alot of menus are wonky because of this, untill reboot or clear cahce

### Checklist

- [X] I have made a separate issue for each feature I am requesting.
- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by jurialmunkey** [comment]
This is not a skin thing. Its a kodi thing and depends on the path you're using in the ActivateWindow command

if you use a generic path like "videos" then Kodi will only open the videos section but will stay where you were, whereas if you use a specific path like "videodb://movies/titles" then it will go to that specific path.

See here for more info:
https://kodi.wiki/view/Opening_Windows_and_Dialogs

**Comment by daveftw84** [comment]
adding &trickToReload=$INFO[System.Time(hh:mm:ss)] prevents it for me
