### ISSUE TITLE
[Feature] Choose Widget List

### ISSUE THREAD

**Issue by Demonseed-jpg** [jurialmunkey/skin.arctic.fuse#138]
### Skin section

Home Widgets

### Feature description

When customizing your Home Screen, if you go to the Categories section of an item, there’s an option to set a submenu list which automatically creates a submenu-like list on the Home Screen for every item in the list and creates a widget when one is selected.
`Customise item 1 > Categories > Choose submenu list`

This is the first time I’ve seen something like this in a skin and is one of the coolest features of the skin. It would be really cool if there was an option that does the same thing, but instead of creating a submenu, it creates a widget out of every single one. 

I’m not sure if this is possible, but it definitely could be utilized to potentially mess up your performance if you say, pointed it to the genres section of an addon and resulted in a widget for every single genre. Though, I think it would be fair to leave it up to the user to use this responsibly. 

### Why is this feature needed? Please justify and explain.

While technically this can just be done manually by creating each widget individually, I think this could cut down the amount of time required creating a Home Screen - especially if used in conjunction with TMDb Helper Nodes. 

### Checklist

- [X] I have made a separate issue for each feature I am requesting.
- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by jurialmunkey** [comment]
I've had a similar idea before and the main reason I didn't implement it was for exactly what you mentioned about genres - most of the scenarios I could see it being useful to have a dynamically created list of widgets would end up with way too many widgets trying to load at once.

Is there a specific example scenario you have in mind? Because maybe there's a more suitable approach / solution.

**Comment by Demonseed-jpg** [comment]
The idea came to me a few days ago, but I decided not to implement it because of the same issue - users accidentally nuking their performance. Likewise I don’t have too many specific use cases currently as most folders (right terminology?) that have exactly what I want to utilize this.

That being said, your comments on using TMDb Helper’s node feature in #135 prompted the idea of using a feature like this to rapidly build a node curated to exactly a Home Screen I want, and just pointing one widget to it to build an entire catalog of widgets.

**Comment by jurialmunkey** [comment]
I've got some improvements to widget management that are coming soon.

I just pushed one of the changes I've made which effectively makes adding a widget from inside the library/addon much simpler -- essentially the same process as adding a node from the context menu for a folder.

It's still very much in a prototype stage and there's a lot of improvements to come (e.g. making it clearer what you're adding the widget to, and options to delete widgets etc.) -- but it does work for the most part currently and makes it a lot simpler (more like adding a favourite).

**Comment by Demonseed-jpg** [comment]
Thanks, I’ll check it out. I’m in the process of moving into a new house, so it might take me some time. I appreciate the quick turn around!

**Comment by jurialmunkey** [comment]
v0.4 changes to use a new method of widget management (my own script, not skinshortcuts) will mean I should be able to implement this feature.

Working on ironing out the major bugs in v0.4 but then definitely very keen to work on getting this feature in.

**Comment by Demonseed-jpg** [comment]
Thanks Jurial, will look into this asap. Before I download the change from the omega branch, since it’s been some time that you commented, is that still the right place to try this out?

**Comment by jurialmunkey** [comment]
4.0+ is the version in my repo now as main version (also available on releases page as a zip).

I haven't implemented this feature yet, just removed that label because 4.0 is in main branch now and I was using it to tag everything that would need those changes before it'd be possible.

**Comment by jurialmunkey** [comment]
@Demonseed-jpg - It isn't quite the same as the original feature idea but next version will add buttons for "Add list" and "Del list" on the side of the widget customisation dialog. These will allow you to choose a folder of items which will then automatically all the items in that folder as individual entries.

It isn't dynamic -- i.e. it doesn't check for updates. However, it is smart about the items it adds -- i.e. it checks for existing items and only adds the new ones, so updating it is simply a matter of re-selecting the list and it will add anything new.

You can also use the "del list" button to remove links for any items in that folder -- i.e. gives a quick way to undo something, for instance if you add a folder of genres and then decide that you dont actually want 20 genre widgets and don't want to delete each one manually!

I'm not certain how necessary a dynamically monitored list is anymore given that the "add menu" button from the context menu on a folder in the library now makes the process of adding an item to a menu essentially the same as adding to a node.
