### ISSUE TITLE
[Feature] Option to disable the "More..." button at the end of widgets with limit

### ISSUE THREAD

**Issue by AakashC2020** [jurialmunkey/skin.arctic.fuse#140]
### Skin section

Home Widgets

### Feature description

Hi @jurialmunkey,

I've noticed that you've added a "More..." button at the end of widgets which have a limit, in the latest update. Could you please add an option to enable/disable it as it doesn't look good for certain widgets like "Card" style or "Top 10"? See attached screenshot.

### Why is this feature needed? Please justify and explain.

This will provide a user with an option to enable/disable the "More..." button functionality as per their need.

### Screenshots and Additional Info

![IMG20230922210605](https://github.com/jurialmunkey/skin.arctic.fuse/assets/65297828/7cd0457a-996f-4dc4-8ca3-9dc0a914dc41)

### Checklist

- [X] I have made a separate issue for each feature I am requesting.
- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by jurialmunkey** [comment]
This wasnt added by me. It's not part of the skin.

**Comment by AakashC2020** [comment]
> This wasnt added by me. It's not part of the skin.

Hi @jurialmunkey,

Oh that's weird! I'm using only TMDb Helper add-on for widgets along with the Arctic Fuse Skin. My Kodi version is v21 Omega Alpha 3. That "More..." button was not there even a few days back. I'm really not able to understand how it came. I've to check then what has changed since it was not added by you. The widget row which I've showed in the screenshot came from the "Most Watched" section under the TMDb Helper add-on. Any suggestions? I can share my log file if you want but I'm not sure if that will help in any way. Kindly advise if possible.

**Comment by jurialmunkey** [comment]
Kodi core change https://github.com/xbmc/xbmc/pull/23682

**Comment by AakashC2020** [comment]
> Kodi core change [xbmc/xbmc#23682](https://github.com/xbmc/xbmc/pull/23682)

Hi @jurialmunkey,

Thank you for checking and for investigating on this! I can see that you've already asked in the Kodi thread about this. Hope some resolution is provided by them. I'll watch this space and the other thread as well for more updates on this. Thank you for your quick response!

**Comment by DROIDshield** [comment]
Thank can be switched off in TMDB helper, it's  the Show next button. If you use poster mode in the skin it will show the arrow for next or more... but if you are using card mode in the skin if the skin... it shows as an empty box but it still works to get another list of widgets once pressed.

If you don't want it, switch it off in TMDB helper im not infront of my tv atm but I believe its the show next in the helper settings.

**Comment by jurialmunkey** [comment]
@DROIDshield - No it's a new Kodi v21 skinning engine feature which applies to all limited lists regardless of skin.

The "Show More" feature you're talking about is an AH2 feature and isn't in this skin.

The new Kodi v21 change means that effectively now **all** skins have that feature natively now. The problem, however, is that currently it cannot be disabled.

**Comment by DROIDshield** [comment]
Oh wow... I will check again when I get in as I'm not using Kodi v21 and I had it using Fuse and got rid of it.. could it be because I'm using a Nvidia Shield (Android) and not PC?🤔

I will check when I get in and let you know.. 👍

**Comment by DROIDshield** [comment]
Yeah I'm still running v20 and that box is there, but I disabled the next page item in TMDB helper to get rid of it.  Didn't know v21 was out. But a man of your brain power.. I'm sure you'll workout a fix to work around it...

![20230923_225110](https://github.com/jurialmunkey/skin.arctic.fuse/assets/97023369/37265941-f3db-4e70-ac73-c0bea6187915)

**Comment by derrgoo** [comment]
I don't mean to hi Jack this thread but was wondering while trying 21 kodi the only issue I found that the still watching or progress mark is partly cut off. Not that it matter a much but thought I would point that out. Everything else working. 👍

**Comment by xyzfre** [comment]
> I don't mean to hi Jack this thread but was wondering while trying 21 kodi the only issue I found that the still watching or progress mark is partly cut off. Not that it matter a much but thought I would point that out. Everything else working. 👍

I experienced the same behavior on 21 with the progress icons with any other plug-in, so I reverted back to Nexus

**Comment by AakashC2020** [comment]
Hi @jurialmunkey,

Thank you so much for adding this option in the Settings! It's really awesome! 🙂👍🏻
