### ISSUE TITLE
[Feature] 'Forget' position of items in widgets.

### ISSUE THREAD

**Issue by ersan** [jurialmunkey/skin.arctic.fuse#144]
### Skin section

Home Widgets

### Feature description

It would be nice to have the option to have all widgets reset their item position to the first item after changing between menus (ex home, movies, tv shows, etc.), instead of remembering which item you were on.

Also it would reset the position to the top widget when changing menus.

### Why is this feature needed? Please justify and explain.

I'm switching over from Plex and this is how it works so it feels more natural to me.  It's simply jarring to not have them reset their positions.

### Checklist

- [X] I have made a separate issue for each feature I am requesting.
- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by woodside007** [comment]
+1 on this.

**Comment by jurialmunkey** [comment]
Would the position reset *only* when opening from a menu item? Or would it also reset when returning from opening a widget?

e.g. You have a widget showing TV shows and you scroll down to click one and open the seasons. When you press back, does it go back to the widget or back to the top of the hub?

What about after playback? 
e.g. You have a widget showing Movies and you scroll down to click one and start playing it. If you press back from the OSD, does it go back to the widget or back to the top of the hub?

**Comment by jurialmunkey** [comment]
This is proving difficult to implement.

I can reset the position back to the top (categories) without too much difficulty. However, so far I haven't figured out any way to reset the widget grouplist -- so you get this annoying behaviour where it looks like it reset but when you scroll down from the menu, you go back to whatever widget you were on previously rather than the top one.
