### ISSUE TITLE
[Feature] Limit on submenu widgets

### ISSUE THREAD

**Issue by RentreX** [jurialmunkey/skin.arctic.fuse#147]
### Skin section

Home Widgets

### Feature description

Being able to limit how many items are shown on submenu widgets like what can be done with normal widgets

### Why is this feature needed? Please justify and explain.

On Google TV with Chromecast having unlimited sized widgets makes Kodi lag and sometimes crash.

I have tested with normal widgets and having a limit above 20 will start lagging the system when scrolling through the items.

### Checklist

- [X] I have made a separate issue for each feature I am requesting.
- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by jurialmunkey** [comment]
I'd actually already added the limit but I forgot to add the button in the config dialog to set it! Button in next release.
