### ISSUE TITLE
[Feature] hide man menu

### ISSUE THREAD

**Issue by MisterSmellvedere** [jurialmunkey/skin.arctic.fuse#148]
### Skin section

Home Widgets

### Feature description

ability to hide main menu after choosing main menu item would be awesome. otherwise, nearly perfect skin. skin rules.

### Why is this feature needed? Please justify and explain.

for looks mainly. im guessing it could lead to burn in issues in some oled tvs if you browse your library for a year staight. but really its only needed cause i think it would be cool.

### Checklist

- [X] I have made a separate issue for each feature I am requesting.
- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

im an idiot, sorry if this was already requested. im new here and thought i had checked in the right place, i didnt not see the previous hundred some odd other comments..... will try to figure out how to delete.

**Comment by jurialmunkey** [comment]
It's not quite the same, but you can get a somewhat similar effect with:
`Skin Settings > Menus > Menu Style > Pull-out Menu (Button)`

That will condense the side menu down to a single button which when clicked opens a menu to switch.

**Comment by MisterSmellvedere** [comment]
thanks for the reply. yes i noticed that option was there a few updates ago if i am correct. your the man.

**Comment by jurialmunkey** [comment]
Next update will also allow for pressing up/down to quickly expand out the menu icons (and clicking will still open the larger side panel on the right).

I think this in effect gives the same behaviour as autohide, so I'll close this one.

**Comment by booyakafoo** [comment]
Hi Jurialmunkey,  Was the setting for Pull-out menu removed?  I can't find it.  Or maybe I misunderstood this persons request. 
 Preferably, I would like for the "Menu" to slide in and out when accessed.  Is that already an option somehow?

![l3X1oF9](https://github.com/jurialmunkey/skin.arctic.fuse/assets/3913228/0d963778-0760-4e89-a4e8-8275fd468b5e)
