### ISSUE TITLE
[Feature] date format for Up Next addon

### ISSUE THREAD

**Issue by RentreX** [jurialmunkey/skin.arctic.fuse#149]
### Skin section

Other

### Feature description

I am not sure if this is a skin issue or the addon

When using the Up Next add-on, the date displayed is currently yyyy-mm-dd (yyyy-dd-mm)

If it is a skin issue, is there any chance to have an option to change it to dd-mm-yyyy (mm-dd-yyyy)

### Why is this feature needed? Please justify and explain.

To be able to have it more readable

### Screenshots and Additional Info

![20231005_020910](https://github.com/jurialmunkey/skin.arctic.fuse/assets/60731904/da60edcb-9cf2-4b06-890c-e260caba3b62)

### Checklist

- [X] I have made a separate issue for each feature I am requesting.
- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by jurialmunkey** [comment]
This is filled by the addon. It just provides a single  property which contains the full date preformatted, so no way for the skin to adjust it afaik.
