### ISSUE TITLE
[Feature] Is there a way to change icons & text of Home, Movies, etc?

### ISSUE THREAD

**Issue by cg00001** [jurialmunkey/skin.arctic.fuse#150]
### Skin section

Other

### Feature description

Be able to change icons & text of Home, Movies, etc.

### Why is this feature needed? Please justify and explain.

I need other names & icons.

### Checklist

- [X] I have made a separate issue for each feature I am requesting.
- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by jurialmunkey** [comment]
Skin settings - menus.

Change type to custom and you can make the shortcut whatever you like.

**Comment by cg00001** [comment]
Thank you, I found it.
From what I understood, Search and Home can not be removed or changed.
