### ISSUE TITLE
[Feature] Bring back the "combined" view

### ISSUE THREAD

**Issue by ditydot** [jurialmunkey/skin.arctic.fuse#153]
### Skin section

Home Widgets

### Feature description

Combined view was a lot cleaner looking than the views the other hubs have, which made it ideal for being on the home hub.

### Why is this feature needed? Please justify and explain.

Simpler and more pleasing to look at. Having submenus makes it more cluttered.

I tried removing all the submenus and disabling the "<none>" dummy entry, but it leaves a large blank space between the category and the first category widget.

### Checklist

- [X] I have made a separate issue for each feature I am requesting.
- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by jurialmunkey** [comment]
Oops I forgot to push a commit. Will be fixed in next release.

Combined view is now handled automatically depending on whether or not submenu items are available.
