### ISSUE TITLE
[BUG] Adding Youtube widgets

### ISSUE THREAD

**Issue by RentreX** [jurialmunkey/skin.arctic.fuse#156]
### Skin section

Home Widgets

### Current Behavior

When trying to add youtube channels (using nodes)to a widget an error pops up.

the error is Mapping for path '/channel/*****/&widget=true&reload=&reload=' not found.

This was not a issue about a week ago when I setup another device (though I had to do a clean install and have not tried again on that device yet)

### Expected Behavior

For error to not occur

### Steps To Reproduce

using the youtube addon.

put channel(s) into a node.

to go settings and try to had the channel as a widget

### Screenshots and Additional Info

![youtube](https://github.com/jurialmunkey/skin.arctic.fuse/assets/60731904/ea0622a1-a17a-4b1b-9f02-e0aa0fe0a749)

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by RentreX** [comment]
If you favourite the channel and use the widget from the favourites section then it works as intended

**Comment by jurialmunkey** [comment]
This is related to how TMDbHelper interacts with SkinShortcuts.

If you enter TMDbHelper via SkinShortcuts, it will add some additional params for widget management functions. If you try to open a node that way, you'll get unexpected behaviour due to the added values.

I should be able to add a check to avoid this.
