### ISSUE TITLE
[BUG] Gaia results not appear

### ISSUE THREAD

**Issue by Nevrdid** [jurialmunkey/skin.arctic.fuse#160]
### Skin section

Home Widgets

### Current Behavior

Hi, I installed your skin yesterday and really like it. 
I however noticed quickly that when i use gaia, the source finding window pop but right after the results are not display.
No matter if i use tmdbhelper or directly from gaia the results not display.

### Expected Behavior

Show the results.

### Steps To Reproduce

1. Install [gaia 6.4.3](https://github.com/gaiakodi/gaiamain/tree/master/plugin.video.gaia)
2. Execute gaia wizard
3. Search for anything
4. Wait for the research to finish
5. Nothing

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
Sorry, I cannot assist with banned addons and will not be installing banned addons to test things.

You will need to speak with the addon author.
