### ISSUE TITLE
[BUG] Issue again with scrolling through customising menu

### ISSUE THREAD

**Issue by RentreX** [jurialmunkey/skin.arctic.fuse#162]
### Skin section

Other

### Current Behavior

An issue that is pretty much the same as posted before:
https://github.com/jurialmunkey/skin.arctic.fuse/issues/155

Though now it is happening with the following:

In customise home menu - categories and widgets - submenu (scroll to "label" then try to scroll one more to "use as widget". It will go to "style" instead.)

In customise movies - categories (scroll to "choose spotlight" then try to scroll down one more to "choose submenu list". It will go to "style" instead.)

In customise tv shows - categories (scroll to "choose submenu list" then try to scroll to "customise fallback submenu". It will not let you scroll.)

I have not tested it with other customised hubs as I do not have any others at this point.

### Expected Behavior

To be able to scroll through the menus correctly 

### Steps To Reproduce

As above 

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
Is this still happening with 0.3.2 onwards?

Fairly sure I fixed it during that update but I'll wait for you to confirm before I close this one.

**Comment by RentreX** [comment]
It is working perfectly in 0.3.3
