### ISSUE TITLE
[BUG] submenu default selection

### ISSUE THREAD

**Issue by RentreX** [jurialmunkey/skin.arctic.fuse#164]
### Skin section

Home Widgets

### Current Behavior

When you go down from the category to submenu on the home/tv/movie ect screen it highlights the second tab from the left.

### Expected Behavior

Got the far left submenu to be highlighted

### Steps To Reproduce

Create a submenu for the home screen.

Go down one from the category list to the submenu list.

The far left submenu will not be selected by default 

### Screenshots and Additional Info

This was not a issue in past versions. Though I am not sure which update changed this

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
Whilst not identical, this is the same underlying cause/issue as #157 -- so I'll close this one and rename the other issue to cover this one too.

At the moment I don't think there's a fix which doesn't sacrifice other functionality -- i.e. going back to the old approach will sacrifice workable mouse/touch functionality and the ability to differentiate between a list on first item and a list which has more items to the left.
