### ISSUE TITLE
[BUG] [Or me being stupid] Update single music artist information

### ISSUE THREAD

**Issue by dm2912** [jurialmunkey/skin.arctic.fuse#165]
### Skin section

Music Info Dialog

### Current Behavior

At the moment, I see no way to update or refresh the information for a single music artist following update of its local nfo etc. Only "refresh information for all artists"

### Expected Behavior

Arctic Horizon you could go into information, refresh, and then it could refresh from local nfo or internet. 

(maybe I am just blind)

### Steps To Reproduce

go to artists
then either try and refresh a single artists information or go to info and try and refresh

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by dm2912** [comment]
Just to clarify, in Artic Horizon, under information you also have a "Manage" option

which then gives options to refresh, my rating, choose art

so on a single artist if you are using artist information folder and your own nfo's you can then refresh and choose over local information or internet to refresh one artist

only option in AF seems to be refresh all

**Comment by jurialmunkey** [comment]
Click the gallery icon (bottom one). Should be able to select art and refresh metadata from there (unless you're saying it's missing from there?)

**Comment by dm2912** [comment]
> Click the gallery icon (bottom one). Should be able to select art and refresh metadata from there (unless you're saying it's missing from there?)

I can choose art type from there, but not seeing any metadata refresh option. 

Its generally artists where I have done a manual nfo because there bios were not on audiodb (and I have not got round to adding them to there yet)

**Comment by jurialmunkey** [comment]
Yep you're right. Now that I'm in front of the computer realised I was only showing those options in videoinfo not musicinfo.
