### ISSUE TITLE
Pressing on addon in settings-addon menu causes kodi crash

### ISSUE THREAD

**Issue by patkino** [jurialmunkey/skin.arctic.fuse#17]
### Skin section

Other

### Current Behavior

Kodi crash on pressing on addons (tried pvr.iptv.simple and tmdbhelper

### Expected Behavior

Normal

### Steps To Reproduce

Go to settings - addons- my addons - video - tmdbhelper, click on it

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
I also can't reproduce this issue either. 

Do you have a stacktrace crash log?

**Comment by patkino** [comment]
I'll try, but I'm not too advanced.
I guess it night be related to aarch64 coreelec nightly architecture. 
But ah2 and estuary run well

**Comment by taiseer999** [comment]
same issue
[01_KODI_CRASH.log](https://github.com/jurialmunkey/skin.arctic.fuse/files/12915959/01_KODI_CRASH.log)

**Comment by jurialmunkey** [comment]
@taiseer999 - Thanks for the crash log, that's useful.

From the stack trace, it looks like CoreElec has some issue with doing string comparisons on labels retrieved from other controls and/or using special characters (I do a check for `(*)` which is what enabled radio buttons return as a label).

To test this hypothesis, can you remove this block of code from DialogAddonInfo.xml then reload the skin and see if you still have the crash
https://github.com/jurialmunkey/skin.arctic.fuse/blob/f63da69e27acfe987935842c129f49d7ce3f3c81/1080i/DialogAddonInfo.xml#L219-L224

Want to confirm that is actually the cause before I go further. If it is, I can look for a workaround but it should also be reported to the CoreELEC guys as the skin is not actually doing anything "wrong" per se (just a bit unconventional).

**Comment by taiseer999** [comment]
@jurialmunkey  thank you so much for taking the time , following the instructions and result is:
Clicking on addons in the file browser section does not hang Kodi anymore but it does not take you anywhere , the context menu shows on long pressing but clicking information does return anything while all other items in menu work(disable, settings , add to favorites)
Thanks again

**Comment by jurialmunkey** [comment]
@taiseer999 - That definitely shouldn't happen --- it should show the info panel but with the side buttons missing. It sounds like you might've accidentally deleted something you shouldn't and the xml is no longer valid

To be sure, use this modified version. I tested it myself so I know it definitely works.

https://gist.githubusercontent.com/jurialmunkey/8c4861e16fbd21e9b12f14dca1b8b8f3/raw/48d33e196fa807fa3a0ae7cb79c695924aa6e60c/DialogAddonInfo.xml

**Comment by taiseer999** [comment]
no cigar :(
[01_KODI_CRASH.log](https://github.com/jurialmunkey/skin.arctic.fuse/files/12981151/01_KODI_CRASH.log)

**Comment by jurialmunkey** [comment]
@taiseer999 - I think that's going to need to be reported to CoreELEC guys then. Looking a bit closer at the stack trace, I think there's some issue introduced with building includes in skinxml

> What is strange that this issue does not occur within AH2.

Not that strange. It will be some type of error not being handled correctly -- for example, Kodi used to have an issue where if an include ended up with a `condition=""` attribute from a blank param then it would segfault because it couldn't decide if blank equals True or False -- it will be some very specific sequence of includes/params creating a circular reference or unexpected value that hasn't been handled well.

I think the thing to do would be to figure out which nightly it started occurring in, then that will give a pretty good clue as to which specific changes brought it about (i.e. narrows down the range of commits)

**Comment by taiseer999** [comment]
Thank you for your feedback, I will report this to Coreelec

**Comment by jurialmunkey** [comment]
@taiseer999 - I installed LibreELEC nightly in a virtual machine and I think I discovered the issue.

These three lines are the culprits (list=50 is the builtin screenshot gallery -- not sure why LibreELEC is freaking out about it)
https://github.com/jurialmunkey/skin.arctic.fuse/blob/d18f593699067dd33668e976c50a9646c6179266/1080i/DialogAddonInfo.xml#L66
https://github.com/jurialmunkey/skin.arctic.fuse/blob/d18f593699067dd33668e976c50a9646c6179266/1080i/DialogAddonInfo.xml#L71
https://github.com/jurialmunkey/skin.arctic.fuse/blob/d18f593699067dd33668e976c50a9646c6179266/1080i/DialogAddonInfo.xml#L82

If you comment those out it won't crash (at least that solved it for me on LibreELEC).

**Comment by jurialmunkey** [comment]
Even more specifically, it appears to be the use of  `<aspectratio>scale</aspectratio>` in those image controls.

That definitely should be reported to CoreELEC/LibreELEC guys as definitely shouldn't happen.

**Comment by jurialmunkey** [comment]
Okay, think I might've narrowed it down.

Looks like some combo of using a flat `<nested />` include tag not inside a group, the aspectratio tag, and image controls.

The above commit "fixes" for me in my virtual machine on LibreELEC nightly (essentially is a workaround by wrapping the include in a group).

Really weird bug...

**Comment by taiseer999** [comment]
No freezing now in addon browser section 
Clicking on an addon now opens a new window missing options like run/disable/ etc
![IMG_0804](https://github.com/jurialmunkey/skin.arctic.fuse/assets/118752825/272f1c39-58d9-4db5-80f2-40d15232334e)

**Comment by taiseer999** [comment]
[v0.3.4] :(
[01_KODI_CRASH.log](https://github.com/jurialmunkey/skin.arctic.fuse/files/13024999/01_KODI_CRASH.log)

**Comment by jurialmunkey** [comment]
@taiseer999 - According to your log, you're still on 0.3.3 not 0.3.4

> 2023-10-18 11:56:46.741 T:13011    info <general>: CAddonMgr::FindAddons: skin.arctic.fuse v0.3.3 installed

**Comment by taiseer999** [comment]
Confirming that it works like a charm now with version .34

**Comment by jurialmunkey** [comment]
Great thanks for confirming. 

Now that I know how to reproduce the issue, I'll make up a test case using Estuary so that I can report the underlying bug -- because a skin definitely shouldn't be able to create crashes like this. At worst, the includes builder should simply ignore the problematic code -- but ideally it should work as expected.
