### ISSUE TITLE
[BUG] Focused submenu not creating widgets

### ISSUE THREAD

**Issue by YorkshireTom** [jurialmunkey/skin.arctic.fuse#173]
### Skin section

Home Widgets

### Current Behavior

Created a category and then used a dynamic list as the submenu, with option use as widget. 

The submenu displays on the home screen, but no widgets are created and/or displayed. 

I am trying to use a TMDB node and also tried to replicate the “Movies” category configuration under the “Movies” hub but does not work.

### Expected Behavior

As per description of Categories on the skin setting menu: The use as widget option will display items from the focused submenu in a widget below.

### Steps To Reproduce

> Go to settings
> Customise home page
> Categories 
> Create new category
> Choose submenu
> Select dynamic list
> Select a TMDB helper submenu
> Use as widget
> Return to home page
> No widgets displayed for created category 

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by YorkshireTom** [comment]
Just to update, I followed the same steps as above but on the default movies hub, the widgets get created successfully.

**Comment by jurialmunkey** [comment]
If you've got no other standard (non-submenu) widgets in the category, sometimes you need to add a blank widget to get skinshortcuts to build the category. The easiest way is to go in to the widgets selection, choose any normal widget but then disable it (but not delete). I haven't found any other way to force it to build without adding any widgets.

**Comment by jurialmunkey** [comment]
Should be addressed by v0.4 which no longer uses skinshortcuts at all and uses a new script I've developed for managing shortcuts. 

Preview available in omega testing branch (note because it doesn't use skinshortcuts it wont inherit old setup -- but also wont delete it so should be able to rollback)

https://github.com/jurialmunkey/skin.arctic.fuse/archive/refs/heads/omega_testing.zip
