### ISSUE TITLE
[BUG] Navigation > content > on left action does not save

### ISSUE THREAD

**Issue by YorkshireTom** [jurialmunkey/skin.arctic.fuse#174]
### Skin section

Home Widgets

### Current Behavior

Changing the default navigation action for “Content > OnLeft” to menu does not save when restarting Kodi. The setting will persist only until you exit. It then resets to loop.

This seems to be the only one not persisting. 

### Expected Behavior

Changing the onleft action to menu should persist.

### Steps To Reproduce

> Skin settings
Navigation 
Content>OnLeft
Select Menu
Home
Go to content
Press left > goes to menu
Exit kodi
Launch kodi
Go to content
Press left > loop
Go to Skin Settings
Navigation
Note Content>OnLeft = Loop

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
Ah I made a typo. If the "Menu > Onleft" action was empty it was setting its default value to "Content > Onleft" instead of itself.
