### ISSUE TITLE
Widget spacing

### ISSUE THREAD

**Issue by adamosborne83** [jurialmunkey/skin.arctic.fuse#179]
### Skin section

Home Widgets

### Feature description

Apologies in advance, I am trying to switch from AH2 to Fuse, very different skins, but, as I can see updates are limited, I feel I need to take the jump.... rambling over....

Is there a way on widgets so the widget beneath does not show?

### Why is this feature needed? Please justify and explain.

Helps my OCD with spaces 😀

### Screenshots and Additional Info

Video below shows what I mean

https://github.com/jurialmunkey/skin.arctic.fuse/assets/78307374/8132c032-53d3-4159-980f-6191fbb52d27

This shows it through addon, which I think looks better

https://github.com/jurialmunkey/skin.arctic.fuse/assets/78307374/e370dde5-81b9-4ba2-ab86-3372cbfcd92d

### Checklist

- [X] I have made a separate issue for each feature I am requesting.
- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by jurialmunkey** [comment]
`Skin Settings > Menus > Home > Combine widget stack`

That creates a single widget with a selector underneath similar to combined views in the library.

**Comment by adamosborne83** [comment]
Yea, I actually saw a video someone posted a video last night on Reddit and I did enquire.

I'm going to give it another go tonight, feel I need to move away from AH2.

Thanks as always though.
