### ISSUE TITLE
[Feature] spotlight button icons

### ISSUE THREAD

**Issue by A30B06** [jurialmunkey/skin.arctic.fuse#181]
### Skin section

Home Widgets

### Feature description

This one will totally be down to total preference, but do you think the spotlight play and more information icons could be more greyscale/not as white when not selected? I quite often think I have the play button selected when it’s not

### Why is this feature needed? Please justify and explain.

Makes it confusing to know what button is currently highlighted

### Checklist

- [X] I have made a separate issue for each feature I am requesting.
- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by jurialmunkey** [comment]
Are you using an inverted highlight colour? Because I otherwise it seems fairly clear which button is focused

![image](https://github.com/jurialmunkey/skin.arctic.fuse/assets/4618719/0eefbbd1-934e-49cb-9ac1-b3e70f2abef3)


Inverted colour scheme definitely has some bug/work needed though.

**Comment by jurialmunkey** [comment]
If this is only an issue with inverted color schemes (i.e. where highlighted text becomes dark - e.g. monochrome highlight) then I can address that specifically for inverted -- but want to make sure that is the issue here and not something else before going further

**Comment by A30B06** [comment]
Ohh it is obviously clear when you have a coloured highlight 🤦🏼‍♂️ when I loaded the skin the first thing I done was to make the highlight colour white. This then makes it hard to differentiate.![image](https://github.com/jurialmunkey/skin.arctic.fuse/assets/149116005/ecf475bd-ec83-45ef-b24e-a7d682ae0003)
