### ISSUE TITLE
Options 

### ISSUE THREAD

**Issue by adamosborne83** [jurialmunkey/skin.arctic.fuse#182]
### Skin section

Home Widgets

### Feature description

Sorry, 2 little requests.

Can you add the ability to change colour of Watched items.

Also, ability to turn off footer ie codecs

### Why is this feature needed? Please justify and explain.

I cannot justify it, I just like ability to make things 'cleaner'

### Screenshots and Additional Info

![firetv_2023-10-29_10_05_58](https://github.com/jurialmunkey/skin.arctic.fuse/assets/78307374/c2713b42-e116-45ce-b05d-9b3c8c151f1e)
![firetv_2023-10-29_10_06_14](https://github.com/jurialmunkey/skin.arctic.fuse/assets/78307374/925bb128-3a25-48b0-a7e4-09fe51d94b81)

### Checklist

- [X] I have made a separate issue for each feature I am requesting.
- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by jurialmunkey** [comment]
Indicator colour can be changed in the colour customisation dialog.

`Skin Settings > Appearance > Customise highlight colours > Customise > Indicator`

**Comment by adamosborne83** [comment]
Brilliant, thank you.

I know I should had created another 'enhancement' but is it possible to have full customisation on the footer so it doesn't show providers etc?

**Comment by jurialmunkey** [comment]
Provider icons can be disabled in TMDbHelper settings

**Comment by adamosborne83** [comment]
> Provider icons can be disabled in TMDbHelper settings

Sorry, and you know I'm usually good at this, but for the life of me, I cannot see that option.....

**Comment by adamosborne83** [comment]
Found it...

**Comment by onlytanmoy** [comment]
> Found it...

can you please share a screenshot to refer to? :)

**Comment by onlytanmoy** [comment]
> Found it... BUT when I click them off and 'ok' it, it doesn't save it.
> 
>  firetv_2023-10-29_15_05_21.mp4

Did you try doing this and then check?
![image](https://github.com/jurialmunkey/skin.arctic.fuse/assets/48493659/0458c4e0-2ef8-4902-a201-e39dd7955871)
