### ISSUE TITLE
'None' item in widgets

### ISSUE THREAD

**Issue by adamosborne83** [jurialmunkey/skin.arctic.fuse#184]
### Skin section

Home Widgets

### Current Behavior

Apologies for the spam, as I am sure you can guess I am playing with this skin.

After watching a program or trailer, the start of all widgets have a 'none' poster.

### Expected Behavior

Not to display this item

### Steps To Reproduce

Watch anything

### Screenshots and Additional Info

https://github.com/jurialmunkey/skin.arctic.fuse/assets/78307374/1c82e866-1796-4d45-b1f5-103c0667154f

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by bassemhelal18** [comment]
I got the same issue android tv

**Comment by jurialmunkey** [comment]
It is related to #116 

The None item needs to be displayed whilst the widget is reloading otherwise one of two things happen: (1) the bug in that issue; or (2) the widget never reloads because it has no items and so permanently hides.

Current behavior is not ideal but so far I haven't found a better solution.

**Comment by jurialmunkey** [comment]
I believe this should be fixed for the most part in v0.4 which will be released in next couple of days.

You can get a preview of the new version from the Omega testing branch:
https://github.com/jurialmunkey/skin.arctic.fuse/archive/refs/heads/omega_testing.zip
 
Note that v0.4 no longer uses the SkinShortcuts addon at all. Which means it will not inherit your current setup as the new widget system uses an entirely different script (it won't delete your old shortcuts setup, so you can still rollback to an earlier version).

**Comment by adamosborne83** [comment]
Good Morning,

I thought you'd been quiet, so had been working on something major, and indeed you have. 
I will test and play today. Thank you

**Comment by adamosborne83** [comment]
> I believe this should be fixed for the most part in v0.4 which will be released in next couple of days.
> 
> You can get a preview of the new version from the Omega testing branch:
> https://github.com/jurialmunkey/skin.arctic.fuse/archive/refs/heads/omega_testing.zip
>  
> Note that v0.4 no longer uses the SkinShortcuts addon at all. Which means it will not inherit your current setup as the new widget system uses an entirely different script (it won't delete your old shortcuts setup, so you can still rollback to an earlier version).

OK, found a bug, didn't know if you wanted a new bug raised or not, as it's not released, so did not know if you wanted the masses on it already.

https://imgur.com/a/IEwZ0pj

Here you can see what I mean, apologies for it being off my phone, it seems your skin doesn't play well with my screen recorder.
Odd.

**Comment by adamosborne83** [comment]
Here is another example. 

https://imgur.com/a/gqUfP9m


Also, is there a way to turn off the warnings?

**Comment by adamosborne83** [comment]
Also, whilst adding, shouldn't it add a blank? Not duplicate 

https://imgur.com/a/YDe3OVY

**Comment by adamosborne83** [comment]
Also, Spotlights.... so my set up is Home... spotlight none...edit categories..... movies (what I made) edit spotlight... tmdbh (then my trakt list) Nothing then shows.

**Comment by jurialmunkey** [comment]
Why are you trying to delete all the items in the menu?

Script deliberately regenerates the menu file from the skin default if there are no items. Otherwise you would get stuck with no items.

Also I don't see the issue about duplicating rather than creating a blank item? Why is that a problem?

**Comment by adamosborne83** [comment]
> Why are you trying to delete all the items in the menu?
> 
> Script deliberately regenerates the menu file from the skin default if there are no items. Otherwise you would get stuck with no items.
> 
> Also I don't see the issue about duplicating rather than creating a blank item? Why is that a problem?

So, let's use side menu for example.
I like just to have my 3 icons Quit, Settings, Reload.
I wish to do away with Favourites below and Quit on the right. 

![20231119_102318.jpg](https://github.com/jurialmunkey/skin.arctic.fuse/assets/78307374/21b85f5a-2304-40ae-8bed-fa6d8657c14c)

Also, when adding new categories it copes the entire folder and what's included, then that means I would need to go into it and edit it to actually do what is expected 

https://imgur.com/a/UdAG9hL

**Comment by jurialmunkey** [comment]
Latest changes on Omega testing branch combined with [v2.0.2 of SkinVariables](https://github.com/jurialmunkey/script.skinvariables/releases) will now allow this.

Delete warning is removed. Ability to delete all items added. Ability to disable items in power menu. Adding will create a new item rather than copy it.

BTW if you use the padlock to unlock the menus and then press rebuild, you'll now be able to use context menu directly on the categories and sidemenu on the home screen to live edit the items. 

It's slower to load in unlocked mode, so you should definitely lock and rebuild once you're done editing -- but it's really useful for configuring the basics "live" without having to go back and forth:

![screenshot00225](https://github.com/jurialmunkey/skin.arctic.fuse/assets/4618719/d47dc1fc-3669-42ee-8fc2-a296a0c207e6)

**Comment by adamosborne83** [comment]
> Latest changes on Omega testing branch combined with [v2.0.2 of SkinVariables](https://github.com/jurialmunkey/script.skinvariables/releases) will now allow this.
> 
> Delete warning is removed. Ability to delete all items added. Ability to disable items in power menu. Adding will create a new item rather than copy it.
> 
> BTW if you use the padlock to unlock the menus and then press rebuild, you'll now be able to use context menu directly on the categories and sidemenu on the home screen to live edit the items. 
> 
> It's slower to load in unlocked mode, so you should definitely lock and rebuild once you're done editing -- but it's really useful for configuring the basics "live" without having to go back and forth:
> 
> ![screenshot00225](https://github.com/jurialmunkey/skin.arctic.fuse/assets/4618719/d47dc1fc-3669-42ee-8fc2-a296a0c207e6)
> 
> 
> 

OK, now the ability to ADD has disappeared all together 

https://imgur.com/a/0S4E2r2


Also, spotlight is the same on all, regardless of what has been set up. Was ok prior to this.

https://imgur.com/a/Aztsei8

**Comment by jurialmunkey** [comment]
> OK, now the ability to ADD has disappeared all together

You must choose a shortcut to add one.

**Comment by adamosborne83** [comment]
> > OK, now the ability to ADD has disappeared all together
> 
> You must choose a shortcut to add one.

No, it seems to just change it

https://imgur.com/a/p9X1spc

**Comment by adamosborne83** [comment]
Latest update allowed me to add new, thanks. 
Spotlights still not working, even after recreating.
Thanks again though,

**Comment by jurialmunkey** [comment]
Just pushed something which should fix spotlight. Forgot to add the visibility condition to the locked mode so it was only working when unlocked.

**Comment by adamosborne83** [comment]
> Just pushed something which should fix spotlight. Forgot to add the visibility condition to the locked mode so it was only working when unlocked.

OK, we seem to be back in action with spotlights. 
1 more thing,obviously, on maybe 5 or 6 occasions (no pattern) top light hand corner, Alarm notification pops up.... never seen that before.

**Comment by Uka-Uka** [comment]
@adamosborne83 How many times have you received compliments about your wallpaper?
