### ISSUE TITLE
[Query] Love the skin & 2 queries

### ISSUE THREAD

**Issue by onlytanmoy** [jurialmunkey/skin.arctic.fuse#185]
### Skin section

Home Widgets

### Feature description

First things first, really enjoying this new skin, so very refreshing UI, great work as always mate 👍

2 quick queries:
a) When I reload the skin and go to say any of the menus I see the focus always goes on the 2nd widget tab instead of the 1st widget. Have you noticed that?
b) When I switch the menu and the widgets refreshes, it shows on the top - None, info, Kodi (IP address), Version, any way to stop that from being shown?

### Why is this feature needed? Please justify and explain.

Queries for now

### Checklist

- [X] I have made a separate issue for each feature I am requesting.
- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by adamosborne83** [comment]
1. This is a kodi bug, see issue already raised https://github.com/jurialmunkey/skin.arctic.fuse/issues/157

2. You could add a spotlight to stop it showing up ![firetv_2023-10-29_10_11_39.jpg](https://github.com/jurialmunkey/skin.arctic.fuse/assets/78307374/06a9681d-0a85-4a5d-ac51-a10c06da0f68)

**Comment by onlytanmoy** [comment]
@adamosborne83 thanks for your responses.
For 2 - you mean I can add a spotlight along with my existing widgets? never tried a spotlight before haha, possible to share a screen record please?

**Comment by adamosborne83** [comment]
> @adamosborne83 thanks for your responses.
> For 2 - you mean I can add a spotlight along with my existing widgets? never tried a spotlight before haha, possible to share a screen record please?

https://github.com/jurialmunkey/skin.arctic.fuse/assets/78307374/04bb196a-160c-4648-9d37-7805ed5d7d50

It also auto scrolls the movies, orwhatever you point it too.
