### ISSUE TITLE
Context menu on spotlight 

### ISSUE THREAD

**Issue by adamosborne83** [jurialmunkey/skin.arctic.fuse#187]
### Skin section

Home Widgets

### Feature description

I use tmdbh for my trakt lists for Spotlight, would it be possible to enable context menu on this?

### Why is this feature needed? Please justify and explain.

Context menu is always good on movies etc

### Checklist

- [X] I have made a separate issue for each feature I am requesting.
- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by jurialmunkey** [comment]
Unfortunately there's no way in the skinning engine to capture the context menu action. The only possibilities are onclick oninfo and onback (and directions).

**Comment by adamosborne83** [comment]
OK, thanks for that.
Not that I will understand, but, how was it possible on ah2? 
Thanks as always.

**Comment by jurialmunkey** [comment]
Oh you mean a button on screen that is specifically to open the context menu - that's possible. 

I thought you were saying to press the context menu button on your remote and have it work for the spotlight (e.g. while on the play button) -- that's not possible.

**Comment by adamosborne83** [comment]
Sorry thus is why I'm better with pictures, even if people laugh at me.....


So scenario is, as the spotlight movies are scrolling across,  I sometimes like to change the artwork, 

So I would hit the context button on my remote, which then gives me the ability to change the artwork there and then.

The work around is that I go directly into my trakt list through tmdbhelp and change them that way, but easier to do it from spotlight when I see the movie.

Hope Ive explained it better

**Comment by jurialmunkey** [comment]
As I mentioned, using the context menu button on your remote on the spotlight is not possible. 

This wasn't possible in AH2 either.

**Comment by adamosborne83** [comment]
OK, I got confused..https://github.com/jurialmunkey/skin.arctic.fuse/assets/78307374/a8de5f5b-c9f2-4dcb-9c93-775975b83eea

**Comment by adamosborne83** [comment]
Sorry, this might be a me issue 

https://imgur.com/a/LfKlMSN

**Comment by adamosborne83** [comment]
I have also been into tmdbh and chose 'browse' but different context menu
https://github.com/jurialmunkey/skin.arctic.fuse/assets/78307374/5559ad39-1667-46d5-885a-9de32413ee2f

**Comment by jurialmunkey** [comment]
Is that your info button on your remote?

Pressing info on your remote while on the buttons should open context.

But context button on remote will still do nothing. 

That's because, like i said before, it's impossible for the skin to capture a remotes context action.

Since I can capture info action from a remote, I'm using that instead. 

Not ideal I know but at least gives a way to open context until I make an option to toggle what on-screen buttons are used.

**Comment by adamosborne83** [comment]
> Is that your info button on your remote?
> 
> Pressing info on your remote while on the buttons should open context.
> 
> But context button on remote will still do nothing. 
> 
> That's because, like i said before, it's impossible for the skin to capture a remotes context action.
> 
> Since I can capture info action from a remote, I'm using that instead. 
> 
> Not ideal I know but at least gives a way to open context until I make an option to toggle what on-screen buttons are used. 

Thank you for trying for me.

**Comment by jurialmunkey** [comment]
> But the original point is that if you will enable a setting like the one existing on the AH2 skin, to switch the button next to the “Play” - from “more info” to “options”… right?

@fssmoura - Yes, that's why I haven't closed the issue yet 😉

**Comment by adamosborne83** [comment]
Thank you again
