### ISSUE TITLE
[Feature] Options layout

### ISSUE THREAD

**Issue by A30B06** [jurialmunkey/skin.arctic.fuse#189]
### Skin section

Home Widgets

### Feature description

First off, loving the new menu/options look! Especially with adaptive background it gives real Apple TV vibes.

At the top of it you have three tiles (time/date, settings and weather), it would be cool if it was able to be editable so you could pick what you wanted each tile to be, I was thinking having one of the tiles as a big quit button to close Kodi.

Going further in on that, although I’d imagine this would be far more complex, it would look cool if you were able to edit the layout of them, currently you have one big tile and then two square tiles, if there was sort of a layout option where you could choose to have 4 square tiles or 2 big tiles if you wanted

### Why is this feature needed? Please justify and explain.

I think letting you choose the tiles would give users far more flexibility in how they would like to use the options menu

### Checklist

- [X] I have made a separate issue for each feature I am requesting.
- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by jurialmunkey** [comment]
Having the tiles be customisable is something I've thought about before, and same goes for switching up the title layout -- I just haven't quite got to it yet but definitely on the cards!
