### ISSUE TITLE
[Feature] Option to remove left side menu

### ISSUE THREAD

**Issue by reitenth** [jurialmunkey/skin.arctic.fuse#194]
### Skin section

Home Widgets

### Feature description

remove left side menu and add settings as a widget for combined widget stack.

### Why is this feature needed? Please justify and explain.

i think it would look clean without any menu displaying on the left.

### Checklist

- [X] I have made a separate issue for each feature I am requesting.
- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by jurialmunkey** [comment]
The side menu is a core part of the skin and would massively over complicate navigation code if it were removed.

It would also change the spacing in the skin which would require the skin to be completely redesigned. 

You can already practically remove it by disabling all the items other than home (or by using the option to condense it into a single menu button).
