### ISSUE TITLE
Spotlight within Categories.

### ISSUE THREAD

**Issue by adamosborne83** [jurialmunkey/skin.arctic.fuse#196]
### Skin section

Home Widgets

### Feature description

Would you be willing to include an option to have the flix art Extra large on spotlights (full screen) but then have the ability to have different flixart size on widgets such as standard. 

### Why is this feature needed? Please justify and explain.

Visually I've always found full screen to look better on spot lights, more imposing, then a smaller imagine on widgets. 

### Checklist

- [X] I have made a separate issue for each feature I am requesting.
- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by jurialmunkey** [comment]
Being able to choose the specific art style would be too complicated (also waste resources as essentially would need to duplicate the background to be able to switch between the two by fading each in and out). 

However, I could add an option to have the spotlight show a fullscreen fanart without too much trouble and would be less resource intensive (basically the same as having a landscape widget - just really large).

**Comment by adamosborne83** [comment]
Where would that setting be 👀👀👀

**Comment by adamosborne83** [comment]
Much better, thanks
