### ISSUE TITLE
Load times

### ISSUE THREAD

**Issue by adamosborne83** [jurialmunkey/skin.arctic.fuse#197]
### Skin section

Home Widgets

### Current Behavior

Not a bug, just more curious in ways of workings.
The first video below is Kodi running from start to first widget loading in Ah2, total load time is around 35 seconds.
2nd video is AF load to first widget is a good 30 seconds more.
I have exactly the same amount of widgets on both set ups.
I'm just curious, is there a lot more going on in the background in AF to make the additional load time.

### Expected Behavior

Just curious

### Steps To Reproduce

I know both skins are very very different, but people mention it's faster.
I'm happy to provide logs if required.

I use FireCube version 3 is that makes any difference, I know you don't use android 

Happy to contribute more if you'd like me to get you one haha ...

### Screenshots and Additional Info

https://github.com/jurialmunkey/skin.arctic.fuse/assets/78307374/f6337612-40ab-4ab0-8966-bbbc8f60e85f

https://github.com/jurialmunkey/skin.arctic.fuse/assets/78307374/ab5bc4a8-77f4-4b7d-8501-2661520dc5d0

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
Skins dont affect how fast or slow content loads. This is a complete myth that one skin might be "faster" to load content than another.

There's a ton of different reasons a plugin might take longer to load at a different time, none of which relate to the skin used. For instance, I can see different items in both lists, some of those items might be cached, others might not. A cached item is going to load much faster than one which isnt.

Unless you can replicate exactly the same conditions each time (which is impossible) then these types of comparisons are largely meaningless.

**Comment by jurialmunkey** [comment]
In both videos I can see that the spotlight loads at practically the same time.

The list you are comparing at the bottom is just about the worse possible list to use for comparison. It has completely different items in it, relies on Trakt account authorisation and a history sync, and requires the TMDb server to generate recommendations based on a randomised movie.. All these things could have wildly different response times depending on the state of each server and how recently each of these bits of data were access. In particular, Trakt authorisation and sync times can vary significantly.
