### ISSUE TITLE
Home Screen

### ISSUE THREAD

**Issue by adamosborne83** [jurialmunkey/skin.arctic.fuse#198]
### Skin section

Home Widgets

### Feature description

Have you thought about making the homescreen larger?
So you don't see as much of the widgets?

### Why is this feature needed? Please justify and explain.

Larger spotlight, Play Button and More Info button would be lower down

### Screenshots and Additional Info

![firetv_2023-11-05_13_21_21](https://github.com/jurialmunkey/skin.arctic.fuse/assets/78307374/bf187ff6-37ea-4df8-941a-ddd380e977f6)

### Checklist

- [X] I have made a separate issue for each feature I am requesting.
- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by jurialmunkey** [comment]
The dimensions are designed to be consistent throughout the skin. Changing the spotlight would also change the other parts of the skin and thus break it.

**Comment by jurialmunkey** [comment]
Also, the only reason the widget is higher up in your screenshot is because you dont have a submenu. With a submenu it is pushed further down.
