### ISSUE TITLE
[Feature] widget label (remove sort by default and item count)

### ISSUE THREAD

**Issue by 666jones** [jurialmunkey/skin.arctic.fuse#20]
### Skin section

Home Widgets

### Feature description

Would be a cleaner look if the widget labels didn't have (sort by default ect) or the item count included in the label.

### Why is this feature needed? Please justify and explain.

It's not needed but I personally think it would be more minimalistic and cleaner

### Checklist

- [X] I have made a separate issue for each feature I am requesting.
- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by r95sguy** [comment]
Actually, I find these info useful, especially the number of items

**Comment by 666jones** [comment]
> Actually, I find these info useful, especially the number of items

Ahh that's fair enough. I only use tmdb helper widgets and they all contain 20 items per page so i know there's only 20 items. However I can see how this could be useful for some. I'm sure the (sort by default) with the descending symbol is not really necessary though is it 🤷🏻‍♂️

**Comment by jurialmunkey** [comment]
Add an option to disable the label
`Skin Settings > Furniture > Sort method`
