### ISSUE TITLE
[Feature] Disable footer

### ISSUE THREAD

**Issue by adamosborne83** [jurialmunkey/skin.arctic.fuse#200]
### Skin section

Home Widgets

### Feature description

Me again,

Would you consider having an option in Left Footer and Right to have the option of None.

### Why is this feature needed? Please justify and explain.

This again, is personal preference.
I prefer a very clean interface. 

### Checklist

- [X] I have made a separate issue for each feature I am requesting.
- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by jurialmunkey** [comment]
Right footer definitely no issue with disabling it. I've added some config that will allow it in next update.

Left footer I'll have to think about for a bit because it impacts more than just showing codecs. It's also needed for things like scrollbar item counts and setting information.

**Comment by adamosborne83** [comment]
> Right footer definitely no issue with disabling it. I've added some config that will allow it in next update.
> 
> Left footer I'll have to think about for a bit because it impacts more than just showing codecs. It's also needed for things like scrollbar item counts and setting information.

Thank you again, left is fine, I disabled codecs in tmdbh, the rest of the info it shows is helpful.
