### ISSUE TITLE
[BUG] widget initialisation splash screen

### ISSUE THREAD

**Issue by A30B06** [jurialmunkey/skin.arctic.fuse#201]
### Skin section

Home Widgets

### Current Behavior

First off apologies, I didn’t know whether this was a bug or a feature.

I have the “hide widget initialisation behind splash” turned on which is great. There was an issue the other day when the skin variables and skin updated, but for whatever reason the skin variables then did not create the homescreen/widgets. Because of this the splash screen would stay on constantly and not load into Kodi. Only a Kodi cache clear would fix the issue which then allowed skin variables to rebuild the Home Screen

### Expected Behavior

Would it be possible to add a delay timer as a back up/redundancy? So say if the widgets have not loaded after 60 seconds it will still take you to the Home Screen, so you are then able to get to settings if needed to change skin/check Addons etc

### Steps To Reproduce

Widget initialisation splash turned on.
Open Kodi and while widgets are initialising the skin and skin variables update
For whatever reason, skin variables then did not update the homescreen, so it was stuck on the initialisation splash screen as the widgets had not loaded

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by A30B06** [comment]
To add more info on this, the addons updated while the initialisation splash screen was on after just starting Kodi.

**Comment by jurialmunkey** [comment]
Yeah that's easy to do. 60 second timeout added for next release.

The widget splash is just an image overlayed on the home screen to hide the loading (it's visible while spotlight is loading). The actual home screen is still active underneath, so if you've got a way to open options menu ("S" on keyboard) then you should be able to get out of it.

I've also made it so side hubs buttons cancel the timeout timer, so now pressing back a couple of times should also get you out of the splash early.

**Comment by jurialmunkey** [comment]
On this topic since you use this feature, I'm wondering if it would be useful to have the splash also for the other hubs? --i.e. first open of movies hub displays splash until its spotlight loads -- Or do you think that would be annoying?
