### ISSUE TITLE
Trailer, widget refresh. 

### ISSUE THREAD

**Issue by adamosborne83** [jurialmunkey/skin.arctic.fuse#202]
### Skin section

Home Widgets

### Current Behavior

I have made a video, but maybe not a bug, maybe an enhancement. 
So when I watch a trailer (full screen) it closes the information screen, which then refreshes the widget.
Therefore losing the film you were on.
I have also tried not play trailer in full screen, but that doesn't seem to play well with firecube. 

### Expected Behavior

When trailer opens it then returns to the information of the movie selected. 

### Steps To Reproduce

Click on movie in widget from library.
Click trailer

### Screenshots and Additional Info

https://github.com/jurialmunkey/skin.arctic.fuse/assets/78307374/7c1ea639-c778-4070-af97-e594227460b4

Here is a perfect example. You can actually see the widget refresh before the trailer starts, ignore the flickering, that's the trailer playing, but I will not allow it to be recorded. 

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by adamosborne83** [comment]
Also, curious now, you see that the widget has refreshed to James Bond, but at the end of the trailer it refreshes again, so 2 refreshes in 1 playback action. Can this be prevented anyway?guessing that would help with the 'None widget'

**Comment by jurialmunkey** [comment]
Kodi behaviour. And yep it's really frustrating. It's why I don't have an auto play trailers feature.

Whenever playback starts or stops, kodi forces all containers to refresh.

Skins don't have any control over the loading process, so nothing can be done

**Comment by jurialmunkey** [comment]
Also there's no way to play a video fullscreen without closing information dialog. Active dialogs need to be closed for Kodi to switch windows -- so to open the fullscreen video window, Kodi must first close all active dialogs.

Closing the dialog can be avoided by overlaying a video control on top of the screen to fake fullscreen video-- but if you're having issues with playing video in the background then that won't help you because it's essentially the same thing (just the order of the layers is changed to bring the video layer from the background to the top).

**Comment by adamosborne83** [comment]
> Also there's no way to play a video fullscreen without closing information dialog. Active dialogs need to be closed for Kodi to switch windows -- so to open the fullscreen video window, Kodi must first close all active dialogs.
> 
> Closing the dialog can be avoided by overlaying a video control on top of the screen to fake fullscreen video-- but if you're having issues with playing video in the background then that won't help you because it's essentially the same thing (just the order of the layers is changed to bring the video layer from the background to the top).

I'll send another video later of what I mean with trailers playing within the info screen. In AH2 I had full ability to pause and stop the trailer, in AF every movement I make is still on the info screen. I cannot pause or stop the trailer.

**Comment by jurialmunkey** [comment]
> I'll send another video later of what I mean with trailers playing within the info screen. In AH2 I had full ability to pause and stop the trailer, in AF every movement I make is still on the info screen. I cannot pause or stop the trailer.

Oh! You mean issues related to navigation. I thought you were saying it was a display or performance issue -- because I know some systems cant render the video overlay properly.

That's something I definitely can do something about.

**Comment by adamosborne83** [comment]
> > I'll send another video later of what I mean with trailers playing within the info screen. In AH2 I had full ability to pause and stop the trailer, in AF every movement I make is still on the info screen. I cannot pause or stop the trailer.
> 
> Oh! You mean issues related to navigation. I thought you were saying it was a display or performance issue -- because I know some systems cant render the video overlay properly.
> 
> That's something I definitely can do something about.

Brilliant, look forward to trying it 😊

**Comment by adamosborne83** [comment]
> > I'll send another video later of what I mean with trailers playing within the info screen. In AH2 I had full ability to pause and stop the trailer, in AF every movement I make is still on the info screen. I cannot pause or stop the trailer.
> 
> Oh! You mean issues related to navigation. I thought you were saying it was a display or performance issue -- because I know some systems cant render the video overlay properly.
> 
> That's something I definitely can do something about.

Is it just me, or am I missing something?


https://imgur.com/a/maWa9dD

**Comment by jurialmunkey** [comment]
Not implemented anything yet

**Comment by adamosborne83** [comment]
> Not implemented anything yet 

So me then haha

**Comment by adamosborne83** [comment]
Love it, thank you. Looks spot on, and love the option to have it full screen within the dialogue too
