### ISSUE TITLE
[BUG] Spotlight Autoscroll is not working anymore

### ISSUE THREAD

**Issue by AakashC2020** [jurialmunkey/skin.arctic.fuse#207]
### Skin section

Home Widgets

### Current Behavior

Hi @jurialmunkey,

Hope you are doing well.

The Spotlight Autoscroll has stopped working since last update. Could you please look into the issue?

### Expected Behavior

Spotlight should Autoscroll like it used to earlier.

### Steps To Reproduce

On load Spotlight is not Autoscrolling, and even if we go to the Spotlight section from any widget it's still not Autoscrolling.

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
Resolved by https://github.com/jurialmunkey/skin.arctic.fuse/commit/c32f0ea13fc835a8f380a8c3aedb27435ab130c5

**Comment by AakashC2020** [comment]
> Resolved by [c32f0ea](https://github.com/jurialmunkey/skin.arctic.fuse/commit/c32f0ea13fc835a8f380a8c3aedb27435ab130c5)

Thank you @jurialmunkey !
