### ISSUE TITLE
:sparkles: Option to focus spotlight instead of categories by default

### ISSUE THREAD

**Issue by A30B06** [jurialmunkey/skin.arctic.fuse#209]
### Skin section

Home Widgets

### Current Behavior

I like the new “categories slide up on focus” option, but now with this enabled when clicking on a menu item it focuses straight on the category and so the spotlight is more in the background now instead of being the main thing focused on

### Expected Behavior

The first thing selected when clicking a menu item/home should be the spotlight, instead of the first category

### Steps To Reproduce

Enable “categories slide up on focus”, when clicking a menu item because AF highlights the first category the spotlight now is more in the background than the foreground

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
The main problem with focusing the spotlight first is what if it ends up having no items? Then you'll get stuck in a blank space.

Also it's possible to mix and match categories with and without spotlight, which might also create that scenario.

Not disagreeing with you, just not sure how to overcome that issue other than always forcing the spotlight buttons to be available - which will then be confusing if there's no spotlight items.

**Comment by A30B06** [comment]
Hmm you’re right about that, is it possible for an if statement? If spotlight is blank, focus on categories, if it is not, focus on spotlight?

**Comment by jurialmunkey** [comment]
No because focus is set when the window loads and the widget doesn't load until after the window loads.

i.e. Window Loads > Focus goes to Spotlight > Spotlight loads > it has not items > Buttons hide > you're stuck.

**Comment by jurialmunkey** [comment]
I was going to revisit this but I think it is proving too challenging so going to close as unplanned.
