### ISSUE TITLE
[Feature] Coloured ratings 

### ISSUE THREAD

**Issue by SJ1O** [jurialmunkey/skin.arctic.fuse#21]
### Skin section

Home Widgets

### Feature description

Coloured ratings for IMDb, tmdb, trakt would be a nice touch

### Why is this feature needed? Please justify and explain.

Not needed but it would be a welcomed option 

### Checklist

- [X] I have made a separate issue for each feature I am requesting.
- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by taiseer999** [comment]
Would be nice to have it as an option

**Comment by SJ1O** [comment]
Thanks for this update much appreciated :)
