### ISSUE TITLE
:sparkles: Option to mirror list views

### ISSUE THREAD

**Issue by adamosborne83** [jurialmunkey/skin.arctic.fuse#210]
### Skin section

Home Widgets

### Feature description

I totally love the new view 'list media' just wondering if be possible to add an option to flip where the art work is, and the title 

### Why is this feature needed? Please justify and explain.

Depending on which side of the brain you use more, it helps with quick reading. 

### Screenshots and Additional Info

![firetv_2023-11-12_20_10_05](https://github.com/jurialmunkey/skin.arctic.fuse/assets/78307374/9076482b-2fde-4ca3-a076-7c1b39f4e8f9)

### Checklist

- [X] I have made a separate issue for each feature I am requesting.
- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by DROIDshield** [comment]
Been looking for this view to check it out but can't see it anywhere?

**Comment by jurialmunkey** [comment]
@DROIDshield

Only in the library windows. Go to bottom view buttons and choose view then "list media". 

Should be available for all media content types (ie movies, shows, sets, seasons, episodes, artists, albums, songs)

Also of course if you've changed you navigation settings for ondown then you'll need to change it back to "view" to be able to access the view changer.

**Comment by DROIDshield** [comment]
I've tried every trick in the book to create the List View as above but some how can't seem to recreate it from the settings I've enabled so please give a little detail into getting it to activate the image above with 007 in.

Also in my pic, how do I get rid of the folder option that leads back to TMDB if I keep pressing the back button or scroll upto it. As again in your picture above it's not shown.
![20231115_062205](https://github.com/jurialmunkey/skin.arctic.fuse/assets/97023369/9f1672cd-cbde-4f85-83bd-d4ccdfd221af)

**Comment by jurialmunkey** [comment]
@DROIDshield 
https://kodi.wiki/view/Settings/Media/General#Show_parent_folder_items

You're currently in Genres. That's not one of the media list content types.
Media list is only available for movies, tvshows, seasons, episodes, artists, albums, songs.

Media list is not available for Genres content type because Genres has no artwork to display. The only reason the combined view you're currently in has artwork is because the combined view has an attached widget showing the currently focused subfolder.

**Comment by DROIDshield** [comment]
Understood and all working as it required cheers big man.😊👍

**Comment by adamosborne83** [comment]
Got to ask, what does Sparkles mean?

**Comment by jurialmunkey** [comment]
> Got to ask, what does Sparkles mean?

It's the emoji ✨ for a new feature

![image](https://github.com/jurialmunkey/skin.arctic.fuse/assets/4618719/15145286-32e9-444d-b605-a599a75bb9fc)

Helps me to categorise issues and commits to see purpose at a glance.
I use a scheme adapted from https://gitmoji.dev/

🐛 Bug
⚡ Improvement
✨ New feature
👽 Localization
🚑 Critical fix
🚧 Future feature groundwork
🔖 Version or dependency bump
🎨 Artwork assets
🧹 Cleanup unused code

**Comment by jurialmunkey** [comment]
Closing as not planned. I think this one is going to overcomplicate the code too much, particularly when it comes to different screen sizes.

**Comment by adamosborne83** [comment]
> Closing as not planned. I think this one is going to overcomplicate the code too much, particularly when it comes to different screen sizes.

It's fine, I'm use to it now.... that was your plan all along... give it a few weeks then I'd never notice it.
Thanks as always 😀
