### ISSUE TITLE
[BUG] "The dependency on script.skinvariables version 1.1.47 could not be satisfied."

### ISSUE THREAD

**Issue by RaraCool** [jurialmunkey/skin.arctic.fuse#211]
### Skin section

Other

### Current Behavior

The dependencies for Skin Variables and TheMovieDB Helper cannot be satisfied upon install of Arctic Fuse. All other dependencies show which version they will install to but these two just say "Not available".

### Expected Behavior

Arctic Fuse and all its dependencies install successfully.

### Steps To Reproduce

1. Add repository.jurialmunkey to File Manager sources
2. Enable unknown sources
3. Install repository from ZIP file
4. Install Arctic Fuse from repository

### Screenshots and Additional Info

Kodi 20.2
OSMC 2023-08-1 fresh install
Raspberry Pi 4

Was previously running Arctic Fuse (happily) on this Pi before a necessary OS reinstall
Neither Skin Variables or TMDB Helper show up in jurialmunkey repository
Installing Skin Variables from Kodi default repository does not satisfy the dependency

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
You need to enable allow updates for official addons from any repository.

**Comment by RaraCool** [comment]
Thank you, that worked! It had been a while since I did a fresh install of Kodi so I forgot that step.
