### ISSUE TITLE
List Media not showing movie data

### ISSUE THREAD

**Issue by DROIDshield** [jurialmunkey/skin.arctic.fuse#216]
### Skin section

Home Widgets

### Feature description

Just looking at some movies in List Media and noticed i can't see if the movie is Atmos, 5.1 or 7.1 and all the media types that would usually show across the bottom of the screen.

Any chance of adding this? Just a thought. 

### Why is this feature needed? Please justify and explain.

This detail is always nice to see across the bottom when the fanart is displayed.
![20231118_050446](https://github.com/jurialmunkey/skin.arctic.fuse/assets/97023369/352a3111-cc5c-4b49-9c96-93b8c2101940)

### Checklist

- [X] I have made a separate issue for each feature I am requesting.
- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by jurialmunkey** [comment]
It works fine for me.

Check your left footer furniture settings and make sure it is set to codecs.

**Comment by DROIDshield** [comment]
Thanks, I got going.

![20231118_135228](https://github.com/jurialmunkey/skin.arctic.fuse/assets/97023369/ec549815-bfed-4760-8a7a-3deae9e75adb)
