### ISSUE TITLE
Add a pin number to unlock a addon.

### ISSUE THREAD

**Issue by DROIDshield** [jurialmunkey/skin.arctic.fuse#217]
### Skin section

Home Widgets

### Feature description

Is there any way of implementing pin lock to addons via the skin. I know this can be done in Kodi but I wonder if when a long press on a addon via AF to bring up its menus could a pin be added so the addon cannot be accessed until the pin is inserted for individual addons of ones choosing. 

Setting this up now In kodi means adding a profile with a pin, doing this now I could possibly lose data, mess up my setup with AF so would not want to mess-up my settings as well as not having a backup button for the skin I don't want to lose data at all.

### Why is this feature needed? Please justify and explain.

Ie: rather than disabling a "certain type" of addon so it cannot be seen or accessed if it had a pin 1234 that then opens the addon for use until it's closed and then no longer can get accessed because of a time out, this would be so much easier.

It's just a thought.

### Checklist

- [X] I have made a separate issue for each feature I am requesting.
- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by jurialmunkey** [comment]
This is not something a skin could do in any meaningful way.

At best I'd be able to pin lock shortcuts on the sidemenu or categories but that won't solve the issue. You'd still be able to get access to the addons via the normal means (e.g. addon browser or add-ons node in library).

This is exactly what profiles and master pin locks are for.
https://kodi.wiki/view/Settings/Interface/Master_lock

**Comment by DROIDshield** [comment]
I'll do a backup and try the lock in kodi....thanks for looking at this....
