### ISSUE TITLE
Pluto Addon 

### ISSUE THREAD

**Issue by derrgoo** [jurialmunkey/skin.arctic.fuse#218]
### Skin section

PVR and Live TV

### Current Behavior

When I run iptv simple client with Pluto using fuse it seems it has problems when commercials come. It just freezes. I tested the same with stock estuary skin and it has no issues with commercials. So wondering if something in fuse is having an issue. 

### Expected Behavior

Run to commercial and star playing. 

### Steps To Reproduce

Play Pluto using iptv simple client and wait for commercial. Thank you!

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
I'm fairly sure it's related to this issue in inputstream adaptive:
https://github.com/xbmc/inputstream.adaptive/issues/1071

I have a similar issue with a few Australian IPTV channels.

It's only a certain type of advert which causes a freeze, not all of them - so if you only tested briefly in Estuary that'd be why you didn't see the same issue.

**Comment by derrgoo** [comment]
Thanks I think you’re right. Hopefully, they can fix this.

**Comment by jurialmunkey** [comment]
I'll close this as dont think there's much I can do from the skin side of things.
