### ISSUE TITLE
[BUG] All my widget settings changed to default after latest update

### ISSUE THREAD

**Issue by AakashC2020** [jurialmunkey/skin.arctic.fuse#219]
### Skin section

Home Widgets

### Current Behavior

Hi @jurialmunkey,

All my widgets settings and menu items changed to default after today's update. Please help! I forgot to take backup recently and don't want to build everything from scratch. This happened across both my Kodi profiles.

### Expected Behavior

The widgets and menu items shouldn't have changed to default.

### Steps To Reproduce

Checked widgets and menu items after latest update.

### Screenshots and Additional Info

![IMG20231120202813](https://github.com/jurialmunkey/skin.arctic.fuse/assets/65297828/689a8308-155d-486e-b914-1a9bcc09bb35)

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
Expected behaviour. See this post:
https://forum.kodi.tv/showthread.php?tid=373859&pid=3172616#pid3172616

v0.4 onwards removes skinshortcuts dependency and so is not backwards compatible. Older versions are available from releases if you're not ready to make the change.

**Comment by AakashC2020** [comment]
> Expected behaviour. See this post: https://forum.kodi.tv/showthread.php?tid=373859&pid=3172616#pid3172616
> 
> v0.4 onwards removes skinshortcuts dependency and so is not backwards compatible. Older versions are available from releases if you're not ready to make the change.

Hi @jurialmunkey,

Okay, thanks for letting me know! Didn't follow your Kodi forum posts recently, so missed your warning about the massive changes in the latest update. Fine I'll rebuild everything from scratch, but guess that needs to be done in the weekend or so. Nevertheless, thanks for your prompt response! Looking forward to all the new and important changes that are going to come to this skin. 👍🏻
