### ISSUE TITLE
:sparkles: Spotlight widget label

### ISSUE THREAD

**Issue by berkhornet** [jurialmunkey/skin.arctic.fuse#225]
### Skin section

Home Widgets

### Feature description

Would it be possible to define / display a label for the spotlight widget? 

### Why is this feature needed? Please justify and explain.

Might just be me, but I'm not always sure what is being displayed! This would add clarity.

### Checklist

- [X] I have made a separate issue for each feature I am requesting.
- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by AakashC2020** [comment]
Hi @jurialmunkey,

How can I turn off the newly Spotlight text label? I was happy without it earlier, as it looks a bit distracting. Kindly advise.

**Comment by Omarscomin** [comment]
> Hi @jurialmunkey,
> 
> How can I turn off the newly Spotlight text label? I was happy without it earlier, as it looks a bit distracting. Kindly advise.

Curious about this as well!

**Comment by xyzfre** [comment]
Or at least a option for this label to be enable or disable and a way to rename it if it's got to stay Thank you @jurialmunkey

**Comment by xyzfre** [comment]
![image](https://github.com/jurialmunkey/skin.arctic.fuse/assets/49699869/f036c7f3-a227-480a-bf46-5e02ca409378) for example here, at least if I could remove the sort by year descending.
