### ISSUE TITLE
[Feature] remove title of the side menu page

### ISSUE THREAD

**Issue by 666jones** [jurialmunkey/skin.arctic.fuse#23]
### Skin section

Home Widgets

### Feature description

I think there is quite abit of space getting wasted where the side menu title is I have included photos.

### Why is this feature needed? Please justify and explain.

Just to create a cleaner look

### Screenshots and Additional Info

![20230730_014517](https://github.com/jurialmunkey/skin.arctic.fuse/assets/121204283/9f40c81e-94c9-4725-b97f-4a72df4bed55)

### Checklist

- [X] I have made a separate issue for each feature I am requesting.
- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by jurialmunkey** [comment]
Sorry, not planned. The header label is necessary for a lot of parts of the skin like on the OSD for chapter titles and in settings dialogs/windows. I don't like inconsistent positioning where parts of the skin move around.
