### ISSUE TITLE
[BUG] Submenu sorting order should be default

### ISSUE THREAD

**Issue by AakashC2020** [jurialmunkey/skin.arctic.fuse#238]
### Skin section

Home Widgets

### Current Behavior

Hi @jurialmunkey,

Currently the submenu sorting order automatically takes alphabetical by default, but could you please make it take the default sorting order of a list?

### Expected Behavior

For example, if we choose Your TV Shows Airing Calendar as the submenu, the sorting order changes to alphabetical which messes the days, like Fortnight comes first, Monday comes next, Sunday comes after that, etc. If I choose sort by default also it still takes alphabetical sorting only. Could you please fix this like it was earlier?

### Steps To Reproduce

Create a submenu widgets list, for example your TV Shows calendar and notice the sorting order, it will become alphabetical by default.

### Screenshots and Additional Info

![IMG20231124071455](https://github.com/jurialmunkey/skin.arctic.fuse/assets/65297828/fdfe9357-862b-4e35-9887-943190f9b44d)

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
It's not actually implemented yet but it is now.

The sort method you were changing changes the sorting of the widget not the submenu. I've added some extra options to allow sorting the submenu list.

**Comment by AakashC2020** [comment]
> It's not actually implemented yet but it is now.
> 
> The sort method you were changing changes the sorting of the widget not the submenu. I've added some extra options to allow sorting the submenu list.

Thank you so much @jurialmunkey !
