### ISSUE TITLE
[BUG] unable to Access the numbers on the keyboard 

### ISSUE THREAD

**Issue by 666jones** [jurialmunkey/skin.arctic.fuse#24]
### Skin section

Other

### Current Behavior

I'm unable to access the numbers on the keyboard it won't scroll across to them. It round Robbins at the following symbols ] and ' and / ect 

### Expected Behavior

To be able to use / select any buttons on the keyboard 

### Steps To Reproduce

1.Go to the search menu or create a custom action ect and try to select a number.

This seems to be happening wherever the keyboard is used.

### Screenshots and Additional Info

![20230730_022524](https://github.com/jurialmunkey/skin.arctic.fuse/assets/121204283/fc5024a9-4dea-412f-8331-299c80f20fc4)

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
Ah, this is a good reminder - been meaning to fix this and then forgot about it.

The numbers used to be in the top row but I forgot to change the navigation when moved them to the side (you'll see what I mean if you press up from the QWERTY row).
