### ISSUE TITLE
[BUG] Text overlapping in right side menu

### ISSUE THREAD

**Issue by AakashC2020** [jurialmunkey/skin.arctic.fuse#242]
### Skin section

Home Widgets

### Current Behavior

Some texts are overlapping in the right side menu, like above the profile picture, etc. Could you please fix it?

### Expected Behavior

Texts shouldn't overlap in the right side menu.

### Steps To Reproduce

Open and see the right side menu.

### Screenshots and Additional Info

![IMG20231124073422](https://github.com/jurialmunkey/skin.arctic.fuse/assets/65297828/e0740f27-9224-4ea8-92d1-85cc9245b990)

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
This tile is only suitable for the long tile. I can't "fix" the date overlapping on a short tile because the date is too long for the space.

**Comment by AakashC2020** [comment]
> This tile is only suitable for the long tile. I can't "fix" the date overlapping on a short tile because the date is too long for the space.

Hi @jurialmunkey,

Fine. No problem. Thanks for letting me know!
