### ISSUE TITLE
[BUG] No Artist Name on Music Hub spotlight

### ISSUE THREAD

**Issue by Dml2023** [jurialmunkey/skin.arctic.fuse#244]
### Skin section

Home Widgets

### Current Behavior

Using Random Artists as Music Hub Spotlight is not showing the artist name

### Expected Behavior

The artist name should appear.

### Steps To Reproduce

Use RandomArtists skin playlist as spotlight

### Screenshots and Additional Info

![kodi](https://github.com/jurialmunkey/skin.arctic.fuse/assets/149931300/4311ba39-96bd-4295-b151-ca255d5f87d6)

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
Ah I never noticed because practically all my artists have clearlogos

**Comment by Dml2023** [comment]
No Problem. Thanks for such a speedy fix!!
