### ISSUE TITLE
Spotlight in Home

### ISSUE THREAD

**Issue by adamosborne83** [jurialmunkey/skin.arctic.fuse#254]
### Skin section

Home Widgets

### Current Behavior

Hey Jurial,

I may have missed something, as been away a few days.
In HOME it seems to no longer have the option for spotlight, and neither if I edit widgets can I.
I only have home, then all my widgets set up off that.

### Expected Behavior

As before spotlights in Home and its widgets 

### Steps To Reproduce

Go into home

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
It's there for me...

![screenshot00244](https://github.com/jurialmunkey/skin.arctic.fuse/assets/4618719/eddca2ed-a4a0-4d49-a554-3a6a5333bb73)

**Comment by jurialmunkey** [comment]
Unless you're talking about this bug? https://github.com/jurialmunkey/skin.arctic.fuse/issues/255
Which is now fixed on latest github master and will add to next release.

**Comment by adamosborne83** [comment]
> Unless you're talking about this bug? https://github.com/jurialmunkey/skin.arctic.fuse/issues/255
> Which is now fixed on latest github master and will add to next release.

Absolutely am talking about that.... I did see that error report too, and thought it was the same as mine. 
Just A LOT more detailed and how it should be 😉
