### ISSUE TITLE
Skin Fuse[Feature]

### ISSUE THREAD

**Issue by audiosistem** [jurialmunkey/skin.arctic.fuse#256]
### Skin section

Home Widgets

### Feature description

Hello! 
Maybe just as an inspiration, for the new Fuse skin. 
Populating widget from plugin.video.themoviedb.helper (your other work). 
Possibility to view the trailer in mark movie/tvshow.
With the possibility of changing after the installation if the user does not like it.
It is not useful, it does not take into account.
Have a good day!

### Why is this feature needed? Please justify and explain.

I'm always frustrated because I would like to change the current skin.
To have a Jurial brand package.

### Screenshots and Additional Info

I don't have images. It was just a suggestion.

### Checklist

- [X] I have made a separate issue for each feature I am requesting.
- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by rapteev** [comment]
Really?
Did you at least go to skin settings and try to explore a bit?

1. You can populate widgets from any addon.
2. Already implemented on spotlight.
3. It’s one of the most customizable skins I have seen.

**Comment by audiosistem** [comment]
My mistake. A beautiful day!

**Comment by audiosistem** [comment]
https://i.postimg.cc/jd4hxnQQ/Jurial-Fuse.jpg

**Comment by adamosborne83** [comment]
You can watch trailers if on spotlight

![20231127_181004.jpg](https://github.com/jurialmunkey/skin.arctic.fuse/assets/78307374/018ea9c1-a8e3-4261-ae32-83d61b848238)

Of you look back at some of jurials comments you'll see that this is a great debate, and I agree why. 

Every time a tailer plays, it refreshes kodi widgets, bloody nightmare.

**Comment by jurialmunkey** [comment]
Duplicate of #141

**Comment by audiosistem** [comment]
In case it helps: https://github.com/beatmasterRS/skin.arctic.zephyr.mod

**Comment by rapteev** [comment]
Do you know that the original arctic zephyr was developed by jurialmunkey??

**Comment by audiosistem** [comment]
Stu, you're absolutely right. In this skin mod, the trailer works perfectly when marking, only it lasts for at least 3 seconds.

**Comment by audiosistem** [comment]
Yes.Thank you @Unpleased1153!In the modded skin it works.
