### ISSUE TITLE
[Feature] Request to add a sorting code for widgets in Add-ons Hub

### ISSUE THREAD

**Issue by AakashC2020** [jurialmunkey/skin.arctic.fuse#26]
### Skin section

Home Widgets

### Feature description

Hi @jurialmunkey,

Hope you're doing well and thanks for this amazing new skin!

Since the Add-ons hub is not customizable. Could you please add the below few sorting codes for the Videos, Music, Programs, and Pictures add-on widgets in the skin's "**Custom_1132_Window_Addons.xml**" file?

The sorting code required is: **sortby="lastused" sortorder="descending"** and can be included in the following 4 places for Videos, Music, Programs, and Pictures add-on widgets:

            <include content="NextAired_GroupList">
                <include content="NextAired_Widget">
                    <param name="id">01</param>
                    <param name="label">$LOCALIZE[1037]</param>
                    <param name="visible">true</param>
                    <param name="include">List_Square_Row</param>
                    <content target="videos" sortby="lastused" sortorder="descending">addons://sources/video/</content>
                </include>
                <include content="NextAired_Widget">
                    <param name="id">02</param>
                    <param name="label">$LOCALIZE[1038]</param>
                    <param name="visible">true</param>
                    <param name="include">List_Square_Row</param>
                    <content target="music" sortby="lastused" sortorder="descending">addons://sources/audio/</content>
                </include>
                <include content="NextAired_Widget">
                    <param name="id">03</param>
                    <param name="label">$LOCALIZE[1043]</param>
                    <param name="visible">true</param>
                    <param name="include">List_Square_Row</param>
                    <content target="programs" sortby="lastused" sortorder="descending">addons://sources/executable/</content>
                </include>
                <include content="NextAired_Widget">
                    <param name="id">04</param>
                    <param name="label">$LOCALIZE[1]</param>
                    <param name="visible">true</param>
                    <param name="include">List_Square_Row</param>
                    <content>
                        <item>
                            <label>$LOCALIZE[39031]</label>
                            <icon>DefaultAddSource.png</icon>
                            <onclick>ActivateWindow(pictures,-,return)</onclick>
                        </item>
                    </content>
                    <content target="pictures">sources://pictures/</content>
                    <content target="pictures" sortby="lastused" sortorder="descending">addons://sources/image/</content>
                </include>

### Why is this feature needed? Please justify and explain.

This is the way Kodi sorts the Add-ons by default so that the last used Add-on is always prioritized and will be visible first. I myself added the code but every time the Skin is updating my code is getting over-written. It will be really kind of you to please include this code in the next Skin update. Thanks a lot in advance!

### Checklist

- [X] I have made a separate issue for each feature I am requesting.
- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by jurialmunkey** [comment]
Ah I must've forgot to add these back in. I had it sorted that way in a previous version. Will fix it in next update.

**Comment by AakashC2020** [comment]
> Ah I must've forgot to add these back in. I had it sorted that way in a previous version. Will fix it in next update.

Thank you so much @jurialmunkey ! I'll wait for the next skin update.

**Comment by AakashC2020** [comment]
Thank you @jurialmunkey ! Everything looks fine after the latest update!
