### ISSUE TITLE
[Feature] Always show footer

### ISSUE THREAD

**Issue by AakashC2020** [jurialmunkey/skin.arctic.fuse#27]
### Skin section

Home Widgets

### Feature description

Hi @jurialmunkey,

Currently the footer only shows after the last widget in a menu or we've to go to the video info screen to see it. Is it possible to keep the footer always visible so that we can see the codec icons and studios for all widgets under a menu?

### Why is this feature needed? Please justify and explain.

If the footer is always visible for all widget rows then we can see the codecs and studio icons for all Movies and TV Shows without going to the video info screen, which will be extremely useful and time saving.

### Checklist

- [X] I have made a separate issue for each feature I am requesting.
- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by jurialmunkey** [comment]
Always displaying the footer will clash with the text of the next widget. If there is a next widget it should be visible -- I don't want that type of scenario like in AH2 where it is unclear whether it is possible to scroll to the next widget. 

The footer being in the widget layout at all is only there as a placeholder until I figure out what I want to do at the end of the widget group. Eventually the footer will only be visible in the library to make it clear whether or not the explore/scrollbar features can be used.

**Comment by AakashC2020** [comment]
> Always displaying the footer will clash with the text of the next widget. If there is a next widget it should be visible -- I don't want that type of scenario like in AH2 where it is unclear whether it is possible to scroll to the next widget.
> 
> The footer being in the widget layout at all is only there as a placeholder until I figure out what I want to do at the end of the widget group. Eventually the footer will only be visible in the library to make it clear whether or not the explore/scrollbar features can be used.

Fine @jurialmunkey. I can understand. Thanks for your response!
