### ISSUE TITLE
[BUG] unable to update fuse (not showing in your repo)

### ISSUE THREAD

**Issue by SJ1O** [jurialmunkey/skin.arctic.fuse#270]
### Skin section

Home Widgets

### Current Behavior

Hey Jurial I noticed you pushed 2 updates today so I tried to update mine from v4.15 but I'm unable Todo so. I also updated the repo now when I view your repo (v3.4) and enter look and feel there is no skin option. I reverted back to (v3.3) and there is a skin category within the look and feel part of your repo but fuse is not there. Sorry if this has been mentioned somewhere I have had a brief look around but couldn't find anything mentioned. Is there another method I should use to update fuse?

Cheers
SJ

### Expected Behavior

Blank

### Steps To Reproduce

View Jurial repo v.3.4 there is no fuse skin within the repo.

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by SJ1O** [comment]
Ahh thanks for pointing that out next time I'll also check the issue section for the repo itself. 

I just updated to nightly from 21 beta 1 and all updated fine now. I did also get the update on my lounge setup and that was on 20.2 so should of known it was probably a Kodi version issue.

Ohh well thanks for your help in getting that sorted it's much appreciated hope you have a good weekend.

Cheers
SJ

**Comment by jurialmunkey** [comment]
No worries! Good to know it is working now.
