### ISSUE TITLE
Updates not working on kodi 20.2

### ISSUE THREAD

**Issue by rapteev** [jurialmunkey/skin.arctic.fuse#275]
### Skin section

Other

### Current Behavior

Hi Jurialmunkey 
Updates not showing up on kodi 20.2 after latest repository update.

### Expected Behavior

Updates working on kodi nexus

### Steps To Reproduce

Try to update skin or new installation on kodi 20 nexus

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by adamosborne83** [comment]
You need to update kodi to nightlies or stay on repo 3.3

**Comment by jurialmunkey** [comment]
> You need to update kodi to nightlies or stay on repo 3.3

Repo for Nexus is exactly the same in both 3.3 and 3.4 -- all the version change does is add an Omega branch. It doesn't change the Nexus one.

The issue is I accidentally copied the GUI bump into the nexus version of the skin. It will be fixed soon.

**Comment by rapteev** [comment]
Thank you

**Comment by adamosborne83** [comment]
I'll shut up in future haha
