### ISSUE TITLE
:bug: Wrong version of Skin Variables

### ISSUE THREAD

**Issue by BrutalCSEjziponken** [jurialmunkey/skin.arctic.fuse#283]
### Skin section

Other

### Current Behavior

Hi
Using latest nightly kodi-20231210-9d0ccadd-master-arm64-v8a (2023-Dec-11 03:03), and I can't install this skin.
It says Skin Variables installed v0.2.5 when trying to install 0.4.22-omega.

Someting about version not being satisfied. 

### Expected Behavior

Being installed (lol)

### Steps To Reproduce

1. Install
2. Fail

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by DROIDshield** [comment]
Did you go into skin variables and try to update the dependencies manually before attempting the skin? If not, give that ago.

**Comment by jurialmunkey** [comment]
Follow all the instructions in the forum post
https://forum.kodi.tv/showthread.php?tid=373859
