### ISSUE TITLE
[BUG] Video Add-ons Info panel

### ISSUE THREAD

**Issue by r95sguy** [jurialmunkey/skin.arctic.fuse#29]
### Skin section

Home Widgets

### Current Behavior

The video info panel defaults to weather information for some video addons, the latest update fixed the issue for Youtube, but it's still outstanding for "Youtube Channels" add-on for example. 

### Expected Behavior

Video Title and information to show in the panel instead of weather for all video add-ons, similar to AH2 skin

### Steps To Reproduce

Go to video addon, list of videos

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
That plugin is setting the incorrect container.content and listitem.dbtype

It is setting content as "movies" and leaving dbtype blank (despite setting dbtype being a plugin requirement since 2015).

The correct values would be "videos" and "video". The skin doesn't display info for items without a dbtype

**Comment by r95sguy** [comment]
Oh, makes sense, but is there any workaround? I don't have that issue in AH2 skin.

**Comment by jurialmunkey** [comment]
The "workaround" is to ask the addon author to fix their addon so that it has the correct mediatype and content type.

I'm so tired of having to add skin workarounds for addon authors who can't be arsed putting in even the most basic of metadata details.
