### ISSUE TITLE
:bug: Unable to change Weather location

### ISSUE THREAD

**Issue by berkhornet** [jurialmunkey/skin.arctic.fuse#291]
### Skin section

Other

### Current Behavior

After selecting the Weather tile, and then selecting Location, the weather location does not change, and the display remains the same.

### Expected Behavior

Weather location would cycle through those defined in the weather addon settings

### Steps To Reproduce

Set up weather with two locations
Select Options
Select Weather tile
Select Location button

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
I noticed this myself a while ago. Seems to be a Kodi issue.

The command is correct `Weather.LocationNext` however it only seems to work if the MyWeather window is open and it isn't possible to change the location from other windows (the dialog is a custom dialog).

**Comment by jurialmunkey** [comment]
Not really a fix but I will hide the button if Weather *window* is not open under the dialog to at least avoid confusion about why it isn't doing anything

**Comment by jurialmunkey** [comment]
I've added a swap for the button to be "expand" when the weather window is closed. That will then open the full weather window where can click to reopen the dialog and change the location -- not ideal but not really any other way to do it.

**Comment by berkhornet** [comment]
Many thanks again!

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________
