### ISSUE TITLE
System overload when video in the background

### ISSUE THREAD

**Issue by patkino** [jurialmunkey/skin.arctic.fuse#3]
### Skin section

Home Widgets

### Current Behavior

Pressing back or home during videoplayback without stopping it causes system (Coreelec 20.2 on Khadas Vim4) overload (freezes, stuttering, etc)

### Expected Behavior

Normal background videoplayback

### Steps To Reproduce

1. Play video in fullscreen
2. Navigate to home menu without stopping video

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
Can you try disabling backing video in skin settings.

I've got a good guess at possible cause if it is the background video but I just want to make sure that the issue is the background video and not something else before I start making changes.

**Comment by jurialmunkey** [comment]
^^^ That should fix it hopefully. 

Adds options under `Skin Settings > Appearance > Background Video`
I think the problem is likely the "Adaptive aspect ratio" option. Enabling "Fixed aspect ratio" should hopefully fix it.

**Comment by patkino** [comment]
Fixed. Thanks
