### ISSUE TITLE
:bug: Default (Skin)User is not renameable

### ISSUE THREAD

**Issue by peat80** [jurialmunkey/skin.arctic.fuse#300]
### Skin section

Other

### Current Behavior

After playing around with skin users kodi now shows default user in library and menu.
Before it showed the name of my kodi user. Trying to rename the default user on the skin login screen produces an skinvariables error.

### Expected Behavior

Add ability to rename the default user or show the name of the kodi user as before if there is only one user.

### Steps To Reproduce

Enable skin users and choose default user.
Disable skin users and default name stays.

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
Ah I forgot to log out the user when toggling that setting. Toggling it again should clear the user now.
