### ISSUE TITLE
[BUG] Keyboard only in English

### ISSUE THREAD

**Issue by The-cpu-max** [jurialmunkey/skin.arctic.fuse#31]
### Skin section

Fonts and Languages

### Current Behavior

Language switch button

### Expected Behavior

There is a shortened keyboard, where it is not possible to change the language to any language

### Steps To Reproduce

1.enter to kodi 
2.search for it 

### Screenshots and Additional Info

![image](https://github.com/jurialmunkey/skin.arctic.fuse/assets/102416233/af884bd5-ca2d-4b52-a3bc-4564d0e37bff)

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
Not possible. That "keyboard" is just skin buttons using JumpSMS to input the letters to the edit control. JumpSMS only sends alphanumeric and cannot send other characters. Kodi does not provide a way to send other letters via custom input

Even if it were possible, it would be a nightmare for me to manage every possible character set and a switch for the buttons. If you need non-latin characters you can click the edit control to show the full keyboard.
