### ISSUE TITLE
[Feature] Port 'Ends at x'

### ISSUE THREAD

**Issue by RagnarLothbrok-Odin** [jurialmunkey/skin.arctic.fuse#32]
### Skin section

Fullscreen Video OSD

### Feature description

Port the `Ends at x` to the OSD (from Arctic Horizon 2, or at least give it as an option)

### Why is this feature needed? Please justify and explain.

It was a feature I genuinely used often when I need to know if I have time to finish an episode for example... Or when I am asked when I am free and I can give an oddly specific time 😂.

### Checklist

- [X] I have made a separate issue for each feature I am requesting.
- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by 666jones** [comment]
I agree this is a good feature I also liked it when the progress bar displays time remaining. It's definitely a handy bit of info

**Comment by AakashC2020** [comment]
> ### Skin section
> Fullscreen Video OSD
> 
> ### Feature description
> Port the `Ends at x` to the OSD (from Arctic Horizon 2, or at least give it as an option)
> 
> ### Why is this feature needed? Please justify and explain.
> It was a feature I genuinely used often when I need to know if I have time to finish an episode for example... Or when I am asked when I am free and I can give an oddly specific time 😂.
> 
> ### Screenshots and Additional Info
> _No response_
> 
> ### Checklist
> * [x]  I have made a separate issue for each feature I am requesting.
> * [x]  I have searched the issues and this feature has not been requested.
> * [x]  I am using the most recent skin version.

Hi @jurialmunkey,

Please add "Ends at x" to both the OSD and the Spotlight text like Arctic Horizon 2. It's really very useful.

**Comment by jurialmunkey** [comment]
`Skin Settings > Details > Infoline > Optional Details (Ends at time)`
