### ISSUE TITLE
[BUG] Submenu Widget not loading automatically at Kodi launch

### ISSUE THREAD

**Issue by AakashC2020** [jurialmunkey/skin.arctic.fuse#33]
### Skin section

Home Widgets

### Current Behavior

Hi @jurialmunkey,

I have added only single Submenu Widgets and no other normal widgets under the Home menu. At first Kodi launch the Submenu W
Widget is not loading automatically and I've to go to the Submenu manually to load the Widget under it. Once I do this all other Submenu Widgets load automatically. Is there any wait to load the first focused Submenu Widget at Kodi launch? Please advise.

### Expected Behavior

The first focused Submenu Widget should load automatically at Kodi launch.

### Steps To Reproduce

Create Submenu Widgets only under the Home menu and no other normal Widgets. Launch Kodi. The first focused Submenu Widget should load automatically at launch but it's not loading at present.

### Screenshots and Additional Info

How it looks currently at Kodi launch:
![IMG20230731030939](https://github.com/jurialmunkey/skin.arctic.fuse/assets/65297828/6974e39d-878a-4651-ad21-36fda6af034b)

How it should actually look at Kodi launch:
![IMG20230731030953](https://github.com/jurialmunkey/skin.arctic.fuse/assets/65297828/da7cf199-4ab0-4984-b1c5-ad40be13940e)

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
Hmmm, this might be difficult to solve -- Submenu is only visible once mainmenu gains focus (otherwise it doesn't know which submenu to show) but the widget gets set when the mainmenu gains focus (so first time submenu not visible so it ends up empty).

I cheated a bit on the hubs by making it fallback to the spotlight path so that at least something will display when that happens -- I could do the same for the homescreen. I think that's probably the best I can get it.

**Comment by AakashC2020** [comment]
> Hmmm, this might be difficult to solve -- Submenu is only visible once mainmenu gains focus (otherwise it doesn't know which submenu to show) but the widget gets set when the mainmenu gains focus (so first time submenu not visible so it ends up empty).
> 
> I cheated a bit on the hubs by making it fallback to the spotlight path so that at least something will display when that happens -- I could do the same for the homescreen. I think that's probably the best I can get it.

Fine @jurialmunkey . I'll wait for this update. Thank you!

**Comment by jurialmunkey** [comment]
Does this issue still happen?

**Comment by AakashC2020** [comment]
> Does this issue still happen?

Hi @jurialmunkey,

I'll check and let you know.

**Comment by AakashC2020** [comment]
Hi @jurialmunkey,

I've checked and can confirm that this issue is resolved now. You can close this issue ticket. Thank you!
