### ISSUE TITLE
:zap: Hardcoded unlocalizable strings in Skin Variables.

### ISSUE THREAD

**Issue by taiseer999** [jurialmunkey/skin.arctic.fuse#335]
### Skin section

Widgets

### Current Behavior

Although I did all of the Arabic language of the skin some areas do not get translated as shown in the screenshots

### Expected Behavior

To have the parts showing the translated text

### Steps To Reproduce

changing Kodi language to Arabic should get all the translated text to show what the strings.po of resource.language.ar_sa contains 

please note that the strings.po of resource.language.ar_sa is updated and translated as per [v0.4.36](https://github.com/jurialmunkey/skin.arctic.fuse/releases/tag/v0.4.36)

here https://github.com/jurialmunkey/skin.arctic.fuse/pull/334 

### Screenshots and Additional Info

![Screenshot 2023-12-20 at 10 39 36 AM](https://github.com/jurialmunkey/skin.arctic.fuse/assets/118752825/b7b1a4eb-79c7-4827-8e7e-c9e8aff277ac)
![Screenshot 2023-12-20 at 10 39 59 AM](https://github.com/jurialmunkey/skin.arctic.fuse/assets/118752825/017815f0-a78d-4b80-8a4f-6d2b7de65701)
![Screenshot 2023-12-20 at 10 40 45 AM](https://github.com/jurialmunkey/skin.arctic.fuse/assets/118752825/28dd497a-195a-4d77-b377-216dca464f42)
![Screenshot 2023-12-20 at 10 40 54 AM](https://github.com/jurialmunkey/skin.arctic.fuse/assets/118752825/c25d1f6e-596a-4494-934b-c062e565916a)

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
In your first two screenshots, if you have translated these then they should show (maybe you needed to reload the skin or had some other issue with the translation file).

For the second two screenshots, these are strings in SkinVariables so cannot be translated in the skin. These are currently hardcoded into the addon and are not yet available for translation as I'm still working out the specifics of the functionality.

**Comment by jurialmunkey** [comment]
FYI I've updated skinvariables now with localized versions of these strings.

**Comment by icarok99** [comment]
I just solved this.

![IMG_20231223_225532](https://github.com/jurialmunkey/skin.arctic.fuse/assets/46580318/b2d18016-bd5b-48dd-b868-eeef223489f2)

**Comment by icarok99** [comment]
The problem is here.
![IMG_20231223_230636](https://github.com/jurialmunkey/skin.arctic.fuse/assets/46580318/bdc8e0ca-a212-41e6-99dd-e28bacdd1435)
