### ISSUE TITLE
return to previous

### ISSUE THREAD

**Issue by kris06** [jurialmunkey/skin.arctic.fuse#336]
### Skin section

Other

### Feature description

a return to the initial state of navigation would be welcome (This function exists in artic horizon2)

The return action on the remote control does not return navigation to the previous state... (see picture)

### Why is this feature needed? Please justify and explain.

More comfortable

### Screenshots and Additional Info

![20231220_114332](https://github.com/jurialmunkey/skin.arctic.fuse/assets/31409100/8c5f8829-b10a-47d0-b4bb-7e8c73d18403)

### Checklist

- [X] I have made a separate issue for each feature I am requesting.
- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by jurialmunkey** [comment]
I can't reproduce this behaviour. It works correctly for me.
