### ISSUE TITLE
:bug: Music Library recommendations window empty

### ISSUE THREAD

**Issue by berkhornet** [jurialmunkey/skin.arctic.fuse#338]
### Skin section

Library

### Current Behavior

When pressing down down anywhere in the music library, an "empty" screen is displayed and have to press back to continue

### Expected Behavior

I'm not sure!

### Steps To Reproduce

Go to Music Library
Press Down

### Screenshots and Additional Info

Screenshot from Music Library
![screenshot00000](https://github.com/jurialmunkey/skin.arctic.fuse/assets/67786207/fca1d624-dbae-432d-8d29-ed6b214974ae)

After pressing Down
![screenshot00001](https://github.com/jurialmunkey/skin.arctic.fuse/assets/67786207/851f540c-07af-4452-b182-6db4668a7dbb)

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
Yeah this is the recommendations window you get in movies/tvshows. Obviously not a good fit for music.

Trying to think of ideas for this window for other places where it isn't a good fit. I was leaning towards something similar to recs window but with a few music based widgets (e.g. recently played albums, top 100 etc.).

**Comment by berkhornet** [comment]
Looks good! Many thanks.
