### ISSUE TITLE
[BUG] Spotlight image vanishes on going to Options menu

### ISSUE THREAD

**Issue by AakashC2020** [jurialmunkey/skin.arctic.fuse#34]
### Skin section

Home Widgets

### Current Behavior

Hi @jurialmunkey,

Everytime I go to the Options menu box the Spotlight image vanishes. I've to then manually scroll to the next Spotlight item to make it visible again. The Clearlogo (if any) appears fine though. Could you please check and advise?

### Expected Behavior

The Spotlight image shouldn't vanish on going to the Options menu.

### Steps To Reproduce

Stay on any of the two Spotlight buttons. Long press back to open the Options menu box. Go inside Settings or any other menu inside the Options menu box. On returning back the Spotlight image will vanish.

### Screenshots and Additional Info

![IMG20230731032537](https://github.com/jurialmunkey/skin.arctic.fuse/assets/65297828/df3650c2-5579-4d9e-927c-00b0800b0896)

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
I can't reproduce this issue. Are you on Nexus?

**Comment by AakashC2020** [comment]
> I can't reproduce this issue. Are you on Nexus?

Yes, I'm on Nexus v20.2, but using Kodinerds Maven's build for Dolby Vision videos playback.

**Comment by jurialmunkey** [comment]
Oh I just had a thought about possible cause for this issue.

What background style are you using? (fanart / blur etc.?)

**Comment by AakashC2020** [comment]
> Oh I just had a thought about possible cause for this issue.
> 
> What background style are you using? (fanart / blur etc.?)

Hi @jurialmunkey,

I'm currently using "Real Blur (Quality)" as the Background style.

**Comment by jurialmunkey** [comment]
>
> I'm currently using "Real Blur (Quality)" as the Background style.
>

Okay definitely not the issue I thought it was. 

But I just realised I misread your initial report. I thought you meant the background disappeared *when* opening the options menu (i.e. whilst you were still on the home screen and the options menu panel was open).

I see now you mean if you go into settings and then come *back* to home the image is missing then. It's not necessarily anything to do with the options menu at all -- it's going into settings and then returning. I *can* reproduce that issue.

**Comment by AakashC2020** [comment]
Hi @jurialmunkey,

I've checked and can confirm that this issue is resolved now. Thank you so much!
