### ISSUE TITLE
Code typo in Includes_Search_View.xml

### ISSUE THREAD

**Issue by vspin** [jurialmunkey/skin.arctic.fuse#343]
### Skin section

Widgets

### Current Behavior

I believe there's a typo in [Includes_Search_View.xml ](https://github.com/jurialmunkey/skin.arctic.fuse/blob/omega/1080i/Includes_Search_View.xml) on lines 239-240:

`<onback condition="Integer.IsEqual(Container(5083).CurrentItem,1)">SetFocus(5081)</onback>
<onback condition="Integer.IsEqual(Container(5081).CurrentItem,1)">9097</onback>`

### Expected Behavior

I suspect the code should read;

`<onback condition="Integer.IsEqual(Container(5083).CurrentItem,1)">SetFocus(5083)</onback>
<onback condition="Integer.IsEqual(Container(5083).CurrentItem,1)">9097</onback>`

### Steps To Reproduce

Read code.

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
Yeah the whole condition is wrong with the recent changes to how it functions. ^^^ Should fix it.
