### ISSUE TITLE
:bug: Side Menu not focussed on Home screen

### ISSUE THREAD

**Issue by berkhornet** [jurialmunkey/skin.arctic.fuse#346]
### Skin section

Widgets

### Current Behavior

Using Classic (Widgets Only), when first loading the Home screen, or later when returning to it, it is not obvious where the focus is.

Other symptoms noticed:
1. Pressing "right" from the screenshot below highlights the first item in the side menu.
2. Until "down" and then "up" is pressed it is not possible to press right to focus on the widget(s)
3. Pressing "up" from the screenshot below cycles to the bottom of the side menu (I would have thought it should go to the Search icon)

### Expected Behavior

focussed item should be highlighted

### Steps To Reproduce

Set up Classic mode
restart Kodi

### Screenshots and Additional Info

Scree
![screenshot00003](https://github.com/jurialmunkey/skin.arctic.fuse/assets/67786207/3896f144-1820-4af0-8f82-bc7d8bcb5e3c)
nshot after restarting Kodi

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
I can't reproduce.

Check that you haven't left your layout in configuration mode (padlock unlocked).

The unlocked mode is only for configuration. It is not for general use and will cause several issues if you leave your layout unlocked. Will be removing this feature entirely next update.

**Comment by berkhornet** [comment]
Thanks for reply. I checked and the layout is locked. However, I had the first item in the side menu disabled. When I enabled the first item, on start up the home screen focussed on the first item in the first widget.

**Comment by jurialmunkey** [comment]
Ah right, that'll be an ID mismatch then because it is trying to send focus to first item which doesn't exist. If you move the position of the home icon to the end, it should fix it (doesn't actually matter what position it is, as long as first item is not disabled).

**Comment by berkhornet** [comment]
That fixed it. Thanks.
