### ISSUE TITLE
TV Show playback Bug

### ISSUE THREAD

**Issue by adamosborne83** [jurialmunkey/skin.arctic.fuse#351]
### Skin section

Widgets

### Current Behavior

Morning jurial, I hope you can help. 

I get an issue with TV Shows and only on TV shows. Where I get an error saying failed to play media.
I've been playing around, and I currently have Kodi to 'show media' If I play off a Widget, with View 'List Media' It will not play...
See log I have included Kodi and umbrella log.
Https://paste.kodi.tv/ojoridugep
Https://paste.kodi.tv/adinugapox 

But, if view type on TV Shows is 'Combined Landscape' then it plays, see logs again 

Https://paste.kodi.tv/boxopameta
Https://paste.kodi.tv/oderusahiv

### Expected Behavior

Tv shows to playback regardless of view type. 

### Steps To Reproduce

As above

### Screenshots and Additional Info

Hope I have provided enough info.

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
The list view doesn't do anything special, so this sounds like either an issue with the plugin itself or the widget setup.

This line looks weird to me:
`Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.umbrella/VIDEO_TS/VIDEO_TS.IFO]`

Looks like it is trying to play a DVD...

On the skin side, one thing to check is to make sure you haven't added your widgets as "programs" and are actually adding them via a videos path (i.e. via video add-ons, not program add-ons).

**Comment by jurialmunkey** [comment]
Also I don't know what this means?
` I currently have Kodi to 'show media'`

I don't think that's a Kodi setting? If that's a plugin setting, then it sounds like an issue with that setting.

**Comment by jurialmunkey** [comment]
Actually, there's something really weird going on with that view. It's just crashing Kodi whenever I try to play an episode. It makes no sense at all -- I've even stripped it right back to a super simple view and it is still having problems. There must be some sort of weird issue with an ID that Kodi dislikes.

**Comment by jurialmunkey** [comment]
Nope it's an Omega nightly issue.

It doesn't matter what view it is, Kodi will crash or have weird behaviour when trying to play episodes via .strm in any view. Going back to earlier nightlies resolves the issue.

The reason it is okay in combined is because that's a widget view which uses the PlayMedia() command instead.

This is a Kodi bug of some sort.

**Comment by adamosborne83** [comment]
Thanks for the info, I also meant 'show info'
This is why kodi needs to be able to separate l, Movies Show Info, TV Shows Play.
Hopefully, kodi fix it.

**Comment by adamosborne83** [comment]
PS, thanks for raising it on Kodi GitHub, nightmare for me to raise issues using Umbrella.

**Comment by adamosborne83** [comment]
Sorry, as I know it passes Devs off when people post in closed issues, what nightlies did you get it to work on? As I down graded to beta2, and still have the issue.
