### ISSUE TITLE
:sparkles: Font size suggestion 

### ISSUE THREAD

**Issue by icarok99** [jurialmunkey/skin.arctic.fuse#354]
### Skin section

Fonts and Languages

### Feature description

Change font size from 64 to 57.

### Why is this feature needed? Please justify and explain.

Font size 57 is ideal for some content with a large name.

### Screenshots and Additional Info

Before 
![Screenshot_2023-12-24-17-37-08-466_org xbmc kodi](https://github.com/jurialmunkey/skin.arctic.fuse/assets/46580318/00ed48cb-2487-4b57-b26c-f0a564e50c1d)
After 
![Screenshot_2023-12-24-17-37-55-538_org xbmc kodi](https://github.com/jurialmunkey/skin.arctic.fuse/assets/46580318/7b65b30b-7fc9-4f6b-9037-ecca52f4b7a7)
Before 
![Screenshot_2023-12-24-17-37-23-982_org xbmc kodi](https://github.com/jurialmunkey/skin.arctic.fuse/assets/46580318/3ed0bf1d-8e2e-4f66-922d-71c13a3f79c2)
After
![Screenshot_2023-12-24-17-38-07-924_org xbmc kodi](https://github.com/jurialmunkey/skin.arctic.fuse/assets/46580318/28ab99fb-5093-4106-a30b-52c41f658283)

### Checklist

- [X] I have made a separate issue for each feature I am requesting.
- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by jurialmunkey** [comment]
It actually was meant to be 56 the whole time as you can see in the Font.xml comment about the size rules:
https://github.com/jurialmunkey/skin.arctic.fuse/blob/f8391f98cfbeaccb8257642d9aef91d1ae27be2c/1080i/Font.xml#L4-L20


I must've accidentally left in the larger size when I was testing it out and then never noticed.
