### ISSUE TITLE
Search not showing tv shows and nothing happens when i click tmdb tv shows

### ISSUE THREAD

**Issue by sajith2505** [jurialmunkey/skin.arctic.fuse#355]
### Skin section

Widgets

### Current Behavior

Search not showing tv shows and nothing happens when i click tmdb tv shows, like when i search rick and morty only the movies come up
![image](https://github.com/jurialmunkey/skin.arctic.fuse/assets/118279708/7a5f33cd-0fbd-47a3-90b7-ca3d568f4c56)

### Expected Behavior

expect to see both movies and tv shows after search

### Steps To Reproduce

1. go to search
2. type in whatever i want to search
3. only movies come up

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
You need to **focus** the tmdb tv shows button with your **remote** or **keyboard** (not the mouse). Then you will see the TV show results.

**Comment by sajith2505** [comment]
that works thank you
