### ISSUE TITLE
Ability to go onto Page Line

### ISSUE THREAD

**Issue by adamosborne83** [jurialmunkey/skin.arctic.fuse#356]
### Skin section

Widgets

### Feature description

I'm sure I use to be able to go onto the page line and slide across to scroll through movies and pages.

### Why is this feature needed? Please justify and explain.

Easier visually to scroll

### Screenshots and Additional Info

https://imgur.com/a/fi1lwjZ

### Checklist

- [X] I have made a separate issue for each feature I am requesting.
- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by jurialmunkey** [comment]
Press right.

**Comment by jurialmunkey** [comment]
Right from list. I made it so that it has a proper vertical scrollbar.
