### ISSUE TITLE
Widget full circle loop 

### ISSUE THREAD

**Issue by DROIDshield** [jurialmunkey/skin.arctic.fuse#36]
### Skin section

Home Widgets

### Feature description

@jurialmunkey, hey I wonder if its posto join the back end of the widgets to the front so where the end row runs out it loops back to the beginning as otherwise as shown in my pic it leaves a gap until the first widget starts again?

BTW the othe enhancements you've been making are epic.👍
![20230731_005604](https://github.com/jurialmunkey/skin.arctic.fuse/assets/97023369/716ecdfe-d289-46e6-8208-493413a43b0d)

### Why is this feature needed? Please justify and explain.

Keeps the screen uniform rather than a missing batch of wide open space at the end of a row.

### Checklist

- [X] I have made a separate issue for each feature I am requesting.
- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by jurialmunkey** [comment]
Do you mean the list would endlessly wrap around so that there is no start or end?

A wrap like that is definitely possible and I could add it as an option. It would mean that you can't return to the side menu by pressing left though because Kodi will wrap it around in both directions.

**Comment by DROIDshield** [comment]
> Do you mean the list would endlessly wrap around so that there is no start or end?
> 
> A wrap like that is definitely possible and I could add it as an option. It would mean that you can't return to the side menu by pressing left though because Kodi will wrap it around in both directions.

Yes... exactly that. I knowing would not go back to the side menu but that's just a double click and your back at it...

So if it could be implemented formethat would be excellent.. see what you think.  Cheers.
