### ISSUE TITLE
[BUG] Main Menu Problem 

### ISSUE THREAD

**Issue by test01203** [jurialmunkey/skin.arctic.fuse#37]
### Skin section

Other

### Current Behavior

Changing the main menu according to my choice
Does nothing in the main view
There is indeed a setting and I added things to it, but nothing appears in the main menu

### Expected Behavior

Changing the menu according to the user's choice

### Steps To Reproduce

1.Settings - main menu

### Screenshots and Additional Info

![image](https://github.com/jurialmunkey/skin.arctic.fuse/assets/104188844/20be9306-8e8b-493f-88f5-99b8423cc4d1)
![image](https://github.com/jurialmunkey/skin.arctic.fuse/assets/104188844/0328b008-c311-46a1-9e29-cc80ba51b277)
![image](https://github.com/jurialmunkey/skin.arctic.fuse/assets/104188844/2d659676-94ee-4513-82e8-500f0d10b28d)

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
You are configuring the HOME menu. That is different from the SIDE menu.

The HOME menu is the categories, submenus and widgets listed UNDER the play button.

To configure the SIDE menu you must scroll further down and you can change each of the individual items:

![screenshot00108](https://github.com/jurialmunkey/skin.arctic.fuse/assets/4618719/d232639e-d6c8-4351-94f6-b840549bcda5)

**Comment by test01203** [comment]
> You are configuring the HOME menu. That is different from the SIDE menu.
> 
> The HOME menu is the categories, submenus and widgets listed UNDER the play button.
> 
> To configure the SIDE menu you must scroll further down and you can change each of the individual items:
> 
> ![screenshot00108](https://user-images.githubusercontent.com/4618719/257154979-d232639e-d6c8-4351-94f6-b840549bcda5.jpg)

Ok, I understand how it works
The problem right now is that for some reason you limited the side menu to 4 widgets
And if you want more, there is no option.
In addition, when moving over the name of the menu with the keyboard, it does not open by itself
But you have to choose it
