### ISSUE TITLE
Navigation, again.

### ISSUE THREAD

**Issue by adamosborne83** [jurialmunkey/skin.arctic.fuse#371]
### Skin section

Widgets

### Feature description

I know you're trying to simplify navigation, so feel free to dismiss this.

But when in Box Srts for example, on clicking back up on android remote, it now always goes to menu 1st then requiring another back up to get out of it, then on main page it defaults to the menu icon.

### Why is this feature needed? Please justify and explain.

See video, additional taps.

### Screenshots and Additional Info

https://github.com/jurialmunkey/skin.arctic.fuse/assets/78307374/6cc2245f-2c09-4661-89f9-d09611faa8f4

### Checklist

- [X] I have made a separate issue for each feature I am requesting.
- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by jurialmunkey** [comment]
It needs to be this way. Otherwise there's no way to get to side menu if navigation is set to wrap. 
It'd also defeat the entire purpose of standardising the behaviour.

Given that some of the most frequent repeatedly raised issues relate to inconsistencies in navigation, I think it would be a massive step backwards (heh) to undo that work. Consistency beats mild inconvenience of pressing back twice.

Also -- if you're wanting a way to close the entire window, it's simply a matter of changing your keymap to remap your back key to the `PreviousMenu` action instead of the `Back` action in the videos window
https://kodi.wiki/view/Keymap

Can use the Keymap Editor addon to remap keys via GUI
https://kodi.wiki/view/Add-on:Keymap_Editor

**Comment by adamosborne83** [comment]
> It needs to be this way. Otherwise there's no way to get to side menu if navigation is set to wrap. 
> It'd also defeat the entire purpose of standardising the behaviour.
> 
> Given that some of the most frequent repeatedly raised issues relate to inconsistencies in navigation, I think it would be a massive step backwards (heh) to undo that work. Consistency beats mild inconvenience of pressing back twice.
> 
> Also -- if you're wanting a way to close the entire window, it's simply a matter of changing your keymap to remap your back key to the `PreviousMenu` action instead of the `Back` action in the videos window
> https://kodi.wiki/view/Keymap
> 
> Can use the Keymap Editor addon to remap keys via GUI
> https://kodi.wiki/view/Add-on:Keymap_Editor
> 

Thanks again Jurial for the reply, and then going out your way to try and find a solution, I did actually play with keymap editor, unfortunately it did not have the desired effect, as it takes you totally out of the menu.... ie Home Screen l, Then Boxsets, then for example Batman, the 'PreviousMenu' remap would then take you to homescreen, it does not stay within the BoxSets so I could then jeep scrolling.

Mild (very mild) inconvenience it is 😀

**Comment by jurialmunkey** [comment]
It's also annoying because there is a `ParentDir` action which is *meant* to do exactly what you're looking for (take you up one folder to parent dir) but as far as I can tell at some stage it just became another name for Back rather than doing its own thing.

**Comment by adamosborne83** [comment]
> It's also annoying because there is a `ParentDir` action which is *meant* to do exactly what you're looking for (take you up one folder to parent dir) but as far as I can tell at some stage it just became another name for Back rather than doing its own thing.

100%, I looked at the one too.... but.... in the box set, then takes you to exactly where I want to be, but then.... it takes you to 'movies folder' then 'files' etc etc, keeps going back within the directory itself as opposed to just the once.

No worries, you know I am thankful.
