### ISSUE TITLE
:sparkles: Quick Access to Addon Settings within an addon. 

### ISSUE THREAD

**Issue by Goldenfreddy0703** [jurialmunkey/skin.arctic.fuse#372]
### Skin section

Within an Addon itself

### Feature description

Hey there, i got AF setup and everything and it is fantastic but one downside im having is that i can no longer access the addon settings within the addon im using, Im able to in AH2 but not in AF. If you guys could add a quick way to access addon settings in the addon itself that would be very useful and fantastic.
 
 Here are some screenshots of what i mean:
 - AH2 with Addon Settings:
 ![AH2 Addon Settings](https://github.com/jurialmunkey/skin.arctic.fuse/assets/62456796/f7404dac-6ce1-4d07-b87b-c6565ca91030)

- AF without Addon Settings:
![AF Addon Settings Request](https://github.com/jurialmunkey/skin.arctic.fuse/assets/62456796/9867d9d9-192e-40f9-a994-2f53533689ac)

### Why is this feature needed? Please justify and explain.

Reason why i think this feature would be needed is so that users can easily access the addon settings encase something goes wrong within there addon or streams without having to back out all the way. It would be very convenient and useful for the user and they would not have to back out all the way and all. 

### Screenshots and Additional Info

If you guys could add this in the future, that would be very much appreciated and would help significantly.

Thank you

### Checklist

- [X] I have made a separate issue for each feature I am requesting.
- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by jurialmunkey** [comment]
I'm not sure that it should go up the top with the filter/sort/view options, so instead I've put it into the contextmenu side buttons.

Should be able to now longpress on an item inside an addon and get to the settings that way. Probably more convenient that way anyway rather than having to go all the way up to the top.

**Comment by Goldenfreddy0703** [comment]
Oh that's very convenient, thank you so much and your the best. This is going to help me out significantly so if something ever goes wrong in an addon, I can always access addon settings without backing out all the way. 

Again, thank you so much, your the best and I'm so happy to be using this skin. Your awesome!!!!!!
