### ISSUE TITLE
:sparkles: return / back button (don't open side menu)

### ISSUE THREAD

**Issue by SJ1O** [jurialmunkey/skin.arctic.fuse#374]
### Skin section

Widgets

### Feature description

Hello Jurial, I hope you had a good Christmas. I was just wondering would it be possible to make the return / back button just go back / return rather then open up the side menu. 

This Is new behaviour since afew updates back and it kinda effects the navigation when going back pages. 

### Why is this feature needed? Please justify and explain.

For me personally I think it's a more natural Browing / navigation experience. If I need the side menu I click left if I want to go back a page I go back. Rather then constantly opening the side menu every time you want to go back a page.

### Checklist

- [X] I have made a separate issue for each feature I am requesting.
- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by jurialmunkey** [comment]
Then how do you ever go to the side menu? You will be forever stuck on the widgets/categories.

See discussion that was had here https://github.com/jurialmunkey/skin.arctic.fuse/issues/371#issuecomment-1872452990

**Comment by jurialmunkey** [comment]
I mean, I can add an option to disable special handling of the back button but I don't think you guys are going to like it as much as you think.

Disabling special handling will mean back does nothing on the home screen. 
It will mean in a hub it just closes the hub immediately.
If you're on a scrollbar or a combined window, it will also close immediately.
If you are on the filter buttons at the top of the screen, it will close immediately.

It has to be an all or nothing approach because without standardisation it just ends up a confusing mess both in terms of behaviour and for me to maintain/fix issues.

**Comment by SJ1O** [comment]
Hmm id maybe just have the wrap function on right clicks but I'm not a coding expert like yourself so it's easy for me to say things. I'm not sure how it functioned previously as I never used wrap. But wrap and loop seem basically the same to me. 

Yh I don't think thats the best option probably better just to press back twice as you mentioned. Or a option to disable wrap haha. 

Sorry for the duplicate I did have a brief look at other requests and also used the search issue field before creating the issue.

**Comment by jurialmunkey** [comment]
Wrap navigation goes immediately to start/end of widget without going through the menu, that's the point of the option vs. loop. It's only possible to have that option with the current back behaviour. 

I don't have an issue with having an option to disable special handling of back but it will have consequences that you might also not like (see my edit to comment above).

The takeaway point is that the behaviour needs to be standardised across the skin. It needs to be either on or off, and not have micro-specialised behaviour which differs from place to place. 

All having specialised behaviour does is make it confusing for lay-person users. It also makes it exceedingly difficult for myself to maintain codewise. Lots of micro-options turns it into an endless game of whack-a-mole where fixing one thing causes another.

**Comment by xyzfre** [comment]
My opinion, I think things are perfect The way they are working now.

**Comment by SJ1O** [comment]
I think the special handling has more benefits then just pressing back twice so I think I'll just get used to pressing back twice. 

Will changing the back button to PreviousMenu via the keymap option that you mentioned going Todo the same thing as disabling special handling?  If so I'll give this try and see how I get on. However I do imagine that I'd miss the way the special handling makes things function. I have a feeling it might not be worth you wasting your time adding the option.

And I completely understand and I imagine it's a very complex task as it is without adding all these micro options.

Just more question how did it previously work/function when using wrap how did people get back to the menu before the back button opened the menu. I no longer have a old version to test.

**Comment by jurialmunkey** [comment]
> Will changing the back button to PreviousMenu via the keymap option that you mentioned going Todo the same thing as disabling special handling?

Close but not exactly. It's a slightly more extreme version in that it closes the entire window instead of going up to parent folder.

So e.g. say you go `Home > TVShows Hub > TVShows > Breaking Bad > Season 1 > Episodes` then "PreviousMenu" will close the TVShow library window and take you immediately back to TVShows Hub rather than Seasons.

> Just more question how did it previously work/function when using wrap how did people get back to the menu before the back button opened the menu. I no longer have a old version to test.

By having a lot of (buggy) special handling for specific scenarios that would break and cause weird behaviour (e.g. focus getting stuck on a non-existent control).

**Comment by SJ1O** [comment]
Ok thanks very much for explaining. I think I would like to test this disabled special handling option then if it's not to much bother for yourself. I did just look at the keymap option but got a little overwhelmed and didn't want to mess up my current keymap I previously had some help setting that and hate to bug people for help haha.

Ahh I see we'll probably for the best than pressing back twice isn't a issue just different to what I was used to on previous versions. And less bugs is definitely better than pressing back twice.

Sorry to have pestered you and thanks for your explanations.

I'm going to grab you a coffee now you definitely deserve it :)

**Comment by jurialmunkey** [comment]
Okay I've added a secret option to disable back button special handling. In next version you can toggle it by adding a shortcut to your options menu with the action:
```
Skin.ToggleSetting(Navigation.DisableOnBackSpecialHandling)
```

I'm not sure if I want to expose this via the GUI yet as it is honestly very frustrating in some places like home where back essentially will do nothing now.

**Comment by adamosborne83** [comment]
> Okay I've added a secret option to disable back button special handling. In next version you can toggle it by adding a shortcut to your options menu with the action:
> 
> ```
> Skin.ToggleSetting(Navigation.DisableOnBackSpecialHandling)
> ```
> 
> I'm not sure if I want to expose this via the GUI yet as it is honestly very frustrating in some places like home where back essentially will do nothing now.

Worse update EVER, you know I mean that in a nice way haha....
It's shut me up about navigation in future.
