### ISSUE TITLE
:sparkles: 'Refresh' option on the Manage... context menu

### ISSUE THREAD

**Issue by Dml2023** [jurialmunkey/skin.arctic.fuse#375]
### Skin section

Library

### Feature description

Hi JurialMunkey, was wondering if there is the possibility to add in the Refresh menu option on the Manage... context menu in Arctic Fuse like the refresh option that is in your Arctic Horizon skin.

### Why is this feature needed? Please justify and explain.

I use local .nfo files and there are times that I make changes after adding to the Kodi database and I would use the refresh option to update any changes into the database. I cant seem to find refresh on any context menu in Arctic Fuse.

### Checklist

- [X] I have made a separate issue for each feature I am requesting.
- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by jurialmunkey** [comment]
Skins generally can't control the context menu items. The only parts I can control are the side buttons (e.g. the Cancel, Plot etc. ones).

When you say "Refresh" are you talking about the button inside the info dialog which rescrapes the item? I think I might've accidentally removed it in last update -- it is supposed to show in the artwork section.

**Comment by Dml2023** [comment]
Thanks JM. I'd say that is it. I only called it a Context menu as that was the heading I saw on screen. But yes in AH the Refresh item is with the Artwork option.

**Comment by Dml2023** [comment]
Hi Jurialmunkey,

I've just updated to 0.4.45~omega and I can't seem to find the 'Refresh' option. In AH2, from the library view I can long press on a library title, select Information, press left, select Manage and then on the 'menu' that appears I can select Refresh. In AF the Information screen does not have a Manage button to select and selecting 'Manage...' on the menu that appears on a long press in library view does not have the Refresh option (which is where I can find 'Choose Art'). Maybe I'm just looking in all the wrong places, so if you could let me know where I should be directing my remote, that would be awesome. 

Thanks again for your amazing work.

**Comment by jurialmunkey** [comment]
Open info. Go to the artwork icon at the bottom (the gallery). Click it and you can manage artwork including refresh there.

**Comment by Dml2023** [comment]
Ahh. It never occurred to me to actually click/select on that icon. Something that you may want to make uniform though, if you access the Choose Art dialogue from 'long press title in library > Manage... > Choose Art', _that_ version of the dialogue does not have the Refresh or Rating side buttons.

**Comment by jurialmunkey** [comment]
The refresh button is a kodi builtin button for the info dialog. Theres no command for it as far as I know, so it's only possible in info.

**Comment by Dml2023** [comment]
Oh Ok. Thanks for the explanation. It's weird that Kodi would have a Choose Art' dialog that would have different options depending on where it was accessed from. In any case I now know which way to access it to get the refresh button now.

**Comment by jurialmunkey** [comment]
The button isn't part of the choose art dialog. That's a fake button which sends a click to the real button hidden in the background since I don't have space for more buttons in info.

**Comment by Dml2023** [comment]
I think I understand now. Thank you so much for your patience with explaining how this works.
