### ISSUE TITLE
Latest update break skin on Nexus 

### ISSUE THREAD

**Issue by rapteev** [jurialmunkey/skin.arctic.fuse#376]
### Skin section

Widgets

### Current Behavior

Hi
Latest update break skin on kodi Nexus 
It throws a skin variable error and do not build the menu and we cannot do anything.

### Expected Behavior

Everything works ok 

### Steps To Reproduce

Update to the skin variables and latest skin version 

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by ludovik35** [comment]
I confirm, I was also opening an issue.

I join my kodi log and my skin variable.
[script.skinvariables.config_files.zip](https://github.com/jurialmunkey/skin.arctic.fuse/files/13801000/script.skinvariables.config_files.zip)
[kodi.log](https://github.com/jurialmunkey/skin.arctic.fuse/files/13801001/kodi.log)

**Comment by berkhornet** [comment]
I encountered this error after update to 0.4.44.

I fixed it by reinstalling Skin Variables from the  repository and then reinstalling Arctic Fuse.

Hope this helps

**Comment by rapteev** [comment]
That do not seem to work for me. Always get error on skin variables. At least on my windows 11 setup

**Comment by berkhornet** [comment]
@rapteev I think you must have a different issue to me then. My fix worked for another user on the forum.

**Comment by ludovik35** [comment]
I've backup my configuration files (setting+nodes)
I followed your advice and uninstalled Artic Fuse and Script Variable.

After re-installation, everything restarts in its original version.
However, when I want to restore my initial files, the bug prevents me from loading my initial configuration.

So this bug hasn't really been solved. 

I'm also running Windows 11 as @rapteev

**Comment by ludovik35** [comment]
Also no possiblity modify item from inital config => same bug

**Comment by rapteev** [comment]
Yeah I did exactly that. After I copied my old settings the error comes up. Probably something on this new version is incompatible with old settings on skin variables or the skin itself.
I deleted everything and restart kodi with estuary and installed skin and skin variables from scratch and it works ok but now I don’t have my old setup. Well it’s not so much trouble but it was nice if Jurialmunkey can figure the problem. I’m going to wait and now use the skin only with the default setup.

**Comment by berkhornet** [comment]
Strange, as after I reinstalled Skin Variables and Arctic Fuse, I still had my original settings and menus/widgets and everything looks fine.

**Comment by icarok99** [comment]
> Confirmo, também estava abrindo um fascículo.
> 
> Não há mais itens de menu até o lançamento 0.4.44.
> 
> Eu associo meu log kodi e meus arquivos de configuração de variáveis ​​​​de skin:
> 
> [script.skinvariables.config_files.zip](https://github.com/jurialmunkey/skin.arctic.fuse/files/13801000/script.skinvariables.config_files.zip)
> 
> [kodi.log](https://github.com/jurialmunkey/skin.arctic.fuse/files/13801001/kodi.log)

Update Kodi Nexus to latest version 20.2

**Comment by ludovik35** [comment]
Thanks for your advice @icarok99, indeed it's better to be up to date before saying things aren't working.

Unfortunately after the kodi update no change.

So I kept looking.
To try and pinpoint the problem. I reinstalled "script.variable" and "skin.fuse", then reloaded one by one my old node files (.json), going through ui to the widget customization module each time to reload the changes properly.

In the end, I was able to determine that the bug at home came from a single json file.
In my case, it was the "skinvariables-shortcut-searchmenu.json" node. All the other nodes worked fine.

So I went back to the initial "skinvariables-shortcut-searchmenu.json" node, which I modified from the UI, and now everything's fine.

Be careful though, for me the problem came from the "skinvariables-shortcut-searchmenu.json" node, but for others the problem may come from other nodes.

It's up to you to investigate...

**Comment by jurialmunkey** [comment]
@rapteev - I need a log.... Saying "It throws a skin variable error" is not useful.

**Comment by jurialmunkey** [comment]
@ludovik35 Can you try that change https://github.com/jurialmunkey/skin.arctic.fuse/commit/7df58d15875915d39671d102136f3d5feb0b4c08 in the commit above? I think it should fix your issue. 

I forgot that ElementTree returns `None` instead of a `""` blank string for the `.text` of a self-closing tag.

**Comment by rapteev** [comment]
Hi 
Sorry.
Here is the log
[kodi.log](https://github.com/jurialmunkey/skin.arctic.fuse/files/13802474/kodi.log)

**Comment by jurialmunkey** [comment]
@rapteev - Thanks. I think it is the same issue as ludovik35 - can you test that change I posted above?

Should just be able to edit the file `skin.arctic.fuse/shortcuts/generator/data/setup/search_path.xml` in a text editor and change line 263 from `<value />` to `<value></value>` then reload skin and rebuild widgets should work.

**Comment by ludovik35** [comment]
Hi @jurialmunkey,

Happy new year to you.

Sorry for my late reply, I was busy for the change of year 🎉 🍻 . 
Everything works fine with the new update.

Thanks for this quick fix

**Comment by ambulancePilot** [comment]
Unfortunately I'm still getting the skin variables error with the latest version. Any ideas? I seem to be the only one.

https://paste.kodi.tv/baholijeya

**Comment by jurialmunkey** [comment]
@ambulancePilot please install skin variables 2.1.1

**Comment by ambulancePilot** [comment]
Thank you for that, I will give it a try! I haven't tried that version but I do know it wasn't working with 2.1.0... will try when I get back from work tomorrow morning. Thanks for all you do!
