### ISSUE TITLE
Manage Artwork

### ISSUE THREAD

**Issue by adamosborne83** [jurialmunkey/skin.arctic.fuse#378]
### Skin section

Widgets

### Current Behavior

First and foremost, Happy New Year

Can you please bring back the manage artwork from within the actual movie itself.
Use to be beneath the WiKi icon.

### Expected Behavior

Last update removed this ability, and it is now far too difficult to change artwork within local library items. 

### Steps To Reproduce

Go into movie and option is removed. 

### Screenshots and Additional Info

https://github.com/jurialmunkey/skin.arctic.fuse/assets/78307374/f9443b8c-0d41-4afa-81c6-68630ffafcec

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
This was already fixed.

**Comment by adamosborne83** [comment]
> This was already fixed. 

Sorry, this is .45, cannot see anything on your commits either.
This icon was on .44 but gone on .45

**Comment by adamosborne83** [comment]
> > This was already fixed. 
> 
> Sorry, this is .45, cannot see anything on your commits either.
> This icon was on .44 but gone on .45

Sorry, me being an idiot. Didn't realise I have accidently, unticked Search and Options.
