### ISSUE TITLE
:bug: Disabled Widgets not respected

### ISSUE THREAD

**Issue by berkhornet** [jurialmunkey/skin.arctic.fuse#388]
### Skin section

Widgets

### Current Behavior

Widgets marked as disabled in Widget Customisation are still visible

### Expected Behavior

Disabled widgets should not be visible

### Steps To Reproduce

1. Go to Widget Customisation
2. Disable a widget
3. Rebuild
4. Widget ids still visible

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
That should fix it.

Note you might get some weird behaviour with disabled widgets. The big one is that you can't disable the first widget or you'll have focus issues. It will also cause issues for stacked widgets, and possibly the "shorter" widgets like Apps as those rely on being able to check previous/next IDs.

**Comment by berkhornet** [comment]
Many thanks. I’ve run a brief test with Classic and Compound layouts, with and without Stacked Widgets and with disabled widgets not being the first. All looks good. Thanks again.

Mick Rollitt
________________________________
