### ISSUE TITLE
TV Shows 

### ISSUE THREAD

**Issue by adamosborne83** [jurialmunkey/skin.arctic.fuse#389]
### Skin section

Widgets

### Current Behavior

Hi Jurial, in reference to my issue last week with TV Shows not playing.
I believe I have found the issue, now it may be difficult for you to test as it does involves using Umbrella Addon.

So after numerous installs on numerous devices to try and eliminate the 'why' I can now establish that if Play Next is enabled in Umbrella then TVShows will not play.

This is odd as it works on all other skins. I have spoken to Umbrella Dev, and cannot understand the why.

### Expected Behavior

Tv shows to play when play next is enabled in Umbrella.

### Steps To Reproduce

Need use of Umbrella.

### Screenshots and Additional Info

[kodi.log](https://github.com/jurialmunkey/skin.arctic.fuse/files/13833454/kodi.log)
[kodi.old.log](https://github.com/jurialmunkey/skin.arctic.fuse/files/13833455/kodi.old.log)
[umbrella.log](https://github.com/jurialmunkey/skin.arctic.fuse/files/13833456/umbrella.log)

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by adamosborne83** [comment]
Here are some more logs with the EXACT same set up, but without auto play enabled. 
Scrapes and works perfect. 
[umbrella.log](https://github.com/jurialmunkey/skin.arctic.fuse/files/13833495/umbrella.log)
[kodi.old.log](https://github.com/jurialmunkey/skin.arctic.fuse/files/13833496/kodi.old.log)
[kodi.log](https://github.com/jurialmunkey/skin.arctic.fuse/files/13833497/kodi.log)

**Comment by jurialmunkey** [comment]
When you say "all other skins" have you tested in Estuary?

List view is just about the simplest view there is. It is very unlikely to cause unexpected behaviour. It is just standard Kodi list view.

**Comment by jurialmunkey** [comment]
I mean this is why your content is not playing 
```
plugin://plugin.video.umbrella/VIDEO_TS/VIDEO_TS.IFO
```

It's trying to play a DVD... Skin can't change the path of items. Pretty sure this is something wrong with the addon.

**Comment by adamosborne83** [comment]
> When you say "all other skins" have you tested in Estuary?
> 
> List view is just about the simplest view there is. It is very unlikely to cause unexpected behaviour. It is just standard Kodi list view.

So, this is where it does get interesting. On a fresh install, with just Umbrella and Estuary it works fine, play next enabled and disabled.
I install Fuse with Play Next disabled, all is good.
I can play tv shows without issue, as log shows.
As soon as I turn on Play Next, the issue happens. 
Although even if I then disable play next the issue continues and even if I go back to Estuary the issue stays the same.
Some how and reasons I cannot even begin to think of, Fuse seems to be a catalyst for this issue.
Something to donwith play next.

**Comment by jurialmunkey** [comment]
It is highly unlikely that the skin is somehow changing the behaviour of an addon when the skin isn't even active. It doesn't touch addon settings and all the dependencies are fairly separate.

My immediate thought would be that a module used as dependency for Umbrella has an update which isn't installed on a fresh install. Installing the skin would trigger Kodi to check for updates and install them (thus only seeing the behaviour after installing the skin).

The other possibility is that because installing the skin from my repo requires enabling option to allow official addons to be installed from unofficial sources, that then there might be a module getting updated from one of the other repos you've got installed.

**Comment by adamosborne83** [comment]
> It is highly unlikely that the skin is somehow changing the behaviour of an addon when the skin isn't even active. It doesn't touch addon settings and none of skin dependencies (tmdbhelper, skinvariables, texturemaker) do either.
> 
> My immediate thought would be that a module used as dependency for Umbrella has an update which isn't installed on a fresh install. Installing the skin would trigger Kodi to check for updates and install them (thus only seeing the behaviour after installing the skin).
> 
> The other possibility is that because installing the skin from my repo requires enabling option to allow official addons to be installed from unofficial sources, that then there might be a module getting updated from one of the other repos you've got installed.

Yea, I cannot figure it out at all, I will try and do some more investigation but, as you'll see from my logs, repos/addons are at a minimal. 
These have been my addons for the last 3 years.
Maybe I'll blame Kodi 21 somehow.
Just seems so so odd.
