### ISSUE TITLE
Daily font reset after skin update

### ISSUE THREAD

**Issue by cg00001** [jurialmunkey/skin.arctic.fuse#393]
### Skin section

Fonts and Languages

### Feature description

After every skin update my personal favourite font is reset to skin default, it would be nice to have a switch in settings to making this font reset stop before next update.

### Why is this feature needed? Please justify and explain.

It's easily fixed by copying & pasting a file in place, still annoying.

### Checklist

- [X] I have made a separate issue for each feature I am requesting.
- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by jurialmunkey** [comment]
Nothing the skin can control. When an addon updates Kodi overwrites the folder.
