### ISSUE TITLE
:bug: Customise background image

### ISSUE THREAD

**Issue by icarok99** [jurialmunkey/skin.arctic.fuse#396]
### Skin section

Other

### Current Behavior

Unable is to place change background color.

### Expected Behavior

It was supposed to be possible change background color.

### Steps To Reproduce

Customise background image > select the color or choose a custom one.

### Screenshots and Additional Info
Customise background image
![Screenshot_2024-01-07-08-55-38-362_org xbmc kodi](https://github.com/jurialmunkey/skin.arctic.fuse/assets/46580318/bb86e18f-a57b-4b16-8677-02f894b1625f)

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
Startup image and background image are different things.

Startup image changes the image shown in the initialisation splash and login screen:

![screenshot00362](https://github.com/jurialmunkey/skin.arctic.fuse/assets/4618719/d568fac4-38b7-42f2-a3f5-b428ec6a01cd)

The **background** image changes the fallback blur image. If you want to change that then you must do:
Customise background image > Custom > Choose image

Then close settings for the blur to update.

Both work fine for me.

**Comment by icarok99** [comment]
> Startup image and background image are different things.
> 
> Startup image changes the image shown in the initialisation splash and login screen:
> 
> ![screenshot00362](https://private-user-images.githubusercontent.com/4618719/294795721-d568fac4-38b7-42f2-a3f5-b428ec6a01cd.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ2Nzg1NDEsIm5iZiI6MTcwNDY3ODI0MSwicGF0aCI6Ii80NjE4NzE5LzI5NDc5NTcyMS1kNTY4ZmFjNC0zOGI3LTQyZjItYTNmNS1iNDI4ZWM2YTAxY2QuanBnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEwOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMDhUMDE0NDAxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MDNjZDc0YjU2NjFiODc5MDQyMGUxNzA4OWZkYjhiYjVhYTUxNjkxMmVjMzdkNmQ1OTNkZjkwMjdiMTQ4MTUxMCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.dGYuWVIS83wD3F6XZknAbm_rX-Z9CsOJh36yw3O-hjg)
> 
> The **background** image changes the fallback blur image. If you want to change that then you must do: Customise background image > Custom > Choose image
> 
> Then close settings for the blur to update.
> 
> Both work fine for me.


https://github.com/jurialmunkey/skin.arctic.fuse/assets/46580318/0267d1c9-c22e-4d3f-bac2-e6417913df04

**Comment by jurialmunkey** [comment]
You missed an important step:

> Then close settings for the blur to update.

The blur image only updates when the window changes.
