### ISSUE TITLE
Widgets line disabled will not allow the rest of widgets to be scrolled.

### ISSUE THREAD

**Issue by DROIDshield** [jurialmunkey/skin.arctic.fuse#398]
### Skin section

Widgets

### Current Behavior

I have 26 widgets rows. My first one is Xmas Movies which I now don't need until Xmas 24 so I disabled this list, but now I cannot see or scroll down though my next 25 widgets. 

So I can either delete the row completely or keep it showing to make my skin work as it should.

I'd  like to keep this row but hidden so seems a bug is in the code that locks out the widgets when one has been disabled. 

### Expected Behavior

Disabled widget row should be hidden and others should still show an be assessable. 

### Steps To Reproduce

Disable a row in settings
Reload
Check other widget rows.

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
You can't disable the first widget because disabled widgets still occupy an ID slot. Move it down and you should be fine.

I did consider entirely removing the disable option as it will cause issues like this, so you need to be careful with how you use it.

**Comment by DROIDshield** [comment]
I will try that later.. cheers and no, don't disable this feature... its a great idea for hiding widget rows temporarily... saves having to lock all details a second time. Just disable or enable...👍

**Comment by DROIDshield** [comment]
Done the above, works beautifully...thanks again👍
