### ISSUE TITLE
:sparkles: Adding Reviews / Comments in the info page. 

### ISSUE THREAD

**Issue by Goldenfreddy0703** [jurialmunkey/skin.arctic.fuse#399]
### Skin section

Context Menu > Information

### Feature description

Hey there, its me again and i have a feature request about adding Reviews and Comments. In AH skin when you click information in the context menu on a movie or tv show, you would get Writers, Posters, Fanart, List, Reviews/Comments, ect. If you guys could add Reviews/Comments on the Info page on AF, that would be great. 

### Why is this feature needed? Please justify and explain.

Reason why this feature is maybe needed is cause people sometimes go to the Reviews / Comments instead of the ratings on what they think of that movie or tv show and its quite useful for me when watching stuff. 

### Screenshots and Additional Info

Here are some Screenshots of what i mean:

AH Info Page:
![image](https://github.com/jurialmunkey/skin.arctic.fuse/assets/62456796/d44cda0a-8cdc-4a99-915d-5772a4bb9ca1)

AF Info Page:
![image](https://github.com/jurialmunkey/skin.arctic.fuse/assets/62456796/18b30a8d-4229-4d52-85f5-ab41de6a8961)

### Checklist

- [X] I have made a separate issue for each feature I am requesting.
- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by jurialmunkey** [comment]
Authorize Trakt in TMDbHelper. That will give you a Trakt button between Details and Wiki. Focusing the Trakt button shows comments from Trakt.

**Comment by Goldenfreddy0703** [comment]
Oh I thought I already did authorize trakt in tmdb helper, it must have deauthorize itself sense trakt has been always having problems. Will check it out and see, thank you

**Comment by Goldenfreddy0703** [comment]
Ok so i authorized my Trakt but i don't happen to see the Trakt button between Details and Wiki. 

Here are the steps to reproduce:
1. Authorize Trakt in tmdb helper addon settings
2. Find a movie or tv show in your tmdb helper
3. Notice there is no Trakt button between Details and Wiki

Im using Kodi 20.2

**Comment by jurialmunkey** [comment]
Did you restart Kodi afterwards?

**Comment by Goldenfreddy0703** [comment]
> Did you restart Kodi afterwards?

Hey sorry I did not get back to you but unfortunately i should have done that. I did just restart my kodi and it's showing now. I'm honestly surprised that my trakt was not authenticated with tmdb helper, I should have checked that. That was my bad for making this future request, thank you very much for helping me.
