### ISSUE TITLE
:sparkles: A way to fullscreen in a movie or show without pressing Tab

### ISSUE THREAD

**Issue by Goldenfreddy0703** [jurialmunkey/skin.arctic.fuse#400]
### Skin section

Control and Menu

### Feature description

Hey there, I have one last feature request, whenever im watching a show or movie and i need to back out of the show or movie, it would still play in the background which is fine but in order for me to go back to the movie or show i was watching, I would have to go to the main menu and backout and i have no Tab button on my remote, If you could add a way to go back into full screen like in AH2, That would be fantastic. 

### Why is this feature needed? Please justify and explain.

I see this useful in alot of ways cause people may not have a Tab button on there remotes to go back to movies or tv shows and they would have to back out all the way to the main menu. 

### Screenshots and Additional Info

Here is a screenshot of what i mean:

AH2 had this buttons and they were very very useful:
![image](https://github.com/jurialmunkey/skin.arctic.fuse/assets/62456796/6a40540c-d0e2-4fc8-a4d0-1dca7ef8f172)

If you could add those buttons or just the fullscreen button, that would be amazing.
Thank you

### Checklist

- [X] I have made a separate issue for each feature I am requesting.
- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by Goldenfreddy0703** [comment]
Ayyyy thank you very much, this will help significantly, especially for Android tv's. 

Thank you!!!!!!!!

**Comment by jurialmunkey** [comment]
Yeah it was a really useful reminder. I kept forgetting to add them, then I'd be watching TV and get annoyed that they weren't there then promptly forget again! 🤣 

Note it is in the options/powermenu not the top menu
(the menu you get from the left side menu button).

![screenshot00364](https://github.com/jurialmunkey/skin.arctic.fuse/assets/4618719/d2cdcec6-cb7e-4ad3-813d-0cca645f04c2)

**Comment by Goldenfreddy0703** [comment]
Awesome, thank you so much and honestly, I would forget them as well if I was making a skin. 🤣 You did an excellent job with this skin and it's amazing. 

Thank you

**Comment by Goldenfreddy0703** [comment]
> ![screenshot00364](https://github.com/jurialmunkey/skin.arctic.fuse/assets/4618719/d2cdcec6-cb7e-4ad3-813d-0cca645f04c2)

Omg I just noticed, your using a surface laptop studio, I have a surface book 3 and it's been the best.
