### ISSUE TITLE
:bug: If Search/Options not displayed cannot edit artwork

### ISSUE THREAD

**Issue by berkhornet** [jurialmunkey/skin.arctic.fuse#401]
### Skin section

Library

### Current Behavior

If the Search/Options option is turned off, it is not possible to edit artwork in the library, as the "picture" icon is not displayed

### Expected Behavior

Ability to edit artwork irrespective of the Search/Options setting

### Steps To Reproduce

1. Turn off Search/Options
2. Go to Video Library
3. Select any item
4. Press I
5. artwork icon not displayed

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
This is the intended behaviour. 

That option is what would've been called "Kiosk Mode" in other skins. It disables access to the settings and search to make a more locked down experience.

**Comment by berkhornet** [comment]
That explains it. Many thanks!

Mick Rollitt
________________________________
