### ISSUE TITLE
[Feature] Add actors and collections to search widget

### ISSUE THREAD

**Issue by 666jones** [jurialmunkey/skin.arctic.fuse#41]
### Skin section

Home Widgets

### Feature description

On AH2 it has the ability to search for actors and collections in the home page search function. Would it be possible to add this to fuse?

### Why is this feature needed? Please justify and explain.

It's a cool feature and makes full use out of the search function.

### Checklist

- [X] I have made a separate issue for each feature I am requesting.
- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by jurialmunkey** [comment]
You can already do this. Just customise the search widgets and add them.

**Comment by 666jones** [comment]
> You can already do this. Just customise the search widgets and add them.

Ahh I see it now. Customise search widget -add item - choose widget and there already created just had to add them. I was thinking it would be default I should of looked abit harder. Thanks very much

**Comment by jurialmunkey** [comment]
Yeah I cut down a bit on the default lists to keep the loading a bit lighter by default. All the same options should be available to select from
