### ISSUE TITLE
This a question and not a bug or feature request.

### ISSUE THREAD

**Issue by DROIDshield** [jurialmunkey/skin.arctic.fuse#410]
### Skin section

Widgets

### Feature description

How can I remove the tag showing after the title of the widget row if at all possible? 
See picture. 
TIA.
![20240113_074349](https://github.com/jurialmunkey/skin.arctic.fuse/assets/97023369/1a3fd60f-8666-470b-921a-fac63364e0d4)

### Why is this feature needed? Please justify and explain.

I would much prefer just the title and not how the row is sorted.

### Checklist

- [X] I have made a separate issue for each feature I am requesting.
- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by Dml2023** [comment]
Hi DROIDshield,
Go to Settings > Skin Settings > Furniture > Viewline section - uncheck 'Sort Method's and ' Icons'

**Comment by DROIDshield** [comment]
Genius.... you sir have just got yourself a Kofi.... Massive thanks again for the input... 👏👏👏👏
