### ISSUE TITLE
:bug: EPG Listings Date no longer shown

### ISSUE THREAD

**Issue by berkhornet** [jurialmunkey/skin.arctic.fuse#411]
### Skin section

PVR

### Current Behavior

On earlier versions of AF, when viewing the EPG and viewing the previous days listings, the actual date of the listings was shown on the ruler at the top of the EPG. With the latest version, the current date is always shown. This is true if the setting "always show date and time" is true or false.

### Expected Behavior

When viewing the EPG, the listings date should be shown (at least if "always show date and time" is set to false. Perhaps the Bottom Right clock could be used for EPG

### Steps To Reproduce

1 Go to EPG
2 Press back to get to an earlier days listings

### Screenshots and Additional Info

Earlier version (0.4.50)
![screenshot00002](https://github.com/jurialmunkey/skin.arctic.fuse/assets/67786207/05571b38-0c41-4cd3-93fb-d31ce61ca0c5)

Latest version
![screenshot00003](https://github.com/jurialmunkey/skin.arctic.fuse/assets/67786207/2e0a6403-589b-4f4b-920a-85067b1aaedd)

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
I think adding this little program guide details to the footer might be the way to go:
That way keeps date/time position consistent in header but still gives a way to see start date/time of program:

![screenshot00373](https://github.com/jurialmunkey/skin.arctic.fuse/assets/4618719/7d977b74-2cca-4fee-85a7-08398d185ad0)

**Comment by berkhornet** [comment]
Sounds good. And looks good. Thank you.

Mick Rollitt
________________________________
