### ISSUE TITLE
:sparkles: View type for live tv 

### ISSUE THREAD

**Issue by icarok99** [jurialmunkey/skin.arctic.fuse#412]
### Skin section

PVR and Live TV

### Feature description

View type list same as arctic horizon 2 skin

### Why is this feature needed? Please justify and explain.

why the current viewing type the person needs to press the button for a while still needs to select option to play the channel.

### Screenshots and Additional Info

![Screenshot_2024-01-13-20-04-19-583_org xbmc kodi](https://github.com/jurialmunkey/skin.arctic.fuse/assets/46580318/3a03c85c-ec77-4681-a933-62f0081d9e20)

### Checklist

- [X] I have made a separate issue for each feature I am requesting.
- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by jurialmunkey** [comment]
You can get a detailed view with:

`Skin Settings > Viewtypes > EPG and Channels style`

It's different to the AH2 view as the AH2 style does not fit this skin, but it should have all the same information.

**Comment by DROIDshield** [comment]
What PVR is being used in the above pic? As im using Simple PVR Client  and doesn't look as smooth as this...
@icarok99  @jurialmunkey

**Comment by icarok99** [comment]
> What PVR is being used in the above pic? As im using Simple PVR Client and doesn't look as smooth as this... @icarok99 @jurialmunkey

PVR IPTV Simple Client, This type of preview is from the Arctic Horizon 2 skin.

**Comment by DROIDshield** [comment]
> > What PVR is being used in the above pic? As im using Simple PVR Client and doesn't look as smooth as this... @icarok99 @jurialmunkey
> 
> PVR IPTV Simple Client, This type of preview is from the Arctic Horizon 2 skin.

Oh wow... okay I like that view but since I've deleted AH2 a while ago now I didn't know.

Thanks.
