### ISSUE TITLE
:bug:Our Holiday Themes have stopped working 😂

### ISSUE THREAD

**Issue by Goldenfreddy0703** [jurialmunkey/skin.arctic.fuse#416]
### Skin section

Holiday Themes

### Current Behavior

Heyyyyy its not really important at all but our amazing Holiday Themes have stopped working, Whenever i turned them on, nothing happens unfortunately. One of the updates might have broke the setting. 

### Expected Behavior

To have our amazing Holiday Themes working. 🤣

### Steps To Reproduce

1. Settings > Skin Settings > Expert > Holiday Themes
2. Turn on the Holiday Themes
3. See if they are working. 

### Screenshots and Additional Info

![image](https://github.com/jurialmunkey/skin.arctic.fuse/assets/62456796/ab7ad010-66b8-42e3-a254-3d6a4cf912b7)

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
It's not the holidays any more! Time to go back to work!

Seriously though, they have a date expiry where they turn off/on automatically.

**Comment by Goldenfreddy0703** [comment]
> It's not the holidays any more! Time to go back to work!

🤣 True

> Seriously though, they have a date expiry where they turn off/on automatically. 

Oh that's cool, I did not know that. Wait so if you were to turn them on manually, wouldn't they show the snowflakes and all?

**Comment by jurialmunkey** [comment]
You can't manually turn on the themes. 

The setting toggles whether the theme is *allowed* to activate, not whether or not it *is* activated.

**Comment by Goldenfreddy0703** [comment]
Ohhhh ok makes sense, thank you very much!!!

**Comment by DROIDshield** [comment]
That's a pretty damn cool idea...😊
