### ISSUE TITLE
Offer to play from library.

### ISSUE THREAD

**Issue by rapteev** [jurialmunkey/skin.arctic.fuse#417]
### Skin section

PVR and Live TV

### Feature description

Hi
It would be great when we select a live tv channel that is playing a movie (or tv show) if that movie exists on library, offer to play from library or continue playing from live tv.

### Why is this feature needed? Please justify and explain.

Just a great way to watch that program from beginning. And to make live tv experience more immersive.

### Screenshots and Additional Info

Just an example from channels dvr:

![](https://community-assets.getchannels.com/original/3X/7/6/76aefa0df4ca839284d8aa7b9381afaed2884a25.png)

### Checklist

- [X] I have made a separate issue for each feature I am requesting.
- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by jurialmunkey** [comment]
This is a feature which would need to be supported in Kodi first. Skin can't override play action.
