### ISSUE TITLE
Please add some color to those icons

### ISSUE THREAD

**Issue by NeverExists07** [jurialmunkey/skin.arctic.fuse#433]
### Skin section

Library

### Feature description

Please let us use our own media icons or add some color please. They look horrible and hard to see on a TV cause they are very small. Some color would look fantastic!!!!  Your other skins have great icons.

### Why is this feature needed? Please justify and explain.

The current icons look drab and hard to read. I like your icons in your other skins

### Checklist

- [X] I have made a separate issue for each feature I am requesting.
- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by jurialmunkey** [comment]
You can already set your own icons for shortcuts.

**Comment by NeverExists07** [comment]
Sorry I meant the media icons. Like for Dolby Vision and the audio codes.

________________________________

**Comment by jurialmunkey** [comment]
Adding colour icons will not change their size so does not solve this issue.

Also just a note, but saying things that I've spent a lot of time on look "horrible" is not a good way to go about asking for features
