### ISSUE TITLE
Please add some color to the media codec icons

### ISSUE THREAD

**Issue by NeverExists07** [jurialmunkey/skin.arctic.fuse#435]
### Skin section

Other

### Feature description

Hi, can you please add some color to the icons for Dolby Vision. UHD Bluray and such other icons in the bottom info panel? Or at least allow us to change them? Thanks!

### Why is this feature needed? Please justify and explain.

More Customization is always a good thing. Plus it would make the info pop!

### Checklist

- [X] I have made a separate issue for each feature I am requesting.
- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by xyzfre** [comment]
I also notice I don't get the Dolby Vision icon or HDR icon on AH2 they will always show up.
