### ISSUE TITLE
Widget Type : Board :Request

### ISSUE THREAD

**Issue by JFG1000** [jurialmunkey/skin.arctic.fuse#440]
### Skin section

Widgets

### Feature description

Hey jurial would it be atall possible to add a label on the widget or underneath like on the landscape type widget to indicate the season number, title and episode, this would be hugely appreciated. 

### Why is this feature needed? Please justify and explain.

It makes it easier to get info for that particular widget without the need to highlight it on the homescreen as that's currently the only way. 

### Screenshots and Additional Info

![20240124_144040](https://github.com/jurialmunkey/skin.arctic.fuse/assets/76907836/d02ba4da-e44f-4579-98f7-8d477a3c7f64)

### Checklist

- [X] I have made a separate issue for each feature I am requesting.
- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by jurialmunkey** [comment]
Why not use landscape then if you want text labels. 

I feel like it might defeat the purpose of  the board widget to add text to it. That's kinda the reason it exists: to have widget style which shows landscape artwork cleanly at an expanded size without any text.

**Comment by JFG1000** [comment]
I much prefer the bigger size, it had labels with AH2 on the widget and had used it for so long unless you could possibly Implement a setting to enable/disable the text? Would be massively appreciated
