### ISSUE TITLE
HDR Format Icons missing

### ISSUE THREAD

**Issue by NeverExists07** [jurialmunkey/skin.arctic.fuse#444]
### Skin section

Other

### Current Behavior

Hi, thank you so much for the color icons. They look fantastic! Only now there is no HDR Fornat icon for HDR10, Dolby Vision or HDR10+. I would think most people would need this info for their library. Thanks for all your hard work.

### Expected Behavior

Please add back HDR Format codes.

### Steps To Reproduce

Pretty straight forward

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by JFG1000** [comment]
@jurialmunkey i see this was included as a commit, where would the setting be to enable it? I can't see it as a codec logo with a hdr file

**Comment by FrostByteLXV** [comment]
Not working here either.  I'm using the following in MKV file names.
.DV.
.HDR10.
.HDR10plus.

**Comment by JFG1000** [comment]
@FrostByteLXV I'm thinking it just may be in the next repo update to be honest

**Comment by FrostByteLXV** [comment]
> @FrostByteLXV I'm thinking it just may be in the next repo update to be honest

Ahh, got it.  I'm not much of a coder, but I wasn't seeing any string matches for anything past Atmos and DTSX.  Thanks

**Comment by jurialmunkey** [comment]
It does not match filename.

It requires hdrtype to be set.

**Comment by FrostByteLXV** [comment]
Thanks jurialmunkey.  I'm using Emby to scrape movies so I'll see if the dev there can update hdrtype.

**Comment by JFG1000** [comment]
@jurialmunkey could you tell me exactly how to bring up the omega context menu thing to edit the codecs, I was reading about it on the forum, I've got omega but can't figure it out, I'd like to replace all the icons at the bottom of the screen shot with the HDR type ones etc if possible 
![20240219_081104](https://github.com/jurialmunkey/skin.arctic.fuse/assets/76907836/cba7850f-461b-4b86-a7e2-e2c8aaa554cb)

**Comment by jurialmunkey** [comment]
@JFG1000 - You cannot edit the codecs information via context menu. Whether the codec information is set is the responsibility of the plugin. But there really is no reason for a plugin which can have multiple sources to have codec information.

You are confusing this with the video versions feature which is only available for library items.
