### ISSUE TITLE
Info label

### ISSUE THREAD

**Issue by Peter3344** [jurialmunkey/skin.arctic.fuse#445]
### Skin section

Widgets

### Current Behavior

After the last update I got this issue
![image](https://github.com/jurialmunkey/skin.arctic.fuse/assets/129428292/92ec3397-938b-49ab-b6cc-448049ee5727)

### Expected Behavior

—-

### Steps To Reproduce

—

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
Oh I just realised what this might be. What font set are you using?

**Comment by jurialmunkey** [comment]
I assume that's the Arabic/Hebrew font set. Above commit should fix it.

**Comment by Peter3344** [comment]
> I assume that's the Arabic/Hebrew font set. Above commit should fix it.

Yes it's working fine now thank you 🙏
