### ISSUE TITLE
Additional Board/card view option for episodes

### ISSUE THREAD

**Issue by Liquidrag** [jurialmunkey/skin.arctic.fuse#449]
### Skin section

Widgets

### Feature description

Is there a way for an additional board option to be similar to card view for TV episodes? 

### Why is this feature needed? Please justify and explain.

Currently card view for episodes show the poster and fanart while board view shows the episode thumbnail. Would be great if we could have a card view with show posters and episode thumbnails.

### Screenshots and Additional Info

Card view
<img width="1241" alt="Screen Shot 2024-01-28 at 12 30 50 PM" src="https://github.com/jurialmunkey/skin.arctic.fuse/assets/43726430/2d54373d-5f56-4567-863e-b13fc007063c">

Board view
<img width="1235" alt="Screen Shot 2024-01-28 at 12 32 34 PM" src="https://github.com/jurialmunkey/skin.arctic.fuse/assets/43726430/f2622587-7cd7-484b-9841-aa3d81b41216">

Mockup of my idea
<img width="1235" alt="mockup" src="https://github.com/jurialmunkey/skin.arctic.fuse/assets/43726430/fadc3a87-355e-4b50-b8af-c3c904e5f420">

### Checklist

- [X] I have made a separate issue for each feature I am requesting.
- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by jurialmunkey** [comment]
See my comments in the other issue thread: https://github.com/jurialmunkey/skin.arctic.fuse/issues/448#issuecomment-1914050810

Basically see how in your mockup that poster on the right edge doesn't line up like the rest of the layouts do? That's a problem for the animations (plus it just irks me to have one layout which doesn't align properly).

**Comment by Liquidrag** [comment]
I see, thanks for the reply.

**Comment by Liquidrag** [comment]
Thinking again could there be a card option with the existing dimensions for episode thumbnails cropped? I like the idea of seeing the series poster of non-focused episodes.
