### ISSUE TITLE
Split movies and TV appearances in the OSD

### ISSUE THREAD

**Issue by Liquidrag** [jurialmunkey/skin.arctic.fuse#450]
### Skin section

Video OSD

### Feature description

In the OSD, have it like AH2 where movies and TV are separate when you press down on the actor instead of them merged into one list.

### Why is this feature needed? Please justify and explain.

It makes it easier to see what shows or movies they have been in,

### Screenshots and Additional Info

Arctic fuse
<img width="1237" alt="Screen Shot 2024-01-28 at 6 17 52 PM" src="https://github.com/jurialmunkey/skin.arctic.fuse/assets/43726430/9ba53224-dd50-4ec1-a300-7c26c6281cc5">

Arctic Horizon
<img width="1230" alt="Screen Shot 2024-01-28 at 6 53 48 PM" src="https://github.com/jurialmunkey/skin.arctic.fuse/assets/43726430/521507cb-206f-4f96-bec5-efa5aa617ee8">

### Checklist

- [X] I have made a separate issue for each feature I am requesting.
- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by jurialmunkey** [comment]
Yeah I keep flip-flopping a bit on whether or not to split them. 

I use this feature a lot personally and I think it's about 50/50 on whether I find it convenient or annoying to have them combined at any given time.

The bit that frustrates me in AH2 is how the navigation direction changes (you've got to go down to the button and then back up).

Considering there's the space on the left side, I was considering putting the buttons there instead. Basically have two buttons: one to swtich between combined/movies/tv and the other to switch sorting between year/popularity/rating (similar to how credits dialog works).

I'm not sure if that'd be annoying or not having to scroll all the way to the left to change.

**Comment by xyzfre** [comment]
I really miss this feature ,which ever approach you take would work for me having movies and TV shows separate for actors on the OSD screen is so much better ,thank you @jurialmunkey for sharing this beautiful skin

**Comment by Liquidrag** [comment]
Going down then back up was very intuitive for me. 

The option on the left seems interesting and I might like it too. Maybe have a way to hit the back button so you don't have to scroll all the way left again or just put the buttons on the bottom again for ease lol.

**Comment by Liquidrag** [comment]
<img width="1256" alt="Screen Shot 2024-02-02 at 9 54 14 AM" src="https://github.com/jurialmunkey/skin.arctic.fuse/assets/43726430/b00d55e3-1c9f-42a7-ba99-997acd00edb0">
LOVE IT!  Thank you so much!
