### ISSUE TITLE
Add Refresh button to side menu of Movie / TV Series infomation screen.

### ISSUE THREAD

**Issue by QuickSwitchLK** [jurialmunkey/skin.arctic.fuse#452]
### Skin section

Video Info Dialog

### Feature description

Could we please have a "Refresh" icon in the side menu section of the information screen of a Movie / TV Series please. Currently, I have to switch back to KODI's default skin Estuary to access this feature. I can not find any way to access it with Arctic Fuse, context menu, or otherwise.

### Why is this feature needed? Please justify and explain.

If for any reason a Movies or TV Series metadata has changed, a library update will not fix / update to the new data when all info is set to local only. Once the file is in the database the only way to update is to refresh the data under information.

If anyone knows of an addon that can watch for file changes and refresh metadata on .nfo file change please let me know.

Thanks, QuickSwitchLK

### Screenshots and Additional Info

**Estuary Option (See Image Below)**

![Screenshot 2024-01-29 205927](https://github.com/jurialmunkey/skin.arctic.fuse/assets/34122743/8d48ea56-a118-4aa5-a6d4-93da9a92fcbd)

**New Place for Arctic Fuse Option if Possible (See Image Below)**

![Screenshot 2024-01-29 210258](https://github.com/jurialmunkey/skin.arctic.fuse/assets/34122743/dda83ddb-a496-4e80-9eb6-15513f8ed506)

### Checklist

- [X] I have made a separate issue for each feature I am requesting.
- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by Dml2023** [comment]
Hi QuickSwitchLK,

On the information screen, go down to the greyed out artwork icon at the bottom left press select on that button. On the Choose Art' dialog that appears there is a Refresh option on the right hand side. I hope this helps.

**Comment by adamosborne83** [comment]
Is this what you mean?

https://github.com/jurialmunkey/skin.arctic.fuse/assets/78307374/0cdeedc6-3f42-411b-9aa3-8e41f4fe5948

**Comment by QuickSwitchLK** [comment]
That's what I was after, thank you both. Didn't realize or think to look in the cover art option. Plus I didn't know that pressing select on the icon would bring up all those options. All I thought it was for was to flick through the art left and right.

Thanks.

**Comment by icarok99** [comment]
Resolved topic can be closed

**Comment by jurialmunkey** [comment]
Haha yeah maybe it'd be better if the icon was a bit more "settings" like. 

Though I kind of do like how it isn't obvious so that guests are less likely to mess with the artwork settings.
