### ISSUE TITLE
[Feature] AH2 Playnext pop up theme support 

### ISSUE THREAD

**Issue by 666jones** [jurialmunkey/skin.arctic.fuse#46]
### Skin section

Fullscreen Video OSD

### Feature description

Some add-ons have a AH2 Theme for playnext popup. While using it on the fuse skin the buttons don't appear correctly is this something you could fix or should I contact the addon developer. It works perfectly while using AH2 Skin

### Why is this feature needed? Please justify and explain.

It's a really nice PlayNext window 

### Screenshots and Additional Info

![20230730_233927](https://github.com/jurialmunkey/skin.arctic.fuse/assets/121204283/5a480c02-8d80-4c07-b1e7-711a74fbd99a)

### Checklist

- [X] I have made a separate issue for each feature I am requesting.
- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by jurialmunkey** [comment]
Addon developer. Skin has different specs so it won't be compatible with something mde for AH2 specs

**Comment by 666jones** [comment]
> Addon developer. Skin has different specs so it won't be compatible with something mde for AH2 specs

I did think this was the case. I'll post a request to the addon dev. Thanks for your help
