### ISSUE TITLE
New icon request in extras/icons folder.

### ISSUE THREAD

**Issue by sargadelos** [jurialmunkey/skin.arctic.fuse#467]
### Skin section

Other

### Feature description

Would you be open to add a new icon in the extras/icon folder?
It is an icon for a streaming service in Spain (Movistar+).

![mplus](https://github.com/jurialmunkey/skin.arctic.fuse/assets/20935699/f25b5ff4-7367-42a9-90f8-822829c50a3c)

### Why is this feature needed? Please justify and explain.

To be honest this is more a personal request rather than an enhancement.
I have added a side button to open an addon to this streaming service and I have to copy the icon in the folder every time the skin is updated. This is even harder in Chromecast with google TV since I cannot access android/data and I have to modify the zip and update by zip file.

Thank you

### Checklist

- [X] I have made a separate issue for each feature I am requesting.
- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by jurialmunkey** [comment]
You dont need to put icons in the skin folder to use them. Just press back a couple of times and you can get out of the folder and navigate to a different location.

**Comment by sargadelos** [comment]
Sorry I did not know that.

Thank you.
