### ISSUE TITLE
:sparkles: Hide left side item peek

### ISSUE THREAD

**Issue by JFG1000** [jurialmunkey/skin.arctic.fuse#468]
### Skin section

Widgets

### Feature description

Hey jurial I'm would it be atall possible to implement a setting to remove the view of the widget we navigate past when on the homescreen 

### Why is this feature needed? Please justify and explain.

I've noticed it times depending on the widget poster it can be difficult to see the menu icons. 

### Screenshots and Additional Info

![Uploading Screenshot_20240205_211309_Gallery.jpg…]()

### Checklist

- [X] I have made a separate issue for each feature I am requesting.
- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by JFG1000** [comment]
![Screenshot_20240205_211309_Gallery](https://github.com/jurialmunkey/skin.arctic.fuse/assets/76907836/e9c875d6-ca42-4ad8-b8cb-f91293889a7e)

**Comment by reitenth** [comment]
I would also like this added. I was thinking maybe having an arrow somewhere to let it be known you can go left.

**Comment by jurialmunkey** [comment]
This was already added. Will be available in next repo update under Skin Settings > Viewtypes

**Comment by JFG1000** [comment]
This is awesome many thanks for this Jurial most appreciated
