### ISSUE TITLE
[Feature] Trailers in full screen

### ISSUE THREAD

**Issue by 666jones** [jurialmunkey/skin.arctic.fuse#47]
### Skin section

Video Info Dialog

### Feature description

Would it be possible to make trailers play in full screen. Currently they play in the window but there is no way to stop them playing.

### Why is this feature needed? Please justify and explain.

Easy way to stop the trailer playing

### Checklist

- [X] I have made a separate issue for each feature I am requesting.
- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by jurialmunkey** [comment]
In next version
`Skin Settings > Behaviour > Play trailers fullscreen`

Note that playing a trailer fullscreen will force the video info dialog to close

**Comment by 666jones** [comment]
> In next version `Skin Settings > Behaviour > Play trailers fullscreen`
> 
> Note that playing a trailer fullscreen will force the video info dialog to close

Ahh very lovely looking forward to it. Thanks very much
