### ISSUE TITLE
Errors in Log

### ISSUE THREAD

**Issue by adamosborne83** [jurialmunkey/skin.arctic.fuse#470]
### Skin section

Widgets

### Current Behavior

Morning Jurial, 
I trust you're well.

Looking through my kodi logs, there seem to be some errors in refernce to, spotlights and colours Slate.

### Expected Behavior

Just wondering if anything to be concerned about.

### Steps To Reproduce

See in the log.

### Screenshots and Additional Info

[kodi.old.log](https://github.com/jurialmunkey/skin.arctic.fuse/files/14176333/kodi.old.log)

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
If you're talking about this error parsing boolean

```
Error parsing boolean expression [integer.isequal(window.property(tmdbhelper.widgetcontainer),301) + !$exp[exp_hubs_spotlight_hasitems] + !$exp[exp_infodialogs]]
```

Then nothing to be worried about. It's some weird Kodi bug where it complains it can't read the expressions used in autoscroll conditions (but nowhere else).

I may as well "fix" it so it doesn't complain by replacing the expression with the actual condition but definitely nothing to worry about other than log spam.

**Comment by adamosborne83** [comment]
Also, 
This

2024-02-05 18:07:16.396 T:25553   error <general>: GetDirectory - Error getting /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/skin.arctic.fuse/extras/backgrounds/blur/slate_blur.jpg


2024-02-05 18:07:16.396 T:25553   error <general>: GetDirectory - Error getting special://skin/extras/backgrounds/blur/slate_blur.jpg

**Comment by adamosborne83** [comment]
2024-02-05 18:05:15.723 T:25221 warning <general>: Skin has invalid include: skinvariables-powersidemenu-staticitems
2024-02-05 18:05:15.721 T:25221 warning <general>: Skin has invalid include: skinvariables-powermainmenu-staticitems

**Comment by jurialmunkey** [comment]
The background issue was also fixed in the above

The invalid include can be ignored. It simply means your skin variables config had not yet built after an update (or possibly you deleted that entire section of the options menu so the include never builds).

**Comment by adamosborne83** [comment]
> The background issue was also fixed in the above
> 
> The invalid include can be ignored. It simply means your skin variables config had not yet built after an update (or possibly you deleted that entire section of the options menu so the include never builds). 

Makes sense as I totally changed the options side menu.
