### ISSUE TITLE
Is it possible to hide unwatched episode titles to avoid spoiler?

### ISSUE THREAD

**Issue by jkoor** [jurialmunkey/skin.arctic.fuse#474]
### Skin section

Library

### Feature description

Add an option to hide unwatched episode name titles.

### Why is this feature needed? Please justify and explain.

In kodi, I can hide unwatched tvshows eposide plots and thumbs to avoid **spoiler**.
`(Settings/Media/Videos/Show information for unwatched items)`

But the eposide title can't be hidden, sometimes there are spoilers in the eposide title.
For example: `1x10: xxx is killed`

So is it possible to hide unwatched episode name titles?

I also submit an issue to another project`skin.arctic.horizon.2`. The two projects are very excellent which are the best skins I've ever seen.

### Checklist

- [X] I have made a separate issue for each feature I am requesting.
- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by jurialmunkey** [comment]
I dont think this is something the skin should manage.
 
It is better handled by a Kodi setting (like the others), or, for content from a plugin, in the plugin's settings.

For library you can already change the titles of your items as you wish with .nfo files.
