### ISSUE TITLE
Widgets created with 'Autowidget' don't work properly

### ISSUE THREAD

**Issue by laramob** [jurialmunkey/skin.arctic.fuse#476]
### Skin section

Widgets

### Current Behavior

If I create a "Merged Widget" in Autowidget 3.7.0, then point 'Arctic Fuse' at the merged widget, the widget is not created in Autowidgets "active widgets", and only exists in the skin until Kodi is restarted.

### Expected Behavior

The widget should continue to exist after restarting Kodi

### Steps To Reproduce

1. Install Autowidget (I am using 3.7.0).  
2. Using Autowidget, create a Widget group. 
3. Add two smart playlists (or addon content, or library nodes)  to that widget group. 
4. Point "Arctic Fuse" widget to shortcut > addons > video addons > autowidget > My Groups > whatever you named your group > whatever you named it (merged) > add folder

At this point, the widget seems to have been created properly, but here is where the difference happens. 

5. Although the widget has been added, if you go to autowidget > active widgets, you'll see that it doesn't exist.  If you try it an AH2, the widget *will* exist. 
6. Restart Kodi, and Autowidget asks to re-merge that widget.  Using AH2, it doesn't.

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [ ] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
Autowidget only works with skins using SkinShortcuts in a very specific way. Fuse does not use SkinShortcuts at all because SkinShortcuts is no longer developed and cannot do the things it needs. So AutoWidget will also not work properly.

There's simply nothing I can do about it. It's down to how AutoWidget was coded to only work with skins using SkinShortcuts.

Practically all the same features can be achieved with SkinVariables filters.

**Comment by Liquidrag** [comment]
> Practically all the same features can be achieved with SkinVariables filters.

Sorry to piggyback on this but I'm also just discovering SkinVariables because of this thread. I made a list but will it function like Autowidget's merge and filter out duplicates?

**Comment by jurialmunkey** [comment]
If you edit the saved filter manually (can find in addon_data folder) and add a parameter for `"no_label_dupes": "true"` then if there are multiple items with the same name only first will be added.

**Comment by Liquidrag** [comment]
> If you edit the saved filter manually (can find in addon_data folder) and add a parameter for `"no_label_dupes": "true"` then if there are multiple items with the same name only first will be added.

Perfect, thank you! Do you think this could be added in a future update so it can easily be selected as a filter?
