### ISSUE TITLE
Add Board viewtype for Plugins - Episodes

### ISSUE THREAD

**Issue by AakashC2020** [jurialmunkey/skin.arctic.fuse#483]
### Skin section

Widgets

### Feature description

Hi @jurialmunkey,

Hope you are doing well.

I was trying to use the Board widget type for Next Episodes with the newly added text labels option. However, when I went to the next page of the widget the viewtype changed to landscape because there is no Board viewtype option for Plugins - Episodes. Could you please add the Board viewtype option for that? Thank you!

### Why is this feature needed? Please justify and explain.

This feature will help streamline the viewtype from Board to Board while moving from one widget page to the next.

### Screenshots and Additional Info

![IMG20240211150326](https://github.com/jurialmunkey/skin.arctic.fuse/assets/65297828/cfc761a5-8fa3-477b-8169-e8b1c3bc7966)

### Checklist

- [X] I have made a separate issue for each feature I am requesting.
- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by Omarscomin** [comment]
"Card" view would be great for plugins as well! :)

**Comment by jurialmunkey** [comment]
Neither of these widget styles work with the wall. Im very hesitant to add viewtype which will not work as expected with some features. It would essentially mean removing wall entirely which I think a lot of users would be upset about.

**Comment by AakashC2020** [comment]
> Neither of these widget styles work with the wall. Im very hesitant to add viewtype which will not work as expected with some features. It would essentially mean removing wall entirely which I think a lot of users would be upset about.

Hi @jurialmunkey,

Oh, if that's the case then please ignore my above request as even I myself use the wall view which is really great. Thank you for your reply!

**Comment by jurialmunkey** [comment]
Wall is in navigation options. You must disable touch to use it.

**Comment by Liquidrag** [comment]
> Wall is in navigation options. You must disable touch to use it.

Just enabled it to test but still don't see what it does. Can you show a screenshot or video?

**Comment by jurialmunkey** [comment]
When you open the view side panel (for scrolling/filtering) in library, any row based view will automatically switch to wall. It also does the same in Discover for any search widgets.

It's a bit of a performance hog, especially when first loading a new library window (you'll see a much longer delay first time before window displays while it loads in the code) - so if you don't find it particularly useful, remember to turn it off.

**Comment by Liquidrag** [comment]
Ah... I don't use library and that's why I couldn't find it. Thnx JM

**Comment by jurialmunkey** [comment]
BTW when I say "library" I mean views in the media windows (i.e. in contrast to widgets on home/hubs). It will work for plugin content too but you need to be inside the media windows.

**Comment by Liquidrag** [comment]
So I would enable wall, go into fen>Movies>trending where it has a list of movies, Change viewtype and wall should be the but its not.

**Comment by jurialmunkey** [comment]
Yes that's how it works.

It's so that you can see more items when scrolling or filtering. It's useful for large libraries with hundreds of titles.

**Comment by jurialmunkey** [comment]
In the local Kodi library, instead of "clear" there is an option for advanced filtering by basically any property - genre year rating votes etc - similar to how the discover feature works for tmdb -- this is where the wall becomes particularly useful.

**Comment by Liquidrag** [comment]
That makes sense, thanks for explaining it to me.
