### ISSUE TITLE
Navigation: Access scrollbar

### ISSUE THREAD

**Issue by adamosborne83** [jurialmunkey/skin.arctic.fuse#484]
### Skin section

Widgets

### Feature description

Hi Juiral, now I know I promised not to mention navigation again, but I cannot think of a way around it.
When I go into movies or whatever, if I need to access the scroll bar to change views etc, scrolling to get to it takes too long. 

### Why is this feature needed? Please justify and explain.

Immeadiate access to scroll bar

### Screenshots and Additional Info

https://github.com/jurialmunkey/skin.arctic.fuse/assets/78307374/cacc2949-756a-47d0-b166-f42eed30b216

### Checklist

- [X] I have made a separate issue for each feature I am requesting.
- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by jurialmunkey** [comment]
I think pressing right from scrollbar instead of looping around is the only way to do it. Still not great because of the change of direction but I think probably better than needing to scroll all the way to the ends -- plus at least this way the list itself can loop around at top/bottom.

**Comment by adamosborne83** [comment]
Sound Brill, thanks for this.

**Comment by adamosborne83** [comment]
Thanks for this, lovely to have wrap back from top to bottom again.
