### ISSUE TITLE
[BUG/Issue] Been getting a lot of “Playback Failed” after fresh installing Kodi Omega Beta 3

### ISSUE THREAD

**Issue by Nuklear92** [jurialmunkey/skin.arctic.fuse#494]
### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by xyzfre** [comment]
I got a couple of those myself last night. Hope this could be addressed.
