### ISSUE TITLE
Changeable number of hubs

### ISSUE THREAD

**Issue by patkino** [jurialmunkey/skin.arctic.fuse#5]
### Skin section

Home Widgets

### Feature description

Ability to at least remove (or even add) hubs from home menu

### Why is this feature needed? Please justify and explain.

If 4 hubs not needed - extra ones are hanging as "add new"

### Checklist

- [X] I have made a separate issue for each feature I am requesting.
- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by jurialmunkey** [comment]
The number is fixed at five but you can customise all the actions of the side menu in skin settings. They don't need to be hubs, you can set custom actions and icons.

**Comment by jurialmunkey** [comment]
Ah sorry, rereading I see you've found the custom option - you're just looking for a way to disable unused side menu items.

Adding *more* items won't be possible but shouldn't be too much of an issue to disable some. I'll have a think about best approach.

**Comment by patkino** [comment]
Yes. Exactly. 
For now I have spotlight, tv channels and youtube widget at the homepage and separate hubs for movies and tvshows. I don't need more stuff, but cand remove items
