### ISSUE TITLE
:bug: Play counts in left footer not correct.

### ISSUE THREAD

**Issue by Dml2023** [jurialmunkey/skin.arctic.fuse#502]
### Skin section

Widgets

### Current Behavior

With the Play counts and dates setting turned on when I have a 'Watched' or 'In-Progress' show the footer is always displaying 'Played 0 of X episodes'. The last played date appears correctly though.

### Expected Behavior

It should display the correct number of played episodes

### Steps To Reproduce

Make sure the skin furniture setting for Play counts and dates is enabled.
Highlight a widget item for a watched or in-progress show at the bottom of a hub screen, or highlight a watched or in-progress show on the TV Show library screen.

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
When you say "incorrect" what do you mean exactly?

The values display correctly for me for my library items.

**Comment by jurialmunkey** [comment]
Yep dumb typo by me. Somewhere along the line I got the conditions reversed.

**Comment by Dml2023** [comment]
No problem. Thanks again for the amazing work you continue to produce with this incredible skin.
