### ISSUE TITLE
[Feature] uk age mppa rating symbols

### ISSUE THREAD

**Issue by 666jones** [jurialmunkey/skin.arctic.fuse#51]
### Skin section

Other

### Feature description

I see the skin displays uk age mppa rating symbols in the footer. A very nice feature I must say. I was wondering if we could have a option to get these symbols to replace the age rating text in the info line. 

### Why is this feature needed? Please justify and explain.

There nice looking symbols however don't often get to see them

### Checklist

- [X] I have made a separate issue for each feature I am requesting.
- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by jurialmunkey** [comment]
I think in the infoline they'd probably be too small to be readable. Their current size is a double row, so they'd be half the size they are now.

**Comment by 666jones** [comment]
Ahh I see. My eyesight ain't great so that's probably not going to be a good idea. If it can't be done it can't be done, was just putting it out there
