### ISSUE TITLE
v0.4.77~omega breaks spotlight in Categories

### ISSUE THREAD

**Issue by Liquidrag** [jurialmunkey/skin.arctic.fuse#510]
### Skin section

Widgets

### Current Behavior

Spotlight in all sections besides "home" don't change when I move through my widgets.

### Expected Behavior

Spotlight would act like it does in the "home" section when I move through widgets, it changes the spotlight.

In previous versions, it acts like the "home" section

### Steps To Reproduce

1. Goto any other section besides "home"
2. navigate through widgets
3. spotlight does not change

### Screenshots and Additional Info

Made a quick video to show the behavior

https://imgur.com/a/tiE4LLO

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by Liquidrag** [comment]
Mustve been on my end. Redid from scratch and is working as should.

**Comment by jurialmunkey** [comment]
Ah great! Yeah I was just about to comment that I couldn't recreate the issue myself.

**Comment by Liquidrag** [comment]
I'm sorry lol.
