### ISSUE TITLE
:sparkles: Allow "Disable Screen Edge Peak" and Media Filter options together

### ISSUE THREAD

**Issue by berkhornet** [jurialmunkey/skin.arctic.fuse#517]
### Skin section

Other

### Feature description

Would it be possible in a non-touch configuration to disable the Screen Edge Peak but continue to allow the Media Wall Filter option. 

### Why is this feature needed? Please justify and explain.

I prefer that the content doesn't overlap the side menu when scrolling, but also like the media wall feature when scrolling through the library. No worries if this is not feasible - I know you can't please all the people all of the time!

### Checklist

- [X] I have made a separate issue for each feature I am requesting.
- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by C-O-D** [comment]
I would also be very much in favor of this...

**Comment by jurialmunkey** [comment]
It's not possible because the wall functions on the basis of items hanging over the edge of the screen.

It isn't disable because it doesn't work with touch, it's disabled because it needs the offset for the various animations.

**Comment by berkhornet** [comment]
Thanks for your reply. I understand. Must say the skin is coming along very nicely!
