### ISSUE TITLE
File Manager.... Add Source

### ISSUE THREAD

**Issue by adamosborne83** [jurialmunkey/skin.arctic.fuse#524]
### Skin section

Widgets

### Current Behavior

Hey Jurial.
Hope all is well.
I cannot pin point when this bug started, as I very rarely need to Add Spurce in file manager, but I don't seem to be able to access it anymore, but can on stock skin.

### Expected Behavior

Able to add source. 

### Steps To Reproduce

As pics show.

### Screenshots and Additional Info

![firetv_2024-02-29_16_31_19](https://github.com/jurialmunkey/skin.arctic.fuse/assets/78307374/dbbbf8b2-77e8-455f-ab55-363811e5f7b2)
![firetv_2024-02-29_16_31_54](https://github.com/jurialmunkey/skin.arctic.fuse/assets/78307374/719ad8e7-3e17-48c5-9325-ca8b90a1bf35)

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by Liquidrag** [comment]
Click the pencil icon
![309001220-719ad8e7-3e17-48c5-9325-ca8b90a1bf35](https://github.com/jurialmunkey/skin.arctic.fuse/assets/43726430/2f9cff55-bab2-4345-b3ef-6d16281b2f0a)

**Comment by adamosborne83** [comment]
> Click the pencil icon
> ![309001220-719ad8e7-3e17-48c5-9325-ca8b90a1bf35](https://github.com/jurialmunkey/skin.arctic.fuse/assets/43726430/2f9cff55-bab2-4345-b3ef-6d16281b2f0a)
> 

The pencil allows you to manually type the path, but usually the folder will allow you to browse, as the picture shows with Estuary. 
Cheers for the comment though.

**Comment by Liquidrag** [comment]
@adamosborne83 odd, it is working on mine. I'm on mac osx, maybe add your os and someone else can test it.
<img width="1235" alt="Screen Shot 2024-02-29 at 10 55 19 AM" src="https://github.com/jurialmunkey/skin.arctic.fuse/assets/43726430/6eb19d2f-f328-4b12-b9fb-0fca236b44dd">

**Comment by adamosborne83** [comment]
> @adamosborne83 odd, it is working on mine. I'm on mac osx, maybe add your os and someone else can test it.
> <img width="1235" alt="Screen Shot 2024-02-29 at 10 55 19 AM" src="https://github.com/jurialmunkey/skin.arctic.fuse/assets/43726430/6eb19d2f-f328-4b12-b9fb-0fca236b44dd">
> 

Thanks for that, now leaning more towards latest kodi nightly.

**Comment by Liquidrag** [comment]
I'm on Omega beta 3.

**Comment by adamosborne83** [comment]
> I'm on Omega beta 3.

I'm on 26th Feb nightly.

**Comment by Liquidrag** [comment]
> > I'm on Omega beta 3.
> 
> I'm on 26th Feb nightly.

Just tested Feb 27 nightly and its working.

**Comment by jurialmunkey** [comment]
Make sure you have the latest version of the skin. It was a bug introduces in 4.79 that was fixed in 4.80

https://github.com/jurialmunkey/skin.arctic.fuse/commit/9eba3b404d62b3a39c84510bf5b0d690f8915563

**Comment by adamosborne83** [comment]
> Make sure you have the latest version of the skin. It was a bug introduces in 4.79 that was fixed in 4.80
> 
> https://github.com/jurialmunkey/skin.arctic.fuse/commit/9eba3b404d62b3a39c84510bf5b0d690f8915563

I'll have to check later, I swear if it's because I'm on .79 and not .80 then I forfeit the right to ever post here again haha.

**Comment by adamosborne83** [comment]
I hang my head in shame.
