### ISSUE TITLE
:sparkles: IMDb & Rotten Tomatoes reviews along with Trakt reviews

### ISSUE THREAD

**Issue by onlytanmoy** [jurialmunkey/skin.arctic.fuse#527]
### Skin section

Other

### Feature description

So we already have a section for Trakt in Details page along with Trailers, wiki etc, where I can view the Trakt reviews of the movie in question which I find very useful. On a similar note can you please add option for IMDb and Rotten tomatoes reviews as well?

### Why is this feature needed? Please justify and explain.

Having the option to view the reviews from the other 2 sources will help me make more informed decisions whether to watch or skip the movie/show.

### Checklist

- [X] I have made a separate issue for each feature I am requesting.
- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by jurialmunkey** [comment]
What api is this data coming from.? Imdb api costs 400k a year.

**Comment by onlytanmoy** [comment]
Ah right, you told me that once I remember now, scratch that request mate 🙂
