### ISSUE TITLE
[BUG] search widget (descover) cast / crew

### ISSUE THREAD

**Issue by 666jones** [jurialmunkey/skin.arctic.fuse#53]
### Skin section

Home Widgets

### Current Behavior

Search widget set as (descover) when selecting cast or crew then selecting a actor TV shows always come back with 0 results. However it works fine for movie results 

### Expected Behavior

TV shows to show results for the selected actor.

### Steps To Reproduce

1.Use the search widget.
2. Select cast or crew.
3.  Select a actor or search a name.
4. You will get movie results but no TV show results for the actor 

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
Not supported by the discover API for tvshows
https://developer.themoviedb.org/reference/discover-tv

Only movies supports with_cast with_crew with_people
https://developer.themoviedb.org/reference/discover-movie

**Comment by 666jones** [comment]
> Not supported by the discover API for tvshows https://developer.themoviedb.org/reference/discover-tv
> 
> Only movies supports with_cast with_crew with_people https://developer.themoviedb.org/reference/discover-movie

Ahh yes I see thanks for clearing that up
