### ISSUE TITLE
Info screen collection sort options?

### ISSUE THREAD

**Issue by Liquidrag** [jurialmunkey/skin.arctic.fuse#530]
### Skin section

Video Info Dialog

### Feature description

Sort options for collection on the info page. 

### Why is this feature needed? Please justify and explain.

Movie collections like James Bond are huge and currently, they are mixed up and hard to sort through.

### Screenshots and Additional Info

1. Sort order is all over the place.
<img width="1236" alt="Screen Shot 2024-03-03 at 10 25 44 AM" src="https://github.com/jurialmunkey/skin.arctic.fuse/assets/43726430/02ce139d-7000-42dc-a206-2ff56c691ffd">
2. Currently when selecting "collection" wiki options pop up.
<img width="1229" alt="Screen Shot 2024-03-03 at 10 43 22 AM" src="https://github.com/jurialmunkey/skin.arctic.fuse/assets/43726430/801ae2b6-1801-4cda-8917-8d4f51423123">
3. Possibly add a context menu or change the wiki panel to have options so that we can change the sort order and also add a wiki page

### Checklist

- [X] I have made a separate issue for each feature I am requesting.
- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by jurialmunkey** [comment]
I think options to change the sort order might be a bit of a pain to manage but these definitely should be in order -- I guess I just assumed they came in order of the collection but it looks like it is actually order they were added to TMDb which pretty much the least desirable order! Will fix so they are in chronological order.

**Comment by Liquidrag** [comment]
Yes, its definitely the least desirable order. TYSVM!
