### ISSUE TITLE
Has Spotlight cycle options been removed?

### ISSUE THREAD

**Issue by Liquidrag** [jurialmunkey/skin.arctic.fuse#531]
### Skin section

Widgets

### Feature description

Bring back the option to manually cycle through spotlight

### Why is this feature needed? Please justify and explain.

If I see an item I want to explore more but it cycles to the next item before I can get to it, I have to wait for it to cycle back through the list 

### Screenshots and Additional Info

I miss you
<img width="1240" alt="Screen Shot 2024-03-03 at 11 07 49 AM" src="https://github.com/jurialmunkey/skin.arctic.fuse/assets/43726430/b6d0bfcd-9e71-4b54-822e-0638fc548b14">

### Checklist

- [X] I have made a separate issue for each feature I am requesting.
- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by xyzfre** [comment]
You can enable it in skin settings/Navigation Spotlight-Spinner,, I thought the same thing, but I found it in the settings. Hope this helps.

**Comment by Liquidrag** [comment]
> You can enable it in skin settings/Navigation/Spotlight-Spinner,, I thought the same thing, but I found it in the settings. Hope this helps.

OMG thank you!
