### ISSUE TITLE
Focus changes when editing widgets

### ISSUE THREAD

**Issue by Liquidrag** [jurialmunkey/skin.arctic.fuse#532]
### Skin section

Other

### Current Behavior

When there are 2 categories, the focus hops to the next category when editing widget items. Does not do it when there are 1 or 3 categories

### Expected Behavior

when editing a widget it should stay on the widget so i can continually edit without it hopping to another widget after every change

### Steps To Reproduce

1. edit widgets
2. make an edit in a widget with 2 columns
3. it will hop to a widget in the next column

### Screenshots and Additional Info

Heres is a video of it happening

https://github.com/jurialmunkey/skin.arctic.fuse/assets/43726430/e655f28f-5644-48f7-84c5-4b973f38d392

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
Is this still an issue with v0.5+ now that I've switched to editing within the dialog?

**Comment by VelimirSaban** [comment]
I have the same problem. With new editing, it's ok when you are in a new window doing changes, but when you go back to this main one, add something, or edit anything on a widget - it's still here, you are moved to a new widget automatically. This started a few versions back, I can't remember exactly, maybe a few days ago.

**Comment by Liquidrag** [comment]
> Is this still an issue with v0.5+ now that I've switched to editing within the dialog?

Looks like its fixed on my end. Thank you.
