### ISSUE TITLE
Text Cut Off

### ISSUE THREAD

**Issue by adamosborne83** [jurialmunkey/skin.arctic.fuse#533]
### Skin section

Video OSD

### Current Behavior

Firstly, I promise I've checked I'm on latest version.
Part of the OSD is now cut off.

### Expected Behavior

All visible 

### Steps To Reproduce

See picture, bottom left.

### Screenshots and Additional Info

![20240303_195101](https://github.com/jurialmunkey/skin.arctic.fuse/assets/78307374/c862e654-870c-44d9-9840-759d746aff3a)

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
I'm fairly confident I didn't move it, so I'd say this looks like an overscan or resolution issue. 

Make sure overscan on your TV is turned off (will depend on tv what the exact setting is called) and that your screen resolution in kodi properly matches TV res. Also double check windowed vs fullscreen in Kodi's resolution settings. And there's a screen calibration tool in kodi settings somewhere which you can use to adjust manually - but shouldn't really need to on a modern TV as long as you've got right resolution and have disabled overscan.

**Comment by adamosborne83** [comment]
It must had a funny 10 mins as today all movies and TV shows are fine.
Joys and wonders of kodi 😀
