### ISSUE TITLE
:bug: Start-up image is black

### ISSUE THREAD

**Issue by supsyman** [jurialmunkey/skin.arctic.fuse#534]
### Skin section

Other

### Current Behavior

Thanks for this great and lovely skin. I am experiencing a problem in which the start up image comes up as a black screen. I have tried to change the start up image to a single file and even an image folder but it always comes up as a black screen.  When I changed it in the skin to a video file, this worked but images come out as a black screen. It also doesn’t work when set to skin default. This happened on Kodi 20.2 and Kodi 20.5 - Android 

Kindly assist. Thanks 

### Expected Behavior

Start up image is supposed to come up on the screen when the skin initializes and when set as either a single file or as an image folder in skin settings 

### Steps To Reproduce

Go to skin settings then appearance and select customize start up background image 

### Screenshots and Additional Info

![IMG_2517](https://github.com/jurialmunkey/skin.arctic.fuse/assets/18212540/1394a088-9694-4f5f-b1a7-48e9d3520fa9)

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by supsyman** [comment]
Thanks for your response. I am currently using Open Wizard maintenance tool. I will try other ones and see if they are less aggressive in cache clearing

**Comment by jurialmunkey** [comment]
Yeah, if you are clearing the texture cache before start up, then the image won't be ready to display and Kodi won't have time to update the texture cache while the splash is still active -- you will also see a lot of blank or slow loading images because the background image loader gets backed up with a lot of jobs in its queue because it needs to rebuild the entire cache every time.
