### ISSUE TITLE
add userrating to ratings-line

### ISSUE THREAD

**Issue by Aemstel2** [jurialmunkey/skin.arctic.fuse#536]
### Skin section

Library

### Feature description

Would like to be able to show the userrating on the ratings-line. Preferably as a fifth option.

### Why is this feature needed? Please justify and explain.

Userrating is not shown anywhere now. Except on moviecovers if you turn that on. But that doesn't look very nice and is confusing because if there is no userrating, it shows what I think is the Kodi rating.

### Checklist

- [X] I have made a separate issue for each feature I am requesting.
- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by jurialmunkey** [comment]
The kodi rating is the user rating. If there's a user rating it shows that or otherwise it falls back to the default rating.

**Comment by Aemstel2** [comment]
I see. Thanks for explaining. I personally would rather have it not fallback to this default rating. This makes it confusing to see if I've rated it or not. I think it would be nicer if it didn't show anything if I haven't rated the movie yet, like in AH2. Thanks again. Great skin once again!
