### ISSUE TITLE
:bug: Addons that use the Jet Extractor script show no content

### ISSUE THREAD

**Issue by Priesy** [jurialmunkey/skin.arctic.fuse#541]
### Skin section

Other

### Current Behavior

Addon content appears blank also affects AH2 skin
Addons affected Black Lightning Sport and Torque

### Expected Behavior

Addon content to display as it does in default and other skins

### Steps To Reproduce

1 Install then BL Sport addon
2 Open addon and it shows as empty

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by Priesy** [comment]
The issue is in the addon Display.py needing to be changed from 'movie' to 'movies'. Other skins can accept either but AH2 and Fuse do not for whatever reason.

**Comment by jurialmunkey** [comment]
That's because "movie" is not a valid container content type but "movies" is
https://romanvm.github.io/Kodistubs/_autosummary/xbmcplugin.html#xbmcplugin.setContent
