### ISSUE TITLE
[Bug] Movie/TV Show title logo not appearing on video OSD

### ISSUE THREAD

**Issue by AakashC2020** [jurialmunkey/skin.arctic.fuse#542]
### Skin section

Video OSD

### Current Behavior

Hi @jurialmunkey,

Hope you are doing well.

I'm on the latest update of Arctic Fuse and using Kodi Omega RC 1. I've noticed that the Movie/TV Show title logo is no longer appearing on the video OSD while playing it. Could you please check and kindly fix the issue?

### Expected Behavior

The Movie/TV Show title logo should appear on the video OSD while playing it.

### Steps To Reproduce

Play any Movie/TV Show and pull up the video OSD.

### Screenshots and Additional Info

![1000046538](https://github.com/jurialmunkey/skin.arctic.fuse/assets/65297828/b5d98abb-cfdc-4dfb-963a-a1ddf909b7c3)

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
That is the correct behaviour. There is an option to toggle whether the title is displayed with the seekbar
Skin Settings > Behaviour > Seekbar displays title details while seeking

All I did was fix it so that setting was also working correctly when videoosd controls are open.

**Comment by AakashC2020** [comment]
> That is the correct behaviour. There is an option to toggle whether the title is displayed with the seekbar Skin Settings > Behaviour > Seekbar displays title details while seeking
> 
> All I did was fix it so that setting was also working correctly when videoosd controls are open.

Hi @jurialmunkey,

Thank you for your prompt response! Actually, I didn't notice this new setting. I guess it was added a couple of updates back. Nevertheless, it's working perfectly fine now like earlier. Thanks again!
