### ISSUE TITLE
Hide Side Menu

### ISSUE THREAD

**Issue by Tropo00** [jurialmunkey/skin.arctic.fuse#548]
### Skin section

Other

### Feature description

To remove or hide the side menu & the shadow on the left side.

### Why is this feature needed? Please justify and explain.

takes up an unnecessary amount of space i feel.

### Screenshots and Additional Info

![20240309_135447](https://github.com/jurialmunkey/skin.arctic.fuse/assets/152965233/02f397be-323d-41c6-8b3b-c22ab7d83a62)

### Checklist

- [X] I have made a separate issue for each feature I am requesting.
- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by jurialmunkey** [comment]
Sorry, removing the margin would require redesigning the entire skin as it changes the dimensions.

If you enable touch mode to remove the screen edge peek for widgets, then the side edge shadow will be removed.
Skin Settings > Viewtypes > Touch Mode
