### ISSUE TITLE
[Feature] Larger cast photos in movie info page

### ISSUE THREAD

**Issue by 92SJ** [jurialmunkey/skin.arctic.fuse#55]
### Skin section

Home Widgets

### Feature description

Larger cast photos in movie info page. The photos of cast are very small would it be possible to add a poster or make the photos larger. Ino this will probably mess with the hole theme but just thought I'd put it out there

### Why is this feature needed? Please justify and explain.

Just for visual purposes 

### Checklist

- [X] I have made a separate issue for each feature I am requesting.
- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by jurialmunkey** [comment]
Yeah, using a poster row would break the functionality where you can press right to view more details about the person. 

But I do agree it is a bit difficult to see the image -- which is a bit of a problem l when trying to find out who plays a character but you're not quite sure what the character's name is. I'll have to think about how to solve this.

**Comment by 666jones** [comment]
> Yeah, using a poster row would break the functionality where you can press right to view more details about the person.
> 
> But I do agree it is a bit difficult to see the image -- which is a bit of a problem l when trying to find out who plays a character but you're not quite sure what the character's name is. I'll have to think about how to solve this.

I thought it would be abit of a problem to keep it all working as is. Not many ways I can think of to overcome it. The cast timeline info seems very unique never seen anything like that before very nice feature I must say :)

**Comment by jurialmunkey** [comment]
Next update will have an option to use Local Cast details (i.e. supplied by library or addon rather than TMDbHelper). Enabling this option will also switch to using larger cast images. Pressing down from cast will open Credits, pressing up from cast will give option to view Wiki or Credits. Clicking cast will perform default Kodi action (in library it finds other movies/shows the cast member stars in via a dialog).

`Skin Settings > Details > Use local cast details`

**Comment by 92SJ** [comment]
Lovely stuff jurial I'll load up Kodi and have a play about at some point today. Thanks for your implementations 🔥 🤗
