### ISSUE TITLE
:bug: Rebuilding Shortcuts after a editing widgets happening twice

### ISSUE THREAD

**Issue by Dml2023** [jurialmunkey/skin.arctic.fuse#556]
### Skin section

Widgets

### Current Behavior

After I make a change to any part of my widgets or categories setup and then back out, after I select yes to rebuild, I can see the skin variables notification for rebuilding and once that completes I see the Widget initialisation splash screen (which I have enabled). While this is displayed the skin variables notification appears again, then the home screen displays while the notification is still on screen. After the notification disappears the widget notification splash screen appears again for a few more seconds and then I am returned to the home screen.

### Expected Behavior

I am guessing that the skin variables rebuilds should only happen the one time, and maybe this is something on the skin variables side that may be causing this to happen.

### Steps To Reproduce

Edit any part of your widget config.
Exit out of the widget/shortcuts customisation.
Select yes to rebuild.

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by L0bsang** [comment]
> I've recently noticed this happening as well! But only very recently.

Can confirm.

**Comment by jurialmunkey** [comment]
Yeah fairly sure I know the reason it started happening. 

In the automatic rebuild from home screen I added a check to see if minimise menu had changed to forced a rebuild but forgot to add it into the rebuild command  in the dialog - so the hash to check never matches after a rebuild from dialog and it gets forced again. If it's that should be an easy fix

**Comment by rowel07** [comment]
This also happens to me after updating or editing something when I click on different add-ons shortcut like Fen Light and The Loop.
