### ISSUE TITLE
Upscaled resolution logo

### ISSUE THREAD

**Issue by Bindou01** [jurialmunkey/skin.arctic.fuse#557]
### Skin section

Other

### Feature description

On large 4k screens, I find that some logos appear slightly blurry. I upscaled the HDR 10 logo and DTS-HD a little. We can see that this is closer to the definition of the other logos.

 If you're interested I can do it for all the "blurry" logos. -> https://mega.nz/folder/1XtUkIID#U7kRdrwgylZ48a3Mhn1QNw
[](https://mega.nz/folder/1XtUkIID#U7kRdrwgylZ48a3Mhn1QNw
)
Thanks

### Why is this feature needed? Please justify and explain.

So that all elements of the interface have the same scaling, and provide an overall feeling of a 4K interface.

### Screenshots and Additional Info

![V1](https://github.com/jurialmunkey/skin.arctic.fuse/assets/39261054/7d8eba13-675e-4929-ae2c-a103171e2223)
![311515053-02703e98-5919-45e2-bb1a-6f36253469aa copie 2](https://github.com/jurialmunkey/skin.arctic.fuse/assets/39261054/93e8e5b4-b644-49c1-8238-982b6026653b)

### Checklist

- [X] I have made a separate issue for each feature I am requesting.
- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by jurialmunkey** [comment]
While these look great at 4K, the bigger problem is that Kodi also does a bad job at *downscaling* images too. Which means this would end up creating the inverse problem for 1920x1080 screens.

For example see how bad these logos from https://kodi.wiki/view/Official:Media_center_logos look when they are downscaled inside Kodi:

![image](https://github.com/jurialmunkey/skin.arctic.fuse/assets/4618719/5a11d494-2918-4488-8c34-67766f7f51f9)

![image](https://github.com/jurialmunkey/skin.arctic.fuse/assets/4618719/17260a20-eb8c-4a53-b4bb-dfc263e81996)

There's no really good solution other than waiting until there is proper SVG support added. Once we have SVG support, work can be done on converting the logos to SVG so they can be scaled to any size.

**Comment by Bindou01** [comment]
> Bien que ceux-ci soient superbes en 4K, le plus gros problème est que Kodi fait également un mauvais travail en matière _de réduction d'échelle_ des images. Ce qui signifie que cela finirait par créer le problème inverse pour les écrans 1920x1080.
> 
> Par exemple, voyez à quel point ces logos de https://kodi.wiki/view/Official:Media_center_logos sont mauvais lorsqu'ils sont réduits dans Kodi :
> 
> ![image](https://private-user-images.githubusercontent.com/4618719/319043534-5a11d494-2918-4488-8c34-67766f7f51f9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIxMzI5OTgsIm5iZiI6MTcxMjEzMjY5OCwicGF0aCI6Ii80NjE4NzE5LzMxOTA0MzUzNC01YTExZDQ5NC0yOTE4LTQ0ODgtOGMzNC02Nzc2NmY3ZjUxZjkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQwMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MDNUMDgyNDU4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Yzc2N2I3M2RmOWQxNTkzODQ3MTMwYzRkODJmN2U0NWZkNjhlODYzMjQyY2VkZGQ4YThiMmQyZjViOTNmNzBiZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.cZy7x8VhpnLvbJax557nSN8C2O9SsNSWSHSzYUCBXmY)
> 
> ![image](https://private-user-images.githubusercontent.com/4618719/319044001-17260a20-eb8c-4a53-b4bb-dfc263e81996.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIxMzI5OTgsIm5iZiI6MTcxMjEzMjY5OCwicGF0aCI6Ii80NjE4NzE5LzMxOTA0NDAwMS0xNzI2MGEyMC1lYjhjLTRhNTMtYjRiYi1kZmMyNjNlODE5OTYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQwMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MDNUMDgyNDU4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MWJiZWJlOWYzMWMzY2IzNDU2OGI3NDIwZDg1ZWQ1YzFkMTQ2NjA1OGRlYmFlODUzYmIwMTQ1OTBjMjQzMTFiMSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Cfkx73bvGTFwOzbh3kpJzsiK8efCZMTWet4VO4H3LIE)
> 
> Il n'y a pas de très bonne solution autre que d'attendre que le support SVG approprié soit ajouté. Une fois que nous aurons pris en charge SVG, nous pourrons travailler sur la conversion des logos en SVG afin qu'ils puissent être mis à l'échelle à n'importe quelle taille.

Thank you for these details Jurial.  Do you know if SVG compatibility is already planned by the developers?  (as the creator of Clear Logo, this might also interest me)
