### ISSUE TITLE
highlighting menu button changes movie info

### ISSUE THREAD

**Issue by Aemstel2** [jurialmunkey/skin.arctic.fuse#560]
### Skin section

Widgets

### Current Behavior

When highlighting the menu button the movie info in the info-line changes to incorrect data. I think it's tmdb data instead of the library data.

Look at the info-line in the screenshots:

Screenshot 1 is when the movie in recent movies widget is highlighted: this is the correct data.
Screenshot 2 is when highlighting the menu button: this data is incorrect.

### Expected Behavior

Don't change the data when moving on the menu button.

### Steps To Reproduce

1. In Home screen highlight a movie in a widget and look at the info-line.
2. Move to the menu-button and see that the info is changed.

### Screenshots and Additional Info

![shot1](https://github.com/jurialmunkey/skin.arctic.fuse/assets/109811164/a6107661-bd02-40b6-b79a-1a7638d6a8ef)
![shot2](https://github.com/jurialmunkey/skin.arctic.fuse/assets/109811164/f15fb099-74b7-4db1-8abe-eb0bd1b8d309)

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
There's not much I can do about this unfortunately.

Kodi only gives data for the focused widget. Since no widget is focused it gives no data so I have to rely on what I can get via TMDbhelper. It is same reason user rating doesn't work for spotlight.

**Comment by jurialmunkey** [comment]
^^^ This change for next version of TMDbHelper should largely solve this issue.

Will need to enable option in TMDbHelper settings to get additional details from Kodi library DB and then restart Kodi, but after that it should make TMDbHelper preference library details first in its service lookups -- so in a roundabout way it will fix the problem in the skin by making the library and TMDbHelper value match.

**Comment by matke-84** [comment]
@jurialmunkey
This led to a certain delay in the display of informations, ratings... It seems that it doesn't remember anything in the cache, but every time you return the focus to the previous movie, it takes about two seconds to display the information again. This is especially noticeable if some content is not in the local library.

**Comment by jurialmunkey** [comment]
@matke-84 the option is optional.

If there is an issue with Tmdbhelper, then report it on the tmdbhelper github.
