### ISSUE TITLE
:bug: User-rating is not shown in Spotlight

### ISSUE THREAD

**Issue by Aemstel2** [jurialmunkey/skin.arctic.fuse#562]
### Skin section

Other

### Current Behavior

Spotlight on homescreen does not show user-rating. It shows correctly everywhere else.

### Expected Behavior

Show the user-rating in spotlight if that is selected in the settings.

### Steps To Reproduce

1. Set ratings to show user-rating
2. Check homescreen spotlight: it doesn't show the user-rating.

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
TMDbHelper can now pull in UserRating from library if its setting to retrieve details from Kodi DB is enabled -- the above commit will add support to use it in the skin as a fallback, which should also fix the spotlight issue since the skin will be able to grab the user rating from TMDbHelper.
