### ISSUE TITLE
Simplify Line of Sight uniquely for Widgets

### ISSUE THREAD

**Issue by Bindou01** [jurialmunkey/skin.arctic.fuse#563]
### Skin section

Widgets

### Feature description

Hi, unless I'm mistaken, it is not possible to modify the order of films on the fly in a Widgets. So, I wonder about the relevance of the presence of the “ascending/decreasing” logo.

On the other hand, for the full screen view, all the information from the "Line of Sight" is necessary because it makes the use of the filter more ergonomic.

**Before** 

![311550327-43121238-8b8c-40b3-905f-d2e41c741c80](https://github.com/jurialmunkey/skin.arctic.fuse/assets/39261054/777f32e1-0f57-480f-883d-718b2a3b8a6b)

**After** 

![311519154-7c2e6a38-fd5d-478f-b9c9-4f7cd7780bda copie](https://github.com/jurialmunkey/skin.arctic.fuse/assets/39261054/fb70971a-56b5-4b01-ba8f-5e0d7ad37d74)

### Why is this feature needed? Please justify and explain.

Being able to remove it from the Widgets interface would simplify the reading of information on the main screen, without sacrificing the indicator of the number of films in the Widget.

### Checklist

- [X] I have made a separate issue for each feature I am requesting.
- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by Bindou01** [comment]
@jurialmunkey 
If you think this is not a good idea, you can close this request, as this is not a request I care much about, as it is a technicality.

**Comment by jurialmunkey** [comment]
I do not have infinite time. Just because I don't action something immediately does not mean I am not considering it.

**Comment by Bindou01** [comment]
If I say that, it's because I don't know if it's a good idea, and it's precisely to lighten your list that I suggested deleting this proposal. I know you have a lot of work.

**Comment by Bindou01** [comment]
The request was fulfilled.
Thank you very much @jurialmunkey !
