### ISSUE TITLE
Navigation- Back- Previous

### ISSUE THREAD

**Issue by adamosborne83** [jurialmunkey/skin.arctic.fuse#567]
### Skin section

Widgets

### Current Behavior

Sorry, this might be a cannot keep everyone happy scenario.

I can now longer exit out of folders.

### Expected Behavior

So,
Back - Previous, does not allow to exit out of folders.

Back - Parent, on combined and then press back goes to Menu on home page

Back - Menu, as it says on the tin

### Steps To Reproduce

Just does not feel intuitive anymore.
Apologies 

### Screenshots and Additional Info

https://github.com/jurialmunkey/skin.arctic.fuse/assets/78307374/2df73f31-cf05-40c5-b0f0-d486d38c252b

https://github.com/jurialmunkey/skin.arctic.fuse/assets/78307374/f70b6905-2167-4307-8853-c5664b9a595b

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
I definitely messed something up there. Forgot to test with the list when making some changes to the behaviour. Should be able to fix.

**Comment by jurialmunkey** [comment]
Yep dumb mistake. Just forgot to flip the condition to match the changes elsewhere.
