### ISSUE TITLE
Codec logo UI issue

### ISSUE THREAD

**Issue by JFG1000** [jurialmunkey/skin.arctic.fuse#569]
### Skin section

Video OSD

### Current Behavior

Hi I've noticed tonight that when highlighting the codecs on the video OSD the logos do not fit on the screen they cut off, is this something that can be adjusted atall if possible? 

### Expected Behavior

Highlight the codecs on video OSD during playback 

### Steps To Reproduce

During playback bring up osd
Navigate to codecs

### Screenshots and Additional Info

![20240311_201847](https://github.com/jurialmunkey/skin.arctic.fuse/assets/76907836/176b5cf0-1cb9-499e-91d8-2fa62f0aef15)

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
Ah I forgot to hide the atmos flag. Only meant to show the five basic details there (resolution aspect+codec fps channels audiocodec) and then show the full when clicking.

Should be able to fix
