### ISSUE TITLE
:bug: unable to scroll the home page widget

### ISSUE THREAD

**Issue by SJ1O** [jurialmunkey/skin.arctic.fuse#570]
### Skin section

Widgets

### Current Behavior

Hey Jurial, just done the most recent update and having some issues. I'm unable to click on the home page widgets it just stays focused on home menu no matter what I do. I tried with the minimised side menu option and had the same issue with the home page.

### Expected Behavior

Ability to scroll on the widget yo select a item.

### Steps To Reproduce

My home page only has 1 widget and is classic mode.

### Screenshots and Additional Info

https://github.com/jurialmunkey/skin.arctic.fuse/assets/121204283/fc358775-a41e-4e82-82c8-3a63d2500ad8

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by SJ1O** [comment]
I just noticed this may have already been reported however this has definitely only started happening after today's update (5.07) for myself. I did try enabling Content - Move between widget groups but this didn't solve the issue.

I'm using omega Kodi RC1 version if that helps.

I have restarted Kodi and my cube but issue still persists.

I'll leave this open for you but feel free to close if it's the same issue thats already been reported.

**Comment by jurialmunkey** [comment]
Yeah this is same issue as #550 

I know that it happens and know the basic reason why it happens but haven't figured out exactly what combination of events causes it.

**Comment by SJ1O** [comment]
I noticed it no longer focuses on the widgets or categories when opening a hub could this be the cause? I cannot get it to scroll at all on the home page using v5.07. also I noticed after v5.01 is when it stopped focusing on the first widget or category.

**Comment by jurialmunkey** [comment]
> I noticed it no longer focuses on the widgets or categories when opening a hub could this be the cause?

In a roundabout way yes this is the cause but not the reason (if that makes sense!)

I removed the forced focus which is why it has started happening but it shouldn't be necessary to force the focus with the current code.
