### ISSUE TITLE
:bug: played count in footer issue

### ISSUE THREAD

**Issue by SJ1O** [jurialmunkey/skin.arctic.fuse#572]
### Skin section

Widgets

### Current Behavior

The played count in the footer just shows (more unavailable) I have included a photo.

### Expected Behavior

Play count to be shown.

### Steps To Reproduce

1.View the last widget from within a hub.

### Screenshots and Additional Info

![20240311_210353](https://github.com/jurialmunkey/skin.arctic.fuse/assets/121204283/75dc70d0-78ee-4cd1-a7fa-e5d6946809b1)

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
If you want widgets to show the footer there is an option under furniture.

**Comment by vella9** [comment]
Hi @jurialmunkey , first of all thank you for your work. I noticed that with the Widgets (disables next widget peek) disabled, and play counts and dates enabled, play count in footer is still not shown. 

Also, if you enable Widgets (disables next widget peek), play counts and dates are shown however during transition from one widget to another, it feels like the footer is fixed and not obeying the transition effect. I am on version 0.5.08

**Comment by jurialmunkey** [comment]
That's all correct. Footer is meant to have a fixed position just like the header. Having it move with the widgets was bad behaviour. 

The widgets options determines if footer is enabled or not for Windows with widgets. The footer appears in a fixed location (the footer).

**Comment by SJ1O** [comment]
> If you want widgets to show the footer there is an option under furniture.

Hey Jurial, Is it possible to have the play count show without disabling next widget peak? As I can only seem to get the play count to show when I disable next widget peak.

Cheers
Sam

**Comment by jurialmunkey** [comment]
@SJ1O I don't understand what you mean? If both are enabled at the same time then they will overlap and be difficult to read. 

If you just want it on the last item, no, not going back to that. That was a huge mistake for me to add in originally I terms of consistency for the skin. 

Either all widgets have footers or none do so that the footer will be in consistent location and not sliding around all over the place.

**Comment by SJ1O** [comment]
Yh I was referring to it on the last item. No worries I understand what your saying and imagine there is a good reason for the change. Thanks for taking the time to explain.

Cheers
Sam
