### ISSUE TITLE
Lost all menus on newest update 

### ISSUE THREAD

**Issue by JFG1000** [jurialmunkey/skin.arctic.fuse#573]
### Skin section

Widgets

### Current Behavior

Just updated to newest version, i had seperate sections on the left, movies etc now I'm left with just a menu tab that brings up the Power menu, is there a fix for this 

### Expected Behavior

Usually have other menus I can navigate to

### Steps To Reproduce

Navigate on homescreen 

### Screenshots and Additional Info

![Uploading 20240311_222852.jpg…]()

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
Skim settings - menus - side menu minimise change to library.

**Comment by JFG1000** [comment]
Thankyou such a relief i thought I'd have do re make everything 😂

**Comment by jurialmunkey** [comment]
> Thankyou such a relief i thought I'd have do re make everything 😂

Yeah definitely nothing deleted!

Just simplifying and standardising some of the navigation and side menu settings to try to reduce some of the buggy or weird navigation -- so there might be a couple of things where you need to go back into the settings and re-enable something.

Definitely won't be touching anyone's actual shortcuts/widgets config files though!
