### ISSUE TITLE
Hub names from the creation window

### ISSUE THREAD

**Issue by Bindou01** [jurialmunkey/skin.arctic.fuse#575]
### Skin section

Other

### Feature description

Hello Jurial,
In the manufacturing area, at the top, next to its real name, in parentheses, it would be interesting to see the personalized name of the Hub (Movie Hub, Serie Hub, Kids Hub, etc.). 

### Why is this feature needed? Please justify and explain.

Because as it stands, you can get lost and choose the wrong Hub during construction. It would be nice to have the name synced to the custom name.

Thank you again for everything you do for us.

### Screenshots and Additional Info

![Capture d'écran 2024-03-12 095912](https://github.com/jurialmunkey/skin.arctic.fuse/assets/39261054/f2eedc4a-c548-4e2f-bef4-0bcbdfb10d53)

### Checklist

- [X] I have made a separate issue for each feature I am requesting.
- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by jurialmunkey** [comment]
This is not possible because the name of the hub changes depending on the name of the shortcut you click to open the hub. They do not have set names.
