### ISSUE TITLE
widgets disappear when home isn't highlighted

### ISSUE THREAD

**Issue by Liquidrag** [jurialmunkey/skin.arctic.fuse#578]
### Skin section

Widgets

### Current Behavior

widgets don't show unless home is in focus

### Expected Behavior

home widgets show all the time

### Steps To Reproduce

1. Run Kodi 
2. Let widgets load
3. move off home hub icon
4. widgets disappear

### Screenshots and Additional Info

https://github.com/jurialmunkey/skin.arctic.fuse/assets/43726430/2329e121-f91f-4982-ad2a-0987449c9489

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
Check the "link visibility" settings for your categories. If linked to the home guid rather than all then will only show for home.

**Comment by Liquidrag** [comment]
Where can I find this? The only "categories" I can find is here in menus.
<img width="1232" alt="Screen Shot 2024-03-12 at 5 40 12 PM" src="https://github.com/jurialmunkey/skin.arctic.fuse/assets/43726430/0fd06186-57fe-4065-8ed0-5ce17a1601b4">

**Comment by ambulancePilot** [comment]
Click customize widgets (top of your screenshot) and then look for link visibility.

**Comment by Liquidrag** [comment]
> Click customize widgets (top of your screenshot) and then look for link visibility.

I still don't see it, can you give a screenshot?

**Comment by jurialmunkey** [comment]
![screenshot00459](https://github.com/jurialmunkey/skin.arctic.fuse/assets/4618719/1c9ecc4e-b2ff-4dae-a83b-d9ba981b0d07)

**Comment by Liquidrag** [comment]
I must've done something wrong because  those options aren't there 
<img width="1235" alt="Screen Shot 2024-03-13 at 12 22 03 PM" src="https://github.com/jurialmunkey/skin.arctic.fuse/assets/43726430/911e208f-d46f-476f-8fdf-fc0d6bfd1358">

https://github.com/jurialmunkey/skin.arctic.fuse/assets/43726430/6fb7a257-76b0-48a8-9c67-eccfc0df6acb

<img width="1233" alt="Screen Shot 2024-03-13 at 12 23 10 PM" src="https://github.com/jurialmunkey/skin.arctic.fuse/assets/43726430/3533b53f-7fe9-4920-96c4-f5104b290968">

**Comment by L0bsang** [comment]
@Liquidrag 
Click on the category text. Where it says "On Deck" in your home menu and "Add Item" on your other menu items. 

It is the visibility of the category you want to change, you are looking at the properties of the menu item instead.

**Comment by Liquidrag** [comment]
> @Liquidrag Click on the category text. Where it says "On Deck" in your home menu and "Add Item" on your other menu items.
> 
> It is the visibility of the category you want to change, you are looking at the properties of the menu item instead. Note how jurial's screenshot says "Home Hub Categories" while your screenshot and video say "Side Menu Icons" under Shortcuts.

It's linked on my Home's On Deck but my other sections there's no option
<img width="1231" alt="Screen Shot 2024-03-13 at 5 21 13 PM" src="https://github.com/jurialmunkey/skin.arctic.fuse/assets/43726430/db20bd42-e5d5-49de-a74a-e488d0a4102c">

https://github.com/jurialmunkey/skin.arctic.fuse/assets/43726430/2e24ba2f-0676-49a5-a39d-f683bc8a2384

**Comment by Liquidrag** [comment]
Forget what I said, The "home" widgets are showing as they're supposed to now.

**Comment by jurialmunkey** [comment]
Yeah only categories in home window can be linked to the sidemenu as it is the only window with a sidemenu.

 categories for other hub windows are always visible since hub windows don't have side menus.
