### ISSUE TITLE
:sparkles: Search History

### ISSUE THREAD

**Issue by onlytanmoy** [jurialmunkey/skin.arctic.fuse#579]
### Skin section

Widgets

### Feature description

Please retain search history - may be show them at the bottom or a separate mode like previous searches, whichever you find easier to implement.
https://streamable.com/8ra1sp
Also is it possible to auto-complete the search as I type as in show me possible matches at the bottom from where I can choose? 

### Why is this feature needed? Please justify and explain.

When I am coming back I can simply select from one of my earlier searches without having to type the string all over again.

### Checklist

- [X] I have made a separate issue for each feature I am requesting.
- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by jurialmunkey** [comment]
Yeah I'm planning on bring the history and autocomplete back, just rethinking how it works a bit with the recent changes.
