### ISSUE TITLE
:bug: Unable to add "Your Recently Watched" and ''Your Most Watched" movie widgets

### ISSUE THREAD

**Issue by dm1tz** [jurialmunkey/skin.arctic.fuse#581]
### Skin section

Widgets

### Current Behavior

Trying to add "Your Recently Watched" or ''Your Most Watched" widget in a widget customisation screen results in a skinvariables dialog "Building directory..." that closes after ~5 seconds and does not proceed to the next "Add folder" dialog.

### Expected Behavior

Be able to add "Your Recently Watched" and ''Your Most Watched" widgets.

### Steps To Reproduce

1. Go to `Skin Settings > Menus > Customise widgets`
2. Proceed to `Side Menu Icons > Movies > Widgets` screen
3. Click on "New" in the left sidemenu
4. Navigate to `TMDbHelper Movies`
5. Select "Your Recently Watched" or "Your Most Watched" entry

### Screenshots and Additional Info

Strangely, the bug only happens on my CoreELEC (Nexus v20.5) TV box. I can't reproduce this on my PC (Nexus v20.2 linux). Also, I believe that Trakt sync is not to blame here since it updates the other widgets flawlessly, plus 
"Your Recently Watched" widget for TV series works fine.

So far I've tried: 
1. Cleaning TMDbHelper cache
2. Reactivating Trakt account in TMDbHelper
3. Re-installing skinvariables
4. Manually adding "Your Recently Watched" entry to `skinvariables-shortcut-sidemenu.json` 

Apologies if this should go to the TMDbHelper or Skinvariables repo and thanks in advance.

[kodi.log](https://pastebin.com/PKSpyBYN)
[skinvariables-shortcut-sidemenu.json](https://pastebin.com/vqPLPZFk)
[TMDbHelper settings.xml](https://pastebin.com/Tkj544bM)

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
This is really strange. I'm not quite sure what the cause might be. I can't see any errors in the log really.

Maybe an obvious question but have you tried going into TMDbHelper itself and opening these lists to make sure they work there first? Would help narrow down if it is TMDbHelper or SkinVariables with the issue.

**Comment by dm1tz** [comment]
Something's definitely not right. On top of that I frequently get
`2024-03-13 23:15:49.492 T:23134   error <general>: GetDirectory - Error getting plugin://plugin.video.themoviedb.helper/?info=trakt_becauseyouwatched&tmdb_type=movie&widget=true&reload=1710344077&reload=1710344077`
So "Because You Watched" widget is not being displayed, albeit it is defined and stored in `skinvariables-shortcut-sidemenu.json`

**Comment by dm1tz** [comment]
Hi, @jurialmunkey. Don't wanna be a nuisance, but just a quick heads up. The issue still persists on Omega but maybe this would help trace the bug: 
I tried replacing an actual widget's path with:
``` 
"path": "plugin://plugin.video.themoviedb.helper/?info=trakt_history&tmdb_type=movie&widget=true&reload=$INFO[Window(Home).Property(TMDbHelper.Widgets.Reload)]&reload=$INFO[Window(Home).Property(TMDbHelper.Widgets.Reload)]",
``` 

Like so: 
```
{
    "label": "IMDb: Top Rated TV Shows",
    "path": "plugin://plugin.video.themoviedb.helper/?info=trakt_history&tmdb_type=movie&widget=true&reload=$INFO[Window(Home).Property(TMDbHelper.Widgets.Reload)]&reload=$INFO[Window(Home).Property(TMDbHelper.Widgets.Reload)]",
    "icon": "special://skin/extras/icons/shapes.png",
    "target": "videos",
    "guid": "guid-129dbb90"
}
```
Doing so ensures that the widget is actually staying in the list. So here's the log with the modified widget included in menu's widgets list:  [kodi.log](https://github.com/jurialmunkey/skin.arctic.fuse/files/14947751/kodi.log). On the UI side TMDbHelper tries to load the entry, but eventually leaves the widget's screen blank:
![screenshot00004](https://github.com/jurialmunkey/skin.arctic.fuse/assets/82608185/4f38a1ef-a68d-4f5c-ae27-47b6530762f9)

**Comment by dm1tz** [comment]
Resolved by hard resetting CoreELEC.

**Comment by jurialmunkey** [comment]
Since you can add it but then it loads no items, it is almost a tmdbhelper related issue rather than anything to do with the skin or skin variables. 

Thought I just had... You don't have "hide watched" for widgets enabled in tmdbhelper settings by any chance? 

Because, well, in that case it is functioning as expected by hiding all your watched items...

**Comment by dm1tz** [comment]
> Thought I just had... You don't have "hide watched" for widgets enabled in tmdbhelper settings by any chance?
Ohh I feel so dumb right now. Yup, that was the case, thanks a bunch for helping me out and thank you for your hard work.
