### ISSUE TITLE
add "refresh" option

### ISSUE THREAD

**Issue by Aemstel2** [jurialmunkey/skin.arctic.fuse#582]
### Skin section

Library

### Feature description

Not sure to label this as a feature request or a bug. But the "refresh" option for a single movie is gone/ missing. Maybe this could be added to the context menu?

### Why is this feature needed? Please justify and explain.

When changing something about a single movie, it is nice to have a "refresh" option. Without it, the movie has to be removed from the library and a complete library scan is necessary.

### Checklist

- [X] I have made a separate issue for each feature I am requesting.
- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by jurialmunkey** [comment]
![screenshot00460](https://github.com/jurialmunkey/skin.arctic.fuse/assets/4618719/8f0b1985-aa1b-4e2e-b761-3d191b0b481b)

**Comment by Aemstel2** [comment]
Oh haha, don't blame me for not finding that :) Thanks again.

**Comment by jurialmunkey** [comment]
Yeah it is definitely a bit hidden away but I kinda like it for that reason since it is a management option -- prevents guests from accidentally messing with things!
