### ISSUE TITLE
Full Screen Spotlight

### ISSUE THREAD

**Issue by adamosborne83** [jurialmunkey/skin.arctic.fuse#589]
### Skin section

Widgets

### Feature description

I've just watched a video, where spotlight is full screen.
Is this something that only works with top bar or a setting I've missed?

Sorry, I know your Git has blown up recently, so do feel bad even asking. 

### Why is this feature needed? Please justify and explain.

Love full screen

### Screenshots and Additional Info

![20240315_123554](https://github.com/jurialmunkey/skin.arctic.fuse/assets/78307374/094a7286-9029-4a09-91a6-1457d9dbf8d6)

### Checklist

- [X] I have made a separate issue for each feature I am requesting.
- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by Rinicko** [comment]
It only works when Top bar is enabled and the spotlight appearance is set to fanart

**Comment by xyzfre** [comment]
> It only works when Top bar is enabled and the spotlight appearance is set to fanart

Thank you for sharing this info ,just tried it out. Looks pretty GOOD. AF only gets better and better loving the skin Thank you @jurialmunkey amazing work💯
