### ISSUE TITLE
🌟 Toggle to switch off plot in widgets

### ISSUE THREAD

**Issue by Rinicko** [jurialmunkey/skin.arctic.fuse#592]
### Skin section

Widgets

### Feature description

I have a button in my shutdown menu linked to Window 1113 which shows the plot whenever I need to read it, I could also check the informations tab for the plot, could it be possible to have a toggle in the details section to switch off and on the plot on widgets like with infoline, ratings e.t.c.

### Why is this feature needed? Please justify and explain.

This will speed up the skin significantly as it will not have to load up each plot as you scroll through widgets. It will add to the minimalist feel of the skin. The plot could also be on by default for users who need it

### Checklist

- [X] I have made a separate issue for each feature I am requesting.
- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by jurialmunkey** [comment]
This will not affect loading speed at all. 

Kodi does not load information the way you think it does. Item metadata is loaded regardless of use and before items are displayed. More importantly it is plain text so there is no real performance saving to be had. 

Removing the info box would require significant skin redesigns in terms of window transitions and how the widgets function and is not planned at this time.
