### ISSUE TITLE
:bug: Seekbar instantly closing after seeking

### ISSUE THREAD

**Issue by qezzo** [jurialmunkey/skin.arctic.fuse#593]
### Skin section

Video OSD

### Current Behavior

the seekbar instantly closes after seeking, it is just a flicker.
I played around with the playback OSD settings but the seekbar options seem to only affect what is displayed and the OSD timeout affects only the menu with controls and info.

### Expected Behavior

the seek bar osd should be visible for at least 1 or 2 seconds after seeking. Ideally the timeout should be configurable by the user.

### Steps To Reproduce

play video and press the seek button.
I have only one skip step enabled and disabed the delay in video playback settings.

### Screenshots and Additional Info

I think `Player.DisplayAfterSeek` should be replaced with `Player.HasPerformedSeek(2)` (or some other value) in

https://github.com/jurialmunkey/skin.arctic.fuse/blob/596f73b9dea90962cb0266e82c7d07453eed3a11/1080i/DialogSeekBar.xml#L7

as it was changed in Kodi 20 (https://forum.kodi.tv/showthread.php?tid=363553 and https://github.com/xbmc/xbmc/pull/21425)

I tested it on my pc and it seems to work as expected. But I didn't check if it interferes with other stuff.

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
For some reason I had it in my head that new HasPerformedSeek was only available in Omega. Thanks for pointing that out as literally only reason I didn't add it before was because I thought it would break on Nexus - I should've double checked!
