### ISSUE TITLE
:bug: Blank Options Dialog from Power/Options Menu

### ISSUE THREAD

**Issue by berkhornet** [jurialmunkey/skin.arctic.fuse#594]
### Skin section

Widgets

### Current Behavior

When selecting "Configure Hubs and Menus" from the Options/Power Menu a blank "Options" Dialog is displayed

### Expected Behavior

the correct configuration window/dialog should open

### Steps To Reproduce

Bring up Power Menu
Select "Configure Hubs and Menus"

### Screenshots and Additional Info

![screenshot00002](https://github.com/jurialmunkey/skin.arctic.fuse/assets/67786207/01e0aced-f5d8-457e-adad-2a1362ff0865)

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
This shortcut was removed as it was a real pain to manage the settings working properly from the dialog.
The exact same settings are available in Skin Settings > Menu

**Comment by berkhornet** [comment]
Thanks. All working from Skin Settings

**Comment by Goldenfreddy0703** [comment]
Waiiitttt is that why im missing the power button? 😂

I've been trying to figure out where in the world the power button is and i thought i was going insane so i asked people in discord about it. 

In the image, this is where the power button use to be. 
![image](https://github.com/jurialmunkey/skin.arctic.fuse/assets/62456796/fdc0ff03-5ddf-4c17-9cf4-eeb8759bddd5)

In this image, i thought i was missing a power button when holding the back button.
![image](https://github.com/jurialmunkey/skin.arctic.fuse/assets/62456796/acb08f66-f4a9-45aa-92c9-cf95baa0f632)

**Comment by jurialmunkey** [comment]
@Goldenfreddy0703 no this is a different matter. The side menu on options has been removed.

The default for quit now displays in the list below the settings button. However, if you have an existing setup you would need to read this button yourself or reset it to defaults in the config as I don't want to reset anyone's config forcibly.

**Comment by Goldenfreddy0703** [comment]
> The default for quit now displays in the list below the settings button. However, if you have an existing setup you would need to readd this button yourself or reset it to defaults in the config as I don't want to reset anyone's config forcibly.

Ahh i see now, ok thank you, will re add the button then, thank you very much
