### ISSUE TITLE
:bug: Clock in footer only showing in movie info screen 

### ISSUE THREAD

**Issue by matthamilton13** [jurialmunkey/skin.arctic.fuse#595]
### Skin section

Library

### Current Behavior

My furniture settings are set to show clock and now playing in the right footer. The clock only shows in movie/series/episode information screens. It is not showing on the main home screens, i.e TV shows, Movies.

### Expected Behavior

The right footer furniture clock is shown on every screen, like a couple of skin versions ago.

### Steps To Reproduce

1. In the furniture settings, set the clock to show in right footer.

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by matthamilton13** [comment]
![PXL_20240316_131159116](https://github.com/jurialmunkey/skin.arctic.fuse/assets/156418611/d0d372ed-dd21-44ed-be94-a8ad8bf14c93)
![PXL_20240316_131147473](https://github.com/jurialmunkey/skin.arctic.fuse/assets/156418611/1e821faf-53fe-46ce-8529-da2dc177dfbd)

**Comment by jurialmunkey** [comment]
Did you enable the setting for the footer to show on widgets?

**Comment by jurialmunkey** [comment]
Skin Settings > Furniture > Widgets

Works fine for me with that enabled.
