### ISSUE TITLE
[BUG] Mouse control is problematic

### ISSUE THREAD

**Issue by test01203** [jurialmunkey/skin.arctic.fuse#60]
### Skin section

Other

### Current Behavior

Full mouse control without glitches

### Expected Behavior

There is no possibility with a mouse to access all the movies as soon as you put the mouse it goes crazy
And the second thing, in the add-on the add-on goes on the side menu
And nothing can be clicked

### Steps To Reproduce

Enter Kodi and activate a mouse

### Screenshots and Additional Info

https://github.com/jurialmunkey/skin.arctic.fuse/assets/104188844/52f4e823-0753-4b0a-a9db-afc2126f4d1c

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
Mouse is currently not supported. It may be eventually but it depends as the options in the Kodi skinning engine are not very good for addressing mouse support
