### ISSUE TITLE
:bug: Video trailer in info not work

### ISSUE THREAD

**Issue by ProArtix** [jurialmunkey/skin.arctic.fuse#601]
### Skin section

Other

### Current Behavior

Not view video background 

### Expected Behavior

Not view video background 

### Steps To Reproduce

Go to info for movie > go to trailers >> play trailer, not show video background 

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
Shin settings - appearance - background video

**Comment by ProArtix** [comment]
![IMG_20240319_081729](https://github.com/jurialmunkey/skin.arctic.fuse/assets/159583868/e5e7ae69-bfa0-46bd-92c8-68d9443e7fb4)

What player trailer? Not view trailer in background

**Comment by jurialmunkey** [comment]
This has nothing to do with the skin. You are using an external player and so it is impossible for the skin to control its appearance.

**Comment by ProArtix** [comment]
I have the kodi recently installed and I have not installed any external player

**Comment by jurialmunkey** [comment]
This works correctly for me with the following settings enabled:

Skin Settings > Appearance > Background Video (enabled)
Skin Settings > Behaviour > Play trailers from information in (background)


If it works correctly for me and I can't reproduce the issue, then you need to give me more information about how to create the problem.

**Comment by ProArtix** [comment]
Now it is visible but when I exit the information the video does not stop, it continues playing in the background
