### ISSUE TITLE
hide widget initialisation behind splash not working

### ISSUE THREAD

**Issue by vella9** [jurialmunkey/skin.arctic.fuse#603]
### Skin section

Widgets

### Current Behavior

even though this setting is enabled, it is not working as shown in the video. I tried toggling and restarting and reloading skin but to no avail.
I am on Kodi version 20.5 and AF version 0.5.15.

### Expected Behavior

Should be able to initialize the widgets during the splash

### Steps To Reproduce

Go to Expert > hide widget initialisation behind splash and make sure this is enabled.
Reload kodi 

### Screenshots and Additional Info

https://github.com/jurialmunkey/skin.arctic.fuse/assets/137268669/0502befd-9a0f-42d7-bf05-33296198226a

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by vella9** [comment]
I am using Classic Mode, and I just noticed that if I change to Complex Mode, the hide widget initialisation behind splash is working. I changed back to Classic Mode and I have the same issue.

**Comment by jurialmunkey** [comment]
It doesn't work for classic. All it does is check if the spotlight has loaded. It isn't possible to check all widgets have loaded

**Comment by vella9** [comment]
thanks for the clarification. Just wanted to ask if spotlight for classic mode is something that you are looking into. Thank you as always!

**Comment by jurialmunkey** [comment]
> thanks for the clarification. Just wanted to ask if spotlight for classic mode is something that you are looking into. Thank you as always!

Yep definitely. If there's an open issue requesting and I haven't closed it then it is something I'm considering. Just a little complicated in terms of implementing it with how classic works, so I want to make sure I'm doing it right to avoid creating a situation where I need to walk it back or try to undo it later after everyone has added it into their setups.
