### ISSUE TITLE
Improve the visual distinction of Hubs

### ISSUE THREAD

**Issue by Bindou01** [jurialmunkey/skin.arctic.fuse#604]
### Skin section

Widgets

### Feature description

In order to better distinguish the Hubs and better determine which one we are in without having to ask questions, I propose 2 ideas that respect the identity of Fuse.

1. Allow you to associate the color of the selector according to the current Hub. Examples:
Miami Vaporwave -> Video Hub
Aqua Classic -> News (TMDB Helper) Hub
Blue Slate -> Kids Hub
Red -> Music Hub

2. Show the current Hub icon at the top, next to the title. Or put the “Current Hub” icon as a “Menu” button to open the side pane.

### Why is this feature needed? Please justify and explain.

I don't know if these ideas are good, but an idea like this would make the interface more intuitive and we would be better aware of the hub we are in. Maybe others have simpler ideas to implement...

### Screenshots and Additional Info

![1](https://github.com/jurialmunkey/skin.arctic.fuse/assets/39261054/85ca99fc-6368-4643-8aa4-f8cce30e867d)
![Capture d'écran 2024-03-19 163950 copie](https://github.com/jurialmunkey/skin.arctic.fuse/assets/39261054/ba6d34ad-9dbf-475e-b71a-5c2a447b1065)

### Checklist

- [X] I have made a separate issue for each feature I am requesting.
- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by xyzfre** [comment]
In the upper corner left-hand side on my end, it always tells me which hub I'm in

**Comment by Bindou01** [comment]
> In the upper corner left-hand side on my end, it always tells me which hub I'm in
Can you please share a screenshot, because I don't know what you're talking about.

**Comment by jurialmunkey** [comment]
Hubs do not have icons. Just because you use a shortcut that opens the hub does not mean that icon is associated with the hub.

You are using hubs incorrectly. They are meant to be a page between the home page and library. What you are looking for is pseudo profiles. Pseudo profiles will have support for alternative colour choices soon.

**Comment by Bindou01** [comment]
Yes, I noticed that the icons were not associated with hubs but with shortcuts. However I thought it was possible to find a clever way to index them. Not knowing the details of what is under the hood, it is not always easy to know what is possible or not possible to do. Too bad it's impossible. This may be one of the reasons why navigation with the old static sidebar was confusing.

Perhaps it is at least possible to index a color preference according to the sub-profile we use to help know where we are? (This post would not have been created entirely for nothing)

**Comment by jurialmunkey** [comment]
> Perhaps it is at least possible to index a color preference according to the sub-profile we use to help know where we are? (This post would not have been created entirely for nothing)

Yes I already said that this would be coming soon.

**Comment by jurialmunkey** [comment]
> Yes, I noticed that the icons were not associated with hubs but with shortcuts. However I thought it was possible to find a clever way to index them. ... Too bad it's impossible. 

I never said it was impossible. I said the icons on the shortcuts are not linked to the hubs.

The bigger issue, however, is that I think that your suggestion about the icon will cause more confusion.

Icons in that position are usually clickable shortcuts. Adding an icon that is not a shortcut in that position will be inconsistent and cause confusion because users will wonder why they cannot click it.

**Comment by Bindou01** [comment]
> > Peut-être est-il au moins possible d'indexer une préférence de couleur en fonction du sous-profil que nous utilisons pour savoir où nous en sommes ? (Ce post n'aurait pas été créé entièrement pour rien)
> 
> Oui, j'ai déjà dit que cela arriverait bientôt.

Sorry, I missed that.  So that's great.  Thank you so much.

**Comment by Bindou01** [comment]
> > Yes, I noticed that the icons were not associated with hubs but with shortcuts. However I thought it was possible to find a clever way to index them. ... Too bad it's impossible.
> 
> I never said it was impossible. I said the icons on the shortcuts are not linked to the hubs.
> 
> The bigger issue, however, is that I think that your suggestion about the icon will cause more confusion.
> 
> Icons in that position are usually clickable shortcuts. Adding an icon that is not a shortcut in that position will be inconsistent and cause confusion because users will wonder why they cannot click it.

You're right, I thought that too.  This is really just the beginning of an idea to open the discussion and find better collectively.  I also suggested replacing the "menu" shortcut icon, so that it is dynamic, and displays the current hub icon.  Which allows us to keep the “clickable” philosophy.

**Comment by Bindou01** [comment]
Damn, I just saw that you closed this proposal.

**Comment by Bindou01** [comment]
Jurial, you did it and it works wonderfully.  You are extremely competent.  Thank you so much.
