### ISSUE TITLE
New alternative to back key navigation

### ISSUE THREAD

**Issue by Bindou01** [jurialmunkey/skin.arctic.fuse#605]
### Skin section

Return key

### Feature description

New return key navigation. That is, deactivate "Hub change" with the "return" key while retaining the rest of the "Previous" function. It would look like this:

Return to the start of the Widget -> Return to the top of the Widgets / return to the categories -> Return to the start of the list of categories -> Return to the Search icon -> Return to the sidebar (without changing Hub).

### Why is this feature needed? Please justify and explain.

This would avoid exiting a Hub accidentally with the "return" key. In addition, it would make sense to deactivate the "Home Page", which would then really be deactivated. In addition, this opens the way to another way of thinking about the Global interface, like "Netflix". This means that we obtain a list of hubs, none of which would have priority over the other.

Thanks again for everything Jurial.

### Checklist

- [X] I have made a separate issue for each feature I am requesting.
- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by jurialmunkey** [comment]
You cannot disable home. It is not possible to prevent going back to it.

**Comment by jurialmunkey** [comment]
Again what you are looking for is pseudo profiles which are available via expert settings. These allow for quickly switching widget sets without using a full profile.

**Comment by Bindou01** [comment]
> Vous ne pouvez pas désactiver la maison. Il n'est pas possible d'empêcher d'y revenir.

I thought there would be a trick for this. :/  
Isn't it at least possible to open the side pane with the back key, before this causes a Hub change? (While maintaining "previous" mode)

**Comment by Bindou01** [comment]
> Again what you are looking for is pseudo profiles which are available via expert settings. These allow for quickly switching widget sets without using a full profile.

I just took a look at changing profile without using a full profile. I also see that there is the possibility of putting a shortcut for this instead of the "search" icon. It may actually be more judicious. It actually seems to meet this need, and it also seems quick. However, at first glance, I would say that the full screen selection takes away some of the intuitiveness of the interface and strays from what I had imagined. I need to think about this and try again. Or maybe think about things differently. I will see. Just in case, do you think it is possible to present the profile selection menu differently, like a window, or a pane?

Thank you very much for your patience and listening.

**Comment by Rinicko** [comment]
> > Vous ne pouvez pas désactiver la maison. Il n'est pas possible d'empêcher d'y revenir.
> 
> I thought there would be a trick for this. :/ Isn't it at least possible to open the side pane with the back key, before this causes a Hub change? (While maintaining "previous" mode)

You can map a key to ActivateWindow(1172)... that's the same as opening side menu with a button and you can pretty much do it from anywhere on the skin

**Comment by Bindou01** [comment]
Thanks for the tip Rinicko, but my remote control has very few buttons. I already use all the keys. And then the goal is to create an interface as intuitive as those of streaming companies. So this should use few buttons. This should be primarily visual. Until now, the Jurial Skins really allowed us to get closer, while offering a little more functionality, so that's great. I'll have to think again, but thank you for all the suggestions.

**Comment by jurialmunkey** [comment]
You can create a shortcut anywhere in the skin to login immediately to a pseudo profile with the command
```
RunPlugin(plugin://script.skinvariables/?info=get_skin_user&skinid=skin.arctic.fuse&folder=1080i&slug=default)
```

The slug for the default user pseudo profile is `default`. Replace `default` in the command with user slug for the profile you want to login into. User slugs for the additional users can be found in the file:
```
.kodi/userdata/addon_data/script.skinvariables/logins/skin.arctic.fuse/skinusers.json
```

**Comment by Bindou01** [comment]
> You can create a shortcut anywhere in the skin to login immediately to a pseudo profile with the command
> 
> ```
> RunPlugin(plugin://script.skinvariables/?info=get_skin_user&skinid=skin.arctic.fuse&folder=1080i&slug=default)
> ```
> 
> The slug for the default user pseudo profile is `default`. Replace `default` in the command with user slug for the profile you want to login into. User slugs for the additional users can be found in the file:
> 
> ```
> .kodi/userdata/addon_data/script.skinvariables/logins/skin.arctic.fuse/skinusers.json
> ```

Thank you Jurial. It “seems” to open the way to this new way of thinking about the global interface as I mentioned. I'm going to do some testing in this direction.  

However, I always think broader, beyond my own use.  I would really like this to be an option integrated into the Skin. Opening up the possibility to all users to have a logic other than the "Home Page + hub" seems great to me.  Fuse would then no longer have any limits in the way of architecting the interface.  Furthermore, having discussed it in real life with loved ones, several of us are looking for this hybrid system which brings us closer to using the Netflix sidebar, but with the intelligent customization of Fuse.  

So, do you think it would one day be possible to be able to create shortcuts for profiles, directly from the interface?  That would be really awesome.  I'm going to do some tests, and I'll come back with a Github improvement proposal that I hope is interesting and realistic.  

Thank you for everything.

**Comment by jurialmunkey** [comment]
You already can add it as a shortcut. Use action in the config dialog and choose edit to enter a custom command and enter the command.

**Comment by Bindou01** [comment]
After numerous tests, it seems that the use of the profile is not entirely suitable for our daily use. My family is unanimous on this point, almost preferring using the hub to changing profiles, mainly due to the interruption of the screen and the loading time being a little too long on less powerful devices. So I will continue my efforts to find the most effective settings using the Hub for now.

One of the persistent ergonomic challenges is the difficulty in clearly distinguishing when navigating from one hub to another, or when returning to the home page. Certainly, the “Close” icon is useful to differentiate the home page of a hub, but it does not distinguish the different hubs from each other. I suggested associating specific icons to each hub and displaying them at the top of the page, next to the title. However, an animation could be an even more effective solution. Do you think you could create an animation similar to the one that plays when you access and leave a movie's information page? This could not only signal to the user that they are changing hubs, but also improve the fluidity of navigation and reinforce the coherence of the site.
