### ISSUE TITLE
:bug: Cannot switch to AF 0.5.16

### ISSUE THREAD

**Issue by berkhornet** [jurialmunkey/skin.arctic.fuse#608]
### Skin section

Other

### Current Behavior

Sorry to trouble you again!

I have just downloaded AF 0.5.16 zip file and installed ok (Kodi set to use Estuary). When I try to switch to AF, the estuary skin remains. Having set Kodi debug on I see the following in the log file:

2024-03-20 11:08:23.145 T:2952     info <general>: Loading skin file: SettingsCategory.xml, load type: KEEP_IN_MEMORY
2024-03-20 11:08:23.182 T:2952    debug <general>: ------ Window Init () ------
2024-03-20 11:08:23.182 T:2952    error <general>: GUIFontManager::LoadTTF: Couldn't load font name: __defaultborder__(notosans-regular.ttf), trying arial.ttf
2024-03-20 11:08:25.618 T:2952    debug <general>: CWinEventsWin32::WndProc: WM_ACTIVATE -> window is inactive
2024-03-20 11:08:25.618 T:2952    debug <general>: CWinEventsWin32::WndProc: window is active
2024-03-20 11:08:25.619 T:2952    debug <general>: CWinEventsWin32::WndProc: window focus lost

### Expected Behavior

Skin would switch to AF

### Steps To Reproduce

Switch to Estuary
Download AF 0.5.16
Install
Switch to AF

### Screenshots and Additional Info

I have tried installing from zip file and repository with the same result

I reverted to the 0.5.15 zip file and that worked fine

I then tried installing from the zip fille for the first commit in the new release (ad06762) and the problem occurred

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
I don't think this is a relevant error message. Would need a full log to see the issue but my best guess is that you didn't update SkinVariables to meet dependency requirement.

**Comment by nkyritsis** [comment]
I just installed this skin and ran into what i believe is the same issue. I found that choosing "Yes" in the Keep Skin? Popup reverts the skin, but if I choose "No" in the Keep Skin? Popup, the skin is applied. I don't know if it's an issue with the actual values or the highlight, but I hope this helps.

**Comment by berkhornet** [comment]
@nkyritsis Many thanks for that - the only thing that I didn't try! I couldn't get 0.5.16 to install over 0.5.15 which was I reverted to Estuary to try and install. Looks good now, but I had to redo a few skin settings. Thanks again.

**Comment by jurialmunkey** [comment]
Ah yeah there will be a texture issue that requires a restart of kodi after installing to get texturemaker to rebuild the gradient textures. So it might look like the opposite button is focused in the confirm dialog since the highlight texture is missing from the focused one.

**Comment by jurialmunkey** [comment]
^^^ I think that commit should do a better job of making sure there is a fallback texture available if the file hasn't built yet. Might still have the same issue on the next update but after that should be fine.

**Comment by jurialmunkey** [comment]
I'll close this as complete but let me know if you have the same issue when installing the next update.

**Comment by jurialmunkey** [comment]
Okay I think 5.18 should fix the textures building issue too (once you return to the home screen). Let me know if the issue with no focus highlight crops up again or the gradients aren't properly rebuilding after an update.

**Comment by berkhornet** [comment]
@jurialmunkey Many thanks - latest update solved the issue
