### ISSUE TITLE
:sparkles: Youtube trailers option

### ISSUE THREAD

**Issue by ProArtix** [jurialmunkey/skin.arctic.fuse#610]
### Skin section

Other

### Feature description

Wouldn't it be a good idea to give the option to search for the trailers on YouTube as well? (within information) and depending on the language you speak, add text to part of the title of the movie or series, for example "FilmName in Spanish"

### Why is this feature needed? Please justify and explain.

More information visual

### Checklist

- [ ] I have made a separate issue for each feature I am requesting.
- [ ] I have searched the issues and this feature has not been requested.
- [x] I am using the most recent skin version.

**Comment by ProArtix** [comment]
Is possible?

**Comment by ZEPLUMBER1** [comment]
You can link the trailers directly on the TMDB page for the movie/show you want. If you set the language in TMDBh to spanish it will look for the spanish version of the movie you want to watch

This is the best way to do it as it will then be available for everyone to watch afterwards, TMDB is user maintained and you would help the community

**Comment by jurialmunkey** [comment]
Yes I think @ZEPLUMBER1 advice here is best.

Contribute trailers to TMDb so that everyone will benefit. It is a community effort.
