### ISSUE TITLE
Bring back fanart on spot light. 

### ISSUE THREAD

**Issue by adamosborne83** [jurialmunkey/skin.arctic.fuse#611]
### Skin section

Widgets

### Feature description

Might just be a setting a I cannot find.
But, spot light use to be full screen without blur.

### Why is this feature needed? Please justify and explain.

See pic of what it use to be, and video of how it now has blur.

### Screenshots and Additional Info

![Screenshot_20240320_200650_Samsung Internet](https://github.com/jurialmunkey/skin.arctic.fuse/assets/78307374/aaba8db1-f5a4-421a-90fc-1b72c247a36b)

https://github.com/jurialmunkey/skin.arctic.fuse/assets/78307374/611b4856-af7d-4e34-a3b0-549524772b94

### Checklist

- [X] I have made a separate issue for each feature I am requesting.
- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by adamosborne83** [comment]
PS, thanks for adding my request even though I closed it 😀 haha....

**Comment by Omarscomin** [comment]
Try this:

Skin settings > Background style > set to "Fanart (Performance)"

**Comment by adamosborne83** [comment]
> Try this:
> 
> Skin settings > Background style > set to "Fanart (Performance)"

No its not that im after, as then it shows it on widgets. 
Just how it was, thanks though.
I feel sorry for J, his github and forum page has exploded this week.

**Comment by Rinicko** [comment]
Skin settings > Appearance > Spotlight style - switch to fanart. 

It only reverts to blur when visible but not highlighted, i.e when categories is highlighted as this is the background style you have chosen

**Comment by adamosborne83** [comment]
> Skin settings > Appearance > Spotlight style - switch to fanart. 
> 
> It only reverts to blur when visible but not highlighted, i.e when categories is highlighted as this is the background style you have chosen

Thanks for the reply, but it is not this.

**Comment by jurialmunkey** [comment]
There's an issue with the transition animation between windows which I haven't been able to solve yet, and is why it is like this at least for the time being.

**Comment by adamosborne83** [comment]
> There's an issue with the transition animation between windows which I haven't been able to solve yet, and is why it is like this at least for the time being.

Cheers for the update. No Drama, feel free to close if need be.

**Comment by adamosborne83** [comment]
> There's an issue with the transition animation between windows which I haven't been able to solve yet, and is why it is like this at least for the time being.

Sorry to comment on closed issue as always.

Correct me if I'm wrong, but still seems the same? https://github.com/jurialmunkey/skin.arctic.fuse/assets/78307374/990d2c95-34ad-4ef2-8acf-1746b02aba2b

**Comment by jurialmunkey** [comment]
Sorry was cleaning up old issues and meant to close as "not planned" not "done".

Got a few ideas that I'm testimg to handle this scenario a little differently, and which will likely make the issue a bit redundant.

**Comment by CyberRooke** [comment]
> Sorry was cleaning up old issues and meant to close as "not planned" not "done".
> 
> Got a few ideas that I'm testimg to handle this scenario a little differently, and which will likely make the issue a bit redundant. 

I'm guessing you're trying to make the spotlight feel like a separate page when on fullscreen 🤔
