### ISSUE TITLE
Autoscrape source select window freezes on navigation

### ISSUE THREAD

**Issue by JFG1000** [jurialmunkey/skin.arctic.fuse#612]
### Skin section

Other

### Current Behavior

Hi there I'm recently been using autoscrape feature with Fen light with omega RC2 and fuse, and I've noticed a navigation bug, when the autoscrape does its thing and brings up the source select window the navigation completely freezes and we can only select the highlighted source as in the picture I've attached, using nvidia shield. Apologies if this goes against any rules on git regarding addons but if you can look into this I'd massively appreciate it, here's a log although I'm not sure anything can come of it, I tested on Estuary and it works fine, so I'm not sure if it's an issue with fuse

https://paste.kodi.tv/remipukequ

### Expected Behavior

Be cable to navigate using the remote to select a source 

### Steps To Reproduce

Enable auto scrape in fen light in playback settings, play a tv show episode, get to 95% playback, let auto scrape do it's thing, press stop to bring up the source select window to choose the next episode source 

### Screenshots and Additional Info

![20240318_205552](https://github.com/jurialmunkey/skin.arctic.fuse/assets/76907836/5b35bcf3-f9cd-485b-b5f2-95646f333518)

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
This dialog isn't part of the skin at all. It is provided by the addon.

**Comment by JFG1000** [comment]
Thanks for confirming, is there any reason as to why it would navigate correctly using estuary out of curiosity?

**Comment by jurialmunkey** [comment]
Could be a conflicting ID. Could be the skin expecting to be able to focus a specific control on back. Could be the scripted window not dealing with a specific scenario. Could be all manner of things. The code for the addon isn't readily visible on git without downloading it so hard to say and I personally don't want to install it on my machine.

**Comment by JFG1000** [comment]
Thankyou for the confirmation, I'll pass this on to tiki and hopefully he can look into this.

**Comment by JFG1000** [comment]
@jurialmunkey I've found out what causes it to freeze on navigation, if i let the whole stream play it works fine, but if i bring up the video OSD and hit stop it freezes, is that any help to narrow done what's happening here?

**Comment by jurialmunkey** [comment]
Do you have `autoclose after X seconds` setting enabled?

**Comment by JFG1000** [comment]
I do set to 3 seconds, it's the source select window that freezes after playback has finished that is the bug I'm facing, if i manually hit stop it freezes after 95% playback, If i let it play all the way through it doesn't freeze

**Comment by jurialmunkey** [comment]
The autoclose sends focus to a hidden button after X seconds to close the OSD. 

My first guess in that case is that the scripted window does not have a `<defaultcontrol>` value set, so Kodi does not know what control to focus when the one it wants to focus (from the autoclose timer) no longer exists

**Comment by JFG1000** [comment]
It's not the autoclose that I'm having issues with it's the skin not playing nice with Fen light auto scrape, it brings up the source window when the next episode is ready and freezes, but it only does this if i bring up the osd and hit stop when re sources are ready, if i let it play through and end the stream it let's me navigate and does not freeze

**Comment by jurialmunkey** [comment]
Yes but the autoclose sets a timer to focus a button control at a specific ID. The button it focuses is what closes the OSD.

When you stop the video, the OSD already closes, but the timer is still active so Kodi tries to focus that control. By that time the scripted window is open, so it focuses nothing. 

If there is no defaultcontrol value set in the scripted window, then Kodi does not know what to focus in the window when focus is lost.

**Comment by jurialmunkey** [comment]
This is just a guess though, since I cannot see the code of the addon without downloading it.

**Comment by jurialmunkey** [comment]
It could also be any number of other things which happen at playback stop from other addons -- e.g. something like Trakt addon trying to open ratings dialog.

Or it could just be an error in the addon itself.

**Comment by JFG1000** [comment]
Appreciate the response jurial would it be atall possible to take a look? It triggered when i created widget and tested on a blank set up

**Comment by jurialmunkey** [comment]
Sorry I'm not going to install that addon.

You can test yourself by deleting the OSD autoclose value and seeing if it still occurs. Make sure to delete it so that the value is empty, not just set to 0s.

**Comment by JFG1000** [comment]
Ok i understand that's fair enough, how would I go about deleting the values?

**Comment by JFG1000** [comment]
Btw whilst I've got you would you please be able to explain how to reset the highlight colours for season Premier etc in skin settings?

**Comment by jurialmunkey** [comment]
> Ok i understand that's fair enough, how would I go about deleting the values?

In skin settings. Delete it using the pop-up number pad and then press ok.

**Comment by JFG1000** [comment]
Many thanks, btw deleting the value worked is there anything that can be done from here onwards or do I need to contact tiki?

**Comment by jurialmunkey** [comment]
> Many thanks, btw deleting the value worked is there anything that can be done from here onwards or do I need to contact tiki?

Next version of the skin will use a different method, so the skin won't cause it to occur. 

However, without the addon having a `<defaultcontrol>` tag in its scripted windows, it will continue to have this issue if anything else causes a loss of focus -- for example, I expect you can likely cause the same problem by bumping the mouse off the list.

**Comment by JFG1000** [comment]
Thankyou so much jurial this is beyond appreciated I'll really looking forward to this update
