### ISSUE TITLE
Category>Focus on second position does not always work.

### ISSUE THREAD

**Issue by Bindou01** [jurialmunkey/skin.arctic.fuse#615]
### Skin section

Widgets

### Current Behavior

Category>Focus on second position does not always work. The “Read / More information” menu often comes up first, unintentionally, when moving between the Home page and the hubs.

### Expected Behavior

If I'm not mistaken, the "Category>Focus on second position" function should avoid showing the reading shortcuts and more information first, and instead make us return to the categories.

### Steps To Reproduce

Go from one hub to the home page, to another hub, then go to the category bar.

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
No this is not what that setting does.

It makes the second item in the category list the main focus instead of the first item.

e.g. if you have Movies | Tvshows | Music | Addons as your categories, then TVShows will be focused first instead of Movies and the focus position will move at the second position instead of the first.

**Comment by Bindou01** [comment]
> No this is not what that setting does.
> 
> It makes the second item in the category list the main focus instead of the first item.
> 
> e.g. if you have Movies | Tvshows | Music | Addons as your categories, then TVShows will be focused first instead of Movies and the focus position will move at the second position instead of the first.

Thanks for the info Jurial. So I don't understand why I managed to hide the "Play/more information" menu which is located above the horizontal list of categories. And for some time now, it has been appearing regularly, by manipulating as I explained above? Is there another way to focus on the categories when exiting the side pane shortcuts rather than on these buttons?
