### ISSUE TITLE
Apple TV Pressing Back exits to main Apple TV Window

### ISSUE THREAD

**Issue by Ade-AV** [jurialmunkey/skin.arctic.fuse#619]
### Skin section

Widgets

### Current Behavior

When focused on a widget item there's no easy way to get back to the Menu, have to keep pressing left/right to get back

### Expected Behavior

On my MacBook pressing Escape acts as a Previous action, would be good if the Back button on Apple TV did the same or go back to the Menu 

### Steps To Reproduce

As above

### Screenshots and Additional Info

Attached the Keymap I think it's using, is there an option in there I could change?
[customcontroller.SiriRemote.txt](https://github.com/jurialmunkey/skin.arctic.fuse/files/14712790/customcontroller.SiriRemote.txt)

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
Sorry, this isn't a skin issue, it's a keymap issue, so it's not something I have any control over. I'm not familiar with Apple TV so I can't offer any advice here sorry. You'd be better off asking in the forums in the tvOS section
https://forum.kodi.tv/forumdisplay.php?fid=137
