### ISSUE TITLE
re-add option to give user-rating

### ISSUE THREAD

**Issue by Aemstel2** [jurialmunkey/skin.arctic.fuse#623]
### Skin section

Library

### Feature description

It is no longer possible to give a user-rating. It could be done in the rating dialog but that has been taken out, which I think is a nice change, except that it is now impossible to give a user-rating. Maybe this option can be added somewhere else.

### Why is this feature needed? Please justify and explain.

It is needed to give a user-rating.

### Checklist

- [X] I have made a separate issue for each feature I am requesting.
- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by jurialmunkey** [comment]
Info > Artwork > Rating.

**Comment by Aemstel2** [comment]
Oh wow, I could've sworn I looked there. Guess not.. Thanks. Sorry for bothering you.
