### ISSUE TITLE
Home header not displaying watch section

### ISSUE THREAD

**Issue by JFG1000** [jurialmunkey/skin.arctic.fuse#625]
### Skin section

Widgets

### Current Behavior

Hi there so on the latest update the header for classic mode is labeled "home" for every section i navigate, so no matter what section i rename for movies, shows etc, it displays it as home at the top, please could you look into this as you changed it before so it displayed as intended. 

### Expected Behavior

When we navigate on menu sections the labels should display what we are navigating over 

### Steps To Reproduce

Highlight a menu icon to display its title 

### Screenshots and Additional Info

![20240323_133141](https://github.com/jurialmunkey/skin.arctic.fuse/assets/76907836/af841696-a9e8-4d5d-aac3-660a4e2288b9)

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
Ah I forgot that I was meaning to link it to the indicator option. Should be fixed now.
