### ISSUE TITLE
[Bug] Profile switching error after recent update

### ISSUE THREAD

**Issue by AakashC2020** [jurialmunkey/skin.arctic.fuse#628]
### Skin section

Other

### Current Behavior

Hi @jurialmunkey,

Hope you're doing well.

I'm using Kodi Omega RC 2 and Arctic Fuse latest version. I have 2 profiles in Kodi. After the recent updates when I'm trying to switch the profile from the top button in the options menu, I'm being re-directed to the default profiles screen instead of my actual available profiles in Kodi. Earlier this issue was not there and the button used to work perfectly. Could you please check the issue and kindly resolve?

### Expected Behavior

The profile switching button in the options menu should open the actual profiles available in Kodi instead of the default profile option.

### Steps To Reproduce

Go to options menu. Click on the top profile switching button.

### Screenshots and Additional Info

![IMG20240323213734](https://github.com/jurialmunkey/skin.arctic.fuse/assets/65297828/4f49400b-63a3-45d1-a157-23afb4ba548b)

![IMG20240323213748](https://github.com/jurialmunkey/skin.arctic.fuse/assets/65297828/2f005f0e-2540-41c7-a1a9-6755f7719f1e)

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
Skin Settings > Expert > Disable Pseudo Profiles

**Comment by AakashC2020** [comment]
> Skin Settings > Expert > Disable Pseudo Profiles

Thank you @jurialmunkey ! That worked. 👍🏻
