### ISSUE TITLE
[BUG] Issue with Endlessly wrap viewstyles

### ISSUE THREAD

**Issue by AakashC2020** [jurialmunkey/skin.arctic.fuse#63]
### Skin section

Home Widgets

### Current Behavior

Hi @jurialmunkey,

Using the newly added feature "Endlessly wrap viewstyles" along with "Combined style - Vertical (detailed) is causing both the styles to overlap each other. See screenshots.

### Expected Behavior

Both the styles shouldn't overlap each other.

### Steps To Reproduce

Use the two features in combination.

### Screenshots and Additional Info

![IMG20230802150212](https://github.com/jurialmunkey/skin.arctic.fuse/assets/65297828/6c359b9e-89ba-4f97-9cf6-97041825bea0)

![IMG20230802150242](https://github.com/jurialmunkey/skin.arctic.fuse/assets/65297828/0645e296-3dd6-44bc-88b6-092f3564e708)

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by 666jones** [comment]
I have had this happen to me afew times before the endlessly wrap view styles was implemented. It always sorted itself out and went back into place after pressing right or left to scroll through

**Comment by jurialmunkey** [comment]
> I have had this happen to me afew times before the endlessly wrap view styles was implemented. It always sorted itself out and went back into place after pressing right or left to scroll through

The problem is that the wraplist causes it always to occur because there's always an item to the left of the focus and there's no way to hide a specific item or mask it.

When it is a fixedlist, it only occurs if the focus item is not the first item - but wrap list always occurs. I honestly don't think it's possible to fix at all via the skin.

**Comment by AakashC2020** [comment]
> > I have had this happen to me afew times before the endlessly wrap view styles was implemented. It always sorted itself out and went back into place after pressing right or left to scroll through
> 
> The problem is that the wraplist causes it always to occur because there's always an item to the left of the focus and there's no way to hide a specific item or mask it.
> 
> When it is a fixedlist, it only occurs if the focus item is not the first item - but wrap list always occurs. I honestly don't think it's possible to fix at all via the skin.

Hi @jurialmunkey,

No problem. In that case it's better to not use both these styles together. The Vertical combined style is so good that by not using the Endlessly wrap viewstyles we won't lose anything. Thanks for this awesome skin!

**Comment by AakashC2020** [comment]
Hi @jurialmunkey,

Thank you! The new solution is good, but I personally prefer not to use the Endlessly wrap viewstyles option. I like the normal viewstyle with Vertical Combined details better.

**Comment by jurialmunkey** [comment]
Well yeah you don't need to use that option. 

There's a reason it isn't enabled by default and that's because I don't use it myself. I think wrap lists make navigation confusing - it was only added as a request.

**Comment by AakashC2020** [comment]
> Well yeah you don't need to use that option.
> 
> There's a reason it isn't enabled by default and that's because I don't use it myself. I think wrap lists make navigation confusing - it was only added as a request.

Sure @jurialmunkey ! Thank you so much!
