### ISSUE TITLE
[Bug] Search button is no longer visible in the side menu

### ISSUE THREAD

**Issue by AakashC2020** [jurialmunkey/skin.arctic.fuse#631]
### Skin section

Other

### Current Behavior

Hi @jurialmunkey,

After the latest update if side menu > minimise is set to library then the search button is no longer visible. Could you please check and kindly advise? I want to see the entire side menu along with the search button like earlier. Currently only minimised side menu is showing the search button.

### Expected Behavior

The search button should be visible along with the other side menu buttons like earlier.

### Steps To Reproduce

See attached screenshots.

### Screenshots and Additional Info

![IMG20240324191716](https://github.com/jurialmunkey/skin.arctic.fuse/assets/65297828/9842798d-ab17-4a55-8117-6b82b461c0df)

![IMG20240324191852](https://github.com/jurialmunkey/skin.arctic.fuse/assets/65297828/75a07049-30a2-4d10-a783-e44875e58d0c)

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by xyzfre** [comment]
The home icon has been replace with the search icon. You can add the shortcut yourself or set it back to default.

**Comment by AakashC2020** [comment]
> The home icon has been replace with the search icon. You can add the shortcut yourself or set it back to default.

Hi @xyzfre and @jurialmunkey,

Okay if I do so, then it looks like the below attached screenshot. However, I still feel that the earlier approach was looking much better with the Home button separately at the top having a distance from the side menu and the options button at the bottom of the side menu.

![IMG20240324194504](https://github.com/jurialmunkey/skin.arctic.fuse/assets/65297828/ae5f1a6b-5962-4ee2-a93c-0e51b09e04dd)

**Comment by Liquidrag** [comment]
> The home icon has been replace with the search icon. You can add the shortcut yourself or set it back to default.

So clicking the home icon is supposed to bring up search? If so, mine does not do that. 
I also enabling/disabling side menu> Minimize>search  seems to do nothing.
How do I set it back to default?

**Comment by xyzfre** [comment]
In the newest update there is no more Home icon by default only a search icon

**Comment by xyzfre** [comment]
![image](https://github.com/jurialmunkey/skin.arctic.fuse/assets/49699869/fbdece6e-ff98-493c-b1c4-51d68f7f8263) this is an example of how the default looks now with the side icons

**Comment by Liquidrag** [comment]
Which version is it? I have v0.6.1~omega 
<img width="1214" alt="Screen Shot 2024-03-24 at 9 45 23 AM" src="https://github.com/jurialmunkey/skin.arctic.fuse/assets/43726430/486a64c3-5f20-47e2-be7b-ecec7565e8fc">
<img width="1223" alt="Screen Shot 2024-03-24 at 9 46 13 AM" src="https://github.com/jurialmunkey/skin.arctic.fuse/assets/43726430/b56973e5-b507-47df-a9a5-d1a6d280f7a8">

**Comment by xyzfre** [comment]
This is how Jurial explains it![image](https://github.com/jurialmunkey/skin.arctic.fuse/assets/49699869/4dffad00-5c48-450b-b649-39e86ad28014)

**Comment by AakashC2020** [comment]
> This is how Jurial explains it![image](https://private-user-images.githubusercontent.com/49699869/316321423-4dffad00-5c48-450b-b649-39e86ad28014.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEyOTU4NTAsIm5iZiI6MTcxMTI5NTU1MCwicGF0aCI6Ii80OTY5OTg2OS8zMTYzMjE0MjMtNGRmZmFkMDAtNWM0OC00NTBiLWI2NDktMzllODZhZDI4MDE0LmpwZWc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyNFQxNTUyMzBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lNWQ2MDk5ZmVkNmUxZjk5ODUxNWViOWM0N2U4Mzg3ZmRiNDA5ZGQxNDcyOGUwNmNiNjJlOWViMmZlZmNhZTUzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.kWH4Xay5cSlOvm9wND6kZDEC9P3i986trRInMfNBZX4)

OMG! 😰 Those top and bottom fixed icons looked so good though... 😔 I'll really miss them @jurialmunkey ... 😥

**Comment by Liquidrag** [comment]
@xyzfre ok so replacing the home hub action to search did the trick, thank you! Works because home hub did nothing.

**Comment by xyzfre** [comment]
I'm trying to adapt myself to all the new changes recently. Sometimes we get used to certain things but we gotta remember he's still working on it and it's still coming along as the best skin ever💯💯

**Comment by AakashC2020** [comment]
> @xyzfre ok so replacing the home hub action to search did the trick, thank you! Works because home hub did nothing.

@Liquidrag Home hub button is used to return to Home when you're inside any other Hub like Movies or TV Shows. I use it regularly.

**Comment by Liquidrag** [comment]
> > @xyzfre ok so replacing the home hub action to search did the trick, thank you! Works because home hub did nothing.
> 
> @Liquidrag Home hub button is used to return to Home when you're inside any other Hub like Movies or TV Shows. I use it regularly.

I can see needing it to switch to other hubs inside of hubs but for home, backspace works

**Comment by AakashC2020** [comment]
> I'm trying to adapt myself to all the new changes recently. Sometimes we get used to certain things but we gotta remember he's still working on it and it's still coming along as the best skin ever💯💯

I know that @jurialmunkey is the best, but it's really difficult to let go such useful features which you use regularly... I agree though that Arctic Fuse is the best Kodi skin ever, but the fixed icons were awesome... Now it's like Arctic Horizon with only Custom icons... I pray that @jurialmunkey listens and atleast provides an option to keep the fixed icons for die hard fans of that feature like us... 🙏

**Comment by AakashC2020** [comment]
> > > @xyzfre ok so replacing the home hub action to search did the trick, thank you! Works because home hub did nothing.
> > 
> > 
> > @Liquidrag Home hub button is used to return to Home when you're inside any other Hub like Movies or TV Shows. I use it regularly.
> 
> I can see needing it to switch to other hubs inside of hubs but for home, backspace works

Ya, that it does, but still it is what it is 🙂

**Comment by Liquidrag** [comment]
> Ya, that it does, but still it is what it is 🙂

At least We have the search button back :)

**Comment by AakashC2020** [comment]
> > Ya, that it does, but still it is what it is 🙂
> 
> At least We have the search button back :)

Ya, that's true... Otherwise, it would've been a nightmare... 🙂 But I'll still say the fixed icons were far better... 😔

**Comment by tduong-cloud** [comment]
Hey, many thanks for the comments here, I was able to add the search menu again. And many thanks jurial for your great work as usual.

I have also noticed that the behavior is different, as one would need to specify the type of content now (movies, tvshows etc.) instead of being able to search for all type of content as previsouly. I personnaly preferred (but maybe it is just me) this behavior rather than having to select the type of content.

Is there a way to configure this? 

Many thanks in advance.

**Comment by jurialmunkey** [comment]
> Also, the first focus of the side menu is now going to the Search button instead of the Home button which doesn't seem ideal.

@AakashC2020 - This has been addressed in main branch and options to set default focus will be available in next version: https://github.com/jurialmunkey/skin.arctic.fuse/issues/637

**Comment by AakashC2020** [comment]
> > Also, the first focus of the side menu is now going to the Search button instead of the Home button which doesn't seem ideal.
> 
> @AakashC2020 - This has been addressed in main branch and options to set default focus will be available in next version: #637

Hi @jurialmunkey,

That's awesome! Thank you so much! 😊

**Comment by xyzfre** [comment]
I've replaced the Home icon with the search icon, and I do not have no blank screen.![image](https://github.com/jurialmunkey/skin.arctic.fuse/assets/49699869/b270f4b0-3fe1-49a7-ac6e-4628f81ac951)

**Comment by L0bsang** [comment]
@xyzfre 
I would assume that is because you are using complex mode and all category visibility is set to "Always visible". Moving around on the sidemenu does not change anything until you click on the entry right?

In classic mode the widgets change based on which sidemenu item is focused. Same as Arctic Horizon.
Also in complex mode if you don't have categories set to be always visible, you have to make and link categories/submenu/widgets to be visible per sidemenu item.

**Comment by xyzfre** [comment]
> @xyzfre 
> 
> 
> 
> Of course as you have done it is possible to just replace the home item with action to open search, but then it is no longer possible to quickly go back to the home menu from the "menu" item in hub/library because onclick goes to search and the other onclicks go to the various hubs (as I believe has already been discussed above). 
> 
> Which is fine of course, pressing back a number of times works (and that is how we had to do it in the past anyways), but my point about having no widgets on a separate search item still stands, because **I am talking about the situation where you add a separate menu item instead of replacing home, which is why I said "manually added search shortcut".**
> 
> 
> 
> To be clear I am not asking for any changes, I too have replaced home with search and find it acceptable., especially since we have the handy labels to clarify. The only reason I was using home anyway is because it was hard to remove before, replacing with search is fine. Just gathering information; having a discussion; exploring the skin's full features and modes to provide feedback.
> 
> 
> 
> The screenshot in your comment is using complex mode and all category visibility is set to "Always visible" or linked to Home. Moving around on the sidemenu does not change anything until you click on the entry.
> 
> 
> 
> However in classic mode the widgets change based on which sidemenu item is focused. Same as Arctic Horizon 2.
> 
> Also in complex mode if you don't have categories set to be always visible, you have to make and link categories/submenu/widgets to be visible per sidemenu item or always visible or you will have nothing there ( have that issue with the addons sidemenu item). Which is why I asked. For example, it might be nice to have some sort of spotlight (classic mode does not have spotlights so it is just blank) or fullscreen widget there. 
> 
> 
> 
> Luckily jurial confirmed there is a plan to combine these modes.

You are correct. I am using complex mode, but when replacing the  Home icon I did not change the action. I changed it to hub search shortcut, but I do see your point.

**Comment by onlytanmoy** [comment]
@xyzfre thanks for pointing me here, I was able to add 'Search' in the right side options widget.
One query: do you know if its possible to set the search default as Movies (TMDb) instead of Movies as the later hardly shows any results?

**Comment by L0bsang** [comment]
> 
> You are correct. I am using complex mode, but when replacing the Home icon I did not change the action. I changed it to hub search shortcut, but I do see your point. I have never tried classic mode only complex

Makes sense! I am enjoying classic mode due to the continuous scrolling. 
Now I have added the hub search shortcut (default focus kept going to the second item and associated widgets) with some global widgets so there is no blank screen. Works well

**Comment by L0bsang** [comment]
> @xyzfre thanks for pointing me here, I was able to add 'Search' in the right side options widget. One query: do you know if its possible to set the search default as Movies (TMDb) instead of Movies as the later hardly shows any results?

Yes, in the widget customization there is an "Options" icon on the bottom for customizing options menus. In there you can set your search widgets and change the order. So put the TMDB ones on top. 

The other ones are for Library content so will not show anything if you don't have anything in your library; you can disable or delete them.

**Comment by onlytanmoy** [comment]
Perfect! thanks a lot @L0bsang

**Comment by jurialmunkey** [comment]
FYI - next version (0.6.4) will add an option for a simplified search screen. The "old" search has been renamed discover. Both can be found in the Hubs section.

The "new" simplified search functions similar to AH2 in that it has a edit control at the top and you can scroll down through the widgets. It only does search and has no filtering. You can also set it as the ondown action.

**Comment by vella9** [comment]
> The "new" simplified search functions similar to AH2 in that it has a edit control at the top and you can scroll down through the widgets. It only does search and has no filtering. You can also set it as the ondown action.

This is great news. One issue though, it seems that I cannot navigate to the widgets after typing in the search box. Up works fine and takes you back to the widgets screen but down, right and left (after scrolling through the characters) does nothing.

**Comment by onlytanmoy** [comment]
Hi @L0bsang any idea if its possible to have the mode defaulted to Search instead of Discover when I launch Search from the right hand side options widget? Even though I have disabled the other ones for library content as you suggested earlier I can see them show up along with the TMDb ones when the mode is Discover however on switching the mode to Search I only have the TMDb ones which is what I want.

**Comment by L0bsang** [comment]
> Hi @L0bsang any idea if its possible to have the mode defaulted to Search instead of Discover when I launch Search from the right hand side options widget? Even though I have disabled the other ones for library content as you suggested earlier I can see them show up along with the TMDb ones when the mode is Discover however on switching the mode to Search I only have the TMDb ones which is what I want.

@onlytanmoy ; That is a question for @jurialmunkey since this discover/search differentiation is absolutely new and I do not know the full capabilities.

FYI here are now two different types of "Search". 
One that uses a sidemenu (called Discover, same one we have been using, just renamed) and the other is new and uses an Arctic Horizon 2 style search where the textbox is on top and then search widgets appear in rows below. Both can be found in Hubs when you are setting the menu shortcuts. 

I don't know if there is a way to have the Discover screen default to 'Search' mode, and in the current version I have not seen an option to change the discover widgets.

But it isn't too hard to just switch to search mode as your first action in this discover screen, then you will have your expected widgets.

**Comment by L0bsang** [comment]
@onlytanmoy Actually after checking it out, you may enjoy the newly added simplified search screen as it uses your search widgets order. 

Reset your search widgets to default, re-order/delete them as you wish and then change your shortcut to launch Search [ActivateWindow(1185)] instead of Discover [ActivateWindow(1105)]. Give it a try. 

No filtering or modes to fiddle with, just search results.

**Comment by jurialmunkey** [comment]
> to launch Search [ActivateWindow(1185)] instead of Discover [ActivateWindow(1105)].

You can also find the shortcuts in the "hubs" shortcut folder

> 
> No filtering or modes to fiddle with, just search results.

Yeah this the thinking - discover drops you into discover mode for more advanced filtering whereas search is a simplified approach. 

Also if your on down action is search you can actually quickly switch between discover and search by pressing down from discover results (ie press back to the list then down)

**Comment by AakashC2020** [comment]
> Hi @L0bsang any idea if its possible to have the mode defaulted to Search instead of Discover when I launch Search from the right hand side options widget? Even though I have disabled the other ones for library content as you suggested earlier I can see them show up along with the TMDb ones when the mode is Discover however on switching the mode to Search I only have the TMDb ones which is what I want.

Hi @jurialmunkey,

Yes, I agree with @L0bsang. If there was an option to select the Search mode as default instead of Discover, like it was earlier, that will be really helpful. The advanced search is better than the classic search, but only this change will make it perfect. Kindly advise. Thank you!

**Comment by onlytanmoy** [comment]
> Reset your search widgets to default, re-order/delete them as you wish and then change your shortcut to launch Search [ActivateWindow(1185)] instead of Discover [ActivateWindow(1105)]. Give it a try.

Thanks for this, just tried, so Search works all fine but I do not find a way to move out of the search box and select a movie or show from the bottom search results. I tried all the directional keys of my shield remote but the focus remains on the search box :( Any idea?

**Comment by L0bsang** [comment]
Youy're welcome @onlytanmoy. 
That issue happened to me too, your answer is here: #653 

Basically that is why I said you need to reset your search widgets to default, there is a bug if you have a custom set.

**Comment by jurialmunkey** [comment]
> Youy're welcome @onlytanmoy. That issue happened to me too, your answer is here: #653
> 
> Basically that is why I said you need to reset your search widgets to default, there is a bug if you have a custom set.

You shouldn't need to reset your config. Maybe just need to force a rebuild of the widgets with the rebuild button in the config window.

**Comment by L0bsang** [comment]
> Yeah this the thinking - discover drops you into discover mode for more advanced filtering whereas search is a simplified approach.
> 
> Also if your on down action is search you can actually quickly switch between discover and search by pressing down from discover results (ie press back to the list then down)

Yes I quite like this approach, the current way the two windows function fits their naming quite well. I especially like that discover has some default content showing even before you search. Very nice.
I found pressing down for search made sense on the homepage (and definitely agree it is nice in discover), but didn't make as much sense for content, especially since in library there is no indication that is what pressing down will do, having a search page suddenly appear seemed unexpected.

However I noticed if the menu is minimized there is always the discover shortcut. So with that in mind I have set my homepage sidemenu to use the new Search shortcut, and then make use of discover everywhere else. That suits the way my family uses the skin, where search is the one-stop shop (youtube, trakt lists, sets etc) and then it is replaced by discover in hubs/content. I'm using Options for on-down, have some handy shortcuts in there (may try filter, still configuring).

>You shouldn't need to reset your config. Maybe just need to force a rebuild of the widgets with the rebuild button in the config window.

Oh I see. Didn't try that, definitely an easier way but can't test it now because it is already fixed and working.

**Comment by jurialmunkey** [comment]
> Oh I see. Didn't try that, definitely an easier way but can't test it now because it is already fixed and working.

I mean it is possible that there was some other issue, but my first guess would be that the template simply didn't rebuild with the new changes. Likely I forgot to bump up the build version to force it to rebuild after the change to the template.
