### ISSUE TITLE
Shortcuts in option menu don't work in v0.6.1

### ISSUE THREAD

**Issue by taiseer999** [jurialmunkey/skin.arctic.fuse#634]
### Skin section

Widgets

### Current Behavior

I have set up shortcuts in side menu to File manager, Add- Browser, Widgets setup that have always worked but on the latest version v0.6.1 clicking the shortcuts does not do anything. 

### Expected Behavior

Shortcuts suppose to work
![IMG_2982](https://github.com/jurialmunkey/skin.arctic.fuse/assets/118752825/11a5b4f7-6a09-4799-bfd5-a0a21b91e041)

### Steps To Reproduce

1 open options menu
2 chose any of File manager, Add- Browser, Widgets setup shortcuts 
3 non will work

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by taiseer999** [comment]
PS I have set same shortcuts in option  tray and all is working

**Comment by jurialmunkey** [comment]
Is this opened from the tray? It's because Kodi refuses to open a new window if another dialog is open -- in this case the tray.

**Comment by taiseer999** [comment]
Works perfectly from the tray
