### ISSUE TITLE
Widgets not building on refresh

### ISSUE THREAD

**Issue by JFG1000** [jurialmunkey/skin.arctic.fuse#635]
### Skin section

Widgets

### Current Behavior

Hey jurial I've noticed a few times this evening when adding new widgets or changing placent of them in a section, they do not build after skin variables has refreshed, you either have to reload skin or restart kodi for them to populate. 

### Expected Behavior

Widgets usually populate after new ones are made or ammendments to current. 

### Steps To Reproduce

Create a widget or ammendment a current one 

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
Can you be a bit more specific about how to recreate? I can't seem to recreate this issue.

The only issue I'm aware of is that Landscape style Search widgets were not building correctly.

**Comment by JFG1000** [comment]
No problem I can get a log for you tomorrow if that's ok? I remember earlier I moved the positing of a widget row, then after backing out to homescreen to let it rebuild nothing happened until done a skin reload, I'll be sure to grab a log tomorrow if i can re create the issue again for you

**Comment by jurialmunkey** [comment]
Less a log, a more just the type of layout, how you're setting the widget etc. -- basically a retrace your path type of thing.

**Comment by JFG1000** [comment]
So I'm using classic mode layout with 5 sections

Trakt library
Movies
Shows
Search
Quit

Trakt library movies and shows each have about 5-6 widget rows, a mixture type of poster, card and board style widgets, as i was creating them earlier and re positioning some up and down, i then backed out to home screen, after skin variables refreshed some sections loaded as intended but some were completely blank.

**Comment by JFG1000** [comment]
I'll have another play tomorrow and I'll see if i can re create it, could have just been kodi having a funny moment. I may be slow on replies so will check back when i can.

**Comment by jurialmunkey** [comment]
It is there. Option is split. Right footer always visible, left footer has more precise controls over exactly where it appears.

**Comment by JFG1000** [comment]
Sorry I'm confused could you tell me what i need to enable?

**Comment by JFG1000** [comment]
Not to worry sorted it, library, information & widgets

**Comment by JFG1000** [comment]
I've noticed this again a couple of times this morning and it's triggered with a search using search mode with Fen light custom paths, and when i back out to home screen none of my trakt widgets load

Took me a few attempts to trigger but I've managed to grab a log hopefully it helps mate

https://paste.kodi.tv/lexidicafa

**Comment by Bindou01** [comment]
Hello, I confirm this behavior.  This happened on the main hub, but also on hub 01. Unable to correctly apply the creation of two new categories.  All the creative work seemed to vanish into thin air.  (Classic Mode, Complex Category.)

**Comment by jurialmunkey** [comment]
Is this still occurring? I haven't been able to reproduce.

**Comment by JFG1000** [comment]
> Is this still occurring? I haven't been able to reproduce.

Seems ok now mate
