### ISSUE TITLE
Loading into skin request

### ISSUE THREAD

**Issue by JFG1000** [jurialmunkey/skin.arctic.fuse#637]
### Skin section

Widgets

### Feature description

Hey jurial would it ever be atall possible to add a setting in widgets that allows us users to pick a section that is highlighted when we load into kodi for example i would love the search icon to be top of the menu I've got on my set up but i would prefer it not be first selected. 

### Why is this feature needed? Please justify and explain.

Quicker navigation for certain sections 

### Checklist

- [X] I have made a separate issue for each feature I am requesting.
- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by jurialmunkey** [comment]
I was actually *just* working on exactly this. Finally figured out what appears to be a good way of setting the focus. Let's hope I haven't broken anything! 🤞 

Will default to 1 (i.e. second icon since arrays start at 0). Can change the default for side menu in customisation screen.

**Comment by JFG1000** [comment]
You absolute hero Jurial thankyou so much, that will be perfect, I'll personally have it load into my trakt library with the search icon on top, appreciate all your work as always 👌🏻
