### ISSUE TITLE
Add ability to create Title submenu list with alphabet grouping in other areas. 

### ISSUE THREAD

**Issue by QuickSwitchLK** [jurialmunkey/skin.arctic.fuse#638]
### Skin section

Widgets

### Feature description

With the prebuilt widgets both Movie Hub and TV Show Hub have shortcuts that have "Titles" with submenu list grouped by the alphabet. See Image.

![Screenshot 2024-03-25 185201](https://github.com/jurialmunkey/skin.arctic.fuse/assets/34122743/56c46d32-6162-4a79-9c1c-921b57d63b72)

![Screenshot 2024-03-25 185126](https://github.com/jurialmunkey/skin.arctic.fuse/assets/34122743/4654d310-4509-4f85-a5b0-5506348aa31e)

When I try to add the feature to another hub I can't find the ability to do so. The option Submenu list "special://skin/extras/hub/movies/titles" is not an option from what I have searched for.

I tried selecting the working submenu link but as soon as you select it to change it, it clears itself to being empty.

### Why is this feature needed? Please justify and explain.

It would be nice to be able to add them manually as currently, the only way I can find to load them is to load the default profile.

### Screenshots and Additional Info

This is as far as I can get...

![Screenshot 2024-03-25 191225](https://github.com/jurialmunkey/skin.arctic.fuse/assets/34122743/5231e9b6-42b4-418e-92d7-f005da057f31)

With none of the 14 options having a special://skin/extras/hub

### Checklist

- [X] I have made a separate issue for each feature I am requesting.
- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by jurialmunkey** [comment]
These are smart playlists and can be found under the "Playlists" grouping:
Playlists > Hub Playlists > movies|tvshows > titles

**Comment by QuickSwitchLK** [comment]
Omg do know how long I spent looking for them, and could not find them lol. Thanks for the help. 👍🤦
