### ISSUE TITLE
✨️ Option to clear search history

### ISSUE THREAD

**Issue by Rinicko** [jurialmunkey/skin.arctic.fuse#640]
### Skin section

Widgets

### Feature description

Thank you for adding a search history feature incase of accidental exit or recurring search terms 🙏🙏... but at the moment there is no way to clear the items in the search history, or i can seem to find it. The context menu for the search items only shows an option to add it to Autowidget... will it be possible to add "Clear item" to this area.

### Why is this feature needed? Please justify and explain.

This will help decluter the search dialog and also help remove terms you don't want other people knowing you searched for.

A request for this was previously made and closed as completed,  but it seems to be from a previous time with another version of this feature.

### Checklist

- [X] I have made a separate issue for each feature I am requesting.
- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by Bindou01** [comment]
And why not limit the amount of searches in history, and overwrite the oldest searches, rather than manually deleting them?

**Comment by Bindou01** [comment]
For my part, I notice a small bug. When you bring up the search hub and click directly on an item in the history without touching the keyboard, then the return key does not just close the pane, but closes the entire search hub.

**Comment by jurialmunkey** [comment]
@Bindou01 please do not hijack other issue threads with other bugs. If there is a separate bug, open a separate issue per bug.

**Comment by jurialmunkey** [comment]
@Rinicko - Did you figure this out yourself?

For reference, it is as simple as `Skin.Reset(SearchHistory)` but I really should add an option for it.

**Comment by Rinicko** [comment]
> @Rinicko - Did you figure this out yourself?
> 
> For reference, it is as simple as `Skin.Reset(SearchHistory)` but I really should add an option for it.

No, I just closed it cause I felt like I've been making too many requests. 

If it won't be an issue to add in the next update, I'd really appreciate it 🙏

**Comment by jurialmunkey** [comment]
No, I don't have any problem with people making many requests (as long as they are sensible which this one definitely is).

The only thing I care about is that the requests are reasonable and have a clear justification, and that people don't get upset if I decide to go in a different direction. Otherwise I very much welcome suggestions.
