### ISSUE TITLE
Widget and Trakt lIsts dont work

### ISSUE THREAD

**Issue by victorabogado** [jurialmunkey/skin.arctic.fuse#641]
### Skin section

Widgets

### Current Behavior

After the last update on Arctic Fuse, I can't add Trakt Lists. For example I try to add 80s Horror Trakt LIst after searching that list under Tmdb All and it doesn't add the widget. What am I doing wrong?

### Expected Behavior

It should include the widget 

### Steps To Reproduce

I go to tmdb all
then search the list with the search engine provided
i find the desired list, in this case I tried with 80s Horror and 1001 films before you die
the skin says it is creating the directory
but then nothing happens

 I am using classic layout btw

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
Debug log?

**Comment by victorabogado** [comment]
If youy tell me how I can do that I would be pleased to send it. but in the meanwhile I took some pics 
![1](https://github.com/jurialmunkey/skin.arctic.fuse/assets/29390729/b9a4fe80-5d8b-4292-b9f0-daa3aa2c2256)
![2](https://github.com/jurialmunkey/skin.arctic.fuse/assets/29390729/8346e928-9e7f-49be-89ac-2ab4f2d051bd)
![3](https://github.com/jurialmunkey/skin.arctic.fuse/assets/29390729/9cf13586-358e-488d-baca-3a231418bcc2)
![4](https://github.com/jurialmunkey/skin.arctic.fuse/assets/29390729/919538df-ad43-4ac3-b977-d4861449a0a3)
![5](https://github.com/jurialmunkey/skin.arctic.fuse/assets/29390729/df83c343-b300-4505-ada7-e03faaef7c3d)
![6](https://github.com/jurialmunkey/skin.arctic.fuse/assets/29390729/a061d30e-f97c-4298-aa8d-5a16cf32df92)
![7](https://github.com/jurialmunkey/skin.arctic.fuse/assets/29390729/a41abbed-4431-4465-8a0d-38aafcdf9121)
![8](https://github.com/jurialmunkey/skin.arctic.fuse/assets/29390729/42f12a24-9ac2-4a5e-9f7c-9b113433d84c)
![9](https://github.com/jurialmunkey/skin.arctic.fuse/assets/29390729/9758799f-d503-4526-b45a-8012ff3b315e)


Thanks

**Comment by victorabogado** [comment]
I figured it out, I had the problem, I reauthorized Trakt and it started to work fine. Thanks for your prompt answer and concern.
