### ISSUE TITLE
On screen way to navigate back to PiP video

### ISSUE THREAD

**Issue by Liquidrag** [jurialmunkey/skin.arctic.fuse#642]
### Skin section

Widgets

### Feature description

On screen way to navigate back to PiP video, maybe a fullscreen button somewhere as the PiP is playing?

### Why is this feature needed? Please justify and explain.

So we don't have to go all the way back to the home screen losing where we were at.

### Screenshots and Additional Info

<img width="1239" alt="Screen Shot 2024-03-25 at 6 33 24 PM" src="https://github.com/jurialmunkey/skin.arctic.fuse/assets/43726430/cb39c8c9-1c89-4bbd-93f3-27abf2b598b5">

### Checklist

- [X] I have made a separate issue for each feature I am requesting.
- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by Rinicko** [comment]
In customize widgets, go down to options. In Tile configuration you can change one of your tiles to Now playing.... Now whenever there is a PIP video, you can just go to your shutdownmenu and click on the Now playing tile.

Another way - If you have keymap editor addon... go into edit > then global > then system > then map a key to toggle fullscreen... then make sure to save. Now you can press that button whenever there is a PIP video to return to fullscreen

**Comment by Liquidrag** [comment]
> In customize widgets, go down to options. In Tile configuration you can change one of your tiles to Now playing.... Now whenever there is a PIP video, you can just go to your shutdownmenu and click on the Now playing tile.

Is there a way to add fullscreen to the options tray?

**Comment by Rinicko** [comment]
> > In customize widgets, go down to options. In Tile configuration you can change one of your tiles to Now playing.... Now whenever there is a PIP video, you can just go to your shutdownmenu and click on the Now playing tile.
> 
> Is there a way to add fullscreen to the options tray?

Yes,  but you'll need to add it yourself... I don't think the shortcut is there by default. 

Go into customize widget, go down to options, select the options tray, then click on new.... add any shortcut or add None... then change the action to togglefullscreen...

**Comment by Liquidrag** [comment]
> Yes, but you'll need to add it yourself... I don't think the shortcut is there by default.
> 
> Go into customize widget, go down to options, select the options tray, then click on new.... add any shortcut or add None... then change the action to togglefullscreen...

perfect! just needed fullscreen instead of togglefullscreen. Thank for the help!
