### ISSUE TITLE
✨️ Option to toggle combined widgets in some hubs and non combined in others

### ISSUE THREAD

**Issue by Rinicko** [jurialmunkey/skin.arctic.fuse#643]
### Skin section

Widgets

### Feature description

This is purely an for aesthetic or increased visual appeal. A toggle could be at the top in customize widgets, right beside complex/classic and local/global. This could read combined/vertical. This will allow the use of combined widgets in some hubs and vertical scrolling widgets in others

### Why is this feature needed? Please justify and explain.

There are some hubs/pages like my explore page or quick play page, where I feel the combined widget option will suit better, then there are others where I feel the vertical scroll will be better, but currently you can only choose one or the other, so adding this feature will give users more options in customizing their different hubs... Not sure how feasible this idea is to implement, but if it is something that could be done, please do consider. 

### Checklist

- [X] I have made a separate issue for each feature I am requesting.
- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by jurialmunkey** [comment]
Okay this was a good motivation to finally getting around to doing this. I have been meaning to do this for a while.

@adamosborne83 - This will interest you since I know you use this feature. Next version the combined widgets setting is per hub window and you can set toggle between stacked or combined in the widget customisation screen.

**Comment by adamosborne83** [comment]
> Okay this was a good motivation to finally getting around to doing this. I have been meaning to do this for a while.
> 
> @adamosborne83 - This will interest you since I know you use this feature. Next version the combined widgets setting is per hub window and you can set toggle between stacked or combined in the widget customisation screen.

Haha brilliant, I did read this earlier and thought, out of all the requests lately I hope you do this one. So thanks J and look forward to giving it a go.

**Comment by Liquidrag** [comment]
@jurialmunkey lol I was going to ask something similar. Would this allow the search hub to show all of the widgets instead of having to select each individual one?

**Comment by Rinicko** [comment]
> Okay this was a good motivation to finally getting around to doing this. I have been meaning to do this for a while.
> 
> @adamosborne83 - This will interest you since I know you use this feature. Next version the combined widgets setting is per hub window and you can set toggle between stacked or combined in the widget customisation screen.

Amazing 🙌

Thank you very much... I'm sure a lot of users would appreciate this feature

**Comment by Rinicko** [comment]
> @jurialmunkey lol I was going to ask something similar. Would this allow the search hub to show all of the widgets instead of having to select each individual one?

I don't think so... The search hub individual search was done for speed, to make Kodi load directly into what you're searching for rather than sorting through all your search paths.... If the combined widget was used, I'm pretty sure it will start sorting through all the search paths again, which will slow it down again.

**Comment by Liquidrag** [comment]
@Rinicko damn, I don't mind the loading times if it makes navigating easier. I had no issues searching in AH2.

**Comment by adamosborne83** [comment]
> Okay this was a good motivation to finally getting around to doing this. I have been meaning to do this for a while.
> 
> @adamosborne83 - This will interest you since I know you use this feature. Next version the combined widgets setting is per hub window and you can set toggle between stacked or combined in the widget customisation screen.

Absolute brilliant. 
Next time, be motivated sooner 😀

**Comment by jurialmunkey** [comment]
> > I actually prefer this search window to the one on Horizon.
> 
> I'll have to get used to it, I still think having the option for all to load in a list of widgets would be easier.

@Liquidrag - I've got a feature coming very soon that I think you will like in this case.

Basically, it is a version of the explore/next-aired type windows but with search widgets. It will be able to be used ondown in the same way as explore (or linked as a shortcut) and will pop-up a keyboard on entry to enter search term.

Then after entering search terms you can either scroll through, return up to exit, or use a button on the side to enter a new search. Just a really minimal "pure" search window with nothing else.

If it works out well, it might be a stepping stone to having search directly on home screen.

**Comment by Liquidrag** [comment]
> @Liquidrag - I've got a feature coming very soon that I think you will like in this case.

I'm excited to try it out!
