### ISSUE TITLE
:sparkles: Loading option

### ISSUE THREAD

**Issue by ProArtix** [jurialmunkey/skin.arctic.fuse#648]
### Skin section

Other

### Feature description

Could you make an option so that until a plugin is started, it does not exit the skin loading screen?

### Why is this feature needed? Please justify and explain.

It is a good option for people whose skin is stuck because the skin loads before the plugin.

### Checklist

- [X] I have made a separate issue for each feature I am requesting.
- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by adamosborne83** [comment]
This is already a setting. I'm not at my TV atm, but believe, skin settings, expert, splash wait for plugin. 
Something like that anyway... someone will defo give you the right setting, or I will when I can.

**Comment by vella9** [comment]
you can find this in expert>hide widget initilisation behind splash. Note that this works if you have a spotlight configured.

**Comment by ProArtix** [comment]
So it would be good if that option could be added with the skin in classic mode

**Comment by vella9** [comment]
indeed. once spotlight is added to classic mode, hopefully, this will be available by default

**Comment by jurialmunkey** [comment]
Yes this is only possible for spotlights because I need a fixed id to check, whereas other widgets have dynamically generated ids. otherwise it might get stuck on forever because first widget I'd might be hidden depending on first focus.
