### ISSUE TITLE
default side menu focus doesn't work

### ISSUE THREAD

**Issue by Aemstel2** [jurialmunkey/skin.arctic.fuse#650]
### Skin section

Widgets

### Current Behavior

In home menu when you have only two items in the sidemenu it seems to always focus on the second item by default, even if the first one is set as default.

### Expected Behavior

Focus the first item if that is set as default.

### Steps To Reproduce

1. Have only two items in side menu. (I disabled "Home")
2. Set the first item as default
3. Load or reload the skin
4. Notice that second item is always focused as default

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
Was already fixed in this commit for next update: https://github.com/jurialmunkey/skin.arctic.fuse/commit/ad236aad75a05bf81f24bb60c9ca5e08b62c463c

**Comment by Aemstel2** [comment]
I just tried v0.6.4 and it still keeps defaulting to the second item even though the first item is set as default.

**Comment by jurialmunkey** [comment]
Do you have disabled items? They will throw off the positioning.

**Comment by Aemstel2** [comment]
Yes, I disabled "Home". When moving the disabled items to the bottom it seems to work.
