### ISSUE TITLE
Search mode broken on Latest update 

### ISSUE THREAD

**Issue by JFG1000** [jurialmunkey/skin.arctic.fuse#651]
### Skin section

Widgets

### Current Behavior

Hey jurial can no longer change mode from discover to search mode on latest update, nothing happens when we select the box to change 

### Expected Behavior

Usually we click mode to change etc 

### Steps To Reproduce

Bring up search dialogue
Click mode
Select search mode 

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
When you say latest update, what version are you referring to?
