### ISSUE TITLE
Cannot move from menu icon in Movies and TV taps

### ISSUE THREAD

**Issue by taiseer999** [jurialmunkey/skin.arctic.fuse#652]
### Skin section

Widgets

### Current Behavior

Indicator gets stuck at the menu icon and cannot browse content of anything other than Home and Addons

https://github.com/jurialmunkey/skin.arctic.fuse/assets/118752825/929517e7-6da3-4d75-8f99-5b412afa355a

### Expected Behavior

To function as expected 

### Steps To Reproduce

Click to select any side menu item from Home
Selector gets stuck at the menu icon 

### Screenshots and Additional Info

https://github.com/jurialmunkey/skin.arctic.fuse/assets/118752825/ec22f1f9-30fa-46f9-a0bd-4b79dc15faec

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by Rinicko** [comment]
This happened to me too, It happens when there is no spotlight while using a complex layout after recent update.
