### ISSUE TITLE
"new" simplified search page navigation issue

### ISSUE THREAD

**Issue by vella9** [jurialmunkey/skin.arctic.fuse#653]
### Skin section

Widgets

### Current Behavior

I am having an issue with the "new" simplified search page, the one similar to AH2 on 0.6.4. I cannot navigate to the widgets after typing in the search box. Up works fine and takes you back to the widgets screen but down, right and left (after scrolling through the characters) does nothing.

### Expected Behavior

should be able to go down to the widget items for either Movies or TV Shows.

### Steps To Reproduce

go to the "new" search page
type a movie/TV show
try to navigate to the Movies/TV Shows widgets

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by vella9** [comment]
nevermind this jurial, sorted it by resetting the search widgets to default. recent changes are amazing and skin is looking fabulous. thank you as always!

**Comment by L0bsang** [comment]
> nevermind this jurial, sorted it by resetting the search widgets to default. recent changes are amazing and skin is looking fabulous. thank you as always!

Good tip! Wouldn't have thought of trying this.

**Comment by xyzfre** [comment]
![image](https://github.com/jurialmunkey/skin.arctic.fuse/assets/49699869/1cea503f-6bed-403a-b7a4-f9f8e25dd8a7)

**Comment by xyzfre** [comment]
![image](https://github.com/jurialmunkey/skin.arctic.fuse/assets/49699869/acbf9158-bc08-4d39-acc6-f22f05ebde16)

**Comment by xyzfre** [comment]
![image](https://github.com/jurialmunkey/skin.arctic.fuse/assets/49699869/3e9546a6-09c8-4d56-8b17-56c8c8f6ccc4)

**Comment by xyzfre** [comment]
> > nevermind this jurial, sorted it by resetting the search widgets to default. recent changes are amazing and skin is looking fabulous. thank you as always!
> 
> 
> 
> Good tip! Wouldn't have thought of trying this. Now just need to find the fen search paths again haha.

Here you go
