### ISSUE TITLE
:bug: No access to settings and power menu

### ISSUE THREAD

**Issue by pgranat** [jurialmunkey/skin.arctic.fuse#658]
### Skin section

Widgets

### Current Behavior

In previous releases I went down with widgets and there I had options tray. There I can choose menu, settings or some other things. Now going down is triggering search and I have no possibility to access settings or power menu. In widgets configurations I still can configure options tray but I see no possiblity to access it. Found workaround to access settings via clicking some folder I have in my favorites widget, and then menu. I have categories view.

### Expected Behavior

Possibility to access power menu and options somehow 

### Steps To Reproduce

1. Set categories view
2. Set up some widgets
3. Try to access settings

### Screenshots and Additional Info

https://github.com/jurialmunkey/skin.arctic.fuse/assets/11504961/66207ef3-97b2-4281-86f8-ed97e6a2e277

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by vella9** [comment]
hold the back button to access powermenu

**Comment by Omarscomin** [comment]
Skin settings  → Navigation  →  Set "Content > Down" to "Options"

**Comment by pgranat** [comment]
Thanks. Indeed both options works

**Comment by Ade-AV** [comment]
Holding Back on Apple TV exits to Apple TV menu and setting Content Down to Options is a Catch-22

**Comment by jurialmunkey** [comment]
> Holding Back on Apple TV exits to Apple TV menu and setting Content Down to Options is a Catch-22

Or you could press info. Or you could set a shortcut. Or you could remap a button on your remote. Or you can use the option to access the menu on left. There are so many ways you could access the menu.
