### ISSUE TITLE
Network logos overlapping content in widgets

### ISSUE THREAD

**Issue by Omarscomin** [jurialmunkey/skin.arctic.fuse#659]
### Skin section

Widgets

### Current Behavior

Network logos from spotlight are currently overlapping content within widgets in side menu sections

### Expected Behavior

For spotlight network logos to not overlap content within widgets

### Steps To Reproduce

1. Create a section on your side menu. Set widget layout to "complex."
3. Create a widget in said section that has a submenu list. Set the style to "card."
4. Set a spotlight widget for said section
5. Set the skin layout to "compound"

### Screenshots and Additional Info

![Kodi_20240329_050025](https://github.com/jurialmunkey/skin.arctic.fuse/assets/129215684/dc468298-299f-49fe-a8c3-c89eb878bd66)

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
Should be resolved in next version with updates to how widget fadeout is managed.
