### ISSUE TITLE
PVR Guide and Channel issues

### ISSUE THREAD

**Issue by Blackysbd** [jurialmunkey/skin.arctic.fuse#663]
### Skin section

PVR and Live TV

### Current Behavior

I cannot get media to show within the guide although it does show on widgets.
When using Channels and selecting channel guide there is on overlap of widget and nothing can be seen or read.

### Expected Behavior

Media should show in guide and channel info should be readable.

### Steps To Reproduce

1. Go to tv guide
2. Click on view channels
3. Select channel guide

### Screenshots and Additional Info

![widget](https://github.com/jurialmunkey/skin.arctic.fuse/assets/53400821/028ec99a-9e9e-4cf2-be77-29ff53513b8e)
![guide](https://github.com/jurialmunkey/skin.arctic.fuse/assets/53400821/39f2ec04-4401-4799-837a-0be1621756ee)
![channels](https://github.com/jurialmunkey/skin.arctic.fuse/assets/53400821/4710a25c-3497-4cba-95ce-a31cb41ecf73)

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
I only ever use this dialog from video osd. I completely forgot it is possible to open it from channels window.
