### ISSUE TITLE
✨️ Option to toggle on and off labels in options tray

### ISSUE THREAD

**Issue by CyberRooke** [jurialmunkey/skin.arctic.fuse#664]
### Skin section

Widgets

### Feature description

A toggle could be in appearance or furniture. Clicking it will turn of labels and revert it to the way it was before

### Why is this feature needed? Please justify and explain.

It's more of a preference thing... I don't think the labels in the options tray look good at all. The highlighter overlaps the label when the item name is long... It also somehow looks more confusing than without labels for me... In the shutdown menu,  it feels like too much text in one dialogue. I tried using blank text to avoid having to bother you with this but even then the icons are moved up and the highlighter still highlights the blank text, which will just be an empty space.

I understand someone requested this feature and it may be useful to other users but I think a toggle to switch it on and off will be good.

### Checklist

- [X] I have made a separate issue for each feature I am requesting.
- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by woodside007** [comment]
+1

**Comment by vella9** [comment]
+1

**Comment by jurialmunkey** [comment]
Sorry, it was meant to be optional. I jumped the gun a bit with pushing the update.

**Comment by vella9** [comment]
nothing to be sorry about jurial. thank you 🙏
