### ISSUE TITLE
✨️ Option to toggle on and off information in footer of landscape widgets 

### ISSUE THREAD

**Issue by CyberRooke** [jurialmunkey/skin.arctic.fuse#665]
### Skin section

Widgets

### Feature description

Could there be an option in the furniture that allows you to toggle off information for landscape widget

### Why is this feature needed? Please justify and explain.

I know board is landscape without the text but in some areas board is too big to use... Board style is kind of in your face, I think it's okay for explore page but not for homepage. If it's doable could we get an option to switch off the information in landscape widget as sometimes it displays double information like the title, which is already on the widget (shown in attached image) or the genre, which is already in the info line. 

Just for your consideration 🙏🙏
![Screenshot_20240330-102341](https://github.com/jurialmunkey/skin.arctic.fuse/assets/162068678/6c701714-a88e-4477-9ca9-3bf81ae349d3)

### Checklist

- [X] I have made a separate issue for each feature I am requesting.
- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by L0bsang** [comment]
> I know board is landscape without the text but in some areas board is too big to use... Board style is kind of in your face, I think it's okay for explore page but not for homepage. If it's doable could we get an option to switch off the information in landscape widget as sometimes it displays double information like the title, which is already on the widget (shown in attached image) or the genre, which is already in the info line.

While more options in a skin is nice in general, it can lead to skin settings becoming overly complicated/complex.

For your screenshot, usually the video addon provides a setting to control the title display, which you can use to avoid the repeated title. TMDBHelper widgets by default do not display the TV show title in episode titles, same with episodes in the library. 
Genre is also something that is not always present in the infoline, personally I use "ends at" to know if I have enough time to start watching something, so then genre in landscape becomes useful.

**Comment by CyberRooke** [comment]
I get what you're saying... most of the feature requests I make are really just personal preference.. But it's hard to think of any real justification sometimes, so I just end up trying to think of some to make a case for the feature you know... 

I never meant to imply that it's a general concern or anything... There's really no way for me to tell... I can only assume

**Comment by CyberRooke** [comment]
> > I know board is landscape without the text but in some areas board is too big to use... Board style is kind of in your face, I think it's okay for explore page but not for homepage. If it's doable could we get an option to switch off the information in landscape widget as sometimes it displays double information like the title, which is already on the widget (shown in attached image) or the genre, which is already in the info line.
> 
> While more options in a skin is nice in general, it can lead to skin settings becoming overly complicated/complex. I'm not against this feature being added. Personally I like text on everything, i even add text to board style, but I can understand people wanting plain pictures with nothing on them or a smaller board style.
> 
> But the reasons you have given I have objections to.
> For your screenshot, usually the video addon provides a setting to control the title display, which you can use to avoid the repeated title. TMDBHelper widgets by default do not display the TV show title in episode titles, same with episodes in the library.
> Genre is also something that is not always present in the infoline, personally I use "ends at" to know if I have enough time to start watching something, so then genre in landscape becomes useful, and also in exploration widgets.
> 
> Same as that other request where you say no one on shield would uses quit instead of just pressing home. Untrue. Quit is the cleanest way to properly close and refresh kodi on android, going home or closing it from the open apps tray has caused me issues in the past.

I know TMBD will have better options for widget labels... but I use Fen because it's faster to play things, especially for continuing episodes.... I know genre can be removed from infoline, but If I do that then what will happen with Spotlight... it'll take the genre off there, too. The screenshot was just one example... my main reason is that the board view is too big for episodes. It doesn't really look nice.

The other request I said quit is not often used by shield users, I was just assuming... there's no way for me to know, I could think of any other way to make the case for it. But now that it's done, you can have quit, I can have reload, some other user can have their favorite addon or any other shortcut... Isn't customization always better.

**Comment by Ade-AV** [comment]
Smaller sized Board would be good

**Comment by jurialmunkey** [comment]
Resolved with option to switch to board style widgets (then use Apps for smaller size without labels)
