### ISSUE TITLE
Fanart jumps back.

### ISSUE THREAD

**Issue by adamosborne83** [jurialmunkey/skin.arctic.fuse#668]
### Skin section

Widgets

### Current Behavior

Morning J,
Apologies as if you blink in the videos you'll miss it. Towards the end of each video, I will scroll past a movie, then fanart will flash up for a second and then revert back to the previous movie fanart.

This has only recently happened.
Don't know if this is a skin or kodi issue?

If it makes a difference all my movies are library not through any addon.

### Expected Behavior

Fanart to be correct movie 

### Steps To Reproduce

Library Films
List Media view
Scroll down

### Screenshots and Additional Info

https://github.com/jurialmunkey/skin.arctic.fuse/assets/78307374/d8fc820d-dabb-4fe8-bf5d-b808f657a05d

https://imgur.com/a/NapfIKk

Https://paste.kodi.tv/ipibonozuz

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by adamosborne83** [comment]
Please excuse the Umbrella errors un the log, I've fixed that issue.
I can confirm it still happens too.

**Comment by jurialmunkey** [comment]
What background settings? If it's real blur probably a TMDbHelper issue with it not keeping up properly and still processing previous item. Best way to test is to switch background to either "Simple" or "Fake Blur" and see if the issue is still there

Fairly likely to be TMDbHelper though -- sometimes the previous item artwork thread gets stuck and there's a bit of a race with the next item which is an issue I know about.

**Comment by adamosborne83** [comment]
> What background settings? If it's real blur probably a TMDbHelper issue with it not keeping up properly and still processing previous item. Best way to test is to switch background to either "Simple" or "Fake Blur" and see if the issue is still there
> 
> Fairly likely to be TMDbHelper though -- sometimes the previous item artwork thread gets stuck and there's a bit of a race with the next item which is an issue I know about.

Yes, I use real blur.
Just tried Fake Blue, and can confirm it no longer happens.
I'll close this issue as its related to TMDBh and you're already aware.

As a side note, last couple updates been awesome. Especially the ability to customise icons on the left, and more importantly when I now start kodi, it defaults to full screen spot light.
Both seen in pic.


Cheers

![firetv_2024-04-01_10_52_23.jpg](https://github.com/jurialmunkey/skin.arctic.fuse/assets/78307374/57b51021-5578-406c-951a-9f4291508eb3)

**Comment by jurialmunkey** [comment]
@adamosborne83 did you turn on extra fanart? Because that will make it significantly worse (I should have tagged that experimentally because extra fanart is a massive hack and will be pretty buggy).

**Comment by adamosborne83** [comment]
> @adamosborne83 did you turn on extra fanart? Because that will make it significantly worse (I should have tagged that experimental because extra fanart is a massive hack and will be pretty buggy).
> 
> I haven't really changed anything in how the background is handled, so there isn't really any reason for it to start being worse - it's really something that should only happen very occasionally with new uncached artwork.
> 
> Extra fanart is the only thing I can think of that would be causing it a lot. 

Cheers J, after a quick play this morning prior to work, this seems to have fixed it 
I didn't think it was anything to do with the image cache, as I have an addon the pre cache all images in my library.
I didn't even realised I had clicked extra fanart, as when I read about it, I didn't find a need.

Thanks as always.

**Comment by xyzfre** [comment]
> @adamosborne83 did you turn on extra fanart? Because that will make it significantly worse (I should have tagged that experimental because extra fanart is a massive hack and will be pretty buggy).
> 
> 
> 
> I haven't really changed anything in how the background is handled, so there isn't really any reason for it to start being worse - it's really something that should only happen very occasionally with new uncached artwork.
> 
> 
> 
> Extra fanart is the only thing I can think of that would be causing it a lot. 

Thank you @jurialmunkey for this info very interesting to know about the extra fanart
