### ISSUE TITLE
🐛 Icon view coming up as Landscape 

### ISSUE THREAD

**Issue by CyberRooke** [jurialmunkey/skin.arctic.fuse#669]
### Skin section

Widgets

### Current Behavior

The widgets that are in icon view are appearing as landscape...  same with when I tried app view

### Expected Behavior

The icon view widget should be small icons

### Steps To Reproduce

Create a widget
Set style to Icon view

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
Do you have the footer enabled?

Small size widgets are incompatible with the footer.

**Comment by CyberRooke** [comment]
> Do you have the footer enabled?
> 
> Small size widgets are incompatible with the footer.

😟😟😰😰 Damn... I do have the footer enabled... But it's been working ever since, why the sudden change? 🤔

**Comment by jurialmunkey** [comment]
Because it is breaks the fade conditions and causes this issue: #659

Different sized widgets are difficult to manage, which is also why I'm hesistant about landscape with no labels. The second size is hard enough to deal with without adding a third into the mix.

**Comment by CyberRooke** [comment]
> Because it is breaks the fade conditions and causes issue similar to this one #659 (not exactly the same but same concept).
> 
> Different sized widgets are difficult to manage, which is also why I'm hesistant about landscape with no labels. The second size is hard enough to deal with without adding a third into the mix.

I see... this is a sad one 🤧. I don't even use the footer for any information, I just like every widget having its own space...

This means anyone who turns footer on can only have 1 size of widget to work with or 2 including banner... 

No worries, though... I'll use whatever is available... but please don't let this go quickly 🙏... Surely, there must be a way. If landscape with no labels is an issue, that can be closed... but having to choose between icons, which my entire setup is built upon, or footer widget, literally my favorite feature... that's tough

**Comment by jurialmunkey** [comment]
> This means anyone who turns footer on can only have 1 size of widget to work with or 2 including banner...

There are five: Card, Poster, Banner, Landscape, Board, Square.

> No worries, though... I'll use whatever is available... but please don't let this go quickly

Honestly these smaller widgets are a huge thorn in my side. I constantly am thinking about removing them entirely because of how much more complicated they make the skin code to manage regardless of footer or not.

**Comment by CyberRooke** [comment]
> > This means anyone who turns footer on can only have 1 size of widget to work with or 2 including banner...
> 
> There are six: Card, Poster, Banner, Landscape, Board, Square.
> 

I meant the overall size... Isn't Landscape same size as board due to labels... forgot about poster and card... I thought square was icons with text🤔

> > No worries, though... I'll use whatever is available... but please don't let this go quickly
> 
> Honestly these smaller widgets are a huge thorn in my side. I constantly am thinking about removing them entirely because of how much more complicated they make the skin code to manage regardless of footer or not.
> 
> All the animations are broken and they are incredibly hacky to get the position correct in the grouplist.

I see... I never knew they were this complicated...

**Comment by CyberRooke** [comment]
> Honestly these smaller widgets are a huge thorn in my side. I constantly am thinking about removing them entirely because of how much more complicated they make the skin code to manage regardless of footer or not.
> 
> All the animations are broken and they are incredibly hacky to get the position correct in the grouplist.


I have switched all my icons to Square, and I honestly prefer having the title labels for the icons, and I don't think I'll switch back even if icons become compatible.... Since this is complicated to pull off... I'll just close this issue to save you the trouble...
