### ISSUE TITLE
[BUG] Incorrect header title in Custom Hub

### ISSUE THREAD

**Issue by AakashC2020** [jurialmunkey/skin.arctic.fuse#67]
### Skin section

Other

### Current Behavior

Hi @jurialmunkey,

I've modified the Music Hub and made it an Anime Hub. After that I've used Custom Hub and used the modified Music Hub for my Anime Hub. I've then labelled the Custom Music Hub as Anime. However, the Header title within the Hub is still showing as Music instead of Anime. Could you please fix this issue so that the Custom Hub will show the title of the Label used?

### Expected Behavior

The Custom Hub header title should show the correct title used in the Label.

### Steps To Reproduce

As described.

### Screenshots and Additional Info

![IMG20230802210238](https://github.com/jurialmunkey/skin.arctic.fuse/assets/65297828/4a656c6a-0b31-45ad-a3be-39c30680e4bc)

![IMG20230802210246](https://github.com/jurialmunkey/skin.arctic.fuse/assets/65297828/272c63fa-7e23-4bc9-8cd3-5b14c86e7ffd)

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
Duplicate #43

**Comment by AakashC2020** [comment]
Hi @jurialmunkey, sorry for creating this duplicate issue ticket. I couldn't find that there was already an existing request for this. I'll follow issue ticket #43 regarding updates on this request.
