### ISSUE TITLE
:sparkles: option to give a delay so you can start a plugin before the skin

### ISSUE THREAD

**Issue by ProArtix** [jurialmunkey/skin.arctic.fuse#670]
### Skin section

Widgets

### Feature description

You can add an option to give a delay of 10/20/30 seconds and keep it on the loading screen without loading the widgets so that it gives time to load the plugins (the plugin that I use causes Kodi to close, why does the skin wants to load the widgets before they are available in the original plugin and crashes) a developer section or something like that would be nice to add those extra options, just as it would be nice to be able to add a line of code to run when the skin starts (ahem : RunPlugin(....) and add a 20 second delay so that all this is done automatically when starting kodi)

PD: The option of waiting for the addons that are already implemented to start does not work for what I say, it keeps crashing

### Why is this feature needed? Please justify and explain.

Extra options that would be very useful for people who use plugins and do not have time for them to load on time because they first try to load the widgets and because of that Kodi crashes

### Checklist

- [X] I have made a separate issue for each feature I am requesting.
- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by jurialmunkey** [comment]
Use a login screen.

```
Skin Settings > Expert > Individual skin user configurations (Enable)
Skin Settings > Expert > Skin user login screen on startup (Enable)
```

Now the skin will not start until you click on the user profile to open it.
