### ISSUE TITLE
Bug concerning the behavior of the return key within the Search Hub

### ISSUE THREAD

**Issue by Bindou01** [jurialmunkey/skin.arctic.fuse#675]
### Skin section

Other

### Current Behavior

The return key does not behave correctly.  When clicking on a word in the history directly after entering the Hub, the back key does not return to the results (does not close the pane) of the search, but directs the output of the Hub directly to the output.  

### Expected Behavior

This should close the pane and access the search result.

### Steps To Reproduce

Open the Search Hub -> click on one of the words in the history to start the search -> press return.

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
I cannot override back key behaviour in the edit control. It is forced by kodi to be backspace. Not possible to change.

**Comment by jurialmunkey** [comment]
> What is surprising is that if you press a letter on the keyboard rather than a word from the history, this time, the return key will close the shutter. 

Pressing back from either search history or the letters will do exactly the same thing.

What I cannot change is the behaviour of the input edit box. When you click a search term, it must focus the edit box to input the search term into the box. Pressing back there Kodi treats as backspace.
