### ISSUE TITLE
✨️ Option to toggle off indicators 

### ISSUE THREAD

**Issue by CyberRooke** [jurialmunkey/skin.arctic.fuse#679]
### Skin section

Widgets

### Feature description

There could be a toggle in the appearance or furniture section, this will allow you to togghle off and on the direction indicators. 

### Why is this feature needed? Please justify and explain.

In the recent update there are up and down indicators in the pages as well as spotlight and categories indicators... The categories indicators pushes the spotlight upwards and takes part of the full screen away and the up and down indicators are not really needed on my part... would be nice to switch them off.

### Checklist

- [X] I have made a separate issue for each feature I am requesting.
- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by jurialmunkey** [comment]
You can switch off by disabling touch mode

**Comment by CyberRooke** [comment]
> You can switch off by disabling touch mode

Oh, okay then 👍👍
