### ISSUE TITLE
🐛 Footer and next text overlap in search 

### ISSUE THREAD

**Issue by CyberRooke** [jurialmunkey/skin.arctic.fuse#680]
### Skin section

Widgets

### Feature description

Can we get the option to toggle off the highlighted footer text that reads out the kodi version along with kodi name. It normally would only come on when you switch off widgets.. After recent update,  it is there when category is highlighted and in the search window as well.

### Why is this feature needed? Please justify and explain.

It overlaps the other footer when in the search window... shown in pictures. I also don't think it looks visually appealing...
![Screenshot_20240403-172204](https://github.com/jurialmunkey/skin.arctic.fuse/assets/162068678/a1ebc3a6-88eb-4592-9b2e-516bace724d7)

### Checklist

- [X] I have made a separate issue for each feature I am requesting.
- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by jurialmunkey** [comment]
This is a bug.
