### ISSUE TITLE
Group widget for PVR

### ISSUE THREAD

**Issue by Priesy** [jurialmunkey/skin.arctic.fuse#684]
### Skin section

Widgets

### Feature description

Would it be possible to add a Channel group widget to pvr/live tv
It existed in AH2 but I can't get it to display in Fuse

### Why is this feature needed? Please justify and explain.

Better navigation of PVR section

### Checklist

- [X] I have made a separate issue for each feature I am requesting.
- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by Ade-AV** [comment]
Take a look at the Last Played widget, if you remove the '*' from Action ```pvr://channels/tv/*``` then it becomes a Group widget
