### ISSUE TITLE
Problem with chapter thumbnails and bookmarks.

### ISSUE THREAD

**Issue by Bindou01** [jurialmunkey/skin.arctic.fuse#686]
### Skin section

Video OSD

### Current Behavior

Hello Jurial, I notice some small problems with the chapter and bookmark thumbnails in the player's OSD.  When you move down a notch in the player OSD : 
1. The pointer moves one notch too low.  It is positioned on the + (add), rather than on the thumbnails.  
2. Chapters do not have thumbnails.  
3. When you click on one of these empty thumbnails, it crashes the player.

 I'm surprised to be the only one reporting this problem.  However, I can't get precise information on the forum to determine if this really comes from Fuse or elsewhere. 

 Thanks again for everything Jurial.

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
Make sure you don't have the same issue in Estuary because these all work perfectly fine for me. Also starting focus on the add button is necessary in case you don't have any chapters or bookmarks because otherwise you would get stuck with no focus.

![screenshot00492](https://github.com/jurialmunkey/skin.arctic.fuse/assets/4618719/648b8f12-d451-4ccb-8d5b-a3310457e417)

![screenshot00494](https://github.com/jurialmunkey/skin.arctic.fuse/assets/4618719/8e331d59-fe2e-467e-9ad1-c52f4e62730a)

**Comment by Bindou01** [comment]
Of course, I tested on Estuary, on Horizon 2, and it works perfectly everywhere else.  But here on Fuse, it crashes.  I don't understand.

**Comment by jurialmunkey** [comment]
The artwork works in Estuary but not Fuse?

The focus is correct on add. It always focuses because it is the default control.

Reinstalling the skin will do nothing. The skin code will still be the same skin code no matter how many times you install it.

**Comment by Bindou01** [comment]
> The artwork works in Estuary but not Fuse?
> 
> The focus is correct on add. It always focuses because it is the default control.
> 
> Reinstalling the skin will do nothing. The skin code will still be the same skin code no matter how many times you install it.

I take back what I said, I looked at it wrong.  It works perfectly on Horizon 2, but not on Estuary or Fuse.  I don't understand why.  Sorry for bothering you, turns out it's not Fuse related then.
