### ISSUE TITLE
[BUG] Completed movies not showing circular watched mark

### ISSUE THREAD

**Issue by AakashC2020** [jurialmunkey/skin.arctic.fuse#69]
### Skin section

Home Widgets

### Current Behavior

Hi @jurialmunkey,

When a movie has been watched completely it's only showing the green tick mark and not the full circle green watched mark. For TV shows it's working perfectly. See screenshots.

### Expected Behavior

Completed movies should show the full circle green watched mark.

### Steps To Reproduce

Go to any watched movie in a widget and check its watched mark.

### Screenshots and Additional Info

For Movies:

![IMG20230802234425](https://github.com/jurialmunkey/skin.arctic.fuse/assets/65297828/5c969a7f-e441-495b-94a9-76285b63d0c6)

![IMG20230802234225](https://github.com/jurialmunkey/skin.arctic.fuse/assets/65297828/ab2d691f-5c90-443f-8150-b5e3f7649126)

For TV Shows:

![IMG20230802234242](https://github.com/jurialmunkey/skin.arctic.fuse/assets/65297828/ae34e847-3db0-4946-8121-3797df917eaf)

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
I can't reproduce. It's working fine for me for watched movies in widgets on home and in media window both from Library and TMDbHelper

![screenshot00113](https://github.com/jurialmunkey/skin.arctic.fuse/assets/4618719/591f0574-55d1-48d0-9550-d869042794d8)

![screenshot00112](https://github.com/jurialmunkey/skin.arctic.fuse/assets/4618719/145bd321-b438-409c-9480-a4fd0c8caced)

![screenshot00111](https://github.com/jurialmunkey/skin.arctic.fuse/assets/4618719/c9424cba-3e29-4467-a8b0-dac7a225e240)

**Comment by jurialmunkey** [comment]
That's really strange. Displays perfectly fine for me via TMDbHelper.

Are you using Trakt to provide watched status or just Kodi?

**Comment by AakashC2020** [comment]
> That's really strange. Displays perfectly fine for me via TMDbHelper.
> 
> Are you using Trakt to provide watched status or just Kodi?

I'm using Trakt completely, not Kodi at all.

**Comment by AakashC2020** [comment]
Hi @jurialmunkey,

The latest update has fixed this issue. Thank you so much! Please see screenshots below.

![IMG20230803223821](https://github.com/jurialmunkey/skin.arctic.fuse/assets/65297828/4a1fa945-26ce-4367-b2fc-77b06a26b6ec)

![IMG20230803223903](https://github.com/jurialmunkey/skin.arctic.fuse/assets/65297828/abefb85d-3007-41be-88f3-af383195d9a3)
