### ISSUE TITLE
:sparkles: Configurable behaviour for TV shows in "In-Progress Shows" widget on click

### ISSUE THREAD

**Issue by cavalrymargarine0x1** [jurialmunkey/skin.arctic.fuse#691]
### Skin section

Widgets

### Feature description

An option to set the behaviour when clicking on TV shows that are in the "In-Progress TV shows" list on the Home page.

Available behaviour options would be:

- Continue Watching
- Browse Into

### Why is this feature needed? Please justify and explain.

As of right now, the default behaviour is browsing into in-progress TV shows on click. 

To continue watching a show, as in start watching the next unwatched episode, you have to bring up the context menu for said show.

Adding an option to set the behaviour for in-progress TV shows on click would allow people who want to directly start watching the next unwatched episode of TV shows to do so without having to open the context menu.

### Checklist

- [X] I have made a separate issue for each feature I am requesting.
- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by xyzfre** [comment]
Have you tried creating a widget with in progress Episodes, it picks up right were you left off.

**Comment by cavalrymargarine0x1** [comment]
> Have you tried creating a widget with in progress Episodes, it picks up right were you left off.

Yes I've tried that but it's not what I'm requesting. 

My request would result in being able to start Kodi with Arctic Fuse and directly start watching the next unwatched episode of TV shows by clicking a show in "In-Progress TV shows", bypassing the context menu > "Continue Watching". 

Compared to resuming an already started episode which is what the in-progress episodes skin playlist does. 

Thanks anyway for the suggestion :)

**Comment by jurialmunkey** [comment]
The skin doesn't control what happens when you select an item. This is controlled by kodi. It is a bad idea to override as otherwise the skin will not honour the default select action people choose in their settings.

Even if I wanted to override, there is no "continue watching" action to use
https://kodi.wiki/view/Action_IDs
