### ISSUE TITLE
Audio osd automatically closes 

### ISSUE THREAD

**Issue by JFG1000** [jurialmunkey/skin.arctic.fuse#694]
### Skin section

Video OSD

### Current Behavior

When bringing up the video osd and navigating over the audio offset settings the osd automatically closes, I've got a log here if it helps

https://paste.kodi.tv/uguvotezob

Running Omega and nvidia shield 

### Expected Behavior

When navigating audio offset etc we should be able to amend the setting

### Steps To Reproduce

Bring up video osd, navigate to Audio settings, highlight audio offset

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
^^^ Should fix it (assuming it is caused by osd autoclose timer).

**Comment by JFG1000** [comment]
Thankyou mate much appreciated
