### ISSUE TITLE
Bump on combined

### ISSUE THREAD

**Issue by adamosborne83** [jurialmunkey/skin.arctic.fuse#695]
### Skin section

Widgets

### Current Behavior

Hi J, hopefully as the video shows, as I scroll on the combined, I would expect it to loop and not bump.
Regardless though it seems to jump back to the spotlight too at times.

### Expected Behavior

Personally I would prefer loop

### Steps To Reproduce

Create combined
Scroll along
Then bumps or jumps to spotlight. 

### Screenshots and Additional Info

https://github.com/jurialmunkey/skin.arctic.fuse/assets/78307374/59e1c6b9-fe1a-425e-892a-cc196d876c62

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
Was debating this myself. Easy to change since I left the code I kept flip-flopping on commented out.
