### ISSUE TITLE
Widget titles flicker 

### ISSUE THREAD

**Issue by adamosborne83** [jurialmunkey/skin.arctic.fuse#697]
### Skin section

Widgets

### Current Behavior

Sorry J, as you know I hate to moan (too much)
If you see the video you'll see that the widget titles seem to flicker

### Expected Behavior

Streamless motion as before

### Steps To Reproduce

See video

https://github.com/jurialmunkey/skin.arctic.fuse/assets/78307374/06190f8b-9f33-40a6-93ce-08df8bf16bc2

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by xyzfre** [comment]
I noticed the same behavior on my end. Looks like if the letters flicker.

**Comment by xyzfre** [comment]
https://github.com/jurialmunkey/skin.arctic.fuse/assets/49699869/740933da-8916-4fc5-a148-46ec6a8c0d50
