### ISSUE TITLE
💬 Discussion - Spotlight labels and Categories spacing

### ISSUE THREAD

**Issue by adamosborne83** [jurialmunkey/skin.arctic.fuse#698]
### Skin section

Widgets

### Feature description

As always, apologies for the vague title. I have noticed there seems to be a larger gap between title menu and widget. Is it possible to decrease this of no sub menu is set?

### Why is this feature needed? Please justify and explain.

I know the layout of Fuse is very specific, so if it means too much code change no worries, just visual aesthetic. 

### Screenshots and Additional Info

As always a video to show....

https://github.com/jurialmunkey/skin.arctic.fuse/assets/78307374/4bcb35a6-73b1-431c-9b7c-2a9a72578f3b

### Checklist

- [X] I have made a separate issue for each feature I am requesting.
- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by L0bsang** [comment]
I do have that gape but after a skin rebuild and a Kodi restart I no longer have the indicator focus on the submenu if there are no items. It goes straight from categories to widgets. This is acceptable to me.
I believe the gap was increased to provide space for studio logos from the spotlight; as requested in #683 and #659.

**Comment by adamosborne83** [comment]
> Yeah I'm not quite sure what is causing that to occur

This happens to me quite a bit, and usually have to restart kodi, when I finish a movie or episode Kodi obviously refreshes, but it can take about 10mins to fully Reload, I put this down to my library to which as you know is rather large. 
Funny thing is on kodi start, takes about 30 seconds.

**Comment by CyberRooke** [comment]
> ![screenshot00498 (3)](https://github.com/jurialmunkey/skin.arctic.fuse/assets/4618719/ef1744b4-1912-406d-bfa7-d3be1e24d350)
> 
> 

Is this what was added here  https://github.com/jurialmunkey/skin.arctic.fuse/commit/2b8368ba8a3919ad2b760779fd8a3d382acda329

If yes, how can it be enabled @jurialmunkey

**Comment by jurialmunkey** [comment]
@CyberRooke no it is still under construction
I thought it was ready but then decided it is not. I disabled the option for the time being until I've got it working well. It works but I'm not 100% on it and, sadly, it is much easier for me to simply not release features if there's any chance I need to change it later.

**Comment by CyberRooke** [comment]
> @CyberRooke no it is still under construction
> I thought it was ready but then decided it is not. I disabled the option for the time being until I've got it working well. It works but I'm not 100% on it and, sadly, it is much easier for me to simply not release features if there's any chance I need to change it later. 

Ahh, I see... Understood then, hoping to see this feature completed soon 🙏 or at least any means of removing spotlight on some complex layouts
