### ISSUE TITLE
[BUG] Spotlight widget buttons

### ISSUE THREAD

**Issue by r95sguy** [jurialmunkey/skin.arctic.fuse#7]
### Skin section

Home Widgets

### Current Behavior

I get 2 buttons that are labeled "More information", nothing happens when I click on the 1st one.

### Expected Behavior

1st button should be to play the video or live tv channel directly, and should be marked accordingly

### Steps To Reproduce

Go to all spotlight widgets, then click on 1st "more information" button

### Screenshots and Additional Info

![Screenshot 2023-07-22 1](https://github.com/jurialmunkey/skin.arctic.fuse/assets/113218125/ecea906d-7502-4ee6-bb4f-d4f9990a8175)

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
Oh this might be a default action issue.

Do you have default action set to show info?

I forgot to test with that enabled.

**Comment by r95sguy** [comment]
Yes, and now the play button is showing up after changing the default action to play, but still nothing happens when I click it

**Comment by jurialmunkey** [comment]
Ah youre right - the button isn't working at all. I must've accidentally edited the code when I was getting it ready for the repo because it was definitely working a few days ago.

**Comment by jurialmunkey** [comment]
Okay that should fix it now.

With default action play the buttons are:
`| Play/Open | More information |`

With default action info the buttons are:
`| Menu | More information |`

Unfortunately I can't override the default select action so next best is context menu - which I think is the same thing I did in AH2.
