### ISSUE TITLE
:bug: Search focus

### ISSUE THREAD

**Issue by vella9** [jurialmunkey/skin.arctic.fuse#701]
### Skin section

Widgets

### Current Behavior

once you finish typing in the search box, focus is not moving automatically to first item as before

### Expected Behavior

once you finish typing in the search box, focus should be on first item 

### Steps To Reproduce

1. open Search (1185)
2. type movie/show 
3. focus is not focusing on first item

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by vella9** [comment]
this is still occurring in v0.6.24 as per below. I don't remember if focus used to move to first item or the highlighted part in the image would update with first item info. 

This only occurs once during the first search. to occur again you need to reload skin or quit.

![image](https://github.com/jurialmunkey/skin.arctic.fuse/assets/137268669/b5c6254d-15a8-44d8-9c9a-2a52aeda966d)

**Comment by jurialmunkey** [comment]
I dont think this is possible to address. I can't know in advance which rows will have content and which rows will not, so I can't preset the widgetcontainer property onload.

Need to wait until a row gains focus to set the property as there isn't any other way in the skinning engine to trigger an action -- triggers are onload for window or onfocus/onclick for lists/buttons. 

Previously I was presetting the top row as widget container, but obviously that's a problem if the top container doesn't end up with results but another row does (then you get the old info for the wrong item).
