### ISSUE TITLE
new version skips widget when a stacked folder is below it

### ISSUE THREAD

**Issue by taiseer999** [jurialmunkey/skin.arctic.fuse#703]
### Skin section

Widgets

### Current Behavior

I set a genres widget for movies for example, latest release does not stop on the widget it jumbs straight down the stacked folder widget. 

### Expected Behavior

Work

### Steps To Reproduce

See video

https://files.fm/u/q3yz5phdss

### Screenshots and Additional Info

![IMG_3063](https://github.com/jurialmunkey/skin.arctic.fuse/assets/118752825/0fe8cfe9-64ab-4948-bda5-5090dcc65116)

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
It looks like you have a blank item before the genre category (in categories not widgets).

Does it work if you delete that blank item?

**Comment by taiseer999** [comment]
It's not actually a blank its a forgin language item that did not show because I switched Kodi language to English for the purpose of the showing the glitch.

**Comment by jurialmunkey** [comment]
I'm really trying to recreate this issue but I simply can't. It works as expected for me.

I tried with TMDbHelper genres and library genres and both worked. Tried to get as close to your settings as possible:

![screenshot00500](https://github.com/jurialmunkey/skin.arctic.fuse/assets/4618719/f3be17d9-3027-4051-8bc8-977ba8d0d1a8)

**Comment by ksefton92** [comment]
@jurialmunkey having the same issue here sadly. Any Stacked Folders gives me a TMDB Helper error, and the widget skips straight past them.

**Comment by taiseer999** [comment]
I sorted the issue here by disabling **use as widget** (probably kept selected from the very early days of the skin) whenever I choose to use widgets and not categories.

**Comment by taiseer999** [comment]
I sorted the issue here by disabling use as widget (probably kept selected from the very early days of the skin) whenever I choose to use widgets and not categories.

**Comment by jurialmunkey** [comment]
Yeah if use as widget is enabled but the submenu doesn't actually provide a valid widget then when kodi gets told to focus the top widget (which isn't there) it will jump to a different spot in the list. Same thing with the stacked widget being blank - kodi is expecting to be able to focus next widget but then can't because it doesn't exist so jumps to another position.
