### ISSUE TITLE
Cant make everyone happy....

### ISSUE THREAD

**Issue by adamosborne83** [jurialmunkey/skin.arctic.fuse#708]
### Skin section

Widgets

### Feature description

Evening J,
Now you know me well enough after the years of posting.... but, can you please see the below video. 
Now I know it is to make you life easier and more consistent, but between 'because you watched' and home, the gap does seem a lot, and then between play on spotlight and ratings, again just seems a lot.... I used [COLOR=00FFFFFF]-[/COLOR] to blank out the text, so theoretically yes I know its still there, but just trying to show. 

Also, on my combined, in Now shows the entire widget total, I'm sure they all use to be a consistent size or would scroll if had selected that.

### Why is this feature needed? Please justify and explain.

All about ME ME ME.

### Screenshots and Additional Info

https://github.com/jurialmunkey/skin.arctic.fuse/assets/78307374/b83eccf7-e6b7-4294-88c8-441ab36fadf6

### Checklist

- [X] I have made a separate issue for each feature I am requesting.
- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by adamosborne83** [comment]
![firetv_2024-04-08_20_18_19.jpg](https://github.com/jurialmunkey/skin.arctic.fuse/assets/78307374/004207a4-adc5-4317-9ddd-1f4125eb58ff)

That's a big ass widget name..... I'm gonna need a bigger screen lol

**Comment by L0bsang** [comment]
From the title of your post I thought it was gonna be about how pushing out changes to please some individual requests (that may not have been fully thought out) can risk creating unintended negative impacts on other people's setups. 
And then maybe proposing a voting system where a request that requires a significant change and that jurial isn't fully certain of implementing should undergo a week or so of deliberation/buy-in from the other active users of this skin....

But that's just what I was thinking of doing, this works too, and is basically the same thing! And this case seems different where although I was scratching my head at why one could need a spotlight label (I made the spotlights, I should know what they are innit...); seems like jurial does like this change for standardisation as far as I can tell.

I respect your acknowledgement that it is just your desires for your setup, and agree that the gaps look a bit large in the video, without a spolight label or footers. But with both spotlight labels and footers utilized it doesn't look quite as bad, if it truly is a move to make the skin more consistent it might be time to embrace the labels and footers (or at least labels since you like combined mode). Just my 2c.

**Comment by adamosborne83** [comment]
Totally agree with everything you've said. I hope after the few years with me being around and conversing with Jurial, I hope he knows that I never mean disrespect, and I chuck in a little humour, I do on Reddit too.

I've been with AF since it was announced on Ko-fi, and been throwing in my 2c worth constantly. 
I always like to embrace new layouts and styles, and for me the ONLY reason I dont have network logos etc, is because it kills my OCD that there isn't always a studio logo on the movie etc etc, so therefore I go for the minimal look.

Also, when an update is pushed, I really do think about if I should comment or not, and usually do only if I see something that just doesn't make sense, and there is logic behind my comment, not just 'I don't like it because......'

**Comment by CyberRooke** [comment]
> From the title of your post I thought it was gonna be about how pushing out changes to please some individual requests (that may not have been fully thought out) can risk creating unintended negative impacts on other people's setups. 
> And then maybe proposing a voting system where a request that requires a significant change and that jurial isn't fully certain of implementing should undergo a week or so of deliberation/buy-in from the other active users of this skin....
> 
> But that's just what I was thinking of doing, this works too, and is basically the same thing! And this case seems different where although I was scratching my head at why one could need a spotlight label (I made the spotlights, I should know what they are innit...); seems like jurial does like this change for standardisation as far as I can tell.
> 
> I respect your acknowledgement that it is just your desires for your setup, and agree that the gaps look a bit large in the video, without a spotlight label or footers. 
> But with both spotlight labels and footers utilized it doesn't look quite as bad (maybe a little cluttered), if it truly is a move to make the skin more consistent it might be time to embrace the labels and footers (or at least labels since you like combined mode). Just my 2c.

Honestly, I wish that was exactly how it was done... I would feel less guilty requesting a feature if most other users are able to vote for or against it... I don't mind the requests I make being tossed in the bin at all. The guy who does Fen hardly ever does requests. He just says, "No." without any reason whatsoever, not complaining though it's his work and I don't pay for it... this is the first time I've encountered a programmer who actually does things that are suggested... I'm pretty new to the Kodi community,  not new to Kodi, just the community, so It is refreshing to see ideas I suggest be implemented... but sometimes I feel some type of way about making any requests even though Jurial already said  he doesn't mind. It still feels like i'm being selfish or annoying when making requests... so a voting system will be pretty good.

**Comment by jurialmunkey** [comment]
> I would feel less guilty requesting a feature if most other users are able to vote for or against it...

@CyberRooke 

You can -- on the feature request with a thumbs up or down or a comment. 
Any issue thread remaining open I am considering implementing. 

The issue to add a spotlight title remained open for months and no-one objected. Then I implemented the feature and then there are objections. A "voting system" would be no different. People will only object after they can try it. 

All a voting system would achieve is creating what essentially amounts to "paper-work" for me. This ain't my job. Unless you're paying me a proper wage, I'm not doing paper-work in my hobby.

I only implement features that I agree with. 99% of requests are not new ideas to me. Almost always, a feature request I implement is more a case of justifying a decision that I was already considering myself. Practically every idea I have already debated and tried myself over and over.

**Comment by jurialmunkey** [comment]
> 
> That's a big ass widget name..... I'm gonna need a bigger screen lol

@adamosborne83 

This ... I didn't consider. Easy for me to address by setting a max value for the autosize buttons.

**Comment by CyberRooke** [comment]
> All a voting system would achieve is creating what essentially amounts to "paper-work" for me. This ain't my job. Unless you're paying me a proper wage, I'm not doing paper-work in my hobby.
> 
Fair enough 😅😅

> I only implement features that I agree with. 99% of requests are not new ideas to me. Almost always, a feature request I implement is more a case of justifying a decision that I was already considering myself. Practically every idea I have already debated and tried myself over and over.

I see... I kind of expected that most of the requested features probably won't be new to you since they are based on already existing features

**Comment by adamosborne83** [comment]
> > 
> > That's a big ass widget name..... I'm gonna need a bigger screen lol
> 
> @adamosborne83 
> 
> This ... I didn't consider. Easy for me to address by setting a max value for the autosize buttons.

Thank you 😊
