### ISSUE TITLE
[Feature] Pulling subtitles from an external add-on

### ISSUE THREAD

**Issue by The-cpu-max** [jurialmunkey/skin.arctic.fuse#71]
### Skin section

Fullscreen Video OSD

### Feature description

When clicking on the subtitles button - it will be possible to display the subtitles from an external plugin in addition to the built-in subtitles

### Why is this feature needed? Please justify and explain.

There is always a subtitle problem of one kind or another
Then I have to go into the settings and change the subtitles
Here in the same list I will show everything together
Of course, the built-in subtitles will be displayed in the first row and then the external ones

### Screenshots and Additional Info

![image](https://github.com/jurialmunkey/skin.arctic.fuse/assets/102416233/fe60f91c-3be3-4c86-8fec-2ead255ee1f5)

### Checklist

- [X] I have made a separate issue for each feature I am requesting.
- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by jurialmunkey** [comment]
Not possible. The only way to download external subtitles is from the settings. Kodi doesnt provide any other way to access these.
