### ISSUE TITLE
:bug: Music OSD Navigation Error

### ISSUE THREAD

**Issue by berkhornet** [jurialmunkey/skin.arctic.fuse#715]
### Skin section

Library

### Current Behavior

When playing music and pressing "M" to bring up the OSD, it is not possible to navigate past the lyrics button - focus returns to the playlist (first) icon

### Expected Behavior

Able to navigate the full OSD

### Steps To Reproduce

Go to Music Library
Select song
Bring up OSD
Navigate right

### Screenshots and Additional Info

![screenshot00005](https://github.com/jurialmunkey/skin.arctic.fuse/assets/67786207/b66809ec-8ab0-4efb-8c60-6e8d2ea1c36d)

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
I should be able to fix this but just wondering how repeat ends up being disabled.

**Comment by berkhornet** [comment]
I've reset to default skin settings in case I've got a conflict there. But the bug remains

**Comment by berkhornet** [comment]
I just noticed that the "microphone" button, which I think used to bring up lyrics, now brings up Artist Details

**Comment by FrostByteLXV** [comment]
I noticed the same thing today.  Repeat is disabled and when scrolling right it jumps you back to the play/pause button.  

However, you can scroll left to get to the last two buttons which takes you in from the right side of the screen.

![ozzy](https://github.com/jurialmunkey/skin.arctic.fuse/assets/15612092/a7d2a24d-99e5-49bb-9d75-93034ca48cf2)

**Comment by jurialmunkey** [comment]
Dumb typo on my part. 

Button 6 (6006) accidentally had same ID as Button 1 (6001)

**Comment by berkhornet** [comment]
Thank you!

Mick Rollitt
________________________________
