### ISSUE TITLE
 Option substitles search 

### ISSUE THREAD

**Issue by timiman1996** [jurialmunkey/skin.arctic.fuse#716]
### Skin section

Widgets

### Current Behavior

When I want to search for subtitles that are on my Nvidia, the skin freezes. downloading works

### Expected Behavior

When I want to search for subtitles that are on my Nvidia, the skin freezes. downloading works

### Steps To Reproduce

Go subtitles - to search

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by celiofk** [comment]
I can confirm that. Download works, but search freezes and restarts Kodi.
RPI4, Libreelec 12, Kodi 21.

**Comment by jurialmunkey** [comment]
Does it work in Estuary?

**Comment by timiman1996** [comment]
> Does it work in Estuary? 

Yea that works!

**Comment by celiofk** [comment]
Works in Estuary, but freezes like in AF. After 10-15 seconds, Estuary opens subtitles's search window, AF restarts Kodi.

**Comment by timiman1996** [comment]
In Estuary it also freez now.

**Comment by celiofk** [comment]
Maybe this is related:
https://github.com/xbmc/xbmc/issues/24779
A lot of technical chats that i don't undestand.

**Comment by jurialmunkey** [comment]
Closing as this doesn't appear to be a skin issue (also occurs in Estuary and seems to be linked to a known issue).
