### ISSUE TITLE
:sparkles: Mixed content widget

### ISSUE THREAD

**Issue by ProArtix** [jurialmunkey/skin.arctic.fuse#718]
### Skin section

Widgets

### Feature description

Would it be possible to create mixed content widget?

### Why is this feature needed? Please justify and explain.

For example, have a widget that mixes new series and movies together (according to release date)

### Checklist

- [X] I have made a separate issue for each feature I am requesting.
- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by jurialmunkey** [comment]
You can do this with a skin variables filter.
