### ISSUE TITLE
PVR Live TV Group Menu

### ISSUE THREAD

**Issue by derrgoo** [jurialmunkey/skin.arctic.fuse#723]
### Skin section

PVR and Live TV

### Current Behavior

I am not sure if this is something that I cannot find but a few updates ago my group menu seems to be gone from the left side. I cannot find in settings how to enable this in classic. Several versions ago you would click back and it goes to the group choice near the bottom which was great. 

### Expected Behavior

The menu for groups would appear so I can watch iptv. 

### Steps To Reproduce

Click on iptv section and I don’t see group selector to change IPTV group. 

### Screenshots and Additional Info

Not needed

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
It depends a bit on the settings you've got for side menu but back should take you to the side menu. From there you should either have a "view" button (if contextual button is enabled) or be able to press left to open view menu (if left to open menu is enabled) or info button on remote whole on menu should also open options.

**Comment by derrgoo** [comment]
Thank you. contextual worked perfectly. Closed
