### ISSUE TITLE
Trakt scrolling whilst in info

### ISSUE THREAD

**Issue by adamosborne83** [jurialmunkey/skin.arctic.fuse#724]
### Skin section

Widgets

### Current Behavior

Apologies, as you know I hate posting when your github is blowing up. 

But noticed a bug whilst reading trakt comments , it's scrolls.
As shown in video.

### Expected Behavior

Also apologies, but this is a request. On my combined, can you make it so it's scrolls the title of the widget. I'm sure it use to do this.? 

### Steps To Reproduce

See video

https://github.com/jurialmunkey/skin.arctic.fuse/assets/78307374/92f04307-393b-4f61-9101-858a4d3547b6

### Screenshots and Additional Info

Thanks 

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by adamosborne83** [comment]
Closing this as gone back to .10 version for a while 😀

**Comment by jurialmunkey** [comment]
Scrolling text boxes can be disabled in skin settings
Skin Settings > Behaviour > Autoscroll Textboxes

**Comment by adamosborne83** [comment]
> Scrolling text boxes can be disabled in skin settings
> Skin Settings > Behaviour > Autoscroll Textboxes

Sorry to comment on closed issue. Can you bring back, that the widget name scrolls when on it.

**Comment by jurialmunkey** [comment]
Not possible to scroll an autowidth button. Skinning engine does not have the capability.

**Comment by jurialmunkey** [comment]
I'm just going to go back to fixed width list for categories. Too many issues with autowidth. Will have to abandon idea about topbar categories.

**Comment by adamosborne83** [comment]
> I'm just going to go back to fixed width list for categories. Too many issues with autowidth. Will have to abandon idea about topbar categories.

Thank you. Fixed widths is cosmetically nicer for the OCD's out there haha.
Hope you had a good weekend.
