### ISSUE TITLE
:bug: Progress indicators not shown for SkinVariables Custom Filter widgets.

### ISSUE THREAD

**Issue by dstaller** [jurialmunkey/skin.arctic.fuse#725]
### Skin section

Widgets

### Current Behavior

Currently when using a SkinVariables custom filter widget there doesn’t seem to be any progress indicators shown. The TMDBHelper menus themselves show the progress indicators including when using them as widgets just not when combined using the filter.

### Expected Behavior

Progress indicators for any relevant content when using the filters as widgets.

### Steps To Reproduce

Enable progress indicators for TMDBHelper.

 Combine a couple TMDBHelper shortcuts in a custom filter.

Create a widget for the filter.

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by OfficerKD637** [comment]
Hi @dstaller 

I don't seem to be able to get the TMDB Helper menu widgets to show progress indicators on the home screen like you mentioned. I'm not using any custom SkinVariables widgets. I am using the 'Your In-Progress' movies inside TMDB Helper (supplied by Trakt). 
The indicators show up when inside the TMDB Helper addon in the Library view, but not when those are acting as widgets on the home screen.

Here are the screenshots:

**Home Screen** - No Progress Indicator
![Home Screen](https://github.com/jurialmunkey/skin.arctic.fuse/assets/167294806/5e605be6-e1f4-4ef6-9019-1709a8de864c)

**Library View** - Progress indicator visible inside the "Your In Progress" folder of TMDB Helper Movies 
![Library View](https://github.com/jurialmunkey/skin.arctic.fuse/assets/167294806/b737c39c-a568-408b-90d6-498517c6af9a)

Would really appreciate if you could help me out with this!

**Comment by jurialmunkey** [comment]
Skin Variables does not retrieve/set progress due to complicated reasons to do with how Kodi manages it. There's not much the skin can do about this as it is related to SV not the skin.
