### ISSUE TITLE
🐛 Global spotlight not sorting properly

### ISSUE THREAD

**Issue by ghost** [jurialmunkey/skin.arctic.fuse#727]
### Skin section

Widgets

### Current Behavior

Global spotlight sorting the items at random when set to default. It doesn't follow the actual default order of the items in the path, it just shows a random order. It is the same for other sorting methods as well

### Expected Behavior

When set to default,  it should show the same way it is in the item list. It also works correctly for category and sidemenu spotlights, problem only on global.

### Steps To Reproduce

Set a global spotlight, set sortby to default.

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by CyberRooke** [comment]
@jurialmunkey Is this an actual bug, or is it something that's been pre-built into the global spotlight?
