### ISSUE TITLE
:bug: lost option to continue from the last minute I left it

### ISSUE THREAD

**Issue by ProArtix** [jurialmunkey/skin.arctic.fuse#729]
### Skin section

Widgets

### Current Behavior

I have created a widget with skinvariable but it loses the option to continue from X minutes, why is this?

### Expected Behavior

It does not give the option to continue watching since the last time I left it
![IMG_20240412_113254](https://github.com/jurialmunkey/skin.arctic.fuse/assets/159583868/52b7b481-b946-494c-ab54-26e77157c3f6)
![IMG_20240412_113146](https://github.com/jurialmunkey/skin.arctic.fuse/assets/159583868/3bde7962-8b0f-4d47-9c4f-987ce1c25888)

### Steps To Reproduce

create new widget from skinvariable

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
Not a skin issue. Skin variables addon.

**Comment by ProArtix** [comment]
Yes, I also have an open topic in the addon but in case you haven't read it, why can't I find a solution?
