### ISSUE TITLE
Widget option request

### ISSUE THREAD

**Issue by JFG1000** [jurialmunkey/skin.arctic.fuse#731]
### Skin section

Widgets

### Feature description

Hey jurial I've noticed a few changes to the widgets recently and am gutted the text on board widget is gone, I loved to use them for next episodes as i prefer them over landscape, would it be possible to an an option to enable in the widget option to let us choose if we want text on them or not? This would be brilliant if it was a possibility, i would love to use landscape widgets for my shows section on my set up to but they currently have text which is not ideal for that scenario, having the text option to turn on and off would be perfect in that instance, it's just a thought which would be most appreciated if you could add for us.

Also plugin widgets have labels now which were never a thing before, could this be removed if possible?

Many thanks for all your hard work on such a great skin as always 

### Why is this feature needed? Please justify and explain.

Just gives us the option to make certain sections of our set ups look better and less cluttered 

### Checklist

- [X] I have made a separate issue for each feature I am requesting.
- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by L0bsang** [comment]
I definitely agree with text on board back as an option, I also used that for next-episodes (and imagine many others do).

Although if you want landscape without text you can just use Board (s), it is a landscape sized board with no text.

Labels and sub-labels are a standard now, unlikely we will be able to toggle them on and off. 
However Square (s) is one of the new styles that does not have sublabels, maybe you can use that for your plugins? It is smaller though, icon sized.

**Comment by JFG1000** [comment]
I much preferred the text on the widget for board mate it looked so much better so I'm hoping we get an option to toggle, back on landscape now but would prefer the board

I'll leave the plugin widgets then, thanks mate

**Comment by vella9** [comment]
I also prefer to have the text on board back as an option for continue watching and next episodes.

So, +1, thanks
