### ISSUE TITLE
✨️ Return of adaptive highlighter

### ISSUE THREAD

**Issue by CyberRooke** [jurialmunkey/skin.arctic.fuse#733]
### Skin section

Widgets

### Feature description

The adaptive highlighter was very useful in quickly identifying long labels that have similar first words in thier titles like "Trending Trakt TV shows" and "Trending Trakt Movies" and for many other use cases

### Why is this feature needed? Please justify and explain.

I'm not sure why this was removed though... If it is possible to get back could you please consider 🙏🙏... or could it be a setting I am missing, I already tried turning on and off touch mode but it seems to be entirely gone

### Checklist

- [X] I have made a separate issue for each feature I am requesting.
- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by CyberRooke** [comment]
> Sorry, I don't know what this is referring to?

Referring to the highlighter, that would be the same length as the label when selecting categories.... it will adjust its size to whichever category is highlighted... was available after turning off touch mode🤔🤔🤔

**Comment by CyberRooke** [comment]
> Sorry, I don't know what this is referring to?

Referring to this https://github.com/jurialmunkey/skin.arctic.fuse/commit/c791395302fe0d1b64a6449d02607d9e6ad39c01

**Comment by jurialmunkey** [comment]
It is removed for being too buggy. 

Scrolling on long labels doesn't work with auto width buttons due to a skinning engine limitation, and that makes it impossible to read the label if it is truncated for going past the max width value. Also had problems with touch/mouse and was creating display issues with blank highlighted items showing whilst it was loading. 

Plus a number of people complained about not liking the style and that they preferred fixed width. Porridge too hot. Porridge too cold. 👩 🐻 🐻 🐻 🥣  I'm not going to please everyone, so I decided less buggy and easier to maintain is best. 

I've already ripped out all the code anyway, and I'm definitely not keen on undoing the undoing. It feels like all I'm doing lately is undoing and I'd rather be doing anything but.

**Comment by CyberRooke** [comment]
> It is removed for being too buggy. 
> 
> Scrolling on long labels doesn't work with auto width buttons due to a skinning engine limitation, and that makes it impossible to read the label if it is truncated for going past the max width value. Also had problems with touch/mouse and was creating display issues with blank highlighted items showing whilst it was loading. 
> 
> Plus a number of people complained about not liking the style and that they preferred fixed width. Porridge too hot. Porridge too cold. 👩 🐻 🐻 🐻 🥣  I'm not going to please everyone, so I decided less buggy and easier to maintain is best. 
> 
> I've already ripped out all the code anyway, and I'm definitely not keen on undoing the undoing. It feels like all I'm doing lately is undoing and I'd rather be doing anything but.
> 
> 

Oh, alright... If that's the situation, then no worries  🙏🙏

**Comment by adamosborne83** [comment]
> It is removed for being too buggy. 
> 
> Scrolling on long labels doesn't work with auto width buttons due to a skinning engine limitation, and that makes it impossible to read the label if it is truncated for going past the max width value. Also had problems with touch/mouse and was creating display issues with blank highlighted items showing whilst it was loading. 
> 
> Plus a number of people complained about not liking the style and that they preferred fixed width. Porridge too hot. Porridge too cold. 👩 🐻 🐻 🐻 🥣  I'm not going to please everyone, so I decided less buggy and easier to maintain is best. 
> 
> I've already ripped out all the code anyway, and I'm definitely not keen on undoing the undoing. It feels like all I'm doing lately is undoing and I'd rather be doing anything but.
> 
> 

But I want it now...... Veruca Salt is my idol.
