### ISSUE TITLE
Widget Titles 

### ISSUE THREAD

**Issue by adamosborne83** [jurialmunkey/skin.arctic.fuse#734]
### Skin section

Widgets

### Current Behavior

Sorry, me again.....
Whilst scrolling the widget titles, it jumps terribly.

### Expected Behavior

Smooth scrolling as in .10

### Steps To Reproduce

See video along the bottom.

### Screenshots and Additional Info

https://github.com/jurialmunkey/skin.arctic.fuse/assets/78307374/d631750a-5a28-4330-96b4-706d40dff5c7

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by adamosborne83** [comment]
Think this shows it better


https://imgur.com/a/yqwXMBx

**Comment by CyberRooke** [comment]
> ### Skin section
> 
> Widgets
> 
> ### Current Behavior
> 
> Sorry, me again.....
> Whilst scrolling the widget titles, it jumps terribly.
> 
> ### Expected Behavior
> 
> Smooth scrolling as in .10
> 
> ### Steps To Reproduce
> 
> See video along the bottom.
> 
> ### Screenshots and Additional Info
> 
> 
> https://github.com/jurialmunkey/skin.arctic.fuse/assets/78307374/d631750a-5a28-4330-96b4-706d40dff5c7
> 
> 
> 
> ### Checklist
> 
> - [X] I have made a separate issue for each bug that I am reporting.
> - [X] I have searched the issues and this bug has not been reported.
> - [X] I am using the most recent skin version.
> - [X] I have confirmed that this bug does not occur in the default skin.

I also noticed this issue

**Comment by jurialmunkey** [comment]
Ah damn. I only tested with fewer than 4 widgets in the hub. Forgot to add the scroll time value back.
