### ISSUE TITLE
Option to append Director's Name to Infoline

### ISSUE THREAD

**Issue by N0mad077** [jurialmunkey/skin.arctic.fuse#735]
### Skin section

Widgets

### Feature description

By infoline I mean the line where the genre and rating are shown. I believe AH2 had this option and it was quite a useful feature.

### Why is this feature needed? Please justify and explain.

Super helpful to see the director's name in the info line, without having to open up the information window.

### Checklist

- [X] I have made a separate issue for each feature I am requesting.
- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by jurialmunkey** [comment]
It's too long for the infoline. You would have to remove practically all other info.

**Comment by N0mad077** [comment]
> It's too long for the infoline. You would have to remove practically all other info.

But isn't it available as an option in AH2? You could enable it in the settings and it worked just fine in terms of space. Is AF any different in that sense?

**Comment by jurialmunkey** [comment]
Yes it is a different skin with different margins.

**Comment by N0mad077** [comment]
> Yes it is a different skin with different margins.

Alright, thanks for responding.
