### ISSUE TITLE
Artwork bug on homescreen

### ISSUE THREAD

**Issue by JFG1000** [jurialmunkey/skin.arctic.fuse#739]
### Skin section

Other

### Current Behavior

Hey jurial I've noticed when hoovering over the last section on my set up being the power button on my homescreen, it's displaying the previous sections widget art work, usually it displays the background window image I've assigned if I'm not focusing on s widget, I've got no widgets on my power section. I hope this makes sense. 

### Expected Behavior

Usually when i hoover over the power button symbol on my homescreen it displays the window back ground image I've assigned not the previous sections art work for that last widget row. 

### Steps To Reproduce

Set a widget row, then create a section in my case a power function, and they widgets art work will not disappear. 

### Screenshots and Additional Info

![20240416_165556](https://github.com/jurialmunkey/skin.arctic.fuse/assets/76907836/1c94619f-062d-4263-bc4b-d339a85c694b)

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
I don't think this issue happens anymore.

It's not really how the skin is intended to work anyway -- expectation is that you will always have some type of content for each side icon.
