### ISSUE TITLE
[Feature] Mark as watched (trakt) season only

### ISSUE THREAD

**Issue by 666jones** [jurialmunkey/skin.arctic.fuse#74]
### Skin section

Home Widgets

### Feature description

When on a shows info page where you can view all the seasons.
When focused on a specific season marking as watched (trakt) marks the hole show as watched.

Would it be possible to make it so it only marks the focused season as watched 

### Why is this feature needed? Please justify and explain.

Just for ease of use

### Checklist

- [X] I have made a separate issue for each feature I am requesting.
- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by jurialmunkey** [comment]
Do you mean via the Trakt button in the info dialog?

Not really possible because Kodi identifies the info dialog for a season as dbtype "tvshow". Which means there's no way to distinguish whether its a tvshow or season.

**Comment by jurialmunkey** [comment]
Also I never wrote code for it in TMDbHelper either as seasons are just about the most complicated to manage (tvshow or single episode are easy as its just adding/removing a single item but season needs to figure out exactly which episodes to add/remove).

**Comment by 666jones** [comment]
> Also I never wrote code for it in TMDbHelper either as seasons are just about the most complicated to manage (tvshow or single episode are easy as its just adding/removing a single item but season needs to figure out exactly which episodes to add/remove).

It turns out the skin doesn't affect the ability to mark a season as watched. I just tested it in the addon I use as my player. And it works perfectly so nothing Todo with the skin. Sorry about that. Must be Todo with how tmdb handles it. And they way I was doing it was focusing on a season then using the context menu and unmarking as watched in trakt. This is very very rarely used so in the rare case I wanted to mark a season as unwatched I could just do it in my player addon or on the trakt website. Sorry to have wasted your time with this one
