### ISSUE TITLE
:sparkles: Hide category and submenu icons

### ISSUE THREAD

**Issue by ambulancePilot** [jurialmunkey/skin.arctic.fuse#744]
### Skin section

Widgets

### Feature description

Text only option for categories and submenu labels. It used to be that way and looked very nice. Please consider it!

### Why is this feature needed? Please justify and explain.

Setting the icon to none just leaves a white circle which is very off-putting.

### Checklist

- [X] I have made a separate issue for each feature I am requesting.
- [x] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by xyzfre** [comment]
If you find the proper icons, it actually looks really nice. It takes some time but well worth it just my opinion.Thank you @jurialmunkey for this amazing skin.

**Comment by ambulancePilot** [comment]
I'm open to that too, where would I find some nice icons?

**Comment by CyberRooke** [comment]
> If you find the proper icons, it actually looks really nice. It takes some time but well worth it just my opinion.Thank you @jurialmunkey for this amazing skin.

My exact thoughts as well... It looks nice with the smaller fonts, too. But I can imagine it being difficult to find the right icons for multiple submenus... personally, I don't use submenus, only categories, and I have the right icons for all. It looks beautiful.

**Comment by xyzfre** [comment]
@CyberRooke Pic please 😁,never tried without submenus

**Comment by CyberRooke** [comment]
> @CyberRooke Pic please 😁,never tried without submenus

What do you use submenus for?🤔🤔

These are my categories... I mainly use them for category spotlight 

![Screenshot_20240418_014739_Gallery.jpg](https://github.com/jurialmunkey/skin.arctic.fuse/assets/162068678/15d2c7fc-a675-49b0-b707-3c5afc178ed5)

![Screenshot_20240418_015016_Gallery.jpg](https://github.com/jurialmunkey/skin.arctic.fuse/assets/162068678/16a3f995-83c3-46f7-84d1-9dc141664684)

**Comment by xyzfre** [comment]
> > @CyberRooke Pic please 😁,never tried without submenus
> 
> What do you use submenus for?🤔🤔
> 
> These are my categories... I mainly use them for category spotlight 
> 
> ![Screenshot_20240418_014739_Gallery.jpg](https://github.com/jurialmunkey/skin.arctic.fuse/assets/162068678/15d2c7fc-a675-49b0-b707-3c5afc178ed5)
> 
> ![Screenshot_20240418_015016_Gallery.jpg](https://github.com/jurialmunkey/skin.arctic.fuse/assets/162068678/16a3f995-83c3-46f7-84d1-9dc141664684)
> 
> 

It does look a lot neater. I will post a pic soon. Thank you my friend.

**Comment by CyberRooke** [comment]
> > @CyberRooke Pic please 😁,never tried without submenus
> 
> What do you use submenus for?🤔🤔
> 
> These are my categories... I mainly use them for category spotlight 
> 
> ![Screenshot_20240418_014739_Gallery.jpg](https://github.com/jurialmunkey/skin.arctic.fuse/assets/162068678/15d2c7fc-a675-49b0-b707-3c5afc178ed5)
> 
> ![Screenshot_20240418_015016_Gallery.jpg](https://github.com/jurialmunkey/skin.arctic.fuse/assets/162068678/16a3f995-83c3-46f7-84d1-9dc141664684)
> 
> 

This my entire setup

https://youtu.be/8JRXL_R10hA

**Comment by xyzfre** [comment]
![image](https://github.com/jurialmunkey/skin.arctic.fuse/assets/49699869/a99c4645-d5e7-4a78-b3be-87258606f0e0)

**Comment by CyberRooke** [comment]
> ![image](https://github.com/jurialmunkey/skin.arctic.fuse/assets/49699869/a99c4645-d5e7-4a78-b3be-87258606f0e0)

Ohh damn 😐😐😐 I didn't know it looked like that... thst is gorgeous 😂😂😂... The last time I tried submenus was 0.6.9... I'm definitely gonna give it a try now

Please, where did you get the icons from?

**Comment by CyberRooke** [comment]
> > > ![image](https://github.com/jurialmunkey/skin.arctic.fuse/assets/49699869/a99c4645-d5e7-4a78-b3be-87258606f0e0)
> > 
> > Ohh damn 😐😐😐 I didn't know it looked like that... thst is gorgeous 😂😂😂... The last time I tried submenus was 0.6.9... I'm definitely gonna give it a try now
> > 
> > Please, where did you get the icons from? 
> 
> From TMDb Helper

Thought so... thank you 🙏🏾🙏🏾

**Comment by xyzfre** [comment]
> This my entire setup
> 
> https://youtu.be/8JRXL_R10hA

Thank you for sharing. You have a really nice set up AF is addicting lately I catch myself messing around more with this skin than watching TV lol but it's all part of making Kodi fun hobby.Thanks to Jurial. When I get a chance, I'll share my set up. I have like 60 widgets lol

**Comment by CyberRooke** [comment]
> > This my entire setup
> > 
> > https://youtu.be/8JRXL_R10hA
> 
> Thank you for sharing. You have a really nice set up AF is addicting lately I catch myself messing around more with this skin than watching TV lol but it's all part of making Kodi fun hobby.Thanks to Jurial. When I get a chance, I'll share my set up. I have like 60 widgets lol

Yeah, very fun skin to use... so many possibilities... I'm looking forward to seeing your setup

**Comment by xyzfre** [comment]
@CyberRooke my apologies not the best video with my phone and the remote in the other hand looks much better in person https://vimeo.com/936992858

**Comment by CyberRooke** [comment]
> @CyberRooke my apologies not the best video with my phone and the remote in the other hand looks much better in person https://vimeo.com/936992858

Nicee.... with that setup, i doubt you do much clicking,  pretty much everything is a widget. Your load times are also pretty fast. Do you use a personal library? and what device are you on?

**Comment by A30B06** [comment]
Hi all, do you know where I can find this option to enable the icons? Currently I have icons set for categories and submenus in the settings, but they do not show on the Home Screen, it shows text only.

**Comment by xyzfre** [comment]
> Hi all, do you know where I can find this option to enable the icons? Currently I have icons set for categories and submenus in the settings, but they do not show on the Home Screen, it shows text only.

![image](https://github.com/jurialmunkey/skin.arctic.fuse/assets/49699869/caa90922-7978-4fa9-9b96-c7cd467ad512) change this setting to detailed

**Comment by A30B06** [comment]
Great thank you! 😊

**Comment by xyzfre** [comment]
@CyberRooke it's a Beelink SER5 Mini PC,AMD Ryzen 5 5600H Processor,Mini Computer with 16G DDR4 RAM/500GB M.2 NVME 2280 SSD,4K FPS/Dual HDMI+Type-C/WiFi 6E(802.11ax)/BT5.2/Support Auto Power On,, haven't turned on my Nvidia Shield since I bought this MiniPC about two years ago,,Windows 11 Pro v21.0 Omega

**Comment by L0bsang** [comment]
> @CyberRooke it's a Beelink SER5 Mini PC,AMD Ryzen 5 5600H Processor,Mini Computer with 16G DDR4 RAM/500GB M.2 NVME 2280 SSD,4K FPS/Dual HDMI+Type-C/WiFi 6E(802.11ax)/BT5.2/Support Auto Power On,, haven't turned on my Nvidia Shield since I bought this MiniPC about two years ago,,Windows 11 Pro v21.0 Omega

Sorry to 'necro' but where did you buy this and does it come with a mouse? 
I have a shield currently, back in the day was gonna replace it with a beelink king gt (or something like that) but then RMA'd my shield instead (turns out the issues I had were because of some hardware issue).

This SER5 seems nice but quite high price (double what I bought the shield for) for just streaming. Especially since i have a decent desktop already.
