### ISSUE TITLE
:bug: Can’t get rid of global spotlight

### ISSUE THREAD

**Issue by deon10** [jurialmunkey/skin.arctic.fuse#745]
### Skin section

Widgets

### Current Behavior

As can be seen in the picture, there is a global spotlight thing above my Movies and TV Shows widget groups

the issue is I have disabled  global spotlight but the skin doesn’t disable it. It instead creates a global spotlight with a “noop” function, instead of takin to that as a command to be disabled

hopefully the pictures I attached show what I mean clearly
![IMG_3684](https://github.com/jurialmunkey/skin.arctic.fuse/assets/71561562/c63ee984-b02f-4f09-b150-dea154136f95)
![IMG_3685](https://github.com/jurialmunkey/skin.arctic.fuse/assets/71561562/1faa58c9-e1b8-43a8-a902-e0a36da1269c)
![IMG_3686](https://github.com/jurialmunkey/skin.arctic.fuse/assets/71561562/67d45464-478b-41c2-86e6-642db7247b53)

### Expected Behavior

The Movies and TV Shows categories should come straight under the Clock on the main screen. And there shouldn’t be any “None” section there

Thank you for your time

### Steps To Reproduce

1. Disable Global Spotlight on the skin widget setting
2. global spotlight still shows with a “None” title

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
Spotlight can be disabled by using classic mode.

**Comment by deon10** [comment]
Respectfully, im not sure why you wouldn’t allow people to just disable global spotlight, which is what was the case for months and months. Since the creation of the skin

With “Classic” how would a person keep the widget categories like is shown on the screenshots posted?

i don’t think my request was an unreasonable one. It’s something we used to be able to do. 

Now disabling global spotlight leaves a blank section called “nope” that has no purpose

Thanks

**Comment by jurialmunkey** [comment]
A lot of technical reasons why it is difficult to manage and caused several problems with navigation.

**Comment by L0bsang** [comment]
> With “Classic” how would a person keep the widget categories/groups (TV Shows and Movies) like is shown on the screenshots posted?

By using topbar menu, or by making use of the sidemenus as category items.
