### ISSUE TITLE
✨️ No sub label in detailed categories and submenus

### ISSUE THREAD

**Issue by CyberRooke** [jurialmunkey/skin.arctic.fuse#746]
### Skin section

Widgets

### Feature description

Detailed submenus and categories to revert back to the way it was in 0.6.21

### Why is this feature needed? Please justify and explain.

This is just a suggestion... I think the detailed submenus and categories looked better without the sublabels.... The sublabels make it seem like too many words for one small area, they also only say "folder" as seen in these images
![Screenshot_20240418_161719_Gallery](https://github.com/jurialmunkey/skin.arctic.fuse/assets/162068678/bcb0c24d-49d0-455a-a6ef-0b1a6b38a8c1)
![Screenshot_20240418_161643_Gallery](https://github.com/jurialmunkey/skin.arctic.fuse/assets/162068678/9d423e5a-c131-46e2-9218-3799ca25b2ad)

Even when I put a movie or an addon, it will still only say folder 
![Screenshot_20240418_161741_Gallery](https://github.com/jurialmunkey/skin.arctic.fuse/assets/162068678/86ce1095-0b89-4887-bfad-4a135f2b044e)

I understand they may be there to fill up space due to the icons on display but I feel like placing the label in the middle like before may be the better approach 

### Checklist

- [X] I have made a separate issue for each feature I am requesting.
- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by xyzfre** [comment]
Definitely agree they look big beautiful this way![image](https://github.com/jurialmunkey/skin.arctic.fuse/assets/49699869/4e8f612a-860e-4c2c-a612-85e2d8a8ea4d)

**Comment by jurialmunkey** [comment]
Btw You can edit the sublabel in widget customisation screen.

The end goal is that category style and combined mode in hubs will match the style used for combined views in library. 

There will be a middle ground option that is icon plus single label, but first I need to get the style switch working for hubs in combined mode - then I'll be looking at further options.

**Comment by CyberRooke** [comment]
> Btw You can edit the sublabel in widget customisation screen.
> 

Ohh damn... can't believe I missed that... it still does look better without the sublabels, but I can definitely see the use case for being able to edit the sublabel

> The end goal is that category style and combined mode in hubs will match the style used for combined views in library. 
> 

I see... that will definitely create consistency, but does it mean the combined mode will switch to a vertical list with the widgets on the side? 🤔🤔 when I imagine it, it does look appealing, but I always struggle when navigating the combined mode in the library 

> There will be a middle ground option that is icon plus single label, but first I need to get the style switch working for hubs in combined mode - then I'll be looking at further options.

Okay... that's good to hear. Thank you for your good work with the skin... many blessings 🫡🫡🫡

**Comment by jurialmunkey** [comment]
> I can definitely see the use case for being able to edit the sublabel

I actually changed my mind. Going to handle it automatically to keep it consistent. Next version has a few extra conditions to make it more informative than just "folder".

**Comment by QuickSwitchLK** [comment]
> > I can definitely see the use case for being able to edit the sublabel
> 
> I actually changed my mind. Going to handle it automatically to keep it consistent. Next version has a few extra conditions to make it more informative than just "folder".

I do like this view with the detailed info and the more detailed sublabel on the latest version, but could it still be an option in the widget setting to edit the text? 

Because I edited some before the update. I now have my previous text stuck in the editing of my widget, but can't change.

![Screenshot 2024-04-21 132500](https://github.com/jurialmunkey/skin.arctic.fuse/assets/34122743/5309e859-a3fb-4e0c-905c-a71f702df1cf)

![Screenshot 2024-04-21 132243](https://github.com/jurialmunkey/skin.arctic.fuse/assets/34122743/eb7e0c27-590f-4d4b-a4c5-3d35b3f245ac)

**Comment by xyzfre** [comment]
Thank you @jurialmunkey Categories and Submenu's look amazing now without the sublabels🤩 (PERFECT)
