### ISSUE TITLE
List items for progress icons

### ISSUE THREAD

**Issue by derrgoo** [jurialmunkey/skin.arctic.fuse#749]
### Skin section

Other

### Feature description

Sorry this is not a bug but a request helping out the dev for POV try to set up watched and progress icons on widgets. Can you show me where he would fix/add to have them show up in widgets being pulled? 

### Why is this feature needed? Please justify and explain.

This will be helpful to addon. 

### Checklist

- [X] I have made a separate issue for each feature I am requesting.
- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by jurialmunkey** [comment]
Watched flag is shown if ListItem.PlayCount > 0 and ListItem.DBType (mediatype) is set to movie, episode, video, or set 
(or tvshow/season will also show watched if unwatchedepisodes is 0). 

Progress shows if Kodi has a resume point and IsResumable is set. A plugin cannot set this directly (just setting a resume point is not enough). It requires the plugin to use the setresolvedurl method of playback, which allows Kodi to manage resume points -- there is also a JSON RPC hack to overwrite the resume point for an item file path, but it is not recommended as it can be buggy.

Alternatively, the plugin can set ListItem.Property(WatchedProgress) with a value from 1-99. This will only work in AH2 and Fuse as this is not a standard infolabel and so requires skin support.
