### ISSUE TITLE
[Feature] OSD Previous episode (skip back button)

### ISSUE THREAD

**Issue by 666jones** [jurialmunkey/skin.arctic.fuse#75]
### Skin section

Home Widgets

### Feature description

The OSD has skip forward (next episode) button is it possible to add skip back ( previous episode button) that would be a cool feature.

### Why is this feature needed? Please justify and explain.

It's not needed just thinking it could come in handy

### Checklist

- [X] I have made a separate issue for each feature I am requesting.
- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by jurialmunkey** [comment]
You can press down and use the playlist to see previous items in the playlist (and if there aren't then a previous button wouldn't do anything anyway) 

I don't think going back one in the playlist is something done frequently enough to warrant its own button.

**Comment by 666jones** [comment]
> You can press down and use the playlist to see previous items in the playlist (and if there aren't then a previous button wouldn't do anything anyway)
> 
> I don't think going back one in the playlist is something done frequently enough to warrant its own button.

I never noticed the playlist in the OSD I just checked and it's there. I have spent most my time playing about with the skin. Thanks for pointing that out
