### ISSUE TITLE
Kodi crash on specific widget content

### ISSUE THREAD

**Issue by Arelav** [jurialmunkey/skin.arctic.fuse#752]
### Skin section

Widgets

### Current Behavior

I recently re-installed everything from scratch after Kodi 21 was released.
And after enabling the skin and using pre-build tmdb it started crashing consistently when focusing on TV shows widget trending. (I use classic layout)
My suspicion is unicode character in one of the shows `Shōgun`.
After removing trending from widgets it’s stopped crashing.
I tried to take a look on logs but didn’t figure much. Please let me know if any specific part of log will help or anything else.

### Expected Behavior

No Kodi crashes

### Steps To Reproduce

Use pre-build tmdb with classic layout from initial wizard. 
scroll to shows -> trending
When it has “Shōgun” it’s crashing. I can’t tell for sure if it’s related or not because I didn’t use nether Kodi or Arctic Fuse for a few weeks

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by Arelav** [comment]
Update: I have "Shōgun" in another widget (Highly rated tv shows) and it's not crashing. The problem some how related to trending tv shows widget

**Comment by jurialmunkey** [comment]
Sounds like a Kodi bug. Possibly something in the skin is agitating it, or something in TMDbHelper. That said, I am able to use Highly Rated TV Shows widget with no issues, so it is likely platform specific.

Very difficult to diagnose what the issue might be without a proper crash debug log with traceback debugging symbols enabled. Anything else is just guess work.

**Comment by valerykh** [comment]
> Sounds like a Kodi bug. Possibly something in the skin is agitating it, or something in TMDbHelper. That said, I am able to use Highly Rated TV Shows widget with no issues, so it is likely platform specific.
I agree. I temporarily switched to AH2, and after I added widget for highly rated TV shows it was also crashing. In general, Kodi 21 release is more fragile than RC2. Let's close this for now. Thank you for your work.

**Comment by Arelav** [comment]
Sounds like a Kodi bug. Possibly something in the skin is agitating it, or something in TMDbHelper. That said, I am able to use Highly Rated TV Shows widget with no issues, so it is likely platform specific.
I agree. I temporarily switched to AH2, and after I added widget for highly rated TV shows it was also crashing. In general, Kodi 21 release is more fragile than RC2. Let's close this for now. Thank you for your work.
