### ISSUE TITLE
Premiere/Finale indicators disappear when sorting set to recentlywatched

### ISSUE THREAD

**Issue by vella9** [jurialmunkey/skin.arctic.fuse#753]
### Skin section

Widgets

### Current Behavior

I am not sure if this is related with the skin or tmdbhelper but whenever I change the widgets>next episodes sort method to recentlywatched on tmdbhelper,  the premiere/finale indicators disappear. I am using the trakt>Your Next Episodes widget. If tmdbhelper sort method is set to airdate. It works normally.

### Expected Behavior

premiere/finale indicators should be displayed even when tmdbhelper>widgets>next episodes sort method is set to recentlywatched

### Steps To Reproduce

change sort method from tmdhhelper to recentlywatched
premiere/finale indicators of Your Next Episodes disappear

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
It's an API thing. Trakt doesn't provide that data with the basic sync (which is by recently watched). Need to sync with extended data which is what all the other sorts do. So by recent is faster because it has less data to retrieve.

**Comment by vella9** [comment]
will check these option out. Thank you!
