### ISSUE TITLE
[BUG] Background and submenu options not hidden when widgets only layout enabled

### ISSUE THREAD

**Issue by 666jones** [jurialmunkey/skin.arctic.fuse#76]
### Skin section

Home Widgets

### Current Behavior

I set a background widget for my home page but the background widget never appears. My home is set to widgets only (basic) 

I have wrote possible bug as I'm not sure if this is intended behaviour or not.

### Expected Behavior

I'm not sure if the background should be visible or not but I have the ability to set one.

### Steps To Reproduce

1. Set home page as widgets only (basic)
2. Set up a background widget for home page.

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by 666jones** [comment]
> No that's intentional. I just haven't got around to disabling the options you can't use when that mode is enabled (same goes for the submenu).

I did think that might be the case. Thanks very much for clarifying.

**Comment by jurialmunkey** [comment]
I'll just leave this open as a reminder that I need to fix it so those options dont display
