### ISSUE TITLE
Change Widget load icon area

### ISSUE THREAD

**Issue by reitenth** [jurialmunkey/skin.arctic.fuse#763]
### Skin section

Widgets

### Feature description

Right now the load icon for widgets is right on top of the first widget. I think it would look cleaner if it showed in the top right like all the other notifications. Thanks

### Why is this feature needed? Please justify and explain.

Cleaner UI, less mess.

### Checklist

- [X] I have made a separate issue for each feature I am requesting.
- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by jurialmunkey** [comment]
Sorry, I think this is a bad idea.

A busy spinner in the corner suggests that the interface is unavailable and the user should wait until the content finishes loading before control is returned.

This is not the case with widget content. A widget loading does not prevent the user from moving or interacting with other parts of the interface. The user can still scroll to other widgets or interact with other content.
