### ISSUE TITLE
[Feature] Adding a synopsis to a movie with a poster when paused

### ISSUE THREAD

**Issue by test01203** [jurialmunkey/skin.arctic.fuse#77]
### Skin section

Fullscreen Video OSD

### Feature description

Every time someone sees a certain video when stopped
There will be a summary of the film - next to it is the poster

### Why is this feature needed? Please justify and explain.

Displaying video summaries next to posters when paused/stopped is important for better user experience. It helps users quickly grasp video content, decide what to watch, and stay engaged. This feature is user-friendly and enhances overall satisfaction.

### Screenshots and Additional Info

I gave you an example of how it should look
![image](https://github.com/jurialmunkey/skin.arctic.fuse/assets/104188844/a351224f-f614-44fb-bc7d-6604beb1a4cb)

### Checklist

- [X] I have made a separate issue for each feature I am requesting.
- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by jurialmunkey** [comment]
You can press info on your remote or click the info button on the right side controls to see extended information including plot and poster.

**Comment by jurialmunkey** [comment]
Duplicate of #57
