### ISSUE TITLE
[Feature] Play / Pause button opposite

### ISSUE THREAD

**Issue by 666jones** [jurialmunkey/skin.arctic.fuse#79]
### Skin section

Fullscreen Video OSD

### Feature description

I was just wondering if the play / pause buttons are the wrong way round. Normally when content is playing it shows a pause button and when content is pused it shows a play button. I have only just noticed this. It's not a issue just thought I'd point it out. It currently shows a play button when playing and a pause button when paused.

### Why is this feature needed? Please justify and explain.

Not needed just curious 

### Checklist

- [X] I have made a separate issue for each feature I am requesting.
- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by jurialmunkey** [comment]
I debated about this a lot.

Because it also displays with the seekbar (eg when paused, seek, step, cache etc) I figured it is better that it displays the current status - it was weird to have the icon switch when focused

**Comment by 666jones** [comment]
> I debated about this a lot.
> 
> Because it also displays with the seekbar (eg when paused, seek, step, cache etc) I figured it is better that it displays the current status - it was weird to have the icon switch when focused

I completely understand, And you know what's best mate. I just thought I'd mention it incase it was a oversight. Really liking the skin thanks for all your hard work. I'll go ahead and close this. Hope you had a lovely weekend

**Comment by RentreX** [comment]
I know this is old and closed though I saw on the forums that this is still being suggested.

Personally I like it the way it is. But would it be possible to add something in skin settings to toggle it from play/pause to pause/play?
