### ISSUE TITLE
:bug: Unable to scroll down to 'side widgets'

### ISSUE THREAD

**Issue by Dml2023** [jurialmunkey/skin.arctic.fuse#796]
### Skin section

Widgets

### Current Behavior

With global widgets now being truely global, I have changed some widgets that I was using in my music side menu section to the Side Widgets (Music) area. I don't have the need for any Category widgets so I am using the side widgets. When I go to the music sidemenu item I can see that my widgets have loaded, but I cannot navigate down to them.

If I add a category widget then I can navigate down to all widgets that are displayed.

### Expected Behavior

I was hoping to not need a category widget to then get to the side widgets.

### Steps To Reproduce

1. Make sure that you don't have any category widgets.
2. Add side widgets.
3. Exit widget editing, and after the rebuild, navigate to the sidemenu item and see the result.

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by FrostByteLXV** [comment]
Think this is related, if not then I'll open a new report.  First noticed I can't navigate down from the side widget Close if the secondary side menu setting in picture is "Contextual" in version v6.26 and still happening in v6.27.  However, I can navigate down from Close if the secondary side menu is set to Menu or Options.

Kodi Omega nightly
nVidia Shield

![Screenshot_20240425-070822](https://github.com/jurialmunkey/skin.arctic.fuse/assets/15612092/1ac1efd9-5d03-46ca-b4b5-8ee5f195622f)

**Comment by jurialmunkey** [comment]
@FrostByteLXV Completely separate bug

**Comment by FrostByteLXV** [comment]
Thanks, I'll open a separate ticket.

**Comment by jurialmunkey** [comment]
Yeah, still need categories *for now*... but this is the definite end goal I'm working towards.

I'm hoping I'll eventually be able to make it possible to have widget groups switch automatically between classic and complex simply based on whether there are categories or not for that item rather than needing a setting.

Will still be a little while off, but the changes coming in next update are looking promising from an "under the hood" perspective.

**Comment by Dml2023** [comment]
Thanks for the update.
