### ISSUE TITLE
last update added widgets

### ISSUE THREAD

**Issue by Aemstel2** [jurialmunkey/skin.arctic.fuse#799]
### Skin section

Widgets

### Current Behavior

The last update added a couple of widgets, such as Top Rated Movies below my custom widgets. I can not remove them in skin settings. They don't show up there.

### Expected Behavior

Weird how those widgets just popped in there. And can't remove them in settings.

### Steps To Reproduce

1. Check the skin main page for new widgets that shouldn't be there.

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by woodside007** [comment]
Go to settings/customize widgets/ select an icon on the far left/ then on the right you should see "Edit side menu widgets". You can edit or disable these widgets by selecting "Edit side widgets(*category*)". Cheers.

**Comment by jurialmunkey** [comment]
Also see global widgets too.

Basically
Adaptive widget (use as widget) = Appears first, adapts to submenu. 
Category widgets = Appear under adaptive widget, based on category focus 
Side widgets = Appear under category widgets, based on side menu focus
Global = Appears last and is always visible.

There will also be a submenu widget group soon to allow setting extra widgets for static submenu items (ie in between adaptive and category widgets).

Will work on config screen being more intuitive - just focusing on getting it all working first before I worry about that.
