### ISSUE TITLE
Navigation broken when on install from zip etc screen

### ISSUE THREAD

**Issue by JFG1000** [jurialmunkey/skin.arctic.fuse#805]
### Skin section

Other

### Current Behavior

So when i bring up the addons screen, i try to navigate to install from zip on the left by clicking down on my remote, the highlight does not move, i press upwards on the remote i can get to it from the opposite end, but otherwise it's stuck. Also we cannot highlight the settings icon on that menu atall

### Expected Behavior

Should be able to navigate downwards to select install from zip, updates etc 

### Steps To Reproduce

Bring up addons screen, navigate downwards from the side of the screen 

### Screenshots and Additional Info

![20240426_074558](https://github.com/jurialmunkey/skin.arctic.fuse/assets/76907836/bc8b575d-ffe0-4645-b765-b5fc4a20f555)

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
This will be the same as this issue: https://github.com/jurialmunkey/skin.arctic.fuse/issues/798

Already fixed. Fix will be in next update.
