### ISSUE TITLE
Version Bug.

### ISSUE THREAD

**Issue by TheOGuser** [jurialmunkey/skin.arctic.fuse#810]
### Skin section

Widgets

### Current Behavior

I believe there is a bug with the zip?

So, I went to install .27 and layout was exactly the same as .28.

This is .26 in the video below which does not show spot light controls, where .27 did.

### Expected Behavior

.27 to show the update prior to .28

### Steps To Reproduce

Install from your zip on github

### Screenshots and Additional Info

https://github.com/jurialmunkey/skin.arctic.fuse/assets/167613811/8d2140e9-c6b0-4283-aa9f-a60703c26a3a

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
Zips are generated by github based on tags. If you want a specific commit then checkout that commit.

**Comment by adamosborne83** [comment]
> Zips are generated by github based on tags. If you want a specific commit then checkout that commit.

Thank You,
I did not know this.... I am looking for a needle in a hay stack, so hope you could maybe help me find the commit.

I am looking for these icons

![firetv_2024-04-27_08_04_43.jpg](https://github.com/jurialmunkey/skin.arctic.fuse/assets/78307374/f8e13a0d-b90c-4870-9858-59217fdb323a)

But here as well.

![firetv_2024-04-27_08_05_09.jpg](https://github.com/jurialmunkey/skin.arctic.fuse/assets/78307374/ee83af04-42c9-42c1-a18c-72c875799f2c)


Please point me in direction.

**Comment by adamosborne83** [comment]
I think it's this one

2e054bd7231d659cf9f7ccd6aab0ee441f83cfec
