### ISSUE TITLE
:bug: Combined mode widget selector flashes when changing groups

### ISSUE THREAD

**Issue by adamosborne83** [jurialmunkey/skin.arctic.fuse#818]
### Skin section

Widgets

### Current Behavior

As I scroll over sections, the name from the bottom title flashes. 

### Expected Behavior

Not to flash

### Steps To Reproduce

See video but do not blink.

### Screenshots and Additional Info

https://imgur.com/a/JPu9JND

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
This issue has actually always existed. It is just more obvious now because I force the selector to reset its position when changing categories. Anyway, will be fixed soon because this was a step on the way to fixing it.
