### ISSUE TITLE
First focused widget dimmed upon kodi start up 

### ISSUE THREAD

**Issue by JFG1000** [jurialmunkey/skin.arctic.fuse#827]
### Skin section

Widgets

### Current Behavior

Hi there I've noticed when we first start up kodi tor skin no longer is focused on the widget it used to on our first section, everything is dimmed, this is hard for me to explain so I'll attach a photo below, in the photo the "next episodes" widget usually would be focused on automatically and highlighted, also I've noticed sometimes after playback has finished when we load back to the homescreen it will be focusing on a completely different widget and it would be dimmed also, so for an example if I'm playing something from the next episode widget, when i come back to the homescreen afterwards it would be focused on the shows watchlist below as an example. 

https://ibb.co/frNd0rn

I've pasted that image link as the upload on git function didn't work for me 

### Expected Behavior

Usually the first widget on the homescreen would never be completely dim and it would be focused on it, displaying the meta data etc 

### Steps To Reproduce

Start up kodi, let widgets load

### Screenshots and Additional Info

![Uploading 20240428_170059.jpg…]()

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by vella9** [comment]
looks fixed in 0.6.31

**Comment by JFG1000** [comment]
EDIT : I've noticed on 6.31 on playback this now sometimes highlights a completely widget  after playback has stopped and it's completely dim, also on startup then highlighted over the first widget it cycles through and then comes back to the focused one

**Comment by JFG1000** [comment]
EDIT : I've discovered this bug only occurs with move between widget groups enabled on classic mode

**Comment by jurialmunkey** [comment]
This should be addressed in 0.7.4 with position always forced to first. Let me know if it is still happening though.

**Comment by JFG1000** [comment]
Thanks mate as always
