### ISSUE TITLE
Trailers broken

### ISSUE THREAD

**Issue by patkino** [jurialmunkey/skin.arctic.fuse#828]
### Skin section

Widgets

### Current Behavior

When playing trailer (auto or manual) the screen turns black just as if resolution error. Have to remotly start some other video to get the picture back. Since some update for some reason there are no options to customize trailer playing modes.

### Expected Behavior

Normal
Please get back Trailer options

### Steps To Reproduce

Go to movie info, press trailer

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by adamosborne83** [comment]
Do you have the latest YouTube installed?

https://github.com/anxdpanic/plugin.video.youtube/releases

**Comment by patkino** [comment]
Yes, I do have

**Comment by patkino** [comment]
Youtube videos run without any problems. The issue is obviously related to the way that trailers play.
Since for some sake options of trailers playmode is gone - there's no way for me to check

**Comment by scoobyd00** [comment]
Trailers working fine for myself on latest version

**Comment by jurialmunkey** [comment]
Enable background video in behaviour.

Works fine for me.

**Comment by jurialmunkey** [comment]
If you are unable to play video in a dialog overlay or in the background, then that is a Kodi bug.
