### ISSUE TITLE
:bug: Back button is going back to the first side menu item and not the default

### ISSUE THREAD

**Issue by eesdil** [jurialmunkey/skin.arctic.fuse#834]
### Skin section

Widgets

### Current Behavior

Using classic mode with move between widget groups.
If you use "Back" on the first widget item it is going to the first side menu item back. Which for me is the search and not the main widget I would like to start with (Movies).

### Expected Behavior

The back is bringing to the "default" side menu item and not the first one.

### Steps To Reproduce

1. go to a widget item
2. use "Back" 
3. the focus goes to the first menu item

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by OfficerKD637** [comment]
Hi!
He addressed this earlier here https://github.com/jurialmunkey/skin.arctic.fuse/issues/826#issuecomment-2081492672
Since all classic mode widgets are now in a single grouplist, pressing back will take you to the top (first) widget.

**Comment by eesdil** [comment]
see, thanks.

The only issue is that I would like to navigate through the widget groups, but I dont want to go back to the first group.
Why? because in a previous commit the search on "Up" was removed (where I used the search functionality) 
Now as it is gone, I put the search to the first group as I didnt find easier place for it.

**Comment by OfficerKD637** [comment]
> see, thanks.
> 
> 
> 
> The only issue is that I would like to navigate through the widget groups, but I dont want to go back to the first group.
> 
> Why? because in a previous commit the search on "Up" was removed (where I used the search functionality) 
> 
> Now as it is gone, I put the search to the first group as I didnt find easier place for it.
> 
> ![screenshot00002](https://github.com/jurialmunkey/skin.arctic.fuse/assets/1408181/d356e692-40b3-4d89-9dab-c16f39a17350)
> 
> 

Yeah I completely understand where you're coming from. I think a few other people on the Kodi forum also had similar setups that want to revert to the previous way of navigation (not exactly sure)?
I would say let's wait for Jurial's reply to understand if there is any possible middle ground between working towards a simple but modular skin and accommodating your preferences.

**Comment by eesdil** [comment]
thanks, sure. Not life threatening :)
