### ISSUE TITLE
Navigation getting stuck in sidebar 

### ISSUE THREAD

**Issue by adamosborne83** [jurialmunkey/skin.arctic.fuse#836]
### Skin section

Widgets

### Current Behavior

After going through widgets and pressing back, there becomes a point where it jumps to sidebar and gets stuck.

### Expected Behavior

Not to happen

### Steps To Reproduce

See video J, alot easier to get.

### Screenshots and Additional Info

https://imgur.com/a/ZBTuo3P

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by adamosborne83** [comment]
Sorry J, still happening. I didn't go fast or anything at all.  See video. Sorry

https://github.com/jurialmunkey/skin.arctic.fuse/assets/78307374/4189a176-8c3f-408d-a4c4-c0b1b63c61ca

**Comment by adamosborne83** [comment]
Seems to happen when on combined widget and press back button.

https://github.com/jurialmunkey/skin.arctic.fuse/assets/78307374/3afa6155-5c36-45aa-9836-940bf6a49de1

**Comment by jurialmunkey** [comment]
Can you turn on debug info overlay in skin settings under expert (end of dependencies) then grab a video.

Must not be the issue I was able to cause.

**Comment by adamosborne83** [comment]
>If you need any more or logs, or anything let me know. 



https://github.com/jurialmunkey/skin.arctic.fuse/assets/78307374/3d7f5f0d-33fa-4074-962d-2a1b125db3ec
