### ISSUE TITLE
:bug: Newly set local clearlogos for TV shows update partially

### ISSUE THREAD

**Issue by cavalrymargarine0x1** [jurialmunkey/skin.arctic.fuse#838]
### Skin section

Library

### Current Behavior

Arctic Fuse updaties newly set clearlogos for shows but only on their landscape tile view, not updating them on the upper half highlight section of the interface (see screenshot for example).

### Expected Behavior

Expected behavior is the the newly locally set clearlogos of shows update everywhere in the interface.

### Steps To Reproduce

1. Hover over a TV Show
2. Open the context menu and go to _Information_
3. Head down to _Artwork_
4. Assign a new clearlogo locally, located in relevant show's folder
5. Refresh the show's artwork
6. Restart Kodi

### Screenshots and Additional Info

![1](https://github.com/jurialmunkey/skin.arctic.fuse/assets/165792428/9b2a015e-4626-4754-86f3-c56285a9651f)

The locally set clearlogo does appear when refreshing the artwork but only on the landscape tile of the show, it remains what it was in the highlight upper half of the interface. 

The correct clearlogo is named clearlogo.png in the show's folder. The wrong clearlogo was the logo that was assigned to the show when I first added it to my library. It still remains even after I've deleted the file and done the following:

- Deleted Thumbnail folder contents and Texture.db file
- Made sure the desired logo file is named clearlogo.png
- Removed/re-added the show to the library
- Set desired clearlogo with Kodi having no internet access (to prevent potential metadata scrapers interfering)
- First set clearlogo to _No Art_, refreshed show artwork, restarted Kodi, then set desired clearlogo

Is there somewhere else where Kodi stores TV show clearlogos that I'm not aware of?

Fanarts updates just fine in the upper half of the interface. It's only the clearlogos that don't.

I'd appreciate some help with this as I cannot figure it out, cheers :D

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
These are cropped by TMDbHelper. You can find the cropped version in its addon_data folder.

If the file has the same name as before, then you will need to remove the cached version from Kodi's texture cache, the cropped version from TMDbHelper's addon_data folder, *and* the cached version of the cropped version in Kodi's texture cache.
