### ISSUE TITLE
[BUG] Episodes watched number missing in Episode video info page

### ISSUE THREAD

**Issue by AakashC2020** [jurialmunkey/skin.arctic.fuse#85]
### Skin section

Video Info Dialog

### Current Behavior

Hi @jurialmunkey,

If we go to the video info page for an episode then the number of watched episodes number is not displaying under Details -> Episodes tab. Instead it's only showing the text "Watched" under Episodes tab which doesn't make any sense. The same feature is working fine for the TV Show's main video info dialog. Please check and correct me if I'm wrong.

### Expected Behavior

As described above.

### Steps To Reproduce

Go to any TV Show. Browse for Episodes. Open the Video Info dialog for any Episode. Go to Play -> Details -> Episodes. See the text under Episodes. It'll only show as Watched for all TV Show Episodes.

### Screenshots and Additional Info

![IMG20230807020007](https://github.com/jurialmunkey/skin.arctic.fuse/assets/65297828/a2c8d5a0-a37f-4e27-b70a-4466996f124e)

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
That value is not available from Episodes info page.

I've changed it so it doesn't say "Watched" and removed the counts from there. The count displays in the footer when available, so it was unnecessarily doubling up anyway.

**Comment by AakashC2020** [comment]
> That value is not available from Episodes info page.
> 
> I've changed it so it doesn't say "Watched" and removed the counts from there. The count displays in the footer when available, so it was unnecessarily doubling up anyway.

Hi @jurialmunkey,

That's fine, but now the video info screen of TV Shows have this entry for Episodes -> * All seasons as shown in the screenshot below. Don't you think it looks a bit weird? Please advise.

![IMG_20230809_141019](https://github.com/jurialmunkey/skin.arctic.fuse/assets/65297828/c32a6c4d-23e6-4054-8d55-d3af9d93513c)
