### ISSUE TITLE
:bug: Side menu in search 

### ISSUE THREAD

**Issue by 719q** [jurialmunkey/skin.arctic.fuse#856]
### Skin section

Widgets

### Current Behavior

Can't go straight to movies/TV shows without selecting "Close" and "Configure" first. It would be a nice QoL upgrade, sorry if this isn't exactly a bug. 

### Expected Behavior

After searching, pushing down goes straight to library. Pushing all the way left from library shows "Close" and "Configure".

### Steps To Reproduce

1. Search something 
2. Can't go directly to results with one click
3. Sad

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
I don't understand what you're trying to describe here.

**Comment by booyakafoo** [comment]
I've noticed this also.  I have the search hub set for side menu > minimize > primary = Search / ActivateWindow(1185).
![20240508_142656](https://github.com/jurialmunkey/skin.arctic.fuse/assets/3913228/dc70f117-4f89-4ac4-8a78-3a4643fbfa3d)

When I use it.  I get a list of movies and TV shows and to navigate to the search results you logically press down. Pressing down I would expect to jump directly to the search results, but you have to press down 3 times to get to the search results after first highlighting close and discover in the left menu area before getting to the search results.
