### ISSUE TITLE
Top label doesn’t follow indicator in classic mode (seems like #835 again)

### ISSUE THREAD

**Issue by OfficerKD637** [jurialmunkey/skin.arctic.fuse#860]
### Skin section

Widgets

### Current Behavior

Hi Jurial!

It seems a variation of a previous bug (https://github.com/jurialmunkey/skin.arctic.fuse/issues/835) has resurfaced. The top label now only shows ‘Home’. It previously used to change with the indicator while scrolling through the widgets in classic mode.
This bug was resolved in v0.6.33 via https://github.com/jurialmunkey/skin.arctic.fuse/commit/7c8903ed09e60e1eec1a0f35cb48072a8b9a719b

But it seems to now be stuck on ‘Home’, irrespective of where the indicator is.

### Expected Behavior

Top label changing with indicator like in v0.6.33

### Steps To Reproduce

1. Create a classic mode setup
2. Scroll through the side widgets
3. Top label is stuck on ‘Home’

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by vella9** [comment]
Hi @jurialmunkey thank you for the latest update and sorry to comment on a closed issue, however I noticed that when group focus indicator=off in 0.7.1 using classic mode, only Home is being shown at the top label.

**Comment by jurialmunkey** [comment]
@vella9 that is the correct behaviour.

When the indicator is enabled, the header shows the label for the group. 

When it is disabled, it shows the window name like every other window.
