### ISSUE TITLE
when entering a searchword in library with a remote, the back button goes back to home instead of closing the filter dialog

### ISSUE THREAD

**Issue by Aemstel2** [jurialmunkey/skin.arctic.fuse#861]
### Skin section

Library

### Current Behavior

When going to library, filter and enter a word in the search box with remote app (I use Yatse), the back button in the app moves back to the home screen instead of closing the filter dialog and focusing the search results.

### Expected Behavior

After entering a search word have the back button close the filter dialog and stay on the search results.

### Steps To Reproduce

1. enter library
2. enter filter dialog
3. enter a word in the search box with (Yatse) remote app
4. press the back button

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
Sounds like a problem with Yatse not the skin. 

This behaviour will occur using the action "PreviousMenu" (this is the action mapped to ESC on keyboard) instead of Back (action mapped to Backspace on keyboard).

**Comment by Aemstel2** [comment]
No you can't use backspace in the searchbox because it will simply remove a letter from the entered text. On keyboard you have to press down first and then backspace. When using Yatse pressing down and back also works (does not go back to previous menu, but closes filter dialog). So I guess it's always necessary to press down first and then back.

**Comment by jurialmunkey** [comment]
There's nothing I can do about this behaviour, it is how kodi edit control works - back deletes and if you issue a different command like previous menu or home, then that is also functioning correctly by going back a window.
