### ISSUE TITLE
:bug: Error installing a build with the Arctic Fuse skin.

### ISSUE THREAD

**Issue by gtkingbuild** [jurialmunkey/skin.arctic.fuse#862]
### Skin section

Other

### Current Behavior

When I install my build with Artyc Fuse, after restarting Kodi, the skin starts asking to install the build addons and when it has already installed some addon suddenly the screen goes black and changes to Estuary... then it comes out a registry error that says that the skin cannot be started because it says that the skin files are missing, from then on the error message changes to another that occurs constantly about SkinVariables.

### Expected Behavior

I would like that when starting Kodi after installing the build it would not change to Estuary and Arctyc Fuse would run normally
### Steps To Reproduce

Install a build with that skin and let time pass until suddenly the skin is automatically changed to Estuary and the error messages start to appear, however, as soon as it is changed from Estuary to the Fuse skin, it does its load correctly.
![Screenshot_2024-05-09-17-15-12-711_org xbmc kodi](https://github.com/jurialmunkey/skin.arctic.fuse/assets/68242121/49b50c06-94fc-43dc-9b7e-4335a5ff4224)

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
Nothing to do with me.

I don't make or support "builds". Skin works fine if installed from my repo following the instructions.
