### ISSUE TITLE
Focus on side menu upon skin reload 

### ISSUE THREAD

**Issue by JFG1000** [jurialmunkey/skin.arctic.fuse#867]
### Skin section

Widgets

### Current Behavior

Hi jurial I've noticed on the newest update the focus is no longer on the second section on the side menu like it used to be, it's now on the first, if this is intentional please could you add a setting for us as its much preferred how it was. Many thanks 

### Expected Behavior

When starting kodi or reloading skin, the focus would usually be on the second section on the side menu 

### Steps To Reproduce

Start kodi or skin reload 

### Screenshots and Additional Info

![20240511_143644](https://github.com/jurialmunkey/skin.arctic.fuse/assets/76907836/2d8ddf31-d4dd-4263-81c5-a08b09cdca48)

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
You can select default item when configuring side menu items in widget customisation.

**Comment by JFG1000** [comment]
Thanks for the quick response mate
