### ISSUE TITLE
[BUG] tmdb players not playing fen directly 

### ISSUE THREAD

**Issue by Santaklawz** [jurialmunkey/skin.arctic.fuse#87]
### Skin section

Other

### Current Behavior

Opens a menu with fen main addon directory 

### Expected Behavior

Opens fen to search for and play the file 

### Steps To Reproduce

Skin settings dependicies tmdb plugin helper
Set default for movies and shows to fen with source select 
Open any tmdb movie and it will show you the addon menu not open fen with source select you have to press back and choose fen and then fen with source select 

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
This has nothing to do with the skin.
