### ISSUE TITLE
Can't navigate to next section from bottom widget 

### ISSUE THREAD

**Issue by JFG1000** [jurialmunkey/skin.arctic.fuse#870]
### Skin section

Widgets

### Current Behavior

Hey I've noticed a possible bug on the latest update, I hope i can explain It well, so when I'm on the latest widget row of a section for example movies, if i press down it would usually move me to the next section and it's widgets, currently it no longer does that and takes me to a search box so the top of the screen instead 

### Expected Behavior

Usually when we keep pressing down it will cycle to the next section after the last widget prior. 

### Steps To Reproduce

Create some widgets, navigate to the last one. 

### Screenshots and Additional Info

![20240511_213452](https://github.com/jurialmunkey/skin.arctic.fuse/assets/76907836/994bd24a-2677-4ffd-8b68-7c24fde4adfa)

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
"move between widget groups" needs to be enabled in navigation settings. 

For end action, Check your Navigation settings on down behaviour. Also possible to set individual hubs to have separate behaviour from the main setting. That's at bottom of widget config screen, so check there too.

**Comment by JFG1000** [comment]
This was not enabled previously and worked fine, has sometimes changed?

**Comment by jurialmunkey** [comment]
> This was not enabled previously and worked fine, has sometimes changed?

That sounds wrong because that is the only purpose of the option -- it switches whether or not you can scroll through to the different groups.

It's been like that for months.

Maybe you forgot that you enabled it at some stage or accidentally toggled it.

**Comment by JFG1000** [comment]
> > This was not enabled previously and worked fine, has sometimes changed?
> 
> That sounds wrong because that is the only purpose of the option -- it switches whether or not you can scroll through to the different groups.
> 
> It's been like that for months.
> 
> Maybe you forgot that you enabled it at some stage or accidentally toggled it.

Possibly it's sorted now, i was able to change the down button behaviour to bump which i much prefer, many thanks
