### ISSUE TITLE
🐛 Date & Time inside Search bar looks weird?

### ISSUE THREAD

**Issue by OfficerKD637** [jurialmunkey/skin.arctic.fuse#873]
### Skin section

Widgets

### Current Behavior

Hi Jurial!

It’s me again haha. Sorry for being such a bother. This is a cosmetic issue so very low priority.

I’m not exactly sure if this is a bug or the intended look, but when the header has ‘Date & Time’ enabled and you scroll up to ‘Search’, it looks kinda weird?
Is there a way we could hide the D&T only when inside the ‘Search’ bar for a cleaner look? 
Or maybe go directly to the text cursor blinking as soon as we scroll up from the Home Screen? (circumventing the initial text i.e. ‘Search’ and ‘Date & Time’ that shows up inside the search bar).

Let me know what you think!

Thank you!

### Expected Behavior

1. No ‘Date & Time’ inside the search bar

OR

2. Go directly to the text cursor blinking as soon as I scroll up from the first side widget in the Home Screen.

### Steps To Reproduce

1. Make a classic mode setup
2. Enable ‘Search & Options’
3. Enable ‘Date and Time’ in Furniture > Header
4. Scroll up from the Home Screen

### Screenshots and Additional Info

![IMG_2693](https://github.com/jurialmunkey/skin.arctic.fuse/assets/167294806/37db1246-c55d-4a61-a55f-2b99ef28d0b8)

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
I've actually already dealt with this in this commit: https://github.com/jurialmunkey/skin.arctic.fuse/commit/51c3f0250d1297f005745be42f31a70186c8af61

Will be in next update.

Also, what's that font? Is it Montserrat? It looks nice.

**Comment by OfficerKD637** [comment]
> I've actually already dealt with this in this commit: https://github.com/jurialmunkey/skin.arctic.fuse/commit/51c3f0250d1297f005745be42f31a70186c8af61
> 
> 
> 
> Will be in next update.
> 
> 
> 
> Also, what's that font? Is it Montserrat? It looks nice.

You're truly the GOAT for everything that you do! You literally came out with a huge update a day ago and you're already back to resolving bugs😭

The font is Product Sans!

**Comment by jurialmunkey** [comment]
> The font is Product Sans!

Ah I thought it looked a bit like half way between Montserrat and Roboto. That explains it. 

Yeah Product Sans is really nice, shame it isn't OpenSource like Roboto

**Comment by OfficerKD637** [comment]
> Yeah Product Sans is really nice, shame it isn't OpenSource like Roboto

Well..... Google's gonna google amirite

**Comment by L0bsang** [comment]
@OfficerKD637 , Will changing the font be overridden by skin updates? Thinking of doing it too, it definitely looks nice!

**Comment by OfficerKD637** [comment]
> @OfficerKD637 , Will changing the font be overridden by skin updates? Thinking of doing it too, it definitely looks nice!

Yeah you'd have to replace the Font.xml file every time you update the skin. Fortunately it's very easy!
Make a copy of the Font.xml file that's inside the 1080i folder. 

Inside the file, duplicate (copy & paste) one of the existing fontset ids and rename it to your liking.

Then replace the font names with your preferred font. Make sure your font has a Black, Bold, Regular and Light variant to keep the overall look cohesive and seamless.

Copy your .ttf files to .kodi > media > Fonts folder. You only have to do this once since updating the skin doesn't affect this.

Now replace the existing Font.xml file with your modified file and that should be it!

You can now go into Settings > Interface > Fonts 
and choose your new font

After performing a skin update, just replace the Font.xml file and it should all work.

Let me know if you need help with anything else while setting this up!

**Comment by jurialmunkey** [comment]
It is even easier if you learn how to use git.

Install skin then disable auto updates for it. 

Delete skin.arctic.fuse folder from addons folder, then use `git clone https://github.com/jurialmunkey/skin.arctic.fuse.git` to recreate the skin folder using a clone of the git repo. 

Make your changes then commit them with
 `git commit -a -m newfontset`

To get new updates, simple do `git pull` from the skin folder and git will pull new changes from upstream and merge on top of yours.

**Comment by OfficerKD637** [comment]
> It is even easier if you learn how to use git.
> 
> 
> 
> Install skin then disable auto updates for it. 
> 
> 
> 
> Delete skin.arctic.fuse folder from addons folder, then use `git clone https://github.com/jurialmunkey/skin.arctic.fuse.git` to recreate the skin folder using a clone of the git repo. 
> 
> 
> 
> Make your changes then commit them with
> 
>  `git commit -a -m newfontset`
> 
> 
> 
> To get new updates, simple do `git pull` from the skin folder and git will pull new changes from upstream and merge on top of yours. 

This is a great tip and exactly what I used to do when I ran Kodi on my Windows PC!

Now that I'm trying to run this on my LG TV (webOS), it gets complicated to automate this process since the write permissions often get revoked and the TV needs to be rebooted. The webOS Dev Manager needs me to manually copy paste items which is cumbersome but works.

If @L0bsang is using Android, you could probably use the git method. There are a few apps (like Termux) that offer clone/push/pull functionality.

Here's an article that might help: https://chribonn.medium.com/how-to-clone-and-synchronise-a-github-repository-on-android-a59ddf7cd092

Many thanks to @jurialmunkey for being open to us experimenting with his skin!

**Comment by Rinicko** [comment]
> > @OfficerKD637 , Will changing the font be overridden by skin updates? Thinking of doing it too, it definitely looks nice!
> 
> Yeah you'd have to replace the Font.xml file every time you update the skin. Fortunately it's very easy!
> 
> Make a copy of the Font.xml file that's inside the 1080i folder. 
> 
> Inside the file, duplicate (copy & paste) one of the existing fontset ids and rename it to your liking.
> 
> Then replace the font names with your preferred font. Make sure your font has Black, Bold, Regular and Light variants to keep the overall look cohesive and seamless.
> 
> Copy your .ttf files to .kodi > media > Fonts folder. You only have to do this once since updating the skin doesn't affect this.
> 
> Now replace the existing Font.xml file with your modified file and that should be it!
> 
> You can now go into Settings > Interface > Fonts 
> and choose your new font
> 
> After performing a skin update, just replace the Font.xml file and it should all work.
> 
> Let me know if you need help with anything else while setting this up!

Hi, you said to copy the font .ttf file to .kodi > media > font folder... but this doesn't work... it only works when the files are in .kodi > addons > skin.arctic.fuse > fonts... How did you make yours work in .kodi > media > font?

**Comment by OfficerKD637** [comment]
> > > @OfficerKD637 , Will changing the font be overridden by skin updates? Thinking of doing it too, it definitely looks nice!
> > 
> > Yeah you'd have to replace the Font.xml file every time you update the skin. Fortunately it's very easy!
> > 
> > Make a copy of the Font.xml file that's inside the 1080i folder. 
> > 
> > Inside the file, duplicate (copy & paste) one of the existing fontset ids and rename it to your liking.
> > 
> > Then replace the font names with your preferred font. Make sure your font has Black, Bold, Regular and Light variants to keep the overall look cohesive and seamless.
> > 
> > Copy your .ttf files to .kodi > media > Fonts folder. You only have to do this once since updating the skin doesn't affect this.
> > 
> > Now replace the existing Font.xml file with your modified file and that should be it!
> > 
> > You can now go into Settings > Interface > Fonts 
> > and choose your new font
> > 
> > After performing a skin update, just replace the Font.xml file and it should all work.
> > 
> > Let me know if you need help with anything else while setting this up!
> 
> Hi, you said to copy the font .ttf file to .kodi > media > font folder... but this doesn't work... it only works when the files are in .kodi > addons > skin.arctic.fuse > fonts... How did you make yours work in .kodi > media > font?

Is the name of your folder ‘Fonts’? It has to have an uppercase ‘F’ and needs to be plural - ‘Fonts’

I think the skin should be able to reference fonts loaded into Kodi’s ‘Fonts’ folder exactly like how you can customize subtitle fonts.

Let me know if this works.

**Comment by Rinicko** [comment]
>  > Hi, you said to copy the font .ttf file to .kodi > media > font folder... but this doesn't work... it only works when the files are in .kodi > addons > skin.arctic.fuse > fonts... How did you make yours work in .kodi > media > font?
> 
> Is the name of your folder ‘Fonts’? It has to have an uppercase ‘F’ and needs to be plural - ‘Fonts’
> 
> I think the skin should be able to reference fonts loaded into Kodi’s ‘Fonts’ folder exactly like how you can customize subtitle fonts.
> 
> Let me know if this works.

still didn't work... is it exactly like that in yours?

**Comment by OfficerKD637** [comment]
> still didn't work... is it exactly like that in yours?

That's weird. Mine works perfectly. What platform are you using? I can check on my end and see if maybe the file directories are different.

**Comment by Rinicko** [comment]
> 
> > still didn't work... is it exactly like that in yours?
> 
> That's weird. Mine works perfectly. What platform are you using? I can check on my end and see if maybe the file directories are different.

I use Nvidia shield 2019

**Comment by OfficerKD637** [comment]
> I use Nvidia shield 2019

For Android, this is the directory
/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/media/Fonts

Are you placing the .ttf files here?

**Comment by Rinicko** [comment]
> > I use Nvidia shield 2019
> 
> For Android, this is the directory
> /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/media/Fonts
> 
> Are you placing the .ttf files here?

Yeah, although I had to create the folder for Fonts in media, as there was no fonts folder there previously

**Comment by OfficerKD637** [comment]
> Yeah, although I had to create the folder for Fonts in media, as there was no fonts folder there previously

I don't know why it's not working. Are you able to use those fonts in your subtitles? If the names of the .ttf files in the Fonts.xml file and the 'Fonts' folder match exactly, Arctic Fuse should be able to reference the .ttf files from Kodi's font folder.

**Comment by Rinicko** [comment]
> > Yeah, although I had to create the folder for Fonts in media, as there was no fonts folder there previously
> 
> I don't know why it's not working. Are you able to use those fonts in your subtitles? If the names of the .ttf files in the Fonts.xml file and the 'Fonts' folder match exactly, Arctic Fuse should be able to reference the .ttf files from Kodi's font folder.
> 
> 

Yeah, the fonts come up in my subtitles when I copy them there but skin refuses to find them... No worries though, I'm learning how to use the git clone method Jurial mentioned... if I can't figure it out I'll just keep copying the folder along with the .xml file

**Comment by Rinicko** [comment]
> > Yeah, although I had to create the folder for Fonts in media, as there was no fonts folder there previously
> 
> I don't know why it's not working. Are you able to use those fonts in your subtitles? If the names of the .ttf files in the Fonts.xml file and the 'Fonts' folder match exactly, Arctic Fuse should be able to reference the .ttf files from Kodi's font folder.
> 
> 

Thanks for your help though... appreciate it

**Comment by OfficerKD637** [comment]
> Thanks for your help though... appreciate it

No worries at all! I am sorry I couldn't help you any further. If I come across any better solutions I'll be sure to send it your way!

Have a great day!

**Comment by OfficerKD637** [comment]
> Hello, sorry to bother you again, just wondering if you could help me out with using git.
> 
> I used git clone to get the code into my computer from git bash... then made the changes... when I tried executing git commit -m... it says "fatal: not a git repository (or any of the parent directories): .git" ... any idea how I can add my changes?

No worries! Always happy to help!

Are you in the right directory when you're opening entering the command prompts? And have you initialized the repo?

Follow these steps to check:

1. Type ls and see if it shows the right files 

2. Type git init if you haven't initialized the repo yet.

**Comment by Rinicko** [comment]
> > Hello, sorry to bother you again, just wondering if you could help me out with using git.
> > 
> > I used git clone to get the code into my computer from git bash... then made the changes... when I tried executing git commit -m... it says "fatal: not a git repository (or any of the parent directories): .git" ... any idea how I can add my changes?
> 
> No worries! Always happy to help!
> 
> Are you in the right directory when you're opening the command line? And have you initialized the repo?
> 
> Follow these steps to check:
> 
> 1. Type ls and see if it shows the right files 
> 
> 2. Type git init if you haven't initialized the repo yet.
> 
> 
> 

The wrong directory comes up when I type ls.... it shows the parent folder for skin.arctic.fuse... instead of the folder itself

**Comment by OfficerKD637** [comment]
> The wrong directory comes up when I type ls.... it shows the parent folder for skin.arctic.fuse... instead of the folder itself 


Okay so you'll need to open the shell in the correct directory.

If you're on Windows, open the folder in Windows File Explorer and then click on the address bar.

Type git-bash and enter

That should open the shell in your specific directory.

Check with the ls command again.

**Comment by Rinicko** [comment]
> > The wrong directory comes up when I type ls.... it shows the parent folder for skin.arctic.fuse... instead of the folder itself 
> 
> 
> Okay so you'll need to open the shell in the correct directory.
> 
> If you're on Windows, open the folder in Windows File Explorer and then click on the address bar.
> 
> Type git-bash and enter
> 
> That should open the shell in your specific directory.
> 
> Check with the ls command again.
> 

when I type git-bash in the address bar... it opens a tab on chrome

**Comment by OfficerKD637** [comment]
> when I type git-bash in the address bar... it opens a tab on chrome


That's weird. That's a shortcut that should work.

How about opening Git Bash and then typing 
cd <your folder directory>

Example: 
cd E:\Desktop\MyFolder

And then try the ls command

**Comment by Rinicko** [comment]
> > when I type git-bash in the address bar... it opens a tab on chrome
> 
> 
> That's weird. That's a shortcut that should work.
> 
> How about opening Git Bash and then typing 
> cd < your folder directory >
> 
> Example: 
> cd E:\Desktop\MyFolder
> 
> And then try the ls command
> 

That worked... thank you so much! 😭

**Comment by OfficerKD637** [comment]
> That worked... thank you so much! 😭

Haha that's great! It's so weird those shortcuts didn't work but I'm glad I could help!

Feel free to reach out if you have any other questions!

**Comment by Rinicko** [comment]
> > That worked... thank you so much! 😭
> 
> Haha that's great! It's so weird those shortcuts didn't work but I'm glad I could help!
> 
> Feel free to reach out if you have any other questions!

Hello, I encountered another issue... when entering command git commit... it says Author identity unknown... even after setting a name using git config ---global user.name... it still says same thing

**Comment by OfficerKD637** [comment]
> Hello, I encountered another issue... when entering command git commit... it says Author identity unknown... even after setting a name using git config ---global user.name... it still says same thing

Run this command

git config --global --edit

Check if your username and email are correctly saved. If not, manually edit the text file and save it.

Example:

[User1] i.e can use any name like Personal, Business, other, etc..
name = <github username>
email = <github email>

Verify the changes by using this command

git config --list

If you don't want to use the command line, you can locate the gitconfig file on your computer and make the changes there directly.

**Comment by Rinicko** [comment]
> > Hello, I encountered another issue... when entering command git commit... it says Author identity unknown... even after setting a name using git config ---global user.name... it still says same thing
> 
> Run this command
> 
> git config --global --edit
> 
> Check if your username and email are correctly saved. If not, manually edit the text file and save it.
> 
> Example:
> 
> [User1] i.e can use any name like Personal, Business, other, etc..
> name = < github username >
> email = < github email >
> 
> Verify the changes by using this command
> 
> git config --list
> 
> If you don't want to use the command line, you can locate the gitconfig file on your computer and make the changes there directly.

Finally!... you are a saint 🫡🫡 Thank you for your assistance. it is greatly appreciated. 

Do you know a quick way to add the

**Comment by OfficerKD637** [comment]
> Finally!... you are a saint 🫡🫡 Thank you for your assistance. it is greatly appreciated. 
> 
> Do you know a quick way to add the files to my .kodi folder in shield 

Awesome! I'm glad everything worked out.

You can create a separate folder with all the files in your shield and after every skin update use X-Plore to copy those to the .kodi folder.
