### ISSUE TITLE
:bug: Options tray not centered if there are 2 or 4 items

### ISSUE THREAD

**Issue by Bindou01** [jurialmunkey/skin.arctic.fuse#876]
### Skin section

Other

### Current Behavior

Hello team, when I use 4 "options tray" shortcuts, I get the icons shifted to the right and the texts superimposed.

### Expected Behavior

Is it possible to refocus, balance the gaps and slightly move the icons apart so as to delay the potential superposition?

### Steps To Reproduce

...

### Screenshots and Additional Info

![Capture d'écran 2024-05-12 152052](https://github.com/jurialmunkey/skin.arctic.fuse/assets/39261054/214b15c6-63cd-408b-a2db-44b836c9d644)

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
It is not possible to change the width depending on number of items. You will need to reduce the size of your labels.

**Comment by jurialmunkey** [comment]
Also not sure why you keep saying I'm a "team". 

I'm a person, not a team. I don't have a secretary or other people working for me... lol.

Other than translations, I do practically all the work on this skin myself.

**Comment by OfficerKD637** [comment]
Really sorry to comment on a closed issue, but this commit actually breaks the option tray if it has 5 items and the labels disabled. The first item is almost at the left edge and the highlight selector overlay goes outside the side menu.

**Comment by Bindou01** [comment]
> Also not sure why you keep saying I'm a "team".
> 
> I'm a person, not a team. I don't have a secretary or other people working for me... lol.
> 
> Other than translations, I do practically all the work on this skin myself.

I was seeing other names displayed in the bug fixes more often than usual.  I didn't look in detail.  Sorry for the confusion.  :D For me the problem is actually solved.  It's now perfect.  Thanks Jurial!

**Comment by Bindou01** [comment]
> Vraiment désolé de commenter un problème résolu, mais ce commit casse en fait la barre d'options si elle contient 5 éléments et les étiquettes désactivées. Le premier élément se trouve presque sur le bord gauche et la superposition du sélecteur de surbrillance sort du menu latéral.

Sorry this is causing a problem for you.  If you remove the disabled items, does the problem go away?

**Comment by OfficerKD637** [comment]
Yes I have removed an item (so currently 4 items now) and it works fine! Thank you!

**Comment by jurialmunkey** [comment]
Solution does not work. Will need to rethink.
