### ISSUE TITLE
Navigation problem with the back key in "previous" mode

### ISSUE THREAD

**Issue by Bindou01** [jurialmunkey/skin.arctic.fuse#878]
### Skin section

Widgets

### Current Behavior

With v0.7.2, the Fuse interface has never been so intuitive and fluid. Congratulations to Jurialmunkey and its community.

However, there remains a small navigation problem, with the return key in "previous" mode: when we are in the Widgets of a Hub (other than Home), pressing the return key leaves the hub and brings us back to the home page, instead of taking us back to the top to the list of categories. I don't think I've ever seen this report anywhere, I hope I'm not mistaken.

### Expected Behavior

Should the behavior be the same in all hubs?

### Steps To Reproduce

Open a hub, go to Widgets, and press return...

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by Bindou01** [comment]
And @jurialmunkey, I haven't found any information regarding the disappearance of the "return to top of the widget list" when pressing the return key. It was so practical. Is this a bug, or a choice?

**Comment by woodside007** [comment]
+1 on the widget stack returning to the top widget on back press. Right now you either have to press multiple up keys to get to the top of the widget stack or back to the category list and left or right then back on to the original category you were on to get the widget stack to reset to the top widget. It's either three key presses or ten if you have that many widget rows (I think I have about seven) just to get the widget stack to reset to the top. If you're on the bottom widget and you press back, you land on the category list but the last widget you were on remains as the top widget under the category list.  Please fix.

**Comment by Bindou01** [comment]
> +1 on the widget stack returning to the top widget row on back press. Right now you either have to press multiple up keys to get to the top of the widget stack or back to the category list and left or right then back on to the original category you were on to get the widget stack to reset to the top widget row. It's either three key presses or ten if you have that many widget rows (I think I have about seven) just to get the widget stack to reset to the top. If you're on the bottom widget and you press back, you land on the category list but the last widget you were on remains as the top widget under the category list. Please fix.

@jurialmunkey 
Is it useful to open a conversation about this?
