### ISSUE TITLE
[Feature] Adding a logo of the network name

### ISSUE THREAD

**Issue by test01203** [jurialmunkey/skin.arctic.fuse#88]
### Skin section

Fullscreen Video OSD

### Feature description

When playing a movie or series, information about the network where the movie or series is located will appear in the movie's announcement section

### Why is this feature needed? Please justify and explain.

The part adds a lot of interest to the skin

### Screenshots and Additional Info

![image](https://github.com/jurialmunkey/skin.arctic.fuse/assets/104188844/dc8e93ba-0a15-4822-b51f-114c5a29b0e4)
An example of what it looks like

### Checklist

- [X] I have made a separate issue for each feature I am requesting.
- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by test01203** [comment]
![image](https://github.com/jurialmunkey/skin.arctic.fuse/assets/104188844/aaec32d2-4a86-4333-b619-fc31b8c382d1)
like that

**Comment by jurialmunkey** [comment]
My screenshot IS on the OSD!

Press the info button either on your remote or from the OSD controls and you can see that info.

**Comment by test01203** [comment]
> My screenshot IS on the OSD!
> 
> Press the info button either on your remote or from the OSD controls and you can see that info.

But that's exactly the problem.. I suggest something better - that we don't have to click information and see all this information..
In the film itself above, a large logo is beautiful and much more accessible
You won't really see anyone click it in the middle of the movie

**Comment by jurialmunkey** [comment]
And I disagree
