### ISSUE TITLE
Clearlogo on Episodes. 

### ISSUE THREAD

**Issue by adamosborne83** [jurialmunkey/skin.arctic.fuse#881]
### Skin section

Widgets

### Current Behavior

Hi J, hope you're well. I know you're keeping awfully busy.

This might be intended, but hoping a bug... clearlogo seems to have changed on episodes now.

### Expected Behavior

To stay the same throuought 

### Steps To Reproduce

As you can see in the video, the Star Trek Clearlollgo stays the same, until it gets the the episode menu, then it just looks 'tacky' personal opinion ofcourse, maybe something to do with the addon I use?

### Screenshots and Additional Info

https://github.com/jurialmunkey/skin.arctic.fuse/assets/78307374/cd91fea9-4661-41dc-a4d2-26f6a487610f

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
I haven't changed how clearlogo are handled in the skin.

Artwork comes from the library/plugin in use. Tmdbhelper will do a lookup if there isnt artwork set for the item, but only if there wasn't artwork already supplied.

There was a small change in how tmdbhelper reads artwork from disk to allow it to support smb and nfs shares. I don't think it would cause this, but you could try rolling back to the version before last of TMDbhelper to confirm (make sure to restart after installing).

If it still happens with the previous from last version of TMDbhelper then it is almost certainly the addon you're using.

**Comment by jurialmunkey** [comment]
Actually, an even simpler way to check if it's the addon supplied artwork is to open info on the item, then go to artwork button and click it. That should show you all the artwork types and what artwork it is attached to the item via the addon you're using.

**Comment by adamosborne83** [comment]
> Actually, an even simpler way to check if it's the addon supplied artwork is to open info on the item, then go to artwork button and click it. That should popup a dialog to show you all the artwork types and what artwork it is attached to the item via the addon you're using.

Thanks, I'll have a look a little later, this has only just started happening. I'll let you know accordingly.

**Comment by adamosborne83** [comment]
> Actually, an even simpler way to check if it's the addon supplied artwork is to open info on the item, then go to artwork button and click it. That should popup a dialog to show you all the artwork types and what artwork it is attached to the item via the addon you're using.

So rolled back to this version

https://github.com/jurialmunkey/plugin.video.themoviedb.helper/tree/9dbe49cadf86c94a93f3f595e9ea79b7c9debe65


All OK again. If you need anything, let me know.

**Comment by adamosborne83** [comment]
This is really odd, I've checked all settings in Umbrella and TMDBh.
Rolled back Af,tmdbh and umbrella. Spoke to Umbrella, no change in how he pulls meta.
Still happening. I've changed widget styles the lot, this has only just happened too.
Seems like a me problem only though.

**Comment by adamosborne83** [comment]
https://github.com/jurialmunkey/skin.arctic.fuse/assets/78307374/d696d523-af71-4a19-86e2-18fa689c8217

**Comment by xyzfre** [comment]
Decided to check for you and if you disable Fanart in Umbrella settings and clear metadata cache it solves the issue.

**Comment by xyzfre** [comment]
![image](https://github.com/jurialmunkey/skin.arctic.fuse/assets/49699869/0ec17495-7449-492f-a990-d460954a2c3d)

**Comment by adamosborne83** [comment]
Haha... turned out was an update he did. My apologies for wasting value github space

**Comment by adamosborne83** [comment]
https://github.com/jurialmunkey/skin.arctic.fuse/assets/78307374/ee08a32f-c651-4473-86e7-a8261dbbe6c4



Ok does this make sense? Or is it my pluggin issue? Seems if series is flat, then clearlogo stays decent, if seasons are shown, then clear logo changes........

**Comment by jurialmunkey** [comment]
It is still going to be the addon.

The preference order for the artwork has been the same way for practically the entire existence of the skin. 

There's just really not much to it - either the item has a url/path to a clearlogo (in which case the skin displays it) or it hasn't set a clearlogo (in which case tmdbhelper tries to find one online).
