### ISSUE TITLE
Classic Mode Headers all set as "Home" 

### ISSUE THREAD

**Issue by JFG1000** [jurialmunkey/skin.arctic.fuse#884]
### Skin section

Other

### Current Behavior

Hi there on the latest update the headers for each section are all labeled "home" again even after being renamed, also whenever we reload the skin the first set of widgets it's focused on are completely dim until we navigate over them. 

Many thanks

### Expected Behavior

Usually when we rename each section, movies, shows etc it's labeled at the top as a header 

### Steps To Reproduce

Rename a section to what we choose. 

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
Works fine for me.

You must enable the group indicator for the header to change.

**Comment by JFG1000** [comment]
That worked thankyou

**Comment by JFG1000** [comment]
I've re opened this mate as the dim issue still persists.

**Comment by jurialmunkey** [comment]
Dim already has an issue open here: https://github.com/jurialmunkey/skin.arctic.fuse/issues/827

**Comment by JFG1000** [comment]
> Dim already has an issue open here: #827

Thanks and apologies I forgot I'd opened that. on that original post it says its only with move widget groups enabled, I've noticed I've does it with it disabled to.
