### ISSUE TITLE
🐛 Options tray positioning wrong with 5 items

### ISSUE THREAD

**Issue by Rinicko** [jurialmunkey/skin.arctic.fuse#898]
### Skin section

Widgets

### Current Behavior

After recent update. The options tray in the shutdown menu, when there are 5 items it shifts to the left with space on the right... as shown in screenshot
![Screenshot_20240518_111450_Gallery](https://github.com/jurialmunkey/skin.arctic.fuse/assets/169211354/51ab2c3a-7f91-46be-af87-ad1f6e1d36dd)

### Expected Behavior

It would normally fill up the space with all 5 items... 

### Steps To Reproduce

.Select 5 or more items for option tray
.Open shutdown menu

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by OfficerKD637** [comment]
Haha just mentioned this https://github.com/jurialmunkey/skin.arctic.fuse/issues/876#issuecomment-2118758852 in the commit that fixed the positioning for 2 and 4 items

**Comment by jurialmunkey** [comment]
Yeah I'm going to revert that change. Something weird is happening with that container -- numitems keeps giving 0 and checking values positionally is also acting weird. Not quite sure why.
