### ISSUE TITLE
[Feature] Clock, Date, and Weather in Header

### ISSUE THREAD

**Issue by r95sguy** [jurialmunkey/skin.arctic.fuse#9]
### Skin section

Home Widgets

### Feature description

The option to add Clock, Date and Weather in header

### Why is this feature needed? Please justify and explain.

nice to have

### Checklist

- [X] I have made a separate issue for each feature I am requesting.
- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by r95sguy** [comment]
I have added the time and date next to the main label as a workaround, and I think it works fine for me
![Screenshot 2023-07-23 1](https://github.com/jurialmunkey/skin.arctic.fuse/assets/113218125/e15f2d28-f168-4153-8aa8-b4051c85b966)

**Comment by DROIDshield** [comment]
Clock now in the bottom right is great but we lose the studios info.. but well it's a light skin so I guess something has to go. Great for the shield though.

**Comment by mmBesar** [comment]
I came to request it, so +1 here.

**Comment by C-O-D** [comment]
+1 from me too. I wouldn't even need the (in this case) 'home' since it's indicated on the left menu.
Above all, however, a permanent time display and especially playing now display are indispensable for me
