### ISSUE TITLE
[Feature] Progress indicators to show percentage 

### ISSUE THREAD

**Issue by r95sguy** [jurialmunkey/skin.arctic.fuse#90]
### Skin section

Home Widgets

### Feature description

Progress indicators to show percentage of current progress/ played

### Why is this feature needed? Please justify and explain.

Good to know the exact percentage of progress

### Checklist

- [X] I have made a separate issue for each feature I am requesting.
- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by jurialmunkey** [comment]
I tried this out but I found it wasn't clear what the number represents. It makes it look like it is a rating of some sort

![image](https://github.com/jurialmunkey/skin.arctic.fuse/assets/4618719/92c3031d-438f-4d79-9e8a-694012fe7e31)

**Comment by jurialmunkey** [comment]
Maybe a better approach would be an overlay tag

![image](https://github.com/jurialmunkey/skin.arctic.fuse/assets/4618719/c42258a9-3dd2-48f8-b173-8f6e8ef0ff18)


That way it also works with TV shows unwatched episode count

![image](https://github.com/jurialmunkey/skin.arctic.fuse/assets/4618719/fdd90d40-822b-494e-897c-7ae7d3764661)

**Comment by Rizhikk** [comment]
It looks very nice! Thank you! But for some reason this doesn’t work in the case of TV series, only with episodes and Movies.

**Comment by Rizhikk** [comment]
> > It looks very nice! Thank you! But for some reason this doesn’t work in the case of TV Shows, only with episodes and Movies.
> 
> Works fine for tvshows in my library.
> 
> Addons it will only work if they set the IsResumable flag.

Well, unfortunately, for some reason it doesn’t work for me...I don’t use addons, but use the widget that is located in Default Widgets-Tv Show-In progress. And on the left there is no information about the percentage( Maybe I need to add something to make it work?

**Comment by Rizhikk** [comment]
> > It looks very nice! Thank you! But for some reason this doesn’t work in the case of TV Shows, only with episodes and Movies.
> 
> Works fine for tvshows in my library.
> 
> Addons it will only work if they set the IsResumable flag.

Well, unfortunately, for some reason it doesn’t work for me...I don’t use addons, but use the widget that is located in Default Widgets-Tv Show-In progress. And on the left there is no information about the percentage( Maybe I need to add something to make it work?

**Comment by jurialmunkey** [comment]
It's working fine for me using that widget.

Are you on Nexus or Omega? I've only tested using Omega beta. Not sure if it works in Nexus. But definitely works for me in Omega for In-Progress shows without doing anything special (other than enabling the indicator of course!)


![image](https://github.com/jurialmunkey/skin.arctic.fuse/assets/4618719/30ca744e-6fdd-4083-8a40-a1eef4f1b9f1)

**Comment by Rizhikk** [comment]
> It's working fine for me using that widget.
> 
> Are you on Nexus or Omega? I've only tested using Omega beta. Not sure if it works in Nexus. But definitely works for me in Omega for In-Progress shows without doing anything special (other than enabling the indicator of course!)
> 
> 
> ![image](https://github.com/jurialmunkey/skin.arctic.fuse/assets/4618719/30ca744e-6fdd-4083-8a40-a1eef4f1b9f1)
> 

 The version of Kodi that is currently installed is, if I'm not mistaken, 20.2.. I apologize in advance. There's just no way to watch it right now. For me this wonderful function only works in the case of episodes and Movies🙂 This doesn't work for TV Shows. ![IMG_20231109_181212.jpg](https://github.com/jurialmunkey/skin.arctic.fuse/assets/150350281/1d7218cf-ab62-4ce5-9ae6-b23d8a0148a0)

![IMG_20231109_181304.jpg](https://github.com/jurialmunkey/skin.arctic.fuse/assets/150350281/3e2b1e12-644f-443f-ad2d-090fe6aee51f)

**Comment by Rizhikk** [comment]
I updated Kodi from Nexus to Omega and everything worked automatically! Sorry if anything. Looks incredible!)
