### ISSUE TITLE
:bug: Classic mode - Navigation bug

### ISSUE THREAD

**Issue by berkhornet** [jurialmunkey/skin.arctic.fuse#908]
### Skin section

Widgets

### Current Behavior

Setup:
- Classic Mode
- Side Menu > Minimise set to Library
- Content > Back set to Previous, Parent or Menu
- Menu > Left set to None
- 5 Side Menu Items set

For side items 2, 3 and 4, having pressed "right" to focus on widgets, pressing "back" results in the focus being on the wrong Side Menu item (if selecting widgets from Side Item 2, focus is returned to Side Item 3; 3 to 4 and 4 to 5). Selecting widgets from Side Menu item 1 or 5 and then pressing "back" results in the correct focus.

Similar behaviour happens when Side Menu > Minimise is ser to Topbar

### Expected Behavior

Pressing "back" from widgets should focus on the correct Side Menu item

### Steps To Reproduce

See "Current Behaviour"

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
Make sure you don't have disabled items inbetween or above. Any disabled sidemenu items must be placed at the end.

**Comment by berkhornet** [comment]
Thank you!
