### ISSUE TITLE
Intermittent navigation bug with the function back to the top.

### ISSUE THREAD

**Issue by Bindou01** [jurialmunkey/skin.arctic.fuse#909]
### Skin section

Widgets

### Current Behavior

When I am on the last Widget of one of the categories, clicking back does not take me back to the top, it has no effect.  While on other Widgets it works perfectly, it takes you back to the list of categories.  But be careful, this does not happen in all categories.  This bug appears in only one of the categories, and strangely, it regularly changes categories.  (I do not know if I'm clear ?)

### Expected Behavior

...

### Steps To Reproduce

...

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
I cannot reproduce this issue. 

The description of how to reproduce is very vague.

**Comment by Bindou01** [comment]
> I cannot reproduce this issue.
> 
> The description of how to reproduce is very vague.

Today I was unable to reproduce it.  If it doesn't happen again before tomorrow, I will delete this request.
