### ISSUE TITLE
Issue with back function in TMDb Helper series navigation.

### ISSUE THREAD

**Issue by Bindou01** [jurialmunkey/skin.arctic.fuse#910]
### Skin section

TMDB Helper navigation 

### Current Behavior

I reported the following bug _"when I am in a Hub made up of Widgets from the TMDb Helper series, if I enter a Season, and I want to leave it, the return click not only leaves the season folder, but we  returns to the top Widgets (on the list of categories) directly_ " 

This bug has only been partially fixed.  This only works if you focus on the thumbnails.  But if we are positioned on the bottom tab "Season 1", nothing happens when you press the back key.  I feel like the next one will finally be the right one :D Many thanks Jurial !

### Expected Behavior

...

### Steps To Reproduce

...

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by Bindou01** [comment]
@jurialmunkey 
This time it looks good, finally 99%.  ^^ I don't know if you can do otherwise, but if we click on "return" while the page has not completely loaded.  We come across this...
![Uploading 20240520_113321.jpg…]()

**Comment by Bindou01** [comment]
@jurialmunkey 
This time it looks good, finally 99%.  ^^ I don't know if you can do otherwise, but if we click on "return" while the page has not completely loaded. We come across this...

![20240520_113321](https://github.com/jurialmunkey/skin.arctic.fuse/assets/39261054/cb5f70bf-1980-47ad-9446-7a1ef6d4938d)

**Comment by Bindou01** [comment]
@jurialmunkey 
Furthermore, I note that if it does indeed work perfectly most of the time, in fact, unfortunately it does not work the first time.  Let me explain, if we leave the Hub, then come back, the bug returns (if we click on return from the episode navigation, it takes us directly to the top in the list of categories).  Whereas if we then do it again, it works, all the time, until we come out and come back to the hub.  Really sorry again to bore you with this, we have never been so close to success. 
THANKS 🙏

**Comment by Bindou01** [comment]
@jurialmunkey 
Do I need to recreate a topic?

**Comment by xyzfre** [comment]
https://github.com/jurialmunkey/skin.arctic.fuse/assets/49699869/21775db9-40a9-429a-8f3a-2834899db1d5  is this what you mean? it works the same way when I go into my TV show hub

**Comment by xyzfre** [comment]
is this what you mean? it works the same way when I go into my TV show hub

**Comment by Bindou01** [comment]
> @jurialmunkey Furthermore, I note that if it does indeed work perfectly most of the time, in fact, unfortunately it does not work the first time. Let me explain, if we leave the Hub, then come back, the bug returns (if we click on return from the episode navigation, it takes us directly to the top in the list of categories). Whereas if we then do it again, it works, all the time, until we come out and come back to the hub.
> 
> Really sorry again to bore you with this, we have never been so close to success. THANKS 🙏

So indeed after yet another reboot, the problem I talked about above no longer occurs at all.  Odd.  But that’s so much the better! :D

**Comment by Bindou01** [comment]
> @jurialmunkey Merci beaucoup Jurial. 🙏 Cette fois, ça s'annonce bien, enfin à 99%. ^^ Je ne sais pas si vous pouvez faire autrement, mais si on clique sur "retour" alors que la page n'est pas complètement chargée. On tombe sur ça...
> 
> ![20240520_113321](https://private-user-images.githubusercontent.com/39261054/332017059-cb5f70bf-1980-47ad-9446-7a1ef6d4938d.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYzMDI3NzksIm5iZiI6MTcxNjMwMjQ3OSwicGF0aCI6Ii8zOTI2MTA1NC8zMzIwMTcwNTktY2I1ZjcwYmYtMTk4MC00N2FkLTk0NDYtN2ExZWY2ZDQ5MzhkLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIxVDE0NDExOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlhYTdmNDc4YTRjNWYzZDA1ZTkyNzdhNjc3MTdjMDQ5YTgxMGZhYjFjZGRjYzFlYjhlM2NhY2RiYTk1MDM2ZmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Hfz-bCRq1oRrT4gY3snQfVTBUExWOYWxj-B4T5jEg00)

However, the problem I am reporting here still occurs.  If you click on return a little too quickly, it opens this page.

-> 
https://photos.app.goo.gl/K5V3dNZPzeJ5HPXv7

**Comment by xyzfre** [comment]
That is a Different issue. You are using a different view type than me. Looks like you're using combine season ,I use poster for TV shows and landscape for seasons,maybe you should try to change view type and see if the issue still occurs.

**Comment by Bindou01** [comment]
Okay, that's not happening.  So I'm going to open a new topic.

**Comment by xyzfre** [comment]
I don't mean change view type permanently just to check ,it could be a issue with specific view types and that could help narrow it down.

**Comment by Bindou01** [comment]
Thanks for your help, I was able to refine it : https://github.com/jurialmunkey/skin.arctic.fuse/issues/915
