### ISSUE TITLE
When inside a hub going all the way down to the last widget explore mode causes A skin reload

### ISSUE THREAD

**Issue by xyzfre** [jurialmunkey/skin.arctic.fuse#911]
### Skin section

Widgets

### Current Behavior

After the recent update, I notice when inside a hub scrolling all the way down to your last widget to you hit explorer mode pressing the return key causes a skin reload, this does not happen when you’re in home hub.

### Expected Behavior

When scrolling down to your last widget to you hit explore mode and push the back button for the skin not to do a reload.

### Steps To Reproduce

Enter one of your hubs/scroll down all the way to your last widget to you hit explorer mode/push the back button when it reaches categories the skin reloads

### Screenshots and Additional Info

//

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by xyzfre** [comment]
https://github.com/jurialmunkey/skin.arctic.fuse/assets/49699869/71ceddea-9bde-4bbc-9bb1-375dc23e327e

**Comment by Bindou01** [comment]
Maybe a link with the last two bugs I noticed?

**Comment by xyzfre** [comment]
Possibly, it started happening on my end just after this recent update was working fine yesterday, @jurialmunkey hopefully can fix this issue or if we can have a bump feature for the hubs in complex mode

**Comment by xyzfre** [comment]
@jurialmunkey earlier today when I did the update, didn't get a chance to play anything but now that I check every time I watch ,example TV show and hit stop. It also causes a reload for that specific hub.

**Comment by xyzfre** [comment]
Thank you @jurialmunkey for your AMAZING work ,love AF best skin ever💯
