### ISSUE TITLE
Latest navigation problem with the back key.

### ISSUE THREAD

**Issue by Bindou01** [jurialmunkey/skin.arctic.fuse#915]
### Skin section

Library

### Current Behavior

Hi Jurial, I don't know if you can do otherwise, but know that if we click on "return" while the page is not completely loaded (with this view specifically) we come across this... 
https://photos.app.goo.gl/xrf79HUG8afQd7US7

This is the  last navigation bug I noticed.  Thank you very much for everything 🙏

### Expected Behavior

...

### Steps To Reproduce

...

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
Nothing to do with back key.

Kodi simply reloading container. Nothing can be done about it. Not controlled by the skin.
