### ISSUE TITLE
:bug: No access to side widgets from Spotlight slide if there are no categories.

### ISSUE THREAD

**Issue by Gl17chV** [jurialmunkey/skin.arctic.fuse#918]
### Skin section

Mouse and Touch

### Current Behavior

When Spotlight > Slide is enabled, widgets cannot be accessed without a category bar, and the same occurs when Categories > Detailed is activated. When categories are set to Basic or Icon, simply clicking the bottom center of the screen allows access.

### Expected Behavior

Access side widgets with a click

### Steps To Reproduce

1 - Slide Spotlight
2 - Click on the bottom center

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
I can't reproduce this issue. It works fine for me on mouseover with or without categories.

There is some aspect of the steps to reproduce missing here.

**Comment by Gl17chV** [comment]
I get it, thanks anyway :)
