### ISSUE TITLE
[BUG] Reg. Episodes text under video info dialog for TV Shows

### ISSUE THREAD

**Issue by AakashC2020** [jurialmunkey/skin.arctic.fuse#92]
### Skin section

Video Info Dialog

### Current Behavior

Hi @jurialmunkey,

After the latest update the video info screen of TV Shows have this entry for Episodes -> * All seasons as shown in the screenshot below. Don't you think it looks a bit weird? Please advise.

### Expected Behavior

As described.

### Steps To Reproduce

As described.

### Screenshots and Additional Info

![IMG_20230809_141019](https://github.com/jurialmunkey/skin.arctic.fuse/assets/65297828/c5a81f14-9174-4d27-b2e7-f4f2d0bb67b5)

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
If you focus it, it will show you all the episodes for the tvshow -- it does what it says it does.

**Comment by AakashC2020** [comment]
> If you focus it, it will show you all the episodes for the tvshow -- it does what it says it does.

Apologies, I wrote too soon without checking properly. Yes, it looks really great when focused. Thank you!

One off the topic question, in the latest update you've mentioned "On left Discover". Could you please let me know how to use that new feature?

**Comment by AakashC2020** [comment]
One off the topic question, in the latest update you've mentioned "On left Discover". Could you please let me know how to use that new feature?

This one:

![IMG_20230809_151707](https://github.com/jurialmunkey/skin.arctic.fuse/assets/65297828/833a2164-9411-4f23-b03a-8251365dc2ae)
