### ISSUE TITLE
Shadow on the image when the video player OSD appears.

### ISSUE THREAD

**Issue by Bindou01** [jurialmunkey/skin.arctic.fuse#920]
### Skin section

Video OSD

### Current Behavior

Hi Jurial,
The Clear Logo shadow remains, even if Clear Logo is deactivated.  This shadow which extends in the middle of the image is particularly annoying for fast forwards, when looking for a scene which takes place at night for example.

### Expected Behavior

However, I think that the best solution would be to distinguish different parameters for fast forward (with left/right click) from the total display (with OK click), so as to minimize the OSD when moving forward, and be not obstruct the image. While information such as the movie title (and the shadow behind it) should be displayed when pressing OK to navigate the OSD.

### Steps To Reproduce

...

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
This is not a bug. It is intentional. Without dimming the background, the osd controls are practically impossible to view on a bright/busy background or when subtitles are visible.

![screenshot00565](https://github.com/jurialmunkey/skin.arctic.fuse/assets/4618719/72415064-d0bd-4fbf-9188-c894e9127f93)


![screenshot00568](https://github.com/jurialmunkey/skin.arctic.fuse/assets/4618719/ad17d563-4375-442f-83bb-2df9df0d70f0)

**Comment by Bindou01** [comment]
> Ce n'est pas un bug. C'est intentionnel. Sans atténuer l'arrière-plan, les commandes osd sont pratiquement impossibles à visualiser sur un arrière-plan clair/occupé ou lorsque les sous-titres sont visibles.
> 
> ![capture d'écran00565](https://private-user-images.githubusercontent.com/4618719/333843138-72415064-d0bd-4fbf-9188-c894e9127f93.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY3MDkwNzksIm5iZiI6MTcxNjcwODc3OSwicGF0aCI6Ii80NjE4NzE5LzMzMzg0MzEzOC03MjQxNTA2NC1kMGJkLTRmYmYtOTE4OC1jODk0ZTkxMjdmOTMuanBnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUyNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MjZUMDczMjU5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZDUwNmEzYWI1ZDM0MDkxY2QyMGFiYTI3ZTYyYWNhMzZiYTI5YTVjOWM2NmFiZjU2YjI3YzMxNjFjZDhlN2EwZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.yUNskg3hI2acXdVsFvomguRoOVTS_MVc150cr3MIvEs)
> 
> ![capture d'écran00568](https://private-user-images.githubusercontent.com/4618719/333843147-ad17d563-4375-442f-83bb-2df9df0d70f0.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY3MDkwNzksIm5iZiI6MTcxNjcwODc3OSwicGF0aCI6Ii80NjE4NzE5LzMzMzg0MzE0Ny1hZDE3ZDU2My00Mzc1LTQ0MmYtODNiYi0yZGY5ZGYwZDcwZjAuanBnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUyNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MjZUMDczMjU5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NmY4ZGU5NzFkZTQ0ZGZkOTZmNGIyNDQ2ZDkzYWJlYjFiYzliOGNkOGZhYjRmNDI5NGY5OGM4ZjhjYTU3YzZlNCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.xPL-4T-y_RugHL8KG45RWjglg8kAza-Hy1lghC-yQhU)

Of course, shade is essential. What I mean is that the shadow also extends to the left center of the image, where the title/Clear Logo is located, even when Clear Logo is turned off. Consequently, this prevents you from seeing the content of the film, which is annoying when fast forwarding when searching for a scene, especially when the scene is dark. We have to wait for the OSD to disappear to see better.

And as I said, I find that the presence of the Clear Logo is on the other hand very relevant when you display the complete video OSD, by pressing "OK".

**Comment by Bindou01** [comment]
> Ce n'est pas un bug. C'est intentionnel. Sans supprimer l'arrière-plan, les commandes osd sont pratiquement impossibles à visualiser sur un arrière-plan clair/occupé ou lorsque les sous-titres sont visibles.
> 
> ![capture d'écran00565](https://private-user-images.githubusercontent.com/4618719/333843138-72415064-d0bd-4fbf-9188-c894e9127f93.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY3MDkwNzksIm5iZiI6MTcxNjcwODc3OSwicGF0aCI6Ii80NjE4NzE5LzMzMzg0MzEzOC03MjQxNTA2NC1kMGJkLTRmYmYtOTE4OC1jODk0ZTkxMjdmOTMuanBnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUyNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MjZUMDczMjU5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZDUwNmEzYWI1ZDM0MDkxY2QyMGFiYTI3ZTYyYWNhMzZiYTI5YTVjOWM2NmFiZjU2YjI3YzMxNjFjZDhlN2EwZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.yUNskg3hI2acXdVsFvomguRoOVTS_MVc150cr3MIvEs)
> 
> ![capture d'écran00568](https://private-user-images.githubusercontent.com/4618719/333843147-ad17d563-4375-442f-83bb-2df9df0d70f0.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY3MDkwNzksIm5iZiI6MTcxNjcwODc3OSwicGF0aCI6Ii80NjE4NzE5LzMzMzg0MzE0Ny1hZDE3ZDU2My00Mzc1LTQ0MmYtODNiYi0yZGY5ZGYwZDcwZjAuanBnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUyNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MjZUMDczMjU5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NmY4ZGU5NzFkZTQ0ZGZkOTZmNGIyNDQ2ZDkzYWJlYjFiYzliOGNkOGZhYjRmNDI5NGY5OGM4ZjhjYTU3YzZlNCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.xPL-4T-y_RugHL8KG45RWjglg8kAza-Hy1lghC-yQhU)

Of course, shade is essential. What I mean is that the shadow also extends to the left center of the image, where the title/Clear Logo is located, even when Clear Logo is turned off. Consequently, this prevents you from seeing the content of the film, which is annoying when fast forwarding when searching for a scene, especially when the scene is dark. We have to wait for the OSD to disappear to see better.

And as I said, I find that the presence of the Clear Logo is on the other hand very relevant when you display the complete video OSD, by pressing "OK".

**Comment by jurialmunkey** [comment]
The shadow is needed to extend from top left to bottom right in a curve to ensure that the top left header is also visible.

**Comment by Bindou01** [comment]
> The shadow is needed to extend from top left to bottom right in a curve to ensure that the top left header is also visible.

Yes I understand.  However, with Estuary, we do not find this problem.  Probably because Estuary displays the Clear Logo small in the top bar.  I understand that you want to keep this style specific to Fuse.  Is it not possible to display the Clear Logo in small size when fast forwarding (partial display of the Video OSD with a press on the left or right arrow), and leave it in full screen as you do?  have done, but only in "full" display of the video OSD (when you press the OK key)?  Finally suppose you can generate a different shadow based on these two posters...?
