### ISSUE TITLE
Cannot shutdown :bug: Short Description

### ISSUE THREAD

**Issue by EnricoSanchez** [jurialmunkey/skin.arctic.fuse#923]
### Skin section

Widgets

### Current Behavior

I can not shutdown, if i press power Button on Option tray, nothing happens 
On RPi4 Liebreelec 12 kodi Omega 

How should i restrart or power down? 

### Expected Behavior

? Shouldnt it show power Menü? 
System should Restart or power down.  

### Steps To Reproduce

1 open Option tray 2 klick power icon. 3 nothing happens 

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
By default the button with the power icon does the `Quit()` command which closes Kodi. You can change this to a different command in the widget customisation screen from Skin Settings. The options menu can be configured at the bottom of the screen.
