### ISSUE TITLE
Title Changed

### ISSUE THREAD

**Issue by truth7seeker** [jurialmunkey/skin.arctic.fuse#924]
### Skin section

Widgets

### Current Behavior

When changing between widgits, each of the title menus use to say TV Shows and Movies, etc, now they all show as Home as in this picture, any ideas?

![20240527_184734](https://github.com/jurialmunkey/skin.arctic.fuse/assets/156481990/818ed3d4-5953-400b-b178-f237282b5f29)

### Expected Behavior

Should be saying the name of the menu I named them, such as TV Shows and Movies

### Steps To Reproduce

I don't know this is completely unexpected, I am simply scrolling and it won't change back. 

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
Skin settings - menu - group indicator.

**Comment by truth7seeker** [comment]
I was about to close this, my spotlight even though I was on classic had gotten turned off, that was able to fix it for me.

**Comment by L0bsang** [comment]
> I was about to close this, my spotlight even though I was on classic had gotten turned off, that was able to fix it for me.
> 
> Thank you for your kind response.

Are there now spotlights in classic mode? I thought that wasn't possible.

I have been using complex mode for the spotlight feature. However my household quite enjoys the continuous scrolling from widget group to widget group, which is only available in classic mode.
