### ISSUE TITLE
:bug: History beneath the Discover text field is buggy. Selected term becomes invisible.

### ISSUE THREAD

**Issue by OfficerKD637** [jurialmunkey/skin.arctic.fuse#926]
### Skin section

Widgets

### Current Behavior

Hey Jurial!

The new design looks awesome! Both Search and Discover feel much more cohesive now!

There's a bug in the history bar beneath the Discover text field. The highlighted term becomes invisible instead of the underline that used to show up in earlier versions.

Example: You have 3 previously searched movies saved in your discover history. When you bring your cursor to the history row, only 2 items are visible (which are pushed to the right) and there's a blank space where the first term should be.

### Expected Behavior

Visibility and the underline beneath the history text like earlier to make it easier to select.

### Steps To Reproduce

1.  Go to the Discover hub
2.  Search for a few movies/tv shows (3 should do the job)
3.  Try selecting one of the previously searched terms from the history bar beneath the text field

### Screenshots and Additional Info

![IMG_2760](https://github.com/jurialmunkey/skin.arctic.fuse/assets/167294806/39044a65-d763-4b3e-8c54-a74282c005a5)

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by xyzfre** [comment]
My apologies but off-topic what font styles are you using? Looks really nice.

**Comment by jurialmunkey** [comment]
I can't reproduce. Works fine for me.

![screenshot00572](https://github.com/jurialmunkey/skin.arctic.fuse/assets/4618719/a28404b4-73e6-4b9d-8dcf-fc0802886837)

**Comment by jurialmunkey** [comment]
Unrelated. It's not got anything to do with skin variables. It is a rendering issue of some kind not displaying the control.

**Comment by OfficerKD637** [comment]
> Unrelated. It's not got anything to do with skin variables. It is a rendering issue of some kind not displaying the control.
> 
> Can I have a proper debug log please?

I thought maybe webOS is the issue so I tried installing it on Windows and the same thing happens. This is the unmodified skin (default font, no changes to any XML files, etc.). There is one 3rd party plugin installed just for testing so I'm sorry about that.

Here's the log: https://paste.kodi.tv/femusanifa.kodi

**Comment by jurialmunkey** [comment]
> 21.90.700

Why are you using Kodi nightlies? Please use Omega.

**Comment by OfficerKD637** [comment]
> > 21.90.700
> 
> Why are you using Kodi nightlies? Please use Omega.
> 
> If this doesn't occur on proper Omega stable release then it relates to change in alpha version of Kodi for togglebutton and should be reported on Kodi github.

Yeah you were right. I downloaded the stable release and it works perfectly fine. I was using a nightly on my main device (webOS) to get the 'Dolby Vision compatibility mode' that converts P7 to P8. 

Will report this on their github. 

Thank you so much for helping me with this!

**Comment by OfficerKD637** [comment]
If you don't mind answering one more question, what exactly should I report on their github? Just that the 'togglebutton' in their alpha versions are buggy? or it's causing compatibility issues in some Omega skins?

**Comment by xyzfre** [comment]
> I can't reproduce. Works fine for me.
> 
> 
> 
> ![screenshot00572](https://github.com/jurialmunkey/skin.arctic.fuse/assets/4618719/a28404b4-73e6-4b9d-8dcf-fc0802886837)
> 
> 

My apologies @jurialmunkey off-topic from this issue,I noticed in your pic on the left-hand side the logo says the Kodi version and nothing about profile. Is there a setting to make it look this way?

**Comment by jurialmunkey** [comment]
> If you don't mind answering one more question, what exactly should I report on their github? Just that the 'togglebutton' in their alpha versions are buggy? or it's causing compatibility issues in some Omega skins?

@OfficerKD637 

It's a togglebutton using `<width>auto</width>` 

However, I couldn't reproduce the issue with any of the recent nightly versions, so if you're downloading a custom compiled build from somewhere then it might be an issue with that build rather than Kodi itself. I'd make sure to try with the versions from Kodi downloads page first and make sure you can actually reproduce it with those.

> My apologies @jurialmunkey off-topic from this issue,I noticed in your pic on the left-hand side the logo says the Kodi version and nothing about profile. Is there a setting to make it look this way?

This is with the footer disabled and down set to filter.

**Comment by OfficerKD637** [comment]
> > If you don't mind answering one more question, what exactly should I report on their github? Just that the 'togglebutton' in their alpha versions are buggy? or it's causing compatibility issues in some Omega skins?
> 
> 
> 
> @OfficerKD637 
> 
> 
> 
> It's a togglebutton using `<width>auto</width>` 
> 
> 
> 
> However, I couldn't reproduce the issue with any of the recent nightly versions, so if you're downloading a custom compiled build from somewhere then it might be an issue with that build rather than Kodi itself. I'd make sure to try with the versions from Kodi downloads page first and make sure you can actually reproduce it with those.


The issue is only with nightlies downloaded from the 'master' branch (the one that incorporates the Dolby Vision compatibility mode). 
If I download a nightly from the 'Omega' branch, everything works fine.

**Comment by jurialmunkey** [comment]
@OfficerKD637 - Ah I see, I overlooked that it was Kodi 22 not 21 in the log (I initially tried with Omega nightlies). Yep I can reproduce with latest nightlies from master branch for Kodi P

Reported in issue thread above with a simply test case for Estuary (so it definitely isn't skin specific).

**Comment by OfficerKD637** [comment]
> @OfficerKD637 - Ah I see, I overlooked that it was Kodi 22 not 21 in the log (I initially tried with Omega nightlies). Yep I can reproduce with latest nightlies from master branch for Kodi P
> 
> 
> 
> Reported in issue thread above with a simply test case for Estuary (so it definitely isn't skin specific).

Thank you so much for taking the time to recreate it in Estuary and reporting it to them. 
I know how strict they can be with their rules, so it would have been pretty difficult for me to recreate this issue with the default skin, addons, settings, etc. and then report it to them.

You truly go above and beyond for this community and I can't thank you enough for that.
