### ISSUE TITLE
:bug: Single back button press does not move focus

### ISSUE THREAD

**Issue by vella9** [jurialmunkey/skin.arctic.fuse#929]
### Skin section

Widgets

### Current Behavior

layout = complex
content>back=parent (works fine when set to menu)
spotlight and widgets (Sidemenu) only

with the above settings, first back press from any widget row does nothing. Second back press works fine and takes you to respective side menu item. This is only from widgets, if focus is on spotlight, it works fine. 

### Expected Behavior

focus should move to side menu item upon first back button press.

### Steps To Reproduce

same as Current Behavior.

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
I was maybe overthinking it a bit before. Found a simple solution that appears to work well. 

Only thing I wonder is if it would be more natural to go back to Spotlight first instead of straight to menu.

**Comment by vella9** [comment]
thank you jurial.

> Only thing I wonder is if it would be more natural to go back to Spotlight first instead of straight to menu.

I do not think that parent would be the spotlight in this case, right?

However, both options are fine for me.

thanks again!

**Comment by jurialmunkey** [comment]
> I do not think that parent would be the spotlight in this case, right?

Yeah it's definitely the more "correct" place to land, which is why I went with that. It just felt a bit weird when I was testing with it going diagonally rather than straight up, if that makes sense.

Less noticable if menu is either topbar or not set to minimise because there isn't the menu unhide slide animation causing extra movement. But when it goes from hidden to unhidden it feels a bit weird is all.

**Comment by L0bsang** [comment]
Was coming here to report this issue and am glad I looked around a bit first. Was potentially prepared to accept it as a side-effect of complex mode with no categories.

Thanks for reporting it @vella9 and thanks for fixing it in the latest commit @jurialmunkey!
