### ISSUE TITLE
Clock definitely not in the righ position!

### ISSUE THREAD

**Issue by DROIDshield** [jurialmunkey/skin.arctic.fuse#93]
### Skin section

Home Widgets

### Feature description

@jurialmunkey great seeing the clock on the home screen,  I so needed this feature but I think the only place for it is top right, its the only clock in our living room so its the main focus when looking for content to play but as it has been moved up it overlaps widget text.

See images.

### Why is this feature needed? Please justify and explain.

The main clock the living room, while looking for an item, everyone always want to know what time it is... 

### Screenshots and Additional Info

See both images. 
![20230809_110247](https://github.com/jurialmunkey/skin.arctic.fuse/assets/97023369/dfb725d3-beec-4b50-a358-662062882145)
![20230809_110233](https://github.com/jurialmunkey/skin.arctic.fuse/assets/97023369/ce5cd500-8b43-4d14-94d5-c6f138231eef)

### Checklist

- [X] I have made a separate issue for each feature I am requesting.
- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by jurialmunkey** [comment]
This has already been fixed:
https://github.com/jurialmunkey/skin.arctic.fuse/commit/aa5f71400c7cbe23d1d1f5bd0054d83a3013b2f1

**Comment by jurialmunkey** [comment]
Top right will never be used.

**Comment by jurialmunkey** [comment]
To clarify, I'm still looking for a solution but top right is not it due to visibility on light backgrounds. I don't want to introduce any type of corner shadow like in AH2, so that space has to remain free.

**Comment by DROIDshield** [comment]
I / we will await your thoughts as even i can see this is a tricky one... keep doing what you do, well appreciated.
