### ISSUE TITLE
:bug: Icons not visible in active state with white highlight color

### ISSUE THREAD

**Issue by Professio73** [jurialmunkey/skin.arctic.fuse#932]
### Skin section

Widgets

### Current Behavior

In some cases a highlighted square widget doesn't get an inverted icon when the highlight color is set to "white". making the active state unviewable. It works on in certain other widgets but not consistently everywhere.

### Expected Behavior

A widget active state should only get a border/outline instead of a complete background highlight if a monochrome (white) color is chosen as a skin highlight color.

### Steps To Reproduce

1. Set "Customise highlight colours" to "White" in "Skin Settings -> Appearance" window
2. Browse on any view where the "Square" widget is used

### Screenshots and Additional Info

It doesn't seem to be an issue with a color or gradient highlight.

<img width="1710" alt="Screenshot 2024-05-29 at 14 38 43" src="https://github.com/jurialmunkey/skin.arctic.fuse/assets/80830038/083a05d4-3167-4843-a551-b553359f7d5a">
<img width="1710" alt="Screenshot 2024-05-29 at 14 37 58" src="https://github.com/jurialmunkey/skin.arctic.fuse/assets/80830038/191cba1b-7fdb-4d5b-b90f-a62425be5557">
<img width="1710" alt="Screenshot 2024-05-29 at 14 37 20" src="https://github.com/jurialmunkey/skin.arctic.fuse/assets/80830038/61616ff7-0e0f-45f5-a87d-fa388068353a">

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
The above commits should fix up default/genre icon colour inversion on the main layouts, and also the issue with the seams on the selectbox.

There's probably quite a few spots where I've missed including the colour inversion as it won't show up as an issue with other themes (because selected text is white in those and white is the default colour) -- so please let me know any other spots.

Also, side note slightly off topic, but the skin works best if you disable parent folder items. 
`Settings > Media > General > Show parent folder items (disable)`

**Comment by Professio73** [comment]
Thanks jurialmunkey! Works great now with icons 🙏. I will let you know if i find other spots where it's still an issue.

One thing i noticed however, right on the home screen now, is that poster widgets now get a dark overlay when highlighted. Surprisingly again only when the highlight color "white" is set in the skin settings ...

<img width="1710" alt="Screenshot 2024-05-30 at 15 44 32" src="https://github.com/jurialmunkey/skin.arctic.fuse/assets/80830038/671d5d0d-f03b-4064-88c4-7de5b5722e7e">

**Comment by jurialmunkey** [comment]
> One thing i noticed however, right on the home screen now, is that poster widgets now get a dark overlay when highlighted. Surprisingly again only when the highlight color "white" is set in the skin settings ...

Ah, I forgot that this was the issue originally with inverting the icon colour for default icons, which is why I didn't do it originally. I will have to consider a different approach.

**Comment by jurialmunkey** [comment]
It will still work for genres/countries/studios but will need to think of a different approach for the library node default icons.
