### ISSUE TITLE
Player

### ISSUE THREAD

**Issue by Romik2505** [jurialmunkey/skin.arctic.fuse#94]
### Skin section

Fullscreen Video OSD

### Feature description

No end time of the movie, episode on the player.

### Why is this feature needed? Please justify and explain.

It makes it easier to organize your time

### Checklist

- [X] I have made a separate issue for each feature I am requesting.
- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by jurialmunkey** [comment]
Duplicate of #32
