### ISSUE TITLE
:bug: Cant select a search item as action for categories or sidemenu items

### ISSUE THREAD

**Issue by Nervulox** [jurialmunkey/skin.arctic.fuse#941]
### Skin section

Widgets

### Current Behavior

Selecting a category, setting up its action for the on click event, chosing an addon search item and leaving it blank does nothing, doesnt change the category action.
(Happens with main menu items too)

### Expected Behavior

When selecting an addon search and leaving the search blank, the action should change to the search item and when selecting that category/menu item it should bring up the keyboard and lets us do a search.

### Steps To Reproduce

1. Go to skinn setting > Customize Widgets
2. Select a category and chose Action
3. Select Browse and navigate to any addon with a search
4. Select the search item and when the keyboard pops up, dont write anything and press ok

### Screenshots and Additional Info

It used to work a few months back, but i had to reinstall everything and now its not working, dont know since when.
The addon i need it to work with wont let us use the search bar to query it and its impossible to write the path manually because it looks literally like plugin://plugin.palantir3/Ewqe32edwe5efHY53QWd34SDFferqwer345dfKIj2...Kuy65TRfea3DFer43gErf43gf
Ive also tested it with the official kodi repository youtube addon, same behavior.
Tested chosing it when creating a TMDB player and works as expected so it SHOULDNT be Palantir's fault

Dont know if relevant but im using most recent version from the repository, on kodi 21, on LibreELEC 

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
Go to addon, long press select on the search folder to open context menu, choose "Menu" button with plus icon from side bar of context menu to add the folder to a menu.
