### ISSUE TITLE
:bug: Weird Widget behavior

### ISSUE THREAD

**Issue by rahaaatul** [jurialmunkey/skin.arctic.fuse#945]
### Skin section

Widgets

### Current Behavior

Gets stuck, and if you go down then go up, it disappears and keeps loading.

### Expected Behavior

It should hide the widget if there's no content available.

### Steps To Reproduce

1. Add a continue watching widget (must be empty)
2. Go to home widgets.
3. See the problem.

### Screenshots and Additional Info

https://github.com/jurialmunkey/skin.arctic.fuse/assets/86149861/075540e6-6d22-405e-8966-fed08b95ecc6

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
Need to make sure that the first widget is something which always has content. There is no way around this for classic mode. 

If you want the widget to fall back to other content, there is an option in skin variables for that. See discussion in this thread for more details https://github.com/jurialmunkey/skin.arctic.fuse/discussions/879#discussioncomment-9476974

**Comment by rahaaatul** [comment]
This is a let down.

What widget do you recommend to use as a fallback?
