### ISSUE TITLE
:bug: Freezing when open any Tv show to browse it

### ISSUE THREAD

**Issue by Mollver** [jurialmunkey/skin.arctic.fuse#948]
### Skin section

Widgets

### Current Behavior

When I choose a TV show and click on it, its freez (frame drop), I'm using omega 21 kodi and CCwGTV, that was not happening before 4 updates from now. It was open more smoothly 

### Expected Behavior

To open ore quick wirh out freezing (I'm aware of my device capabilities not that much but not to point for freezing like that.

### Steps To Reproduce

.

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
Did you enable wall in nav settings? Disable it.

I didn't change anything that would cause a freeze in the skin. This is either a change in your settings or your kodi install, not the skin.
