### ISSUE TITLE
:bug: Spotlight autoscroll doesn't stop when context menu or plot info is visible [Proposed Fix]

### ISSUE THREAD

**Issue by OfficerKD637** [jurialmunkey/skin.arctic.fuse#959]
### Skin section

Widgets

### Current Behavior

Hey Jurial!

Hope you're doing well!

After playing around with the spotlight a bit more, I noticed the carousel keeps going even after clicking the context menu button (button id=313) and having the context menu or subsequently clicking the plot side button to bring up the plot info. 

This feels a bit jarring when you're trying to read the plot of a movie and the autoscroll timer runs out and it switches to the next one.

Adding ` + !Window.IsVisible(DialogContextMenu.xml) + !Window.IsVisible(Custom_1113_Dialog_Plot.xml)` to the end of the condition [here](https://github.com/jurialmunkey/skin.arctic.fuse/blob/fbfadce4ed9c053ddf2d617f9db9592c5dd0fca9/1080i/Includes_Spotlight.xml#L78) has fixed the issue for me. 

_Optional: I also added `+ !Window.IsVisible(1170)` to stop the Spotlight from autoscrolling when the Options Tray is visible._

Let me know if this works!

### Expected Behavior

Spotlight autoscroll to stop when context menu or plot info is on screen.

### Steps To Reproduce

1. Create a complex setup with a Spotlight
2. Set a autoscroll time interval
3. Click on the context menu button in the spotlight

You'll notice the carousel behind the context menu doesn't stop.

Although clicking on anyone of the options like 'Select Player', 'Trakt Options' will take you to the correct film/show i.e. the one you pressed the context info button for, so this is more for visual coherence.

4. Once the context menu is visible, click on the Plot side button

This will bring up the Plot Info Window

This is more of a bigger fix since if you have the auto scroll interval to something low (like 5s or 8s) and you're trying to read the plot (and maybe you're a slow reader haha), it'll switch to the plot info of the next item as soon as the timer runs out.

Proposed fix: Adding ` + !Window.IsVisible(DialogContextMenu.xml) + !Window.IsVisible(Custom_1113_Dialog_Plot.xml)` to the end of the condition [here ](https://github.com/jurialmunkey/skin.arctic.fuse/blob/fbfadce4ed9c053ddf2d617f9db9592c5dd0fca9/1080i/Includes_Spotlight.xml#L78)

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
I don't think it should stop for options tray, but definitely should for plot and context. I also added trailer dialog and wikipedia, as I think we don't want it to change on those either.

**Comment by jurialmunkey** [comment]
The glitch is weird, but the autoscroll starting is expected because the dialog you're on isn't wikipedia, it's just DialogSelect (to "select" the wikipedia title to open).

Not sure what that glitch is though -- I would've just expected it to scroll to the next item.

**Comment by OfficerKD637** [comment]
Haha this is perfect! Cutting off the problem from its root is the best solution. 
I am actually learning a lot about skinning by just studying your commits.
