### ISSUE TITLE
[Feature] Porting the Discover feature to AH2

### ISSUE THREAD

**Issue by Mr-7mdan** [jurialmunkey/skin.arctic.fuse#96]
### Skin section

Other

### Feature description

Hi, 
Previously, i requested a feature on AH2 
https://github.com/jurialmunkey/skin.arctic.horizon.2/issues/864

And thanks to your efforts, the discover feature in Arctic Fuse covers what I was looking for. 

### Why is this feature needed? Please justify and explain.

Fuse and AH2, have distinct looks and both are arguably the best there is for kodi. 
I hope that both would be on the same levels from features-set perspective.
I know some features will be unique to each skin due to how each skin was built up. 

But porting the discover feature is so valuable to AH2. It will be worth it especially if it has its own xml.

Thanks

### Checklist

- [X] I have made a separate issue for each feature I am requesting.
- [X] I have searched the issues and this feature has not been requested.
- [X] I am using the most recent skin version.

**Comment by jurialmunkey** [comment]
No I won't be porting any features to AH2
