### ISSUE TITLE
:bug: Issue with Trailers both Spotlight and Information

### ISSUE THREAD

**Issue by vella9** [jurialmunkey/skin.arctic.fuse#964]
### Skin section

Widgets

### Current Behavior

Hi @jurialmunkey, thank you for the latest update, I just wanted to let you know since I noticed the following issues all related to Trailers;

Spotlight
1. When focus is on spotlight and you press back to go to side menu item while trailer is playing,  it looks like it triggers fullscreen for a split second and goes back to spotlight first item instead.
2. Once trailer finishes, it automatically starts again. I do not know if this is the intended behavior or not. Does it make sense to autoscroll to next item instead of starting same trailer again?
3. If you press the context menu button while a trailer is playing, the trailer stops, which is fine, but if you press back from the context menu, the trailer starts from the beginning. Can this be set to resume instead maybe? This can also apply to the information spotlight button, so when you press this button the trailer resumes/continues on the information page.

Information
1. When trying to view trailer fullscreen by pressing Trailer button in the information page, I am getting a black screen and no option to toggle fullscreen.

### Expected Behavior

Spotlight
1. pressing back should take you back to the side menu item I guess.
2. autoscroll to next item instead of starting same trailer again?
3. resume trailer after returning from context menu window and while accessing information page.

Information
1. option to toggle trailer to fullscreen.

### Steps To Reproduce

same as current behavior

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
> When focus is on spotlight and you press back to go to side menu item while trailer is playing, it looks like it triggers fullscreen for a split second and goes back to spotlight first item instead.

Nothing I can do. Kodi overrides back behaviour when playback is on. Back always toggles fullscreen from home window when the player has video or audio.

> Once trailer finishes, it automatically starts again. I do not know if this is the intended behavior or not. Does it make sense to autoscroll to next item instead of starting same trailer again?

No definitely not intended.

> If you press the context menu button while a trailer is playing, the trailer stops, which is fine, but if you press back from the context menu, the trailer starts from the beginning. Can this be set to resume instead maybe? This can also apply to the information spotlight button, so when you press this button the trailer resumes/continues on the information page.

Can't control this behaviour. If I set PlayMedia to resume then it will always resume, which is likely also not desired behaviour in some cases (e.g. half watched trailer a few days ago).

> When trying to view trailer fullscreen by pressing Trailer button in the information page, I am getting a black screen and no option to toggle fullscreen.

Please, separate issue threads per issue/bug. Hard for me to deal with four different items in one commit.

**Comment by jurialmunkey** [comment]
^^^ This commit should prevent the last played trailer from replaying, which, in a roundabout way, deals with the contextmenu issue (trailer will just stop and simply not restart after closing context menu -- which is probably a good idea anyway since contextmenu was likely used to do something like play the actual movie etc. and we don't want the trailer starting up again and overriding that).

Please open separate thread for issue in info and I'll look at it later.
