### ISSUE TITLE
:bug: Latest commit to allow Large Text vs Small Logo is breaking Clear Logo in the Discover hub

### ISSUE THREAD

**Issue by OfficerKD637** [jurialmunkey/skin.arctic.fuse#968]
### Skin section

Widgets

### Current Behavior

If you have Clearlogo enabled plus either of the text settings (large text + no logo OR small text + logo), the Discover hub keeps glitching and showing only the text.

Clearlogo works fine elsewhere in the Skin (like Spotlight or Widgets), but the Discover hub doesn't work well.

### Expected Behavior

Clearlogo applied throughout the skin.

### Steps To Reproduce

Set Title Clearlogo to Crop and Text settings to either of them

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
Works fine for me. Tried with both settings.

![screenshot00594](https://github.com/jurialmunkey/skin.arctic.fuse/assets/4618719/b28ea80a-a324-46f5-a297-912b5ddbaa04)

![screenshot00593](https://github.com/jurialmunkey/skin.arctic.fuse/assets/4618719/fff3ddfe-cb58-46b3-a4d7-614537048f41)

![screenshot00595](https://github.com/jurialmunkey/skin.arctic.fuse/assets/4618719/6ed59cb7-3630-4e4a-8ba9-c2f6cf994283)

**Comment by OfficerKD637** [comment]
Sorry! Clearing the TMDb helper cache did the trick.

**Comment by vella9** [comment]
> Sorry! Clearing the TMDb helper cache did the trick.

@OfficerKD637 where can I find this please?

**Comment by OfficerKD637** [comment]
> > Sorry! Clearing the TMDb helper cache did the trick.
> 
> @OfficerKD637 where can I find this please?

Go to TMDb Helper Settings > Expert > Delete Cache (Under the 'Other' section)

![image](https://github.com/jurialmunkey/skin.arctic.fuse/assets/167294806/684af6e3-6804-4116-a959-882b5e7293fa)


Also, just FYI I later figured out that my glitch was actually because I tried to decrease the size of font_info_black in the Includes_Font.xml file. 
So, it's better to not touch that file and just add your custom fontsets in the Font.xml file and the skin will scale everything auto-magically haha

**Comment by xyzfre** [comment]
> Works fine for me. Tried with both settings.
> 
> 
> 
> ![screenshot00594](https://github.com/jurialmunkey/skin.arctic.fuse/assets/4618719/b28ea80a-a324-46f5-a297-912b5ddbaa04)
> 
> 
> 
> ![screenshot00593](https://github.com/jurialmunkey/skin.arctic.fuse/assets/4618719/fff3ddfe-cb58-46b3-a4d7-614537048f41)
> 
> 
> 
> ![screenshot00595](https://github.com/jurialmunkey/skin.arctic.fuse/assets/4618719/6ed59cb7-3630-4e4a-8ba9-c2f6cf994283)
> 
> 
> 
> 

@jurialmunkey how did you make the text smaller in your pic that says searching?

**Comment by vella9** [comment]
> Go to TMDb Helper Settings > Expert > Delete Cache (Under the 'Other' section)

I did this tbh but if I search for let's say John Wick, I get some results with clearlogo and some without. Not sure why.

> So, it's better to not touch that file

No, I did not touch any skin files

**Comment by xyzfre** [comment]
> > how did you make the text smaller and the Kodi logo in your pic that says searching?
> 
> 
> 
> you now have the option to choose. This is located under `Settings > Interface > Title text`

Thank you I didn't see the update this morning. This is awesome. THANK YOU @jurialmunkey for adding this feature ,I love the small text with the Kodi logo

**Comment by OfficerKD637** [comment]
> > Go to TMDb Helper Settings > Expert > Delete Cache (Under the 'Other' section)
> 
> I did this tbh but if I search for let's say John Wick, I get some results with clearlogo and some without. Not sure why.
> 
> > So, it's better to not touch that file
> 
> No, I did not touch any skin files

Hmm that's weird. Once I reverted to the original Includes_Font.xml file, everything seemed to fix itself. If it's a similar kind of bug, I can reopen this issue so you can continue the conversation with Jurial. 
Can you also please try to recreate the issue and post the log and some screenshots?

**Comment by vella9** [comment]
> Can you also please try to recreate the issue and post the log and some screenshots?

I took a video of this issue that I am experiencing as per below. Sorry for the delay.

https://streamable.com/f0e82d

Can you maybe try and replicate the same from your end please? To see if it occurs as well. Thank you

**Comment by vella9** [comment]
> Go to TMDb Helper Settings > Expert > Delete Cache (Under the 'Other' section)

I presume then you need to select "Delete TMDB Cache" right? This is what I had deleted but the issue persisted.

**Comment by vella9** [comment]
> Maybe try deleting all the caches (TMDb, Fanart TV, OMDB, Item Details, Trakt) and then reloading the skin to see if it works?

I tried this and it worked at first, but then the same issue occurred within minutes.
I also tried and reinstalled v0.7.25 but the same occurred.  

However I noticed this morning that this is only occurring on my test system (windows). So I tried and restored to the same build I use on my live system (android) and the same issue occurred. I checked the logs and I have errors related to TMDBh as per [extract](https://github.com/user-attachments/files/16008987/untitled.txt). Maybe you can take a look please. It is related to cache but I don't know what I can do in this case.

TIA @OfficerKD637!

**Comment by OfficerKD637** [comment]
Hi! Sorry that didn't work out.

I think that error occurs when the skin cannot find the specific image file it's trying to look for. I am not exactly sure if that's what is causing your particular issue but let's try doing the following steps as a last resort:

After deleting the caches, go to the Thumbnails folder and make sure all the images are actually deleted (check all the subfolders like crop_v2, blur_v2, folders 0 to 9, etc.). 

Then go to your 'Database' folder and delete Textures13.db 
Now go inside the database_v6 folder and delete all the database (.db) files.

Restart Kodi

This is probably very overkill but I'm hoping when Kodi has to rebuild it's texture databases, it would fix any corrupted ones that might be causing any conflicts.

At this point I am just guessing everything, so I am re-opening this issue because @jurialmunkey is much better equipped at helping you solve this. 

Sorry I couldn't be of much help.

**Comment by vella9** [comment]
> Hi! Sorry that didn't work out.
> 
> I think that error occurs when the skin cannot find the specific image file it's trying to look for. I am not exactly sure if that's what is causing your particular issue but let's try doing the following steps as a last resort:
> 
> After deleting the caches, go to the Thumbnails folder and make sure all the images are actually deleted (check all the subfolders like crop_v2, blur_v2, folders 0 to 9, etc.). 
> 
> Then go to your 'Database' folder and delete Textures13.db 
> Now go inside the database_v6 folder and delete all the database (.db) files.
> 
> Restart Kodi
> 
> This is probably very overkill but I'm hoping when Kodi has to rebuild it's texture databases, it would fix any corrupted ones that might be causing any conflicts.
> 
> At this point I am just guessing everything, so I am re-opening this issue because @jurialmunkey is much better equipped at helping you solve this. 
> 
> Sorry I couldn't be of much help.

This worked! 

One of the above suggestions must have fixed the issue. After following all of the above, the issue is no longer present.

Thank you @OfficerKD637

**Comment by OfficerKD637** [comment]
That's great! Glad it got fixed. I'm closing the issue now but if this re-appears please let me know.

**Comment by jurialmunkey** [comment]
> I think that error occurs when the skin cannot find the specific image file it's trying to look for. I am not exactly sure if that's what is causing your particular issue but let's try doing the following steps as a last resort:

Nothing to do with the skin. Skin's don't "find" images. All rendering is handled by Kodi.

> error <general>: CImageLoader::DoWork - Direct texture file loading failed for special://masterprofile/Thumbnails/f/f5e62e1e.png

This type of error occurs when Kodi looks-up its image cache database (Textures.db) to see if it has already downloaded and cached an image, but when it tries to access the associated disk location it finds that the file no longer exists.

Usually this happens because a user deleted part or all of their Thumbnails folder without also cleaning the associated entries from Kodi's Texture database which stores the cached location of thumbnails.

Often this is due to some poorly designed "maintenance" addon and bad advice on the internet about needing to "clean" Kodi regularly (you shouldn't be doing this). It's bad practice to be deleting thumbnails cache unless you have severe disk space issues as it wastes server resources of these free APIs by forcing images to be redownloaded all the time (Trakt specifically stopped providing image access via its API for this reason in 2016...)

**Comment by OfficerKD637** [comment]
Thank you so much for the detailed response Jurial. And I apologize to you and @vella9 for my previous replies trying to solve the problem. I was trying to throw everything at it to see what sticks instead of a more technical and methodical approach. 
And yes I agree that one shouldn't be needlessly deleting caches/thumbnails. My advice was for a 'last resort' scenario but I forgot to mention deleting the Textures13.db file in my original comment.

So I'm assuming, if a similar problem pops up in the future the first course of action should be deleting the Thumbnails folder and then the Textures13.db file?

Again, my apologies to both of you. This would have probably been fixed much quicker if I had tagged Jurial much earlier in the thread.

**Comment by jurialmunkey** [comment]
> So I'm assuming, if a similar problem pops up in the future the first course of action should be deleting the Thumbnails folder and then the Textures13.db file?

It depends on the problem.

> error : CImageLoader::DoWork - Direct texture file loading failed for special://masterprofile/Thumbnails/f/f5e62e1e.png

This error indicates that Kodi looked up an image in Textures.db but couldn't find the corresponding image in Thumbnails folder.

Ideally, instead of nuking the entire thing, you should clean the broken entries from the cache database. This can be done with the Texture Cache Maintenance utility: https://kodi.wiki/view/Texture_Cache_Maintenance_utility

There is an exe version for Windows in this post on the forums: https://forum.kodi.tv/showthread.php?tid=158373&pid=3184117#pid3184117

Alternatively, script.database.cleaner has a Python 3 Kodi 19+ compatible version of the cleaner built in (since the original version uses Python 2 which can be a bit difficult to manage a dual install of Python without some knowledge)
https://github.com/klyco/script.database.cleaner

> error <general>: CImageLoader::DoWork - Direct texture file loading failed for resource://resource.images.studios.coloured/Westbrook Studios.png

This is a different (though similar) type of error which can be ignored. The skin has told Kodi to use a studio image which doesn't exist in the resource pack so Kodi is logging that fact. Since skins can't check if files exists, these types of errors are fairly common to see and can be safely ignored.

You can determine the difference by looking at the location being accessed. Thumbnails in master profile is location of cached images.

**Comment by vella9** [comment]
> Often this is due to some poorly designed "maintenance" addon

Then this was the culprit. I do have a "maintenance" addon, but I only use it to backup/restore builds normally. However this week, I did in fact perform a "clean cache" command. So this is what created the issue.

> The other way it might happen is if you copied the Textures.db from one device to another

Not in this case this time. However thank you for pointing this out.

> It will be due to deleting Textures.db from Kodi which then forces recaching of all images. If you are deleting this file, you should also delete your Thumbnails folder as none of these images will be valid anymore.

Noted, thank you!

> I apologize to you and @vella9 for my previous replies trying to solve the problem.

No apologies needed, @OfficerKD637. I appreciate you helping me out. Thanks for your assistance.

> Ideally, instead of nuking the entire thing, you should clean the broken entries from the cache database. This can be done with the Texture Cache Maintenance utility: https://kodi.wiki/view/Texture_Cache_Maintenance_utility
> 
> There is an exe version for Windows in this post on the forums: https://forum.kodi.tv/showthread.php?tid=158373&pid=3184117#pid3184117

Will give this a go if I encounter any similar issues in the future. 

Thank you for everything and for the detailed information provided @jurialmunkey. Really appreciated.
