### ISSUE TITLE
:bug: Sometimes I get stuck on the top menu

### ISSUE THREAD

**Issue by ambulancePilot** [jurialmunkey/skin.arctic.fuse#974]
### Skin section

Widgets

### Current Behavior

When backing out and going to the home screen, sometimes the navigation gets stuck on the top menu in the sense that you can't hit the down button to get down to your spotlight navigation. In fact, the spotlight navigation is hidden somehow.

Moving left or right across the top menu then hitting the down button works to get you out of the top menu. When you do this, the spotlight navigation pops into you and everything starts working as per normal. I can even move down to the category and submitting navigation. 

I think it's important to note that I just use the home hub. The top menu has the home icon and a search icon which doesn't do anything until you click it. I also have a downward icon which serves as a pseudo-minimize button. All it does is open my launcher app. 

Everything is global so when I cycle through the top menu icons, nothing changes in terms of my spotlight, categories, sub menus and widgets.

### Expected Behavior

Expected behavior would be the ability to move down from the top menu without having to cycle left or right across the top menu first.

### Steps To Reproduce

I'm not really sure how to reproduce this, it happens intermittently. I'll try to pay attention to it and come back with something. 

This has been happening for a while though, it's nothing new. I have been lazy about reporting it because it's intermittent and there's an easy way around it.

Please let me know if you would like a log file. It would be hard to generate because I can't predict when this is going to happen, so I'd have to keep debug logging on until it happens again.

Than you so much!! 🙏🏼

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by ambulancePilot** [comment]
I think you managed to fix this! I haven't noticed it in several days.

**Comment by jurialmunkey** [comment]
> I think you managed to fix this! I haven't noticed it in several days.

Oh maybe it was the same issue as the submenu one after all!

I'll close this but if it does popup again then leave a comment and I'll reopen.
