### ISSUE TITLE
:bug: Widget paths don't update via Skin Settings

### ISSUE THREAD

**Issue by ditydot** [jurialmunkey/skin.arctic.fuse#989]
### Skin section

Widgets

### Current Behavior

When changing the Spotlight or widget paths to a new entry (e.g. TMDBh Your In-Progress to TMDBh Recommended), the path is not updated resulting in no change.

### Expected Behavior

The new widget path is set and the skin is populated with the desired content.

### Steps To Reproduce

1. Navigate to Skin Settings
2. Select 'Menus'
3. Select 'Customise widgets'
4. Select 'Spotlight'
5. Select 'choose global spotlight'
6. Select a widget (any will suffice)
7. It will display 'building directory' for a split second
8. See that the path for the global spotlight has not changed

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
Works fine for me. You have to choose "Add folder" to add it after opening the directory. If the directory doesn't display then that sounds like some other issue.

**Comment by ditydot** [comment]
It's possible that it wasn't bringing up the widget path because it had too much content to load and was timing out. I changed to a smaller one, a personal watchlist instead of a public Trakt list, and the 'add folder' window actually popped up.

The list I was using as the spotlight must have been updated with a lot more entries.
