### ISSUE TITLE
Submenu widget categories no longer change

### ISSUE THREAD

**Issue by matthius7** [jurialmunkey/skin.arctic.fuse#996]
### Skin section

Widgets

### Current Behavior

Use the upper portion of the submenu widget and the bottom stacked widget is supposed to change . No longer changes below widget beyond the first picked instance. 

### Expected Behavior

For instance I had them under movies and TV shows. Popular,trending ,most favorited,Oscar winners. Change focus of widget and expect next stacked widget row to reflect what I'm on above. No longer works as of recently. 

### Steps To Reproduce

Create submenu widget under a category widget. 
Choose submenu widget to be used as a widget.
Move focus on submenu item.
Lower stacked widget reveals above choice. 
No longer happens. 

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
Ah I see. It only works for static submenu items, not the dynamic list. I didn't notice because I was testing with static items.

**Comment by matthius7** [comment]
Yes the dynamic list. Thank you my friend. Hope all is well with you.
