### ISSUE TITLE
:bug: Cannot add widget that currently has no content

### ISSUE THREAD

**Issue by xyl-sh** [jurialmunkey/skin.arctic.fuse#997]
### Skin section

Widgets

### Current Behavior

I'm trying to set up my ideal layout, but I cannot add a number of widgets because there is no content. For example, in progress movies from Trakt. I currently don't have any movies in progress, and when I select the sort I want (recently added), it just closes the widget select window instead of letting me add it.

### Expected Behavior

I should be able to add a widget that currently has no content.

### Steps To Reproduce

1. Go through the process to add a widget
2. Select a list that has no content

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
This is less a bug with the skin and more one with SkinVariables.

However, there is a workaround:

1. Navigate to the actual folder inside the plugin/library (not in widget customisation - just in the normal library) 
2. Open context menu on the folder (long press OK)
3. Click the button in the side panel called "Menu" with the plus sign
4. Choose the menu where you want to add it (sidemenu for sidemenu widgets, homemenu with category widgets)
